function out = model(gyroBias_deg_s,accelerometerNoiseRms_mps2)
%MODEL Generate transparent pitch-gyro and accelerometer measurements.
% The prescribed truth is a pure pitch-rate maneuver plus a North-axis
% acceleration pulse. The gyro adds a constant bias. The accelerometer
% reports body-frame specific force, f_b=C_n_to_b*(a_n-g_n), plus a fixed
% zero-mean teaching-error waveform whose vector RMS is the selected value.
arguments
    gyroBias_deg_s (1,1) double {mustBeReal,mustBeFinite} = 0.20
    accelerometerNoiseRms_mps2 (1,1) double ...
        {mustBeReal,mustBeFinite} = 0.15
end

if gyroBias_deg_s<-0.5 || gyroBias_deg_s>0.5
    error('P11:model:GyroBiasRange', ...
        'Gyro bias must be between -0.5 and 0.5 deg/s, inclusive.');
end
if accelerometerNoiseRms_mps2<0 || ...
        accelerometerNoiseRms_mps2>0.5
    error('P11:model:AccelerometerNoiseRange', ...
        ['Accelerometer noise vector RMS must be between 0 and 0.5 ' ...
        'm/s^2, inclusive.']);
end

sampleTime_s=0.01;
timeHorizon_s=8;
time_s=0:sampleTime_s:timeHorizon_s;
sampleCount=numel(time_s);
gravity_mps2=9.80665;
gravityNED_mps2=[0;0;gravity_mps2];

% Prescribed truth: a 10 deg/s sinusoidal pitch-rate lobe from 1 to 5 s.
% It starts and ends at level attitude and is deliberately independent of
% both sensor-error levers.
pitchRateTruth_deg_s=zeros(1,sampleCount);
pitchActive=time_s>1 & time_s<5;
pitchRateTruth_deg_s(pitchActive)=10*sin( ...
    2*pi*(time_s(pitchActive)-1)/4);
pitchAngleTruth_deg=integrateRate(time_s,pitchRateTruth_deg_s);

% A separate smooth North acceleration pulse runs from 2 to 4 s. East and
% Down coordinate accelerations remain zero.
accelerationNED_mps2=zeros(3,sampleCount);
accelerationActive=time_s>2 & time_s<4;
accelerationNED_mps2(1,accelerationActive)=2*sin( ...
    pi*(time_s(accelerationActive)-2)/2);

bodyToNED=zeros(3,3,sampleCount);
idealSpecificForceBody_mps2=zeros(3,sampleCount);
brokenIdealSpecificForceBody_mps2=zeros(3,sampleCount);
specificForceEquationResidualNED_mps2=zeros(3,sampleCount);
dcmOrthonormalityError=zeros(1,sampleCount);
dcmDeterminantError=zeros(1,sampleCount);
for k=1:sampleCount
    pitch_rad=pitchAngleTruth_deg(k)*pi/180;
    cosinePitch=cos(pitch_rad);
    sinePitch=sin(pitch_rad);
    % C_b_to_n maps body [x forward; y right; z down] components into
    % North-East-Down components for positive nose-up pitch.
    bodyToNED(:,:,k)=[ ...
        cosinePitch 0 sinePitch; ...
        0 1 0; ...
        -sinePitch 0 cosinePitch];
    nedToBody=bodyToNED(:,:,k).';
    idealSpecificForceBody_mps2(:,k)=nedToBody*( ...
        accelerationNED_mps2(:,k)-gravityNED_mps2);
    % Deliberately broken comparison: omit gravity and nothing else.
    brokenIdealSpecificForceBody_mps2(:,k)= ...
        nedToBody*accelerationNED_mps2(:,k);
    specificForceEquationResidualNED_mps2(:,k)= ...
        bodyToNED(:,:,k)*idealSpecificForceBody_mps2(:,k)+ ...
        gravityNED_mps2-accelerationNED_mps2(:,k);
    dcmOrthonormalityError(k)=max(max(abs( ...
        bodyToNED(:,:,k).'*bodyToNED(:,:,k)-eye(3))));
    dcmDeterminantError(k)=abs(det(bodyToNED(:,:,k))-1);
end

% This deterministic multitone shape is a replayable teaching error, not a
% stochastic or identified sensor-noise model. Remove each row mean, then
% normalize the vector RMS before applying the selected magnitude.
rawNoiseShape=[ ...
    sin(2*pi*1.7*time_s)+0.35*cos(2*pi*0.43*time_s); ...
    cos(2*pi*1.1*time_s)-0.25*sin(2*pi*0.61*time_s); ...
    sin(2*pi*2.3*time_s+0.4)+0.30*cos(2*pi*0.29*time_s)];
rawNoiseShape=rawNoiseShape-mean(rawNoiseShape,2);
rawNoiseVectorRms=sqrt(mean(sum(rawNoiseShape.^2,1)));
unitNoiseShape=rawNoiseShape/rawNoiseVectorRms;
accelerometerNoiseBody_mps2= ...
    accelerometerNoiseRms_mps2*unitNoiseShape;
accelerometerMeasuredBody_mps2= ...
    idealSpecificForceBody_mps2+accelerometerNoiseBody_mps2;
brokenAccelerometerMeasuredBody_mps2= ...
    brokenIdealSpecificForceBody_mps2+accelerometerNoiseBody_mps2;

pitchRateMeasured_deg_s=pitchRateTruth_deg_s+gyroBias_deg_s;
pitchAngleMeasured_deg=integrateRate(time_s,pitchRateMeasured_deg_s);
pitchAngleError_deg=pitchAngleMeasured_deg-pitchAngleTruth_deg;
expectedPitchAngleError_deg=gyroBias_deg_s*time_s;
gravityOmissionBody_mps2=accelerometerMeasuredBody_mps2- ...
    brokenAccelerometerMeasuredBody_mps2;
gravityOmissionMagnitude_mps2=sqrt(sum(gravityOmissionBody_mps2.^2,1));

out=struct( ...
    'gyroBias_deg_s',gyroBias_deg_s, ...
    'accelerometerNoiseRms_mps2',accelerometerNoiseRms_mps2, ...
    'sampleTime_s',sampleTime_s, ...
    'timeHorizon_s',timeHorizon_s, ...
    'time_s',time_s, ...
    'sampleCount',sampleCount, ...
    'updateCount',sampleCount-1, ...
    'gravity_mps2',gravity_mps2, ...
    'gravityNED_mps2',gravityNED_mps2, ...
    'pitchRateTruth_deg_s',pitchRateTruth_deg_s, ...
    'pitchAngleTruth_deg',pitchAngleTruth_deg, ...
    'accelerationNED_mps2',accelerationNED_mps2, ...
    'bodyToNED',bodyToNED, ...
    'pitchRateMeasured_deg_s',pitchRateMeasured_deg_s, ...
    'gyroError_deg_s',pitchRateMeasured_deg_s-pitchRateTruth_deg_s, ...
    'pitchAngleMeasured_deg',pitchAngleMeasured_deg, ...
    'pitchAngleError_deg',pitchAngleError_deg, ...
    'expectedPitchAngleError_deg',expectedPitchAngleError_deg, ...
    'idealSpecificForceBody_mps2',idealSpecificForceBody_mps2, ...
    'unitNoiseShape',unitNoiseShape, ...
    'accelerometerNoiseBody_mps2',accelerometerNoiseBody_mps2, ...
    'accelerometerMeasuredBody_mps2', ...
    accelerometerMeasuredBody_mps2, ...
    'specificForceEquationResidualNED_mps2', ...
    specificForceEquationResidualNED_mps2, ...
    'brokenIdealSpecificForceBody_mps2', ...
    brokenIdealSpecificForceBody_mps2, ...
    'brokenAccelerometerMeasuredBody_mps2', ...
    brokenAccelerometerMeasuredBody_mps2, ...
    'gravityOmissionBody_mps2',gravityOmissionBody_mps2, ...
    'gravityOmissionMagnitude_mps2',gravityOmissionMagnitude_mps2, ...
    'gyroMeanError_deg_s',mean( ...
    pitchRateMeasured_deg_s-pitchRateTruth_deg_s), ...
    'finalPitchAngleError_deg',pitchAngleError_deg(end), ...
    'peakPitchRateTruth_deg_s',max(abs(pitchRateTruth_deg_s)), ...
    'peakPitchAngleTruth_deg',max(abs(pitchAngleTruth_deg)), ...
    'accelerometerNoiseMeanBody_mps2', ...
    mean(accelerometerNoiseBody_mps2,2), ...
    'accelerometerNoiseVectorRmsMeasured_mps2', ...
    sqrt(mean(sum(accelerometerNoiseBody_mps2.^2,1))), ...
    'maxPitchAngleBiasClosure_deg',max(abs( ...
    pitchAngleError_deg-expectedPitchAngleError_deg)), ...
    'maxSpecificForceEquationResidual_mps2',max(max(abs( ...
    specificForceEquationResidualNED_mps2))), ...
    'maxDcmOrthonormalityError',max(dcmOrthonormalityError), ...
    'maxDcmDeterminantError',max(dcmDeterminantError), ...
    'maxGravityOmissionMagnitudeError_mps2',max(abs( ...
    gravityOmissionMagnitude_mps2-gravity_mps2)), ...
    'frameConvention',[ ...
    'body x forward, y right, z down; navigation frame is ' ...
    'North-East-Down; positive pitch is nose-up'], ...
    'gyroEquation',[ ...
    'q_measured_deg_s=q_truth_deg_s+constant_bias_deg_s; ' ...
    'angle is trapezoidal integration of rate'], ...
    'accelerometerEquation',[ ...
    'f_b=C_n_to_b*(a_n-g_n)+eta_b; a supported level ' ...
    'accelerometer reports approximately -g on body z-down'], ...
    'noiseDefinition',[ ...
    'fixed zero-mean normalized multitone teaching error with selected ' ...
    'three-axis vector RMS; not white Gaussian noise, PSD, or hardware data'], ...
    'brokenCaseDefinition',[ ...
    'gravity is omitted from specific force while truth, attitude, ' ...
    'coordinate acceleration, gyro, and additive noise remain identical'], ...
    'analysisScope',[ ...
    'deterministic two-sensor IMU teaching model; no quantization, ' ...
    'saturation, bandwidth, vibration, fusion, latency, GPS, identified ' ...
    'hardware, or flight-aircraft fidelity']);
end

function angle_deg = integrateRate(time_s,rate_deg_s)
%INTEGRATERATE Make every sample-to-sample trapezoidal update visible.
angle_deg=zeros(size(rate_deg_s));
for k=1:numel(time_s)-1
    step_s=time_s(k+1)-time_s(k);
    angle_deg(k+1)=angle_deg(k)+0.5*step_s*( ...
        rate_deg_s(k)+rate_deg_s(k+1));
end
end
