function run_checks
%RUN_CHECKS Independent checks for P11 flight-sensor measurement models.
clear model;
tol=1e-11;

%% Determinism, fixed shape, finite resources, and bounded accepted inputs
first=model(0.20,0.15);
second=model(0.20,0.15);
assert(isequaln(first,second), ...
    'Identical sensor inputs must produce identical output structures.');
assert(first.sampleCount==801 && first.updateCount==800 && ...
    first.sampleTime_s==0.01 && first.timeHorizon_s==8 && ...
    isequal(size(first.time_s),[1 801]) && ...
    first.time_s(1)==0 && first.time_s(end)==8, ...
    'The synchronous resource boundary must remain 801 samples and 800 updates.');

numericRowFields={ ...
    'pitchRateTruth_deg_s','pitchAngleTruth_deg', ...
    'pitchRateMeasured_deg_s','gyroError_deg_s', ...
    'pitchAngleMeasured_deg','pitchAngleError_deg', ...
    'expectedPitchAngleError_deg','gravityOmissionMagnitude_mps2'};
for k=1:numel(numericRowFields)
    value=first.(numericRowFields{k});
    assert(isequal(size(value),[1 801]) && isreal(value) && ...
        all(isfinite(value)), ...
        'Every scalar history must remain a finite 1-by-801 row vector.');
end
numericThreeAxisFields={ ...
    'accelerationNED_mps2','idealSpecificForceBody_mps2', ...
    'unitNoiseShape','accelerometerNoiseBody_mps2', ...
    'accelerometerMeasuredBody_mps2', ...
    'specificForceEquationResidualNED_mps2', ...
    'brokenIdealSpecificForceBody_mps2', ...
    'brokenAccelerometerMeasuredBody_mps2','gravityOmissionBody_mps2'};
for k=1:numel(numericThreeAxisFields)
    value=first.(numericThreeAxisFields{k});
    assert(isequal(size(value),[3 801]) && isreal(value) && ...
        all(isfinite(value(:))), ...
        'Every three-axis history must remain a finite 3-by-801 matrix.');
end
assert(isequal(size(first.bodyToNED),[3 3 801]) && ...
    all(isfinite(first.bodyToNED(:))) && ...
    isequal(size(first.gravityNED_mps2),[3 1]), ...
    'The DCM and gravity shapes must remain fixed and finite.');

biasEdges=[-0.5 0.5];
noiseEdges=[0 0.5];
acceptedCornerCount=0;
for biasIndex=1:numel(biasEdges)
    for noiseIndex=1:numel(noiseEdges)
        sample=model(biasEdges(biasIndex),noiseEdges(noiseIndex));
        acceptedCornerCount=acceptedCornerCount+1;
        assert(sample.sampleCount==801 && sample.updateCount==800 && ...
            all(isfinite(sample.pitchRateMeasured_deg_s)) && ...
            all(isfinite(sample.accelerometerMeasuredBody_mps2(:))) && ...
            abs(sample.finalPitchAngleError_deg- ...
            biasEdges(biasIndex)*sample.timeHorizon_s)<tol && ...
            abs(sample.accelerometerNoiseVectorRmsMeasured_mps2- ...
            noiseEdges(noiseIndex))<tol && ...
            sample.maxSpecificForceEquationResidual_mps2<tol && ...
            sample.maxGravityOmissionMagnitudeError_mps2<tol, ...
            'Every accepted input corner must remain finite and bounded.');
    end
end
assert(acceptedCornerCount==4, ...
    'The accepted-corner resource check must remain fixed at four calls.');

representativeBias=[-0.5 0.20 0.5];
representativeNoise=[0 0.15 0.5];
representativeCaseCount=0;
for biasIndex=1:numel(representativeBias)
    for noiseIndex=1:numel(representativeNoise)
        sample=model(representativeBias(biasIndex), ...
            representativeNoise(noiseIndex));
        representativeCaseCount=representativeCaseCount+1;
        assert(sample.sampleCount==801 && sample.updateCount==800 && ...
            all(isfinite(sample.pitchAngleMeasured_deg)) && ...
            all(isfinite(sample.accelerometerNoiseBody_mps2(:))), ...
            'The representative sensor grid must retain fixed finite work.');
    end
end
assert(representativeCaseCount==9 && representativeCaseCount<=10, ...
    'The representative resource grid must stay capped at nine calls.');

%% Independently reconstruct truth, every integration update, frames, and noise
expectedTime_s=0:0.01:8;
expectedSampleCount=numel(expectedTime_s);
expectedPitchRate_deg_s=zeros(1,expectedSampleCount);
pitchActive=expectedTime_s>1 & expectedTime_s<5;
expectedPitchRate_deg_s(pitchActive)=10*sin( ...
    2*pi*(expectedTime_s(pitchActive)-1)/4);
expectedPitchAngle_deg=independentTrapezoidalIntegral( ...
    expectedTime_s,expectedPitchRate_deg_s);

expectedAccelerationNED_mps2=zeros(3,expectedSampleCount);
accelerationActive=expectedTime_s>2 & expectedTime_s<4;
expectedAccelerationNED_mps2(1,accelerationActive)=2*sin( ...
    pi*(expectedTime_s(accelerationActive)-2)/2);
expectedGravityNED_mps2=[0;0;9.80665];
expectedBodyToNED=zeros(3,3,expectedSampleCount);
expectedIdealSpecificForceBody_mps2=zeros(3,expectedSampleCount);
expectedBrokenIdealSpecificForceBody_mps2=zeros(3,expectedSampleCount);
for k=1:expectedSampleCount
    pitch_rad=expectedPitchAngle_deg(k)*pi/180;
    expectedBodyToNED(:,:,k)=[ ...
        cos(pitch_rad) 0 sin(pitch_rad); ...
        0 1 0; ...
        -sin(pitch_rad) 0 cos(pitch_rad)];
    expectedNEDToBody=expectedBodyToNED(:,:,k).';
    expectedIdealSpecificForceBody_mps2(:,k)=expectedNEDToBody*( ...
        expectedAccelerationNED_mps2(:,k)-expectedGravityNED_mps2);
    expectedBrokenIdealSpecificForceBody_mps2(:,k)= ...
        expectedNEDToBody*expectedAccelerationNED_mps2(:,k);
end

expectedRawNoise=[ ...
    sin(2*pi*1.7*expectedTime_s)+ ...
    0.35*cos(2*pi*0.43*expectedTime_s); ...
    cos(2*pi*1.1*expectedTime_s)- ...
    0.25*sin(2*pi*0.61*expectedTime_s); ...
    sin(2*pi*2.3*expectedTime_s+0.4)+ ...
    0.30*cos(2*pi*0.29*expectedTime_s)];
expectedRawNoise=expectedRawNoise-mean(expectedRawNoise,2);
expectedUnitNoise=expectedRawNoise/ ...
    sqrt(mean(sum(expectedRawNoise.^2,1)));
expectedNoise_mps2=0.15*expectedUnitNoise;
expectedAccelerometer_mps2= ...
    expectedIdealSpecificForceBody_mps2+expectedNoise_mps2;
expectedBrokenAccelerometer_mps2= ...
    expectedBrokenIdealSpecificForceBody_mps2+expectedNoise_mps2;
expectedPitchRateMeasured_deg_s=expectedPitchRate_deg_s+0.20;
expectedPitchAngleMeasured_deg=independentTrapezoidalIntegral( ...
    expectedTime_s,expectedPitchRateMeasured_deg_s);

assert(isequal(first.time_s,expectedTime_s) && ...
    maxAbsoluteDifference(first.pitchRateTruth_deg_s, ...
    expectedPitchRate_deg_s)<tol && ...
    maxAbsoluteDifference(first.pitchAngleTruth_deg, ...
    expectedPitchAngle_deg)<tol && ...
    maxAbsoluteDifference(first.accelerationNED_mps2, ...
    expectedAccelerationNED_mps2)<tol, ...
    'The fixed truth schedules and independently integrated attitude must match.');
assert(maxAbsoluteDifference(first.bodyToNED,expectedBodyToNED)<tol && ...
    maxAbsoluteDifference(first.idealSpecificForceBody_mps2, ...
    expectedIdealSpecificForceBody_mps2)<tol && ...
    maxAbsoluteDifference(first.brokenIdealSpecificForceBody_mps2, ...
    expectedBrokenIdealSpecificForceBody_mps2)<tol, ...
    'Every DCM and complete/broken ideal specific-force sample must match reconstruction.');
assert(maxAbsoluteDifference(first.unitNoiseShape,expectedUnitNoise)<tol && ...
    maxAbsoluteDifference(first.accelerometerNoiseBody_mps2, ...
    expectedNoise_mps2)<tol && ...
    maxAbsoluteDifference(first.accelerometerMeasuredBody_mps2, ...
    expectedAccelerometer_mps2)<tol && ...
    maxAbsoluteDifference(first.brokenAccelerometerMeasuredBody_mps2, ...
    expectedBrokenAccelerometer_mps2)<tol, ...
    'The deterministic normalized error and both measurements must match reconstruction.');
assert(maxAbsoluteDifference(first.pitchRateMeasured_deg_s, ...
    expectedPitchRateMeasured_deg_s)<tol && ...
    maxAbsoluteDifference(first.pitchAngleMeasured_deg, ...
    expectedPitchAngleMeasured_deg)<tol, ...
    'The biased rate and every independently integrated angle update must match.');

for k=1:first.updateCount
    step_s=first.time_s(k+1)-first.time_s(k);
    expectedTrueNext=first.pitchAngleTruth_deg(k)+0.5*step_s*( ...
        first.pitchRateTruth_deg_s(k)+first.pitchRateTruth_deg_s(k+1));
    expectedMeasuredNext=first.pitchAngleMeasured_deg(k)+0.5*step_s*( ...
        first.pitchRateMeasured_deg_s(k)+ ...
        first.pitchRateMeasured_deg_s(k+1));
    assert(abs(first.pitchAngleTruth_deg(k+1)-expectedTrueNext)<tol && ...
        abs(first.pitchAngleMeasured_deg(k+1)-expectedMeasuredNext)<tol, ...
        'Every true and measured trapezoidal integration update must close.');
end

%% Recognizable baseline, rest, frames, equations, and ideal limits
assert(first.gravity_mps2==9.80665 && ...
    first.peakPitchRateTruth_deg_s==10 && ...
    abs(first.peakPitchAngleTruth_deg-12.732133646887217)<1e-11 && ...
    abs(first.pitchAngleTruth_deg(end))<1e-12 && ...
    abs(max(first.accelerationNED_mps2(1,:))-2)<tol && ...
    abs(first.gyroMeanError_deg_s-0.20)<tol && ...
    abs(first.finalPitchAngleError_deg-1.60)<tol && ...
    abs(first.accelerometerNoiseVectorRmsMeasured_mps2-0.15)<tol, ...
    'The deterministic baseline signature must remain recognizable.');
assert(max(abs(first.accelerometerNoiseMeanBody_mps2))<1e-14 && ...
    abs(sqrt(mean(sum(first.unitNoiseShape.^2,1)))-1)<tol, ...
    'The deterministic multitone must remain zero mean with unit vector RMS.');

assert(first.pitchRateTruth_deg_s(1)==0 && ...
    first.pitchAngleTruth_deg(1)==0 && ...
    all(first.accelerationNED_mps2(:,1)==0) && ...
    isequal(first.bodyToNED(:,:,1),eye(3)) && ...
    isequal(first.idealSpecificForceBody_mps2(:,1),[0;0;-9.80665]) && ...
    isequal(first.brokenIdealSpecificForceBody_mps2(:,1),[0;0;0]), ...
    'Supported level rest must retain zero coordinate acceleration and -g body-z specific force.');
postManeuver=first.time_s>=5;
assert(all(first.pitchRateTruth_deg_s(postManeuver)==0) && ...
    max(abs(first.pitchAngleTruth_deg(postManeuver)))<1e-12 && ...
    all(all(first.accelerationNED_mps2(:,postManeuver)==0)), ...
    'The prescribed truth must return to supported level rest after 5 s.');

% A closure check alone cannot distinguish the declared pitch convention
% from a self-consistent transposed/sign-reversed frame. Pin one nonlevel
% sample where positive pitch and North acceleration both contribute to the
% body-axis observables.
dynamicIndex=find(abs(first.time_s-3)<tol,1);
assert(~isempty(dynamicIndex), ...
    'The fixed grid must retain the 3 s nonlevel reference sample.');
dynamicPitch_rad=12.732133646887217*pi/180;
dynamicCosinePitch=cos(dynamicPitch_rad);
dynamicSinePitch=sin(dynamicPitch_rad);
expectedDynamicBodyToNED=[ ...
    dynamicCosinePitch 0 dynamicSinePitch; ...
    0 1 0; ...
    -dynamicSinePitch 0 dynamicCosinePitch];
expectedDynamicIdealSpecificForce_mps2=[ ...
    2*dynamicCosinePitch+first.gravity_mps2*dynamicSinePitch; ...
    0; ...
    2*dynamicSinePitch-first.gravity_mps2*dynamicCosinePitch];
expectedDynamicBrokenSpecificForce_mps2=[ ...
    2*dynamicCosinePitch;0;2*dynamicSinePitch];
expectedDynamicGravityOmission_mps2=[ ...
    first.gravity_mps2*dynamicSinePitch; ...
    0; ...
    -first.gravity_mps2*dynamicCosinePitch];
assert(abs(first.pitchAngleTruth_deg(dynamicIndex)- ...
    12.732133646887217)<tol && ...
    maxAbsoluteDifference(first.accelerationNED_mps2(:,dynamicIndex), ...
    [2;0;0])<tol && ...
    maxAbsoluteDifference(first.bodyToNED(:,:,dynamicIndex), ...
    expectedDynamicBodyToNED)<tol && ...
    maxAbsoluteDifference(first.idealSpecificForceBody_mps2(:,dynamicIndex), ...
    expectedDynamicIdealSpecificForce_mps2)<tol && ...
    maxAbsoluteDifference( ...
    first.brokenIdealSpecificForceBody_mps2(:,dynamicIndex), ...
    expectedDynamicBrokenSpecificForce_mps2)<tol && ...
    maxAbsoluteDifference(first.gravityOmissionBody_mps2(:,dynamicIndex), ...
    expectedDynamicGravityOmission_mps2)<tol && ...
    first.idealSpecificForceBody_mps2(1,dynamicIndex)> ...
    first.accelerationNED_mps2(1,dynamicIndex), ...
    ['The nonlevel frame-sign signature must rotate positive-pitch gravity ' ...
    'and North acceleration into the declared body x/z directions.']);

for k=1:first.sampleCount
    currentDcm=first.bodyToNED(:,:,k);
    assert(max(max(abs(currentDcm.'*currentDcm-eye(3))))<tol && ...
        abs(det(currentDcm)-1)<tol && ...
        max(abs(currentDcm*first.idealSpecificForceBody_mps2(:,k)+ ...
        first.gravityNED_mps2-first.accelerationNED_mps2(:,k)))<tol, ...
        'Every DCM and ideal specific-force equation must close independently.');
end
assert(first.maxDcmOrthonormalityError<tol && ...
    first.maxDcmDeterminantError<tol && ...
    first.maxSpecificForceEquationResidual_mps2<tol && ...
    first.maxPitchAngleBiasClosure_deg<tol, ...
    'Stored closure metrics must remain inside their declared tolerances.');

zeroBias=model(0,0.15);
zeroNoise=model(0.20,0);
fullyIdeal=model(0,0);
assert(isequal(zeroBias.pitchRateMeasured_deg_s, ...
    zeroBias.pitchRateTruth_deg_s) && ...
    isequal(zeroBias.pitchAngleMeasured_deg,zeroBias.pitchAngleTruth_deg) && ...
    zeroBias.finalPitchAngleError_deg==0, ...
    'Zero gyro bias must exactly reproduce rate and integrated-angle truth.');
assert(all(zeroNoise.accelerometerNoiseBody_mps2(:)==0) && ...
    isequal(zeroNoise.accelerometerMeasuredBody_mps2, ...
    zeroNoise.idealSpecificForceBody_mps2) && ...
    isequal(zeroNoise.brokenAccelerometerMeasuredBody_mps2, ...
    zeroNoise.brokenIdealSpecificForceBody_mps2), ...
    'Zero accelerometer error must exactly reproduce ideal specific force.');
assert(isequal(fullyIdeal.pitchRateMeasured_deg_s, ...
    fullyIdeal.pitchRateTruth_deg_s) && ...
    isequal(fullyIdeal.pitchAngleMeasured_deg,fullyIdeal.pitchAngleTruth_deg) && ...
    isequal(fullyIdeal.accelerometerMeasuredBody_mps2, ...
    fullyIdeal.idealSpecificForceBody_mps2), ...
    'The joint zero-error corner must remain the fully ideal sensor limit.');

%% Two isolated parameter sweeps
gyroBiasSweep_deg_s=[-0.50 -0.25 0 0.25 0.50];
finalAngleError_deg=zeros(size(gyroBiasSweep_deg_s));
for k=1:numel(gyroBiasSweep_deg_s)
    sample=model(gyroBiasSweep_deg_s(k),0.15);
    finalAngleError_deg(k)=sample.finalPitchAngleError_deg;
    assert(isequal(sample.pitchRateTruth_deg_s, ...
        first.pitchRateTruth_deg_s) && ...
        isequal(sample.pitchAngleTruth_deg,first.pitchAngleTruth_deg) && ...
        isequal(sample.accelerationNED_mps2,first.accelerationNED_mps2) && ...
        isequal(sample.bodyToNED,first.bodyToNED) && ...
        isequal(sample.idealSpecificForceBody_mps2, ...
        first.idealSpecificForceBody_mps2) && ...
        isequal(sample.accelerometerNoiseBody_mps2, ...
        first.accelerometerNoiseBody_mps2) && ...
        isequal(sample.accelerometerMeasuredBody_mps2, ...
        first.accelerometerMeasuredBody_mps2) && ...
        isequal(sample.brokenAccelerometerMeasuredBody_mps2, ...
        first.brokenAccelerometerMeasuredBody_mps2), ...
        'The gyro-bias sweep must isolate gyro measurement effects.');
end
assert(max(abs(finalAngleError_deg-[-4 -2 0 2 4]))<tol && ...
    all(diff(finalAngleError_deg)>0), ...
    'The gyro sweep must map bias to final angle error through eight seconds.');

noiseSweep_mps2=[0 0.05 0.15 0.30 0.50];
observedNoiseRms_mps2=zeros(size(noiseSweep_mps2));
for k=1:numel(noiseSweep_mps2)
    sample=model(0.20,noiseSweep_mps2(k));
    observedNoiseRms_mps2(k)= ...
        sample.accelerometerNoiseVectorRmsMeasured_mps2;
    assert(isequal(sample.pitchRateTruth_deg_s, ...
        first.pitchRateTruth_deg_s) && ...
        isequal(sample.pitchAngleTruth_deg,first.pitchAngleTruth_deg) && ...
        isequal(sample.accelerationNED_mps2,first.accelerationNED_mps2) && ...
        isequal(sample.bodyToNED,first.bodyToNED) && ...
        isequal(sample.idealSpecificForceBody_mps2, ...
        first.idealSpecificForceBody_mps2) && ...
        isequal(sample.pitchRateMeasured_deg_s, ...
        first.pitchRateMeasured_deg_s) && ...
        isequal(sample.pitchAngleMeasured_deg, ...
        first.pitchAngleMeasured_deg), ...
        'The accelerometer-error sweep must isolate accelerometer magnitude.');
    if noiseSweep_mps2(k)>0
        assert(maxAbsoluteDifference( ...
            sample.accelerometerNoiseBody_mps2/ ...
            noiseSweep_mps2(k),first.unitNoiseShape)<tol, ...
            'Every nonzero noise case must rescale the same unit shape.');
    end
end
assert(max(abs(observedNoiseRms_mps2-noiseSweep_mps2))<tol && ...
    all(diff(observedNoiseRms_mps2)>0), ...
    'The accelerometer sweep must reproduce every requested vector RMS.');

%% Deliberately broken specific-force equation omits only gravity
expectedGravityOmission=zeros(3,first.sampleCount);
for k=1:first.sampleCount
    expectedGravityOmission(:,k)= ...
        -first.bodyToNED(:,:,k).'*first.gravityNED_mps2;
end
assert(maxAbsoluteDifference(first.gravityOmissionBody_mps2, ...
    expectedGravityOmission)<tol && ...
    maxAbsoluteDifference(first.accelerometerMeasuredBody_mps2- ...
    first.brokenAccelerometerMeasuredBody_mps2, ...
    first.idealSpecificForceBody_mps2- ...
    first.brokenIdealSpecificForceBody_mps2)<tol && ...
    max(abs(first.gravityOmissionMagnitude_mps2-first.gravity_mps2))<tol && ...
    first.maxGravityOmissionMagnitudeError_mps2<tol, ...
    'Complete-minus-broken output must be exactly the rotated omitted gravity.');
assert(maxAbsoluteDifference(first.brokenAccelerometerMeasuredBody_mps2- ...
    first.brokenIdealSpecificForceBody_mps2, ...
    first.accelerometerNoiseBody_mps2)<tol && ...
    first.brokenIdealSpecificForceBody_mps2(3,1)==0 && ...
    first.idealSpecificForceBody_mps2(3,1)==-first.gravity_mps2, ...
    'The broken case must preserve additive error and expose false zero at rest.');

%% Declared meaning and compatibility boundary remain explicit
assert(contains(first.frameConvention,'x forward') && ...
    contains(first.frameConvention,'North-East-Down') && ...
    contains(first.gyroEquation,'constant_bias') && ...
    contains(first.accelerometerEquation,'a_n-g_n') && ...
    contains(first.noiseDefinition,'not white Gaussian') && ...
    contains(first.brokenCaseDefinition,'gravity is omitted') && ...
    contains(first.analysisScope,'no quantization') && ...
    contains(first.analysisScope,'latency'), ...
    'Frames, equations, broken assumption, and analysis limits must stay visible.');

%% Malformed inputs fail clearly, then a valid call recovers
expectFailure(@() model(-0.5001,0.15), ...
    'P11:model:GyroBiasRange','gyro bias below range');
expectFailure(@() model(0.5001,0.15), ...
    'P11:model:GyroBiasRange','gyro bias above range');
expectFailure(@() model(0.20,-0.001), ...
    'P11:model:AccelerometerNoiseRange','accelerometer noise below range');
expectFailure(@() model(0.20,0.5001), ...
    'P11:model:AccelerometerNoiseRange','accelerometer noise above range');
expectFailure(@() model([0.1 0.2],0.15),'','nonscalar gyro bias');
expectFailure(@() model(0.20,[0.1 0.2]),'','nonscalar accelerometer noise');
expectFailure(@() model(0.20+1i,0.15),'','complex gyro bias');
expectFailure(@() model(0.20,0.15+1i),'','complex accelerometer noise');
expectFailure(@() model(NaN,0.15),'','nonfinite gyro bias');
expectFailure(@() model(0.20,Inf),'','nonfinite accelerometer noise');
afterFailure=model(0.20,0.15);
assert(isequaln(afterFailure,first), ...
    'Rejected inputs must not poison deterministic recovery.');

disp(['P11 checks passed: fixed truth, independent integration and frame ' ...
    'reconstruction, specific-force closure, ideal limits, isolated sweeps, ' ...
    'malformed-input recovery, capped resources, and gravity-omission detection.']);
end

function angle_deg = independentTrapezoidalIntegral(time_s,rate_deg_s)
%INDEPENDENTTRAPEZOIDALINTEGRAL Reconstruct each stated update externally.
angle_deg=zeros(size(rate_deg_s));
for k=1:numel(time_s)-1
    step_s=time_s(k+1)-time_s(k);
    angle_deg(k+1)=angle_deg(k)+0.5*step_s*( ...
        rate_deg_s(k)+rate_deg_s(k+1));
end
end

function difference = maxAbsoluteDifference(actual,expected)
%MAXABSOLUTEDIFFERENCE Compare arrays without relying on model metrics.
difference=max(abs(actual(:)-expected(:)));
end

function expectFailure(action,expectedIdentifier,label)
%EXPECTFAILURE Require clear rejection and optionally an exact identifier.
didFail=false;
try
    action();
catch exception
    didFail=true;
    if ~isempty(expectedIdentifier)
        assert(strcmp(exception.identifier,expectedIdentifier), ...
            ['Wrong error identifier for ' label '.']);
    end
end
assert(didFail,['Expected rejection for ' label '.']);
end
