function out = model(airDensity_kgpm3,trueAirspeed_mps,mass_kg,flightPathAngle_deg)
%MODEL Analytic point-mass longitudinal force trim for a small aircraft.
% airDensity_kgpm3 is supplied by the P03 atmosphere model, trueAirspeed_mps
% is the air-relative speed magnitude, mass_kg sets weight, and
% flightPathAngle_deg is positive for a steady climb. Thrust is assumed to
% act along the flight path. The learning domain is rho=[0.04,2] kg/m^3,
% V=[20,200] m/s, mass=[400,3000] kg, and gamma=[-10,10] deg.
arguments
    airDensity_kgpm3 (1,1) double {mustBeReal,mustBeFinite} = 0.736115547399152
    trueAirspeed_mps (1,1) double {mustBeReal,mustBeFinite} = 60
    mass_kg (1,1) double {mustBeReal,mustBeFinite} = 1200
    flightPathAngle_deg (1,1) double {mustBeReal,mustBeFinite} = 0
end

if airDensity_kgpm3<=0
    error('P04:model:PositiveDensity', ...
        'Air density must be positive.');
end
if airDensity_kgpm3<0.04 || airDensity_kgpm3>2
    error('P04:model:DensityRange', ...
        'Air density must be between 0.04 and 2 kg/m^3, inclusive.');
end
if trueAirspeed_mps<=0
    error('P04:model:PositiveAirspeed', ...
        'True airspeed must be positive.');
end
if trueAirspeed_mps<20 || trueAirspeed_mps>200
    error('P04:model:AirspeedRange', ...
        'True airspeed must be between 20 and 200 m/s, inclusive.');
end
if mass_kg<=0
    error('P04:model:PositiveMass', ...
        'Mass must be positive.');
end
if mass_kg<400 || mass_kg>3000
    error('P04:model:MassRange', ...
        'Mass must be between 400 and 3000 kg, inclusive.');
end
if abs(flightPathAngle_deg)>10
    error('P04:model:FlightPathAngleRange', ...
        'Flight-path angle must be between -10 and 10 deg, inclusive.');
end

gravity_mps2=9.80665;
wingArea_m2=16.2;
zeroLiftCoefficient=0.25;
liftCurveSlope_perRad=5.0;
parasiteDragCoefficient=0.025;
inducedDragFactor=0.045;
maximumLiftCoefficient=1.4;
maximumThrust_N=4000;

flightPathAngle_rad=flightPathAngle_deg*pi/180;
weight_N=mass_kg*gravity_mps2;
dynamicPressure_Pa=0.5*airDensity_kgpm3*trueAirspeed_mps^2;
normalForceRequired_N=weight_N*cos(flightPathAngle_rad);
weightAlongPath_N=weight_N*sin(flightPathAngle_rad);

liftCoefficient=normalForceRequired_N/(dynamicPressure_Pa*wingArea_m2);
angleOfAttack_rad=(liftCoefficient-zeroLiftCoefficient)/ ...
    liftCurveSlope_perRad;
angleOfAttack_deg=angleOfAttack_rad*180/pi;
inducedDragCoefficient=inducedDragFactor*liftCoefficient^2;
dragCoefficient=parasiteDragCoefficient+inducedDragCoefficient;

lift_N=dynamicPressure_Pa*wingArea_m2*liftCoefficient;
parasiteDrag_N=dynamicPressure_Pa*wingArea_m2*parasiteDragCoefficient;
inducedDrag_N=dynamicPressure_Pa*wingArea_m2*inducedDragCoefficient;
drag_N=parasiteDrag_N+inducedDrag_N;
thrustRequired_N=drag_N+weightAlongPath_N;

normalForceResidual_N=lift_N-normalForceRequired_N;
axialForceResidual_N=thrustRequired_N-drag_N-weightAlongPath_N;
forceResidualMagnitude_N=hypot(normalForceResidual_N,axialForceResidual_N);

stallSpeed_mps=sqrt(2*normalForceRequired_N/( ...
    airDensity_kgpm3*wingArea_m2*maximumLiftCoefficient));
minimumDragSpeed_mps=sqrt(2*normalForceRequired_N/( ...
    airDensity_kgpm3*wingArea_m2)*sqrt( ...
    inducedDragFactor/parasiteDragCoefficient));
liftCoefficientMargin=maximumLiftCoefficient*(1-( ...
    stallSpeed_mps/trueAirspeed_mps)^2);
thrustLowerMargin_N=thrustRequired_N;
thrustUpperMargin_N=maximumThrust_N-thrustRequired_N;
liftFeasible=liftCoefficientMargin>=0;
thrustFeasible=thrustRequired_N>=0 && thrustRequired_N<=maximumThrust_N;
trimFeasible=liftFeasible && thrustFeasible;

out=struct( ...
    'airDensity_kgpm3',airDensity_kgpm3, ...
    'trueAirspeed_mps',trueAirspeed_mps, ...
    'mass_kg',mass_kg, ...
    'flightPathAngle_deg',flightPathAngle_deg, ...
    'flightPathAngle_rad',flightPathAngle_rad, ...
    'weight_N',weight_N, ...
    'dynamicPressure_Pa',dynamicPressure_Pa, ...
    'normalForceRequired_N',normalForceRequired_N, ...
    'weightAlongPath_N',weightAlongPath_N, ...
    'liftCoefficient',liftCoefficient, ...
    'angleOfAttack_rad',angleOfAttack_rad, ...
    'angleOfAttack_deg',angleOfAttack_deg, ...
    'inducedDragCoefficient',inducedDragCoefficient, ...
    'dragCoefficient',dragCoefficient, ...
    'parasiteDrag_N',parasiteDrag_N, ...
    'inducedDrag_N',inducedDrag_N, ...
    'drag_N',drag_N, ...
    'lift_N',lift_N, ...
    'thrustRequired_N',thrustRequired_N, ...
    'requiredThrustFraction',thrustRequired_N/maximumThrust_N, ...
    'normalForceResidual_N',normalForceResidual_N, ...
    'axialForceResidual_N',axialForceResidual_N, ...
    'forceResidualMagnitude_N',forceResidualMagnitude_N, ...
    'stallSpeed_mps',stallSpeed_mps, ...
    'minimumDragSpeed_mps',minimumDragSpeed_mps, ...
    'liftCoefficientMargin',liftCoefficientMargin, ...
    'thrustLowerMargin_N',thrustLowerMargin_N, ...
    'thrustUpperMargin_N',thrustUpperMargin_N, ...
    'liftFeasible',liftFeasible, ...
    'thrustFeasible',thrustFeasible, ...
    'trimFeasible',trimFeasible, ...
    'wingLoading_Npm2',weight_N/wingArea_m2, ...
    'liftToDragRatio',lift_N/drag_N, ...
    'gravity_mps2',gravity_mps2, ...
    'wingArea_m2',wingArea_m2, ...
    'zeroLiftCoefficient',zeroLiftCoefficient, ...
    'liftCurveSlope_perRad',liftCurveSlope_perRad, ...
    'parasiteDragCoefficient',parasiteDragCoefficient, ...
    'inducedDragFactor',inducedDragFactor, ...
    'maximumLiftCoefficient',maximumLiftCoefficient, ...
    'maximumThrust_N',maximumThrust_N, ...
    'forceConvention', ...
    'along path positive forward; normal positive toward lift', ...
    'thrustConvention','thrust aligned with the flight path');
end
