function run_checks
%RUN_CHECKS Independent analytic checks for the P04 force-trim model.
clear model;
tol=1e-10;
baselineDensity_kgpm3=0.736115547399152;

%% Determinism and fixed resource shape
first=model(baselineDensity_kgpm3,60,1200,0);
second=model(baselineDensity_kgpm3,60,1200,0);
assert(isequaln(first,second), ...
    'Identical trim inputs must produce identical outputs.');
scalarFields={'weight_N','dynamicPressure_Pa','normalForceRequired_N', ...
    'weightAlongPath_N','liftCoefficient','angleOfAttack_rad', ...
    'angleOfAttack_deg','dragCoefficient','parasiteDrag_N','inducedDrag_N', ...
    'drag_N','lift_N','thrustRequired_N','requiredThrustFraction', ...
    'normalForceResidual_N','axialForceResidual_N','forceResidualMagnitude_N', ...
    'stallSpeed_mps','minimumDragSpeed_mps','liftCoefficientMargin', ...
    'thrustLowerMargin_N','thrustUpperMargin_N','wingLoading_Npm2', ...
    'liftToDragRatio'};
for k=1:numel(scalarFields)
    assert(isscalar(first.(scalarFields{k})) && isfinite(first.(scalarFields{k})), ...
        'Trim outputs must remain finite scalars.');
end

edgeDensities_kgpm3=[0.04 2];
edgeSpeeds_mps=[20 200];
edgeMasses_kg=[400 3000];
edgePathAngles_deg=[-10 10];
edgeCaseCount=0;
for densityIndex=1:numel(edgeDensities_kgpm3)
    for speedIndex=1:numel(edgeSpeeds_mps)
        for massIndex=1:numel(edgeMasses_kg)
            for pathIndex=1:numel(edgePathAngles_deg)
                edge=model(edgeDensities_kgpm3(densityIndex), ...
                    edgeSpeeds_mps(speedIndex),edgeMasses_kg(massIndex), ...
                    edgePathAngles_deg(pathIndex));
                edgeCaseCount=edgeCaseCount+1;
                for fieldIndex=1:numel(scalarFields)
                    assert(isfinite(edge.(scalarFields{fieldIndex})), ...
                        'Every accepted input corner must produce finite outputs.');
                end
            end
        end
    end
end
assert(edgeCaseCount==16,'The accepted-corner grid must stay fixed at 16 cases.');

%% Independent deterministic baseline and force-balance identities
expectedGravity_mps2=9.80665;
expectedWingArea_m2=16.2;
expectedZeroLiftCoefficient=0.25;
expectedLiftSlope_perRad=5.0;
expectedParasiteDragCoefficient=0.025;
expectedInducedDragFactor=0.045;
expectedDynamicPressure_Pa=0.5*baselineDensity_kgpm3*60^2;
expectedWeight_N=1200*expectedGravity_mps2;
expectedLiftCoefficient=expectedWeight_N/( ...
    expectedDynamicPressure_Pa*expectedWingArea_m2);
expectedAngleOfAttack_rad=(expectedLiftCoefficient- ...
    expectedZeroLiftCoefficient)/expectedLiftSlope_perRad;
expectedParasiteDrag_N=expectedDynamicPressure_Pa* ...
    expectedWingArea_m2*expectedParasiteDragCoefficient;
expectedInducedDrag_N=expectedInducedDragFactor*expectedWeight_N^2/( ...
    expectedDynamicPressure_Pa*expectedWingArea_m2);
expectedDrag_N=expectedParasiteDrag_N+expectedInducedDrag_N;

assert(abs(first.dynamicPressure_Pa-expectedDynamicPressure_Pa)<1e-9 && ...
    abs(first.weight_N-expectedWeight_N)<1e-9, ...
    'Dynamic pressure and weight must independently follow q=0.5*rho*V^2 and W=m*g.');
assert(abs(first.liftCoefficient-expectedLiftCoefficient)<tol && ...
    abs(first.angleOfAttack_rad-expectedAngleOfAttack_rad)<tol, ...
    'Required lift coefficient and alpha must close the normal force balance.');
assert(abs(first.parasiteDrag_N-expectedParasiteDrag_N)<1e-9 && ...
    abs(first.inducedDrag_N-expectedInducedDrag_N)<1e-9 && ...
    abs(first.drag_N-expectedDrag_N)<1e-9, ...
    'The parabolic polar must retain separate parasite and induced drag.');
assert(abs(first.dynamicPressure_Pa-1325.00798531847)<1e-8 && ...
    abs(first.liftCoefficient-0.548237087298700)<1e-12 && ...
    abs(first.thrustRequired_N-826.952172590503)<1e-9, ...
    'The P03-density baseline must remain numerically recognizable.');
assert(abs(first.normalForceRequired_N-first.weight_N)<tol && ...
    first.weightAlongPath_N==0 && abs(first.lift_N-first.weight_N)<1e-9 && ...
    abs(first.thrustRequired_N-first.drag_N)<tol, ...
    'Level trim must reduce to lift equals weight and thrust equals drag.');
assert(first.forceResidualMagnitude_N<1e-9*first.weight_N && first.trimFeasible, ...
    'The baseline must have negligible residuals and remain within both limits.');

%% Lift law, drag polar, and path-axis equations
general=model(0.9,73,1350,4);
independentQ_Pa=0.5*general.airDensity_kgpm3*general.trueAirspeed_mps^2;
independentWeight_N=general.mass_kg*9.80665;
independentNormal_N=independentWeight_N*cos(general.flightPathAngle_deg*pi/180);
independentAlong_N=independentWeight_N*sin(general.flightPathAngle_deg*pi/180);
independentCL=independentNormal_N/(independentQ_Pa*16.2);
independentCD=0.025+0.045*independentCL^2;
independentDrag_N=independentQ_Pa*16.2*independentCD;
assert(abs(general.liftCoefficient-independentCL)<tol && ...
    abs(general.dragCoefficient-independentCD)<tol, ...
    'Lift and drag coefficients must follow the declared transparent laws.');
assert(abs(general.thrustRequired_N-(independentDrag_N+independentAlong_N))<1e-9, ...
    'Required thrust must balance drag plus the along-path weight component.');
assert(abs(general.normalForceResidual_N)<1e-9*independentWeight_N && ...
    abs(general.axialForceResidual_N)<1e-9*independentWeight_N, ...
    'Both path-axis residuals must close independently.');

%% Limiting speeds and independent scaling laws
atStall=model(baselineDensity_kgpm3,first.stallSpeed_mps,1200,0);
belowStall=model(baselineDensity_kgpm3,0.999*first.stallSpeed_mps,1200,0);
aboveStall=model(baselineDensity_kgpm3,1.001*first.stallSpeed_mps,1200,0);
assert(abs(atStall.liftCoefficient-first.maximumLiftCoefficient)<1e-12, ...
    'The analytic stall speed must require exactly CL max.');
assert(~belowStall.liftFeasible && aboveStall.liftFeasible, ...
    'Crossing the analytic stall speed must toggle the lift-feasibility limit.');

inclinedReference=model(baselineDensity_kgpm3,60,1200,5);
inclinedStallSpeed_mps=inclinedReference.stallSpeed_mps;
inclinedAtStall=model(baselineDensity_kgpm3,inclinedStallSpeed_mps,1200,5);
inclinedJustBelowStall=model(baselineDensity_kgpm3, ...
    inclinedStallSpeed_mps-eps(inclinedStallSpeed_mps),1200,5);
inclinedJustAboveStall=model(baselineDensity_kgpm3, ...
    inclinedStallSpeed_mps+eps(inclinedStallSpeed_mps),1200,5);
assert(abs(inclinedAtStall.liftCoefficient- ...
    inclinedAtStall.maximumLiftCoefficient)<1e-12 && ...
    inclinedAtStall.liftCoefficientMargin==0 && inclinedAtStall.liftFeasible, ...
    'The inclined analytic stall boundary must remain inclusively lift-feasible.');
assert(inclinedJustBelowStall.liftCoefficientMargin<0 && ...
    ~inclinedJustBelowStall.liftFeasible && ...
    inclinedJustAboveStall.liftCoefficientMargin>0 && ...
    inclinedJustAboveStall.liftFeasible, ...
    'The exact stall gate must reject the adjacent lower speed without a tolerance.');

atMinimumDrag=model(baselineDensity_kgpm3,first.minimumDragSpeed_mps,1200,0);
expectedMinimumDrag_N=2*atMinimumDrag.normalForceRequired_N*sqrt(0.025*0.045);
assert(abs(atMinimumDrag.parasiteDrag_N-atMinimumDrag.inducedDrag_N)<1e-9 && ...
    abs(atMinimumDrag.drag_N-expectedMinimumDrag_N)<1e-9, ...
    'At minimum drag, parasite and induced drag must be equal.');

slow=model(baselineDensity_kgpm3,40,1200,0);
fast=model(baselineDensity_kgpm3,80,1200,0);
assert(abs(fast.dynamicPressure_Pa/slow.dynamicPressure_Pa-4)<tol && ...
    abs(fast.liftCoefficient/slow.liftCoefficient-0.25)<tol && ...
    abs(fast.parasiteDrag_N/slow.parasiteDrag_N-4)<tol && ...
    abs(fast.inducedDrag_N/slow.inducedDrag_N-0.25)<tol, ...
    'Doubling speed must expose the V^2 and inverse-V^2 trim scalings.');

light=model(baselineDensity_kgpm3,60,600,0);
heavy=model(baselineDensity_kgpm3,60,1200,0);
assert(abs(heavy.liftCoefficient/light.liftCoefficient-2)<tol && ...
    abs(heavy.parasiteDrag_N/light.parasiteDrag_N-1)<tol && ...
    abs(heavy.inducedDrag_N/light.inducedDrag_N-4)<tol, ...
    'Doubling mass must double CL and quadruple induced drag at fixed q.');

thin=model(0.5,60,1200,0);
dense=model(1.0,60,1200,0);
assert(abs(dense.dynamicPressure_Pa/thin.dynamicPressure_Pa-2)<tol && ...
    abs(dense.liftCoefficient/thin.liftCoefficient-0.5)<tol && ...
    abs(dense.parasiteDrag_N/thin.parasiteDrag_N-2)<tol && ...
    abs(dense.inducedDrag_N/thin.inducedDrag_N-0.5)<tol, ...
    'Doubling density must separate parasite and induced drag responses.');

%% Sweep regressions keep the two levers independent
speedSweep_mps=[40 50 60 80 100];
speedCL=zeros(size(speedSweep_mps));
speedAlpha_deg=zeros(size(speedSweep_mps));
speedParasite_N=zeros(size(speedSweep_mps));
speedInduced_N=zeros(size(speedSweep_mps));
speedThrust_N=zeros(size(speedSweep_mps));
speedFeasible=false(size(speedSweep_mps));
for k=1:numel(speedSweep_mps)
    sample=model(baselineDensity_kgpm3,speedSweep_mps(k),1200,0);
    speedCL(k)=sample.liftCoefficient;
    speedAlpha_deg(k)=sample.angleOfAttack_deg;
    speedParasite_N(k)=sample.parasiteDrag_N;
    speedInduced_N(k)=sample.inducedDrag_N;
    speedThrust_N(k)=sample.thrustRequired_N;
    speedFeasible(k)=sample.trimFeasible;
end
[~,minimumThrustIndex]=min(speedThrust_N);
assert(all(diff(speedCL)<0) && all(diff(speedAlpha_deg)<0), ...
    'The airspeed sweep must lower required CL and alpha.');
assert(all(diff(speedParasite_N)>0) && all(diff(speedInduced_N)<0), ...
    'The airspeed sweep must separate increasing parasite and decreasing induced drag.');
assert(minimumThrustIndex>1 && minimumThrustIndex<numel(speedSweep_mps) && ...
    all(speedFeasible), ...
    'The bounded airspeed sweep must expose an interior thrust minimum and feasible points.');

massSweep_kg=[800 1000 1200 1400 1600];
massCL=zeros(size(massSweep_kg));
massAlpha_deg=zeros(size(massSweep_kg));
massParasite_N=zeros(size(massSweep_kg));
massInduced_N=zeros(size(massSweep_kg));
massThrust_N=zeros(size(massSweep_kg));
for k=1:numel(massSweep_kg)
    sample=model(baselineDensity_kgpm3,60,massSweep_kg(k),0);
    massCL(k)=sample.liftCoefficient;
    massAlpha_deg(k)=sample.angleOfAttack_deg;
    massParasite_N(k)=sample.parasiteDrag_N;
    massInduced_N(k)=sample.inducedDrag_N;
    massThrust_N(k)=sample.thrustRequired_N;
end
assert(all(diff(massCL)>0) && all(diff(massAlpha_deg)>0) && ...
    all(diff(massInduced_N)>0) && all(diff(massThrust_N)>0), ...
    'The mass sweep must raise CL, alpha, induced drag, and required thrust.');
assert(max(massParasite_N)-min(massParasite_N)<tol, ...
    'Mass alone must not change parasite drag at fixed density and speed.');

%% Path-angle symmetry and distinct infeasible requirements
climb=model(baselineDensity_kgpm3,60,1200,5);
descent=model(baselineDensity_kgpm3,60,1200,-5);
expectedThrustDifference_N=2*first.weight_N*sin(5*pi/180);
assert(abs(climb.normalForceRequired_N-descent.normalForceRequired_N)<tol && ...
    abs(climb.drag_N-descent.drag_N)<tol && ...
    abs((climb.thrustRequired_N-descent.thrustRequired_N)- ...
    expectedThrustDifference_N)<1e-9, ...
    'Symmetric climb and descent paths must share normal balance and split thrust by 2*W*sin(gamma).');
negativeThrust=model(baselineDensity_kgpm3,60,1200,-10);
liftLimited=model(baselineDensity_kgpm3,30,1200,0);
thrustLimited=model(baselineDensity_kgpm3,170,1200,0);
assert(negativeThrust.thrustRequired_N<0 && ~negativeThrust.thrustFeasible && ...
    negativeThrust.liftFeasible, ...
    'A steep clean descent must report a negative-thrust infeasibility without inventing reverse thrust.');
assert(~liftLimited.liftFeasible && liftLimited.thrustFeasible, ...
    'A low-speed case must expose the CL limit independently.');
assert(thrustLimited.liftFeasible && ~thrustLimited.thrustFeasible && ...
    thrustLimited.thrustRequired_N>thrustLimited.maximumThrust_N, ...
    'A high-speed case must expose the thrust cap independently.');

%% Deliberately broken dynamic-pressure factor
brokenLiftCoefficient=first.weight_N/(first.airDensity_kgpm3* ...
    first.trueAirspeed_mps^2*first.wingArea_m2);
brokenLift_N=first.dynamicPressure_Pa*first.wingArea_m2*brokenLiftCoefficient;
brokenResidual_N=brokenLift_N-first.normalForceRequired_N;
assert(abs(brokenLift_N/first.normalForceRequired_N-0.5)<tol && ...
    abs(brokenResidual_N/first.normalForceRequired_N+0.5)<tol, ...
    'Omitting the one-half in q must leave a recognizable negative half-weight residual.');

%% Malformed inputs fail clearly, then a valid call recovers
expectFailure(@() model(0,60,1200,0), ...
    'P04:model:PositiveDensity','zero density');
expectFailure(@() model(-1,60,1200,0), ...
    'P04:model:PositiveDensity','negative density');
expectFailure(@() model(0.039,60,1200,0), ...
    'P04:model:DensityRange','density below the learning range');
expectFailure(@() model(2.001,60,1200,0), ...
    'P04:model:DensityRange','density above the learning range');
expectFailure(@() model(baselineDensity_kgpm3,0,1200,0), ...
    'P04:model:PositiveAirspeed','zero true airspeed');
expectFailure(@() model(baselineDensity_kgpm3,-1,1200,0), ...
    'P04:model:PositiveAirspeed','negative true airspeed');
expectFailure(@() model(baselineDensity_kgpm3,19.9,1200,0), ...
    'P04:model:AirspeedRange','true airspeed below the learning range');
expectFailure(@() model(baselineDensity_kgpm3,200.1,1200,0), ...
    'P04:model:AirspeedRange','true airspeed above the learning range');
expectFailure(@() model(baselineDensity_kgpm3,60,0,0), ...
    'P04:model:PositiveMass','zero mass');
expectFailure(@() model(baselineDensity_kgpm3,60,-1,0), ...
    'P04:model:PositiveMass','negative mass');
expectFailure(@() model(baselineDensity_kgpm3,60,399,0), ...
    'P04:model:MassRange','mass below the learning range');
expectFailure(@() model(baselineDensity_kgpm3,60,3001,0), ...
    'P04:model:MassRange','mass above the learning range');
expectFailure(@() model(baselineDensity_kgpm3,60,1200,10.1), ...
    'P04:model:FlightPathAngleRange','flight-path angle above the learning range');
expectFailure(@() model(baselineDensity_kgpm3,60,1200,-10.1), ...
    'P04:model:FlightPathAngleRange','flight-path angle below the learning range');
expectFailure(@() model([0.7 0.8],60,1200,0),'','nonscalar density');
expectFailure(@() model(baselineDensity_kgpm3,60+1i,1200,0),'','complex airspeed');
expectFailure(@() model(baselineDensity_kgpm3,60,NaN,0),'','nonfinite mass');
expectFailure(@() model(baselineDensity_kgpm3,60,1200,Inf),'','nonfinite path angle');
afterFailure=model(baselineDensity_kgpm3,60,1200,0);
assert(isequaln(afterFailure,first), ...
    'Rejected inputs must not alter the next deterministic calculation.');

disp('P04 checks passed: force balance, limits, sweeps, malformed inputs, and broken q factor.');
end

function expectFailure(action,expectedIdentifier,label)
didFail=false;
try
    action();
catch exception
    didFail=true;
    if ~isempty(expectedIdentifier)
        assert(strcmp(exception.identifier,expectedIdentifier), ...
            'Expected %s to raise %s, but received %s.', ...
            label,expectedIdentifier,exception.identifier);
    end
end
assert(didFail,'Expected model to reject %s.',label);
end
