function out = model(speed,alphaDeg,betaDeg,rollDeg,pitchDeg,yawDeg)
%MODEL Express one air-relative velocity vector in wind, body, and NED axes.
% Body axes are x forward, y right, z down. Navigation axes are North,
% East, Down (NED). The direction cosine matrices are passive coordinate
% transforms: v_body = C_wind_to_body*v_wind and
% v_ned = C_body_to_ned*v_body.
arguments
    speed (1,1) double {mustBeFinite,mustBePositive} = 70
    alphaDeg (1,1) double {mustBeFinite} = 6
    betaDeg (1,1) double {mustBeFinite} = 0
    rollDeg (1,1) double {mustBeFinite} = 0
    pitchDeg (1,1) double {mustBeFinite} = 9
    yawDeg (1,1) double {mustBeFinite} = 30
end

if abs(betaDeg)>=90
    error('P02:model:SideslipRange', ...
        'The principal air-data chart requires sideslip strictly between -90 and 90 deg.');
end
if abs(pitchDeg)>=90
    error('P02:model:PitchSingularity', ...
        'This lesson uses the unique 3-2-1 Euler chart strictly between -90 and 90 deg pitch.');
end

ca=cosd(alphaDeg); sa=sind(alphaDeg);
cb=cosd(betaDeg);  sb=sind(betaDeg);
cr=cosd(rollDeg);  sr=sind(rollDeg);
cp=cosd(pitchDeg); sp=sind(pitchDeg);
cy=cosd(yawDeg);   sy=sind(yawDeg);

% Wind-to-body transform C_wind_to_body = R_y(-alpha)*R_z(beta). Its first
% column exposes the air-data relation
% [u;v;w] = V*[cos(alpha)cos(beta); sin(beta); sin(alpha)cos(beta)].
C_wind_to_body=[ca*cb, -ca*sb, -sa; ...
                sb,     cb,     0; ...
                sa*cb, -sa*sb,  ca];

% Body-to-NED transform for the aerospace 3-2-1 yaw-pitch-roll sequence.
C_body_to_ned=[cp*cy, sr*sp*cy-cr*sy, cr*sp*cy+sr*sy; ...
               cp*sy, sr*sp*sy+cr*cy, cr*sp*sy-sr*cy; ...
               -sp,   sr*cp,          cr*cp];
C_wind_to_ned=C_body_to_ned*C_wind_to_body;

velocityWind_mps=[speed;0;0];
velocityBody_mps=C_wind_to_body*velocityWind_mps;
velocityNed_mps=C_body_to_ned*velocityBody_mps;
recoveredBody_mps=C_body_to_ned.'*velocityNed_mps;
horizontalSpeed_mps=hypot(velocityNed_mps(1),velocityNed_mps(2));
trackDeg=atan2d(velocityNed_mps(2),velocityNed_mps(1));
flightPathDeg=atan2d(-velocityNed_mps(3),horizontalSpeed_mps);

orthogonalityError=max([ ...
    norm(C_wind_to_body.'*C_wind_to_body-eye(3),'fro'), ...
    norm(C_body_to_ned.'*C_body_to_ned-eye(3),'fro')]);
determinantError=max(abs([det(C_wind_to_body)-1,det(C_body_to_ned)-1]));
roundTripError_mps=norm(recoveredBody_mps-velocityBody_mps);
normError_mps=abs(norm(velocityNed_mps)-speed);

out=struct( ...
    'speed_mps',speed, ...
    'alphaDeg',alphaDeg, ...
    'betaDeg',betaDeg, ...
    'rollDeg',rollDeg, ...
    'pitchDeg',pitchDeg, ...
    'yawDeg',yawDeg, ...
    'C_wind_to_body',C_wind_to_body, ...
    'C_body_to_ned',C_body_to_ned, ...
    'C_wind_to_ned',C_wind_to_ned, ...
    'velocityWind_mps',velocityWind_mps, ...
    'velocityBody_mps',velocityBody_mps, ...
    'velocityNed_mps',velocityNed_mps, ...
    'recoveredBody_mps',recoveredBody_mps, ...
    'horizontalSpeed_mps',horizontalSpeed_mps, ...
    'trackDeg',trackDeg, ...
    'trackDefined',horizontalSpeed_mps>speed*1e-12, ...
    'flightPathDeg',flightPathDeg, ...
    'orthogonalityError',orthogonalityError, ...
    'determinantError',determinantError, ...
    'roundTripError_mps',roundTripError_mps, ...
    'normError_mps',normError_mps, ...
    'frameConvention','right-handed body x-forward/y-right/z-down and North-East-Down', ...
    'transformDirection','wind components to body components to NED components');
end
