function out = model(timeConstant_s,rateLimit_deg_s)
%MODEL Propagate a transparent first-order actuator with physical limits.
% The signed actuator deflection delta follows a commanded deflection through
% delta_dot = (delta_limited_command-delta)/tau, subject to a symmetric
% rate limit and a symmetric position hard stop. A declared linear gain maps
% delivered deflection into a conceptual body-y moment ledger. P09 uses the
% same physical quantity internally, but its public model does not accept an
% arbitrary moment history and P10 provides no direct adapter.
arguments
    timeConstant_s (1,1) double {mustBeReal,mustBeFinite} = 0.18
    rateLimit_deg_s (1,1) double {mustBeReal,mustBeFinite} = 45
end

if timeConstant_s<0.05 || timeConstant_s>0.50
    error('P10:model:TimeConstantRange', ...
        'Actuator time constant must be between 0.05 and 0.50 s, inclusive.');
end
if rateLimit_deg_s<20 || rateLimit_deg_s>120
    error('P10:model:RateLimitRange', ...
        'Actuator rate limit must be between 20 and 120 deg/s, inclusive.');
end

sampleTime_s=0.01;
timeHorizon_s=5;
time_s=0:sampleTime_s:timeHorizon_s;
positionLimit_deg=15;
momentPerDeflection_Nm_per_deg=80;

% The fixed schedule contains rest, an infeasible positive request, a full
% reversal beyond the negative stop, and a final feasible request.
command_deg=zeros(size(time_s));
command_deg(time_s>=0.5 & time_s<2.0)=25;
command_deg(time_s>=2.0 & time_s<3.5)=-25;
command_deg(time_s>=3.5)=5;

[limitedCommand_deg,deflection_deg,lagRateDemand_deg_s, ...
    rateLimitedDemand_deg_s,actualRate_deg_s,positionRequestInfeasible, ...
    rateLimitActive,kinematicClosureResidual_deg]=simulateActuator( ...
    command_deg,time_s,timeConstant_s,rateLimit_deg_s, ...
    positionLimit_deg,false);

% Deliberately broken comparison: retain the same lag and rate limit while
% omitting both enforcement points of the one declared position envelope.
% The request-infeasibility ledger remains visible even when enforcement is
% disabled, so a broken model cannot erase evidence that the request exceeded
% the declared envelope.
[brokenLimitedCommand_deg,brokenDeflection_deg, ...
    brokenLagRateDemand_deg_s,brokenRateLimitedDemand_deg_s, ...
    brokenActualRate_deg_s,brokenPositionRequestInfeasible, ...
    brokenRateLimitActive,brokenKinematicClosureResidual_deg]=simulateActuator( ...
    command_deg,time_s,timeConstant_s,rateLimit_deg_s, ...
    positionLimit_deg,true);

requestedPitchMoment_Nm=momentPerDeflection_Nm_per_deg*command_deg;
feasiblePitchMoment_Nm=momentPerDeflection_Nm_per_deg*limitedCommand_deg;
deliveredPitchMoment_Nm=momentPerDeflection_Nm_per_deg*deflection_deg;
brokenDeliveredPitchMoment_Nm= ...
    momentPerDeflection_Nm_per_deg*brokenDeflection_deg;
requestedTrackingError_deg=command_deg-deflection_deg;
feasibleTrackingError_deg=limitedCommand_deg-deflection_deg;
momentShortfall_Nm=requestedPitchMoment_Nm-deliveredPitchMoment_Nm;
positionLimitExcess_deg=max(abs(deflection_deg)-positionLimit_deg, ...
    zeros(size(deflection_deg)));
rateLimitExcess_deg_s=max(abs(actualRate_deg_s)-rateLimit_deg_s, ...
    zeros(size(actualRate_deg_s)));
brokenPositionLimitExcess_deg=max( ...
    abs(brokenDeflection_deg)-positionLimit_deg, ...
    zeros(size(brokenDeflection_deg)));
brokenRateLimitExcess_deg_s=max( ...
    abs(brokenActualRate_deg_s)-rateLimit_deg_s, ...
    zeros(size(brokenActualRate_deg_s)));
maximumFeasiblePitchMoment_Nm= ...
    positionLimit_deg*momentPerDeflection_Nm_per_deg;
brokenPeakDeliveredPitchMoment_Nm= ...
    max(abs(brokenDeliveredPitchMoment_Nm));
brokenPeakMomentExcess_Nm=max(0, ...
    brokenPeakDeliveredPitchMoment_Nm-maximumFeasiblePitchMoment_Nm);

positiveNinetyReference_deg=0.9*positionLimit_deg;
positiveNinetyTime_s=firstCrossingTime(time_s, ...
    time_s>=0.5 & deflection_deg>=positiveNinetyReference_deg, ...
    'positive feasible-target 90-percent response');
reversalZeroCrossingTime_s=firstCrossingTime(time_s, ...
    time_s>=2.0 & deflection_deg<=0, ...
    'reversal zero crossing');

out=struct( ...
    'timeConstant_s',timeConstant_s, ...
    'rateLimit_deg_s',rateLimit_deg_s, ...
    'positionLimit_deg',positionLimit_deg, ...
    'sampleTime_s',sampleTime_s, ...
    'timeHorizon_s',timeHorizon_s, ...
    'time_s',time_s, ...
    'sampleCount',numel(time_s), ...
    'updateCount',numel(time_s)-1, ...
    'command_deg',command_deg, ...
    'limitedCommand_deg',limitedCommand_deg, ...
    'deflection_deg',deflection_deg, ...
    'lagRateDemand_deg_s',lagRateDemand_deg_s, ...
    'rateLimitedDemand_deg_s',rateLimitedDemand_deg_s, ...
    'actualRate_deg_s',actualRate_deg_s, ...
    'positionRequestInfeasible',positionRequestInfeasible, ...
    'rateLimitActive',rateLimitActive, ...
    'kinematicClosureResidual_deg',kinematicClosureResidual_deg, ...
    'requestedTrackingError_deg',requestedTrackingError_deg, ...
    'feasibleTrackingError_deg',feasibleTrackingError_deg, ...
    'rmsRequestedTrackingError_deg', ...
    sqrt(mean(requestedTrackingError_deg.^2)), ...
    'rmsFeasibleTrackingError_deg', ...
    sqrt(mean(feasibleTrackingError_deg.^2)), ...
    'totalAbsoluteFeasibleTrackingError_deg_s', ...
    sum(abs(feasibleTrackingError_deg(1:end-1)))*sampleTime_s, ...
    'infeasibleCommandDuration_s', ...
    sum(positionRequestInfeasible(1:end-1))*sampleTime_s, ...
    'rateLimitedDuration_s', ...
    sum(rateLimitActive(1:end-1))*sampleTime_s, ...
    'positiveNinetyReference_deg',positiveNinetyReference_deg, ...
    'positiveNinetyTime_s',positiveNinetyTime_s, ...
    'positiveNinetyResponseTime_s',positiveNinetyTime_s-0.5, ...
    'reversalZeroCrossingTime_s',reversalZeroCrossingTime_s, ...
    'reversalZeroCrossingDelay_s',reversalZeroCrossingTime_s-2.0, ...
    'peakDeflection_deg',max(abs(deflection_deg)), ...
    'peakRate_deg_s',max(abs(actualRate_deg_s)), ...
    'finalDeflection_deg',deflection_deg(end), ...
    'positionLimitExcess_deg',positionLimitExcess_deg, ...
    'rateLimitExcess_deg_s',rateLimitExcess_deg_s, ...
    'momentPerDeflection_Nm_per_deg',momentPerDeflection_Nm_per_deg, ...
    'requestedPitchMoment_Nm',requestedPitchMoment_Nm, ...
    'feasiblePitchMoment_Nm',feasiblePitchMoment_Nm, ...
    'deliveredPitchMoment_Nm',deliveredPitchMoment_Nm, ...
    'momentShortfall_Nm',momentShortfall_Nm, ...
    'peakDeliveredPitchMoment_Nm',max(abs(deliveredPitchMoment_Nm)), ...
    'maximumFeasiblePitchMoment_Nm',maximumFeasiblePitchMoment_Nm, ...
    'maximumMomentShortfall_Nm',max(abs(momentShortfall_Nm)), ...
    'brokenLimitedCommand_deg',brokenLimitedCommand_deg, ...
    'brokenDeflection_deg',brokenDeflection_deg, ...
    'brokenLagRateDemand_deg_s',brokenLagRateDemand_deg_s, ...
    'brokenRateLimitedDemand_deg_s', ...
    brokenRateLimitedDemand_deg_s, ...
    'brokenActualRate_deg_s',brokenActualRate_deg_s, ...
    'brokenPositionRequestInfeasible', ...
    brokenPositionRequestInfeasible, ...
    'brokenRateLimitActive',brokenRateLimitActive, ...
    'brokenKinematicClosureResidual_deg', ...
    brokenKinematicClosureResidual_deg, ...
    'brokenDeliveredPitchMoment_Nm',brokenDeliveredPitchMoment_Nm, ...
    'brokenPositionLimitExcess_deg',brokenPositionLimitExcess_deg, ...
    'brokenRateLimitExcess_deg_s',brokenRateLimitExcess_deg_s, ...
    'brokenPeakDeflection_deg',max(abs(brokenDeflection_deg)), ...
    'brokenPeakDeliveredPitchMoment_Nm', ...
    brokenPeakDeliveredPitchMoment_Nm, ...
    'brokenPeakMomentExcess_Nm',brokenPeakMomentExcess_Nm, ...
    'brokenMaximumPositionExcess_deg', ...
    max(brokenPositionLimitExcess_deg), ...
    'actuatorEquation',[ ...
        'delta_dot=clip((delta_cmd_limited-delta)/tau,+/-rate_limit); ' ...
        'delta is clipped to +/-position_limit after each explicit update'], ...
    'signConvention',[ ...
        'positive generic control-surface deflection produces positive ' ...
        'pitch moment through the declared linear teaching gain'], ...
    'commandSchedule',[ ...
        '0 deg to 0.5 s; +25 deg to 2.0 s; -25 deg to 3.5 s; ' ...
        '+5 deg through 5.0 s'], ...
    'positionRequestLedgerDefinition',[ ...
        'true where requested command exceeds the declared position ' ...
        'envelope, whether or not the comparison enforces it'], ...
    'stateClipRole',[ ...
        'defensive post-update guard; inactive on the declared accepted ' ...
        'grid and parameter domain because each complete update moves ' ...
        'toward a position-limited target'], ...
    'analysisScope',[ ...
        'deterministic single-axis actuator teaching model and conceptual ' ...
        'body-y moment ledger; no direct P09 adapter, servo current, ' ...
        'backlash, hinge moment, aerodynamics, controller, sensor, or ' ...
        'identified-aircraft fidelity']);
end

function [limitedCommand_deg,deflection_deg,lagRateDemand_deg_s, ...
    rateLimitedDemand_deg_s,actualRate_deg_s,positionRequestInfeasible, ...
    rateLimitActive,kinematicClosureResidual_deg] = simulateActuator( ...
    command_deg,time_s,timeConstant_s,rateLimit_deg_s, ...
    positionLimit_deg,omitPositionLimit)
%SIMULATEACTUATOR Apply lag, rate limiting, and optionally the position envelope.
sampleCount=numel(time_s);
if omitPositionLimit
    limitedCommand_deg=command_deg;
else
    limitedCommand_deg=clampArray(command_deg, ...
        -positionLimit_deg,positionLimit_deg);
end
% This position-limit ledger marks an infeasible requested command, not
% physical dwell time at a mechanical stop or successful enforcement. Keep
% it in the broken comparison so the diagnostic remains independent of the
% behavior it is meant to assess. State clipping is separate.
positionRequestInfeasible=abs(command_deg)>positionLimit_deg;

deflection_deg=zeros(1,sampleCount);
lagRateDemand_deg_s=zeros(1,sampleCount);
rateLimitedDemand_deg_s=zeros(1,sampleCount);
actualRate_deg_s=zeros(1,sampleCount);
rateLimitActive=false(1,sampleCount);
kinematicClosureResidual_deg=zeros(1,sampleCount);

for k=1:sampleCount-1
    step_s=time_s(k+1)-time_s(k);
    lagRateDemand_deg_s(k)= ...
        (limitedCommand_deg(k)-deflection_deg(k))/timeConstant_s;
    rateLimitedDemand_deg_s(k)=clampScalar( ...
        lagRateDemand_deg_s(k),-rateLimit_deg_s,rateLimit_deg_s);
    rateLimitActive(k)= ...
        abs(lagRateDemand_deg_s(k))>rateLimit_deg_s;
    candidateDeflection_deg=deflection_deg(k)+ ...
        step_s*rateLimitedDemand_deg_s(k);
    if omitPositionLimit
        deflection_deg(k+1)=candidateDeflection_deg;
    else
        deflection_deg(k+1)=clampScalar(candidateDeflection_deg, ...
            -positionLimit_deg,positionLimit_deg);
    end
    actualRate_deg_s(k)= ...
        (deflection_deg(k+1)-deflection_deg(k))/step_s;
    % This is a kinematic rate/state identity. Independent recurrence
    % reconstruction belongs in run_checks.m rather than this model helper.
    kinematicClosureResidual_deg(k)=deflection_deg(k+1)- ...
        deflection_deg(k)-step_s*actualRate_deg_s(k);
end

lagRateDemand_deg_s(end)= ...
    (limitedCommand_deg(end)-deflection_deg(end))/timeConstant_s;
rateLimitedDemand_deg_s(end)=clampScalar( ...
    lagRateDemand_deg_s(end),-rateLimit_deg_s,rateLimit_deg_s);
actualRate_deg_s(end)=rateLimitedDemand_deg_s(end);
rateLimitActive(end)=abs(lagRateDemand_deg_s(end))>rateLimit_deg_s;
% Samples 1:end-1 store delivered interval slopes. With no 501st update,
% the terminal sample stores the instantaneous derivative that continuation
% would apply; duration metrics intentionally use only 1:end-1.
end

function value = clampScalar(value,lowerBound,upperBound)
%CLAMPSCALAR Apply an explicit inclusive scalar saturation.
value=min(upperBound,max(lowerBound,value));
end

function values = clampArray(values,lowerBound,upperBound)
%CLAMPARRAY Apply the same explicit saturation element by element.
values=min(upperBound,max(lowerBound,values));
end

function crossingTime_s = firstCrossingTime(time_s,condition,label)
%FIRSTCROSSINGTIME Return a required event time for deterministic metrics.
index=find(condition,1,'first');
if isempty(index)
    error('P10:model:ExpectedCrossingMissing', ...
        'The accepted actuator range did not produce the %s.',label);
end
crossingTime_s=time_s(index);
end
