function run_checks
%RUN_CHECKS Independent checks for P10 actuator dynamics and limits.
clear model;
tol=1e-11;

%% Determinism, fixed shape, finite resources, and bounded accepted inputs
first=model(0.18,45);
second=model(0.18,45);
assert(isequaln(first,second), ...
    'Identical actuator inputs must produce identical output structures.');
assert(first.sampleCount==501 && first.updateCount==500 && ...
    first.sampleTime_s==0.01 && first.timeHorizon_s==5 && ...
    isequal(size(first.time_s),[1 501]) && ...
    first.time_s(1)==0 && first.time_s(end)==5, ...
    'The synchronous resource boundary must remain 501 samples and 500 updates.');

numericRowFields={ ...
    'command_deg','limitedCommand_deg','deflection_deg', ...
    'lagRateDemand_deg_s','rateLimitedDemand_deg_s','actualRate_deg_s', ...
    'kinematicClosureResidual_deg','requestedTrackingError_deg', ...
    'feasibleTrackingError_deg','positionLimitExcess_deg', ...
    'rateLimitExcess_deg_s','requestedPitchMoment_Nm', ...
    'feasiblePitchMoment_Nm','deliveredPitchMoment_Nm', ...
    'momentShortfall_Nm','brokenLimitedCommand_deg', ...
    'brokenDeflection_deg','brokenLagRateDemand_deg_s', ...
    'brokenRateLimitedDemand_deg_s','brokenActualRate_deg_s', ...
    'brokenKinematicClosureResidual_deg', ...
    'brokenDeliveredPitchMoment_Nm', ...
    'brokenPositionLimitExcess_deg','brokenRateLimitExcess_deg_s'};
for k=1:numel(numericRowFields)
    value=first.(numericRowFields{k});
    assert(isequal(size(value),[1 501]) && isreal(value) && ...
        all(isfinite(value)), ...
        'Every numeric history must remain a finite 1-by-501 row vector.');
end
logicalRowFields={'positionRequestInfeasible','rateLimitActive', ...
    'brokenPositionRequestInfeasible','brokenRateLimitActive'};
for k=1:numel(logicalRowFields)
    value=first.(logicalRowFields{k});
    assert(isequal(size(value),[1 501]) && islogical(value), ...
        'Every limit ledger must remain a logical 1-by-501 row vector.');
end

timeEdges=[0.05 0.50];
rateEdges=[20 120];
acceptedCornerCount=0;
for timeIndex=1:numel(timeEdges)
    for rateIndex=1:numel(rateEdges)
        sample=model(timeEdges(timeIndex),rateEdges(rateIndex));
        acceptedCornerCount=acceptedCornerCount+1;
        completeCandidate_deg=sample.deflection_deg(1:end-1)+ ...
            diff(sample.time_s).*sample.rateLimitedDemand_deg_s(1:end-1);
        assert(sample.sampleCount==501 && sample.updateCount==500 && ...
            all(isfinite(sample.deflection_deg)) && ...
            all(isfinite(sample.brokenDeflection_deg)) && ...
            max(abs(sample.deflection_deg))<=sample.positionLimit_deg+tol && ...
            max(abs(sample.actualRate_deg_s))<=sample.rateLimit_deg_s+tol && ...
            max(abs(sample.brokenActualRate_deg_s))<= ...
            sample.rateLimit_deg_s+tol && ...
            max(abs(completeCandidate_deg- ...
            sample.deflection_deg(2:end)))<tol && ...
            max(abs(completeCandidate_deg))<= ...
            sample.positionLimit_deg+tol && ...
            max(abs(sample.brokenDeflection_deg))<30, ...
            ['Every accepted input corner must remain finite and bounded, ' ...
            'and its pre-clip candidate must equal the delivered next state.']);
    end
end
assert(acceptedCornerCount==4, ...
    'The accepted-corner resource check must remain fixed at four calls.');

representativeTimes=[0.05 0.18 0.50];
representativeRates=[20 45 120];
representativeCaseCount=0;
for timeIndex=1:numel(representativeTimes)
    for rateIndex=1:numel(representativeRates)
        sample=model(representativeTimes(timeIndex), ...
            representativeRates(rateIndex));
        representativeCaseCount=representativeCaseCount+1;
        assert(sample.sampleCount==501 && sample.updateCount==500 && ...
            all(isfinite(sample.actualRate_deg_s)), ...
            'The representative grid must retain fixed finite work.');
    end
end
assert(representativeCaseCount==9 && representativeCaseCount<=10, ...
    'The representative resource grid must stay capped at nine calls.');

%% Independent command reconstruction and every recurrence update
expectedCommand_deg=zeros(1,first.sampleCount);
expectedCommand_deg(first.time_s>=0.5 & first.time_s<2.0)=25;
expectedCommand_deg(first.time_s>=2.0 & first.time_s<3.5)=-25;
expectedCommand_deg(first.time_s>=3.5)=5;
[expectedLimitedCommand_deg,expectedDeflection_deg, ...
    expectedLagRateDemand_deg_s,expectedRateLimitedDemand_deg_s, ...
    expectedActualRate_deg_s,expectedPositionRequestInfeasible, ...
    expectedRateLimitActive,expectedKinematicClosure_deg]= ...
    independentActuator(expectedCommand_deg,first.time_s,0.18,45,15,false);
[expectedBrokenCommand_deg,expectedBrokenDeflection_deg, ...
    expectedBrokenLagRateDemand_deg_s, ...
    expectedBrokenRateLimitedDemand_deg_s, ...
    expectedBrokenActualRate_deg_s, ...
    expectedBrokenPositionRequestInfeasible, ...
    expectedBrokenRateLimitActive,expectedBrokenKinematicClosure_deg]= ...
    independentActuator(expectedCommand_deg,first.time_s,0.18,45,15,true);

assert(isequal(first.command_deg,expectedCommand_deg) && ...
    isequal(first.limitedCommand_deg,expectedLimitedCommand_deg) && ...
    isequal(first.positionRequestInfeasible, ...
    expectedPositionRequestInfeasible) && ...
    isequal(first.rateLimitActive,expectedRateLimitActive), ...
    'Stored command and complete limit ledgers must match reconstruction.');
assert(max(abs(first.deflection_deg-expectedDeflection_deg))<tol && ...
    max(abs(first.lagRateDemand_deg_s- ...
    expectedLagRateDemand_deg_s))<tol && ...
    max(abs(first.rateLimitedDemand_deg_s- ...
    expectedRateLimitedDemand_deg_s))<tol && ...
    max(abs(first.actualRate_deg_s-expectedActualRate_deg_s))<tol && ...
    max(abs(first.kinematicClosureResidual_deg- ...
    expectedKinematicClosure_deg))<tol, ...
    'Every complete actuator update must match an independent recurrence.');
assert(isequal(first.brokenLimitedCommand_deg,expectedBrokenCommand_deg) && ...
    isequal(first.brokenPositionRequestInfeasible, ...
    expectedBrokenPositionRequestInfeasible) && ...
    isequal(first.brokenRateLimitActive,expectedBrokenRateLimitActive) && ...
    max(abs(first.brokenDeflection_deg- ...
    expectedBrokenDeflection_deg))<tol && ...
    max(abs(first.brokenLagRateDemand_deg_s- ...
    expectedBrokenLagRateDemand_deg_s))<tol && ...
    max(abs(first.brokenRateLimitedDemand_deg_s- ...
    expectedBrokenRateLimitedDemand_deg_s))<tol && ...
    max(abs(first.brokenActualRate_deg_s- ...
    expectedBrokenActualRate_deg_s))<tol && ...
    max(abs(first.brokenKinematicClosureResidual_deg- ...
    expectedBrokenKinematicClosure_deg))<tol, ...
    'Every broken actuator update must match the isolated independent recurrence.');

expectedMomentGain_Nm_per_deg=80;
assert(isequal(first.requestedPitchMoment_Nm, ...
    expectedMomentGain_Nm_per_deg*expectedCommand_deg) && ...
    isequal(first.feasiblePitchMoment_Nm, ...
    expectedMomentGain_Nm_per_deg*expectedLimitedCommand_deg) && ...
    max(abs(first.deliveredPitchMoment_Nm- ...
    expectedMomentGain_Nm_per_deg*expectedDeflection_deg))<tol && ...
    max(abs(first.brokenDeliveredPitchMoment_Nm- ...
    expectedMomentGain_Nm_per_deg*expectedBrokenDeflection_deg))<tol, ...
    'Requested, feasible, and delivered pitch moments must use the declared gain.');

%% Recognizable baseline, exact rest, and physical limit invariants
assert(abs(first.finalDeflection_deg-4.993078514854386)<1e-11 && ...
    abs(first.peakDeflection_deg-14.996320961068609)<1e-11 && ...
    abs(first.peakRate_deg_s-45)<1e-10 && ...
    abs(first.rmsRequestedTrackingError_deg-13.245442291719344)<1e-11 && ...
    abs(first.rmsFeasibleTrackingError_deg-7.700152257797825)<1e-11 && ...
    abs(first.totalAbsoluteFeasibleTrackingError_deg_s- ...
    19.316555655893882)<1e-11 && ...
    first.positiveNinetyReference_deg==13.5 && ...
    abs(first.positiveNinetyResponseTime_s-0.45)<1e-12 && ...
    abs(first.reversalZeroCrossingDelay_s-0.34)<1e-12 && ...
    abs(first.infeasibleCommandDuration_s-3.00)<1e-12 && ...
    abs(first.rateLimitedDuration_s-0.92)<1e-12 && ...
    abs(first.peakDeliveredPitchMoment_Nm-1199.7056768854886)<1e-9, ...
    'The deterministic baseline signature must remain recognizable.');

rest=first.time_s<0.5;
assert(all(first.command_deg(rest)==0) && ...
    all(first.limitedCommand_deg(rest)==0) && ...
    all(first.deflection_deg(rest)==0) && ...
    all(first.actualRate_deg_s(rest)==0) && ...
    all(first.deliveredPitchMoment_Nm(rest)==0), ...
    'Before the first command, the exact rest limiting case must remain zero.');
assert(max(first.positionLimitExcess_deg)==0 && ...
    max(first.rateLimitExcess_deg_s)<1e-10 && ...
    max(abs(first.kinematicClosureResidual_deg))<1e-12 && ...
    max(abs(first.deflection_deg))<=first.positionLimit_deg && ...
    max(abs(first.actualRate_deg_s))<=first.rateLimit_deg_s+tol, ...
    'The complete trajectory must obey position, rate, and update invariants.');

%% Large reversal transitions from rate-limited motion back to lag
reversalIndex=find(first.time_s>=2.0,1,'first');
releaseOffset=find(~first.rateLimitActive( ...
    reversalIndex:first.updateCount),1,'first');
assert(~isempty(releaseOffset), ...
    'The baseline reversal must eventually leave the rate-limited regime.');
releaseIndex=reversalIndex+releaseOffset-1;
rateBoundedIndices=reversalIndex:releaseIndex-1;
assert(first.rateLimitActive(reversalIndex) && ...
    all(first.rateLimitActive(rateBoundedIndices)) && ...
    max(abs(first.actualRate_deg_s(rateBoundedIndices)+ ...
    first.rateLimit_deg_s))<tol, ...
    'The large reversal must initially move at the negative rate stop.');
assert(first.time_s(releaseIndex)>first.reversalZeroCrossingTime_s && ...
    ~first.rateLimitActive(releaseIndex) && ...
    abs(first.actualRate_deg_s(releaseIndex)- ...
    first.lagRateDemand_deg_s(releaseIndex))<tol && ...
    abs(first.actualRate_deg_s(releaseIndex))<first.rateLimit_deg_s, ...
    'After crossing zero, the baseline must release cleanly back to lag dynamics.');

%% Inactive-rate limiting case reduces to first-order Euler dynamics
lagOnly=model(0.50,120);
assert(~any(lagOnly.rateLimitActive), ...
    'The declared lag-only corner must never activate its rate stop.');
for k=1:lagOnly.updateCount
    expectedNext=(1-lagOnly.sampleTime_s/lagOnly.timeConstant_s)* ...
        lagOnly.deflection_deg(k)+ ...
        (lagOnly.sampleTime_s/lagOnly.timeConstant_s)* ...
        lagOnly.limitedCommand_deg(k);
    assert(abs(lagOnly.deflection_deg(k+1)-expectedNext)<tol, ...
        'Without rate limiting, every update must reduce to Euler lag dynamics.');
end

%% Two isolated parameter sweeps
timeSweep=[0.08 0.12 0.18 0.28 0.40];
timeResponse=zeros(size(timeSweep));
timeError=zeros(size(timeSweep));
for k=1:numel(timeSweep)
    sample=model(timeSweep(k),45);
    assert(isequal(sample.command_deg,first.command_deg) && ...
        isequal(sample.limitedCommand_deg,first.limitedCommand_deg) && ...
        sample.rateLimit_deg_s==first.rateLimit_deg_s && ...
        sample.positionLimit_deg==first.positionLimit_deg, ...
        'The time-constant sweep must isolate lag from command and limits.');
    timeResponse(k)=sample.positiveNinetyResponseTime_s;
    timeError(k)=sample.rmsFeasibleTrackingError_deg;
end
assert(all(diff(timeResponse)>0) && all(diff(timeError)>0), ...
    'Increasing time constant must delay response and increase feasible error.');

rateSweep=[20 30 45 60 80];
rateResponse=zeros(size(rateSweep));
rateError=zeros(size(rateSweep));
peakRate=zeros(size(rateSweep));
rateReversalDelay=zeros(size(rateSweep));
for k=1:numel(rateSweep)
    sample=model(0.18,rateSweep(k));
    assert(isequal(sample.command_deg,first.command_deg) && ...
        isequal(sample.limitedCommand_deg,first.limitedCommand_deg) && ...
        sample.timeConstant_s==first.timeConstant_s && ...
        sample.positionLimit_deg==first.positionLimit_deg, ...
        'The rate sweep must isolate rate authority from command, lag, and stop.');
    rateResponse(k)=sample.positiveNinetyResponseTime_s;
    rateError(k)=sample.rmsFeasibleTrackingError_deg;
    peakRate(k)=sample.peakRate_deg_s;
    rateReversalDelay(k)=sample.reversalZeroCrossingDelay_s;
    assert(sample.rateLimitActive(reversalIndex) && ...
        abs(sample.actualRate_deg_s(reversalIndex)+rateSweep(k))<tol, ...
        'Every rate sweep case must enter its declared stop at reversal.');
end
assert(all(diff(rateResponse)<0) && all(diff(rateError)<0) && ...
    all(diff(peakRate)>0) && all(diff(rateReversalDelay)<0), ...
    'Increasing rate authority must shorten response and reversal delays.');

%% Deliberately broken position envelope
assert(isequal(first.brokenLimitedCommand_deg,first.command_deg) && ...
    isequal(first.brokenPositionRequestInfeasible, ...
    first.positionRequestInfeasible) && ...
    any(first.brokenPositionRequestInfeasible) && ...
    first.brokenMaximumPositionExcess_deg>9 && ...
    abs(first.brokenMaximumPositionExcess_deg- ...
    9.986896548243244)<1e-11 && ...
    abs(first.brokenPeakDeliveredPitchMoment_Nm- ...
    1998.9517238594594)<1e-9 && ...
    abs(first.brokenPeakMomentExcess_Nm- ...
    798.9517238594594)<1e-9 && ...
    first.maximumFeasiblePitchMoment_Nm==1200 && ...
    max(first.brokenRateLimitExcess_deg_s)<1e-10 && ...
    max(abs(first.brokenKinematicClosureResidual_deg))<1e-12, ...
    'The broken case must omit only the position envelope and invent authority.');
positiveStepIndex=find(first.time_s>=0.5,1,'first');
positiveReleaseOffset=find(~first.rateLimitActive( ...
    positiveStepIndex:first.updateCount),1,'first');
positiveReleaseIndex=positiveStepIndex+positiveReleaseOffset-1;
firstDivergenceIndex=find(abs(first.brokenDeflection_deg- ...
    first.deflection_deg)>tol,1,'first');
assert(~isempty(positiveReleaseOffset) && ...
    isequal(first.brokenDeflection_deg(1:positiveReleaseIndex), ...
    first.deflection_deg(1:positiveReleaseIndex)) && ...
    firstDivergenceIndex==positiveReleaseIndex+1 && ...
    abs(first.time_s(firstDivergenceIndex)-0.67)<tol, ...
    ['Complete and broken trajectories must agree while the initial rate ' ...
    'stop masks the omitted target envelope, then diverge when complete ' ...
    'motion returns to lag.']);

%% Malformed inputs fail clearly, then a valid call recovers
expectFailure(@() model(0.049,45), ...
    'P10:model:TimeConstantRange','time constant below range');
expectFailure(@() model(0.501,45), ...
    'P10:model:TimeConstantRange','time constant above range');
expectFailure(@() model(0.18,19.9), ...
    'P10:model:RateLimitRange','rate limit below range');
expectFailure(@() model(0.18,120.1), ...
    'P10:model:RateLimitRange','rate limit above range');
expectFailure(@() model([0.18 0.20],45),'','nonscalar time constant');
expectFailure(@() model(0.18,45+1i),'','complex rate limit');
expectFailure(@() model(NaN,45),'','nonfinite time constant');
expectFailure(@() model(0.18,Inf),'','nonfinite rate limit');
afterFailure=model(0.18,45);
assert(isequaln(afterFailure,first), ...
    'Rejected inputs must not poison deterministic recovery.');

disp(['P10 checks passed: fixed actuator recurrence, command reconstruction, ' ...
    'position/rate invariants, limits, isolated sweeps, malformed-input ' ...
    'recovery, capped resources, and broken position-envelope detection.']);
end

function [limitedCommand_deg,deflection_deg,lagRateDemand_deg_s, ...
    rateLimitedDemand_deg_s,actualRate_deg_s,positionRequestInfeasible, ...
    rateLimitActive,kinematicClosureResidual_deg] = independentActuator( ...
    command_deg,time_s,timeConstant_s,rateLimit_deg_s, ...
    positionLimit_deg,omitPositionLimit)
%INDEPENDENTACTUATOR Reconstruct the stated equations without model helpers.
if omitPositionLimit
    limitedCommand_deg=command_deg;
else
    limitedCommand_deg=min(positionLimit_deg, ...
        max(-positionLimit_deg,command_deg));
end
positionRequestInfeasible=abs(command_deg)>positionLimit_deg;
sampleCount=numel(time_s);
deflection_deg=zeros(1,sampleCount);
lagRateDemand_deg_s=zeros(1,sampleCount);
rateLimitedDemand_deg_s=zeros(1,sampleCount);
actualRate_deg_s=zeros(1,sampleCount);
rateLimitActive=false(1,sampleCount);
kinematicClosureResidual_deg=zeros(1,sampleCount);
for k=1:sampleCount-1
    step_s=time_s(k+1)-time_s(k);
    lagRateDemand_deg_s(k)= ...
        (limitedCommand_deg(k)-deflection_deg(k))/timeConstant_s;
    rateLimitedDemand_deg_s(k)=min(rateLimit_deg_s, ...
        max(-rateLimit_deg_s,lagRateDemand_deg_s(k)));
    rateLimitActive(k)=abs(lagRateDemand_deg_s(k))>rateLimit_deg_s;
    nextDeflection=deflection_deg(k)+ ...
        step_s*rateLimitedDemand_deg_s(k);
    if omitPositionLimit
        deflection_deg(k+1)=nextDeflection;
    else
        deflection_deg(k+1)=min(positionLimit_deg, ...
            max(-positionLimit_deg,nextDeflection));
    end
    actualRate_deg_s(k)= ...
        (deflection_deg(k+1)-deflection_deg(k))/step_s;
    kinematicClosureResidual_deg(k)=deflection_deg(k+1)- ...
        deflection_deg(k)-step_s*actualRate_deg_s(k);
end
lagRateDemand_deg_s(end)= ...
    (limitedCommand_deg(end)-deflection_deg(end))/timeConstant_s;
rateLimitedDemand_deg_s(end)=min(rateLimit_deg_s, ...
    max(-rateLimit_deg_s,lagRateDemand_deg_s(end)));
actualRate_deg_s(end)=rateLimitedDemand_deg_s(end);
rateLimitActive(end)=abs(lagRateDemand_deg_s(end))>rateLimit_deg_s;
end

function expectFailure(action,expectedIdentifier,label)
%EXPECTFAILURE Require clear rejection and optionally an exact identifier.
didFail=false;
try
    action();
catch exception
    didFail=true;
    if ~isempty(expectedIdentifier)
        assert(strcmp(exception.identifier,expectedIdentifier), ...
            'Expected %s to raise %s, but received %s.', ...
            label,expectedIdentifier,exception.identifier);
    end
end
assert(didFail,'Expected model to reject %s.',label);
end
