function out=model(speedGain_per_s,throttleTimeConstant_s,speedFeedbackSign)
%MODEL Deterministic level-flight speed control with throttle lag.
% True airspeed and forward force are positive along the flight path.
% Throttle is normalized to [0,1]. The visible drag feedforward is an
% exact teaching-model cancellation, not an engine deck or aircraft adapter.
arguments
    speedGain_per_s (1,1) double {mustBeReal,mustBeFinite}=0.15
    throttleTimeConstant_s (1,1) double {mustBeReal,mustBeFinite}=0.8
    speedFeedbackSign (1,1) double {mustBeReal,mustBeFinite}=1
end

if speedGain_per_s<0 || speedGain_per_s>0.3
    error('P15:model:SpeedGainRange', ...
        'Speed gain must be between 0 and 0.3 per second inclusive.');
end
if throttleTimeConstant_s<0.2 || throttleTimeConstant_s>1.4
    error('P15:model:ThrottleTimeConstantRange', ...
        'Throttle time constant must be between 0.2 and 1.4 seconds inclusive.');
end
if speedFeedbackSign~=1 && speedFeedbackSign~=-1
    error('P15:model:FeedbackSign', ...
        'Speed feedback sign must be +1 for correct feedback or -1 for the broken case.');
end

sampleTime_s=0.02;
timeHorizon_s=30;
time_s=0:sampleTime_s:timeHorizon_s;
sampleCount=numel(time_s);
commandStepTime_s=1;
initialTrueAirspeed_mps=60;
commandedTrueAirspeed_mps=70;
speedCommandStep_mps= ...
    commandedTrueAirspeed_mps-initialTrueAirspeed_mps;

% Retain the transparent level-flight constants and drag decomposition used
% conceptually in P04. Constant lift makes parasite drag grow with V^2 and
% induced drag fall with 1/V^2 over the declared above-stall envelope.
airDensity_kgpm3=0.736115547399152;
wingArea_m2=16.2;
parasiteDragCoefficient=0.025;
inducedDragFactor=0.045;
mass_kg=1200;
gravity_mps2=9.80665;
maximumLiftCoefficient=1.4;
maximumThrust_N=4000;
weight_N=mass_kg*gravity_mps2;
parasiteDragScale_N_per_mps2= ...
    0.5*airDensity_kgpm3*wingArea_m2*parasiteDragCoefficient;
inducedDragScale_N_mps2=2*inducedDragFactor*weight_N^2/( ...
    airDensity_kgpm3*wingArea_m2);
stallSpeed_mps=sqrt(2*weight_N/( ...
    airDensity_kgpm3*wingArea_m2*maximumLiftCoefficient));
initialDrag_N=parasiteDragScale_N_per_mps2* ...
    initialTrueAirspeed_mps^2+inducedDragScale_N_mps2/ ...
    initialTrueAirspeed_mps^2;
trimThrottle=initialDrag_N/maximumThrust_N;
commandedDrag_N=parasiteDragScale_N_per_mps2* ...
    commandedTrueAirspeed_mps^2+inducedDragScale_N_mps2/ ...
    commandedTrueAirspeed_mps^2;
commandedEquilibriumThrottle=commandedDrag_N/maximumThrust_N;

speedCommand_mps=initialTrueAirspeed_mps+ ...
    speedCommandStep_mps*double(time_s>=commandStepTime_s);
trueAirspeed_mps=zeros(1,sampleCount);
speedError_mps=zeros(1,sampleCount);
speedErrorUsed_mps=zeros(1,sampleCount);
parasiteDrag_N=zeros(1,sampleCount);
inducedDrag_N=zeros(1,sampleCount);
drag_N=zeros(1,sampleCount);
requestedAcceleration_mps2=zeros(1,sampleCount);
thrustCommandUnclamped_N=zeros(1,sampleCount);
thrustCommand_N=zeros(1,sampleCount);
throttleCommand=zeros(1,sampleCount);
throttleActual=zeros(1,sampleCount);
throttleRate_per_s=zeros(1,sampleCount);
thrustActual_N=zeros(1,sampleCount);
netForwardForce_N=zeros(1,sampleCount);
longitudinalAcceleration_mps2=zeros(1,sampleCount);

trueAirspeed_mps(1)=initialTrueAirspeed_mps;
throttleActual(1)=trimThrottle;
for k=1:sampleCount
    speedError_mps(k)=speedCommand_mps(k)-trueAirspeed_mps(k);
    speedErrorUsed_mps(k)=speedFeedbackSign*speedError_mps(k);

    parasiteDrag_N(k)=parasiteDragScale_N_per_mps2* ...
        trueAirspeed_mps(k)^2;
    inducedDrag_N(k)=inducedDragScale_N_mps2/ ...
        trueAirspeed_mps(k)^2;
    drag_N(k)=parasiteDrag_N(k)+inducedDrag_N(k);

    % The gain maps speed error to desired acceleration; multiplying by
    % mass exposes the corrective force added to current-drag feedforward.
    requestedAcceleration_mps2(k)= ...
        speedGain_per_s*speedErrorUsed_mps(k);
    thrustCommandUnclamped_N(k)=drag_N(k)+ ...
        mass_kg*requestedAcceleration_mps2(k);
    thrustCommand_N(k)=min(max(thrustCommandUnclamped_N(k),0), ...
        maximumThrust_N);
    throttleCommand(k)=thrustCommand_N(k)/maximumThrust_N;

    % P10's actuator lesson transfers conceptually: requested throttle is
    % not delivered throttle. This first-order lag remains explicit.
    throttleRate_per_s(k)= ...
        (throttleCommand(k)-throttleActual(k))/ ...
        throttleTimeConstant_s;
    thrustActual_N(k)=maximumThrust_N*throttleActual(k);
    netForwardForce_N(k)=thrustActual_N(k)-drag_N(k);
    longitudinalAcceleration_mps2(k)= ...
        netForwardForce_N(k)/mass_kg;

    % Fixed-step forward Euler; every next state uses sample-k values.
    if k<sampleCount
        trueAirspeed_mps(k+1)=trueAirspeed_mps(k)+ ...
            sampleTime_s*longitudinalAcceleration_mps2(k);
        throttleActual(k+1)=throttleActual(k)+ ...
            sampleTime_s*throttleRate_per_s(k);
    end
end

thrustCommandSaturated=thrustCommandUnclamped_N<0 | ...
    thrustCommandUnclamped_N>maximumThrust_N;
activeMask=time_s>=commandStepTime_s;
activeSampleCount=sum(activeMask);
throttleTrackingError=throttleCommand-throttleActual;
throttleTrackingRMS=sqrt(mean(throttleTrackingError(activeMask).^2));
speedTrackingRMS_mps=sqrt(mean(speedError_mps(activeMask).^2));
finalSpeedError_mps=speedError_mps(end);
speedErrorAtTenSeconds_mps=speedError_mps( ...
    find(time_s>=10,1,'first'));
speedAtFiveSeconds_mps=trueAirspeed_mps( ...
    find(time_s>=5,1,'first'));
captureTolerance_mps=0.1*abs(speedCommandStep_mps);
captureIndex=find(activeMask & ...
    abs(speedError_mps)<=captureTolerance_mps,1,'first');
if isempty(captureIndex)
    reachedNinetyPercent=false;
    timeToNinetyPercent_s=timeHorizon_s-commandStepTime_s;
else
    reachedNinetyPercent=true;
    timeToNinetyPercent_s=time_s(captureIndex)-commandStepTime_s;
end
settlingTolerance_mps=0.02*abs(speedCommandStep_mps);
settledByEnd=abs(finalSpeedError_mps)<=settlingTolerance_mps;
outsideTolerance=find(activeMask & ...
    abs(speedError_mps)>settlingTolerance_mps,1,'last');
if settledByEnd && ~isempty(outsideTolerance) && outsideTolerance<sampleCount
    settlingTime_s=time_s(outsideTolerance+1)-commandStepTime_s;
elseif settledByEnd && isempty(outsideTolerance)
    settlingTime_s=0;
else
    settlingTime_s=timeHorizon_s-commandStepTime_s;
end
peakSpeedOvershoot_mps=max(0,max( ...
    trueAirspeed_mps(activeMask)-commandedTrueAirspeed_mps));
minimumStallMargin_mps=min(trueAirspeed_mps)-stallSpeed_mps;

out=struct( ...
    'speedGain_per_s',speedGain_per_s, ...
    'throttleTimeConstant_s',throttleTimeConstant_s, ...
    'speedFeedbackSign',speedFeedbackSign, ...
    'sampleTime_s',sampleTime_s, ...
    'timeHorizon_s',timeHorizon_s, ...
    'time_s',time_s, ...
    'sampleCount',sampleCount, ...
    'intervalCount',sampleCount-1, ...
    'activeSampleCount',activeSampleCount, ...
    'commandStepTime_s',commandStepTime_s, ...
    'initialTrueAirspeed_mps',initialTrueAirspeed_mps, ...
    'commandedTrueAirspeed_mps',commandedTrueAirspeed_mps, ...
    'speedCommandStep_mps',speedCommandStep_mps, ...
    'airDensity_kgpm3',airDensity_kgpm3, ...
    'wingArea_m2',wingArea_m2, ...
    'parasiteDragCoefficient',parasiteDragCoefficient, ...
    'inducedDragFactor',inducedDragFactor, ...
    'mass_kg',mass_kg, ...
    'gravity_mps2',gravity_mps2, ...
    'maximumLiftCoefficient',maximumLiftCoefficient, ...
    'maximumThrust_N',maximumThrust_N, ...
    'weight_N',weight_N, ...
    'parasiteDragScale_N_per_mps2', ...
    parasiteDragScale_N_per_mps2, ...
    'inducedDragScale_N_mps2',inducedDragScale_N_mps2, ...
    'stallSpeed_mps',stallSpeed_mps, ...
    'initialDrag_N',initialDrag_N, ...
    'trimThrottle',trimThrottle, ...
    'commandedDrag_N',commandedDrag_N, ...
    'commandedEquilibriumThrottle',commandedEquilibriumThrottle, ...
    'speedCommand_mps',speedCommand_mps, ...
    'trueAirspeed_mps',trueAirspeed_mps, ...
    'speedError_mps',speedError_mps, ...
    'speedErrorUsed_mps',speedErrorUsed_mps, ...
    'parasiteDrag_N',parasiteDrag_N, ...
    'inducedDrag_N',inducedDrag_N, ...
    'drag_N',drag_N, ...
    'requestedAcceleration_mps2',requestedAcceleration_mps2, ...
    'thrustCommandUnclamped_N',thrustCommandUnclamped_N, ...
    'thrustCommand_N',thrustCommand_N, ...
    'thrustCommandSaturated',thrustCommandSaturated, ...
    'thrustCommandSaturationFraction', ...
    sum(thrustCommandSaturated)/sampleCount, ...
    'throttleCommand',throttleCommand, ...
    'throttleActual',throttleActual, ...
    'throttleRate_per_s',throttleRate_per_s, ...
    'thrustActual_N',thrustActual_N, ...
    'netForwardForce_N',netForwardForce_N, ...
    'longitudinalAcceleration_mps2', ...
    longitudinalAcceleration_mps2, ...
    'throttleTrackingError',throttleTrackingError, ...
    'throttleTrackingRMS',throttleTrackingRMS, ...
    'speedTrackingRMS_mps',speedTrackingRMS_mps, ...
    'speedAtFiveSeconds_mps',speedAtFiveSeconds_mps, ...
    'speedErrorAtTenSeconds_mps',speedErrorAtTenSeconds_mps, ...
    'finalSpeedError_mps',finalSpeedError_mps, ...
    'captureTolerance_mps',captureTolerance_mps, ...
    'reachedNinetyPercent',reachedNinetyPercent, ...
    'timeToNinetyPercent_s',timeToNinetyPercent_s, ...
    'settlingTolerance_mps',settlingTolerance_mps, ...
    'settledByEnd',settledByEnd, ...
    'settlingTime_s',settlingTime_s, ...
    'peakSpeedOvershoot_mps',peakSpeedOvershoot_mps, ...
    'minimumTrueAirspeed_mps',min(trueAirspeed_mps), ...
    'minimumStallMargin_mps',minimumStallMargin_mps, ...
    'stallEnvelopeMaintained',minimumStallMargin_mps>=0, ...
    'peakThrottleCommand',max(throttleCommand), ...
    'peakThrottleActual',max(throttleActual), ...
    'peakAbsoluteThrottleRate_per_s', ...
    max(abs(throttleRate_per_s)), ...
    'peakAbsoluteAcceleration_mps2', ...
    max(abs(longitudinalAcceleration_mps2)), ...
    'finalNetForwardForce_N',netForwardForce_N(end), ...
    'controllerEquation',[ ...
        'e_V=V_command-V; a_request=s*K_V*e_V; ' ...
        'T_command=sat(D(V)+m*a_request,0,T_max)'], ...
    'dragEquation',[ ...
        'D(V)=0.5*rho*S*CD0*V^2+' ...
        '2*k*W^2/(rho*S*V^2)'], ...
    'throttleEquation',[ ...
        'delta_dot=(T_command/T_max-delta)/tau_T; ' ...
        'T=T_max*delta'], ...
    'speedEquation','V_dot=(T-D(V))/m', ...
    'brokenCaseDefinition',[ ...
        'speedFeedbackSign=-1 reverses only speed-error feedback, so a positive ' ...
        'command step removes thrust and grows the proper speed error'], ...
    'analysisScope',[ ...
        'deterministic above-stall level-flight teaching model with exact drag ' ...
        'feedforward and normalized first-order throttle; no altitude/heading ' ...
        'coupling, wind, propulsion deck, sensor, identified aircraft, full 6-DOF, ' ...
        'hardware, HIL, field, or flight fidelity']);
end
