function run_checks
%RUN_CHECKS P15 independent drag, throttle, speed, and recovery checks.
clear model;

%% Determinism, fixed shapes, and finite resources
baseline=model();
repeatedBaseline=model(0.15,0.8,1);
assert(isequaln(baseline,repeatedBaseline), ...
    'Repeated baseline calls must be deterministic and stateless.');
assert(baseline.sampleCount==1501, ...
    'P15 must retain exactly 1501 samples.');
assert(baseline.intervalCount==1500, ...
    'P15 must retain exactly 1500 update intervals.');
assert(baseline.activeSampleCount==1451, ...
    'The command-active segment must retain exactly 1451 samples.');
assert(baseline.time_s(1)==0 && baseline.time_s(end)==30 && ...
    max(abs(diff(baseline.time_s)-0.02))<1e-14, ...
    'The fixed 0:0.02:30 s resource grid changed.');
historyFields={ ...
    'speedCommand_mps','trueAirspeed_mps','speedError_mps', ...
    'speedErrorUsed_mps','parasiteDrag_N','inducedDrag_N','drag_N', ...
    'requestedAcceleration_mps2','thrustCommandUnclamped_N', ...
    'thrustCommand_N','thrustCommandSaturated','throttleCommand', ...
    'throttleActual','throttleRate_per_s','thrustActual_N', ...
    'netForwardForce_N','longitudinalAcceleration_mps2', ...
    'throttleTrackingError'};
for k=1:numel(historyFields)
    values=baseline.(historyFields{k});
    assert(isequal(size(values),[1 baseline.sampleCount]), ...
        'Every retained baseline history must be a fixed row vector.');
    assert(all(isfinite(double(values(:)))), ...
        'Every retained baseline history must be finite.');
end

%% Exact pre-step force trim and signed command onset
commandIndex=find(baseline.time_s>=baseline.commandStepTime_s,1,'first');
onePointFiveIndex=find(baseline.time_s>=1.5,1,'first');
twoSecondIndex=find(baseline.time_s>=2,1,'first');
fiveSecondIndex=find(baseline.time_s>=5,1,'first');
tenSecondIndex=find(baseline.time_s>=10,1,'first');
preStepIndices=find(baseline.time_s<baseline.commandStepTime_s);
assert(all(baseline.speedCommand_mps(preStepIndices)== ...
    baseline.initialTrueAirspeed_mps) && ...
    all(baseline.trueAirspeed_mps(preStepIndices)== ...
    baseline.initialTrueAirspeed_mps) && ...
    all(baseline.speedError_mps(preStepIndices)==0) && ...
    all(baseline.speedErrorUsed_mps(preStepIndices)==0) && ...
    all(baseline.requestedAcceleration_mps2(preStepIndices)==0), ...
    'Command, speed, error, and correction must remain at trim before the step.');
assert(max(abs(baseline.drag_N(preStepIndices)- ...
    baseline.initialDrag_N))<1e-12 && ...
    max(abs(baseline.thrustCommand_N(preStepIndices)- ...
    baseline.initialDrag_N))<1e-12 && ...
    max(abs(baseline.throttleCommand(preStepIndices)- ...
    baseline.trimThrottle))<1e-15 && ...
    max(abs(baseline.throttleActual(preStepIndices)- ...
    baseline.trimThrottle))<1e-15 && ...
    all(baseline.throttleRate_per_s(preStepIndices)==0) && ...
    max(abs(baseline.thrustActual_N(preStepIndices)- ...
    baseline.initialDrag_N))<1e-12 && ...
    max(abs(baseline.netForwardForce_N(preStepIndices)))<1e-12 && ...
    max(abs(baseline.longitudinalAcceleration_mps2(preStepIndices)))<1e-15, ...
    'Drag, thrust, throttle, force, and acceleration must retain exact pre-step trim.');
assert(commandIndex==51 && baseline.time_s(commandIndex)==1 && ...
    baseline.speedCommand_mps(commandIndex)==70 && ...
    baseline.trueAirspeed_mps(commandIndex)==60 && ...
    baseline.throttleActual(commandIndex)==baseline.trimThrottle, ...
    'The retained command must begin at sample 51 from unchanged states.');
assert(baseline.speedError_mps(commandIndex)==10 && ...
    baseline.speedErrorUsed_mps(commandIndex)==10 && ...
    baseline.requestedAcceleration_mps2(commandIndex)==1.5, ...
    'Correct feedback must convert the +10 m/s error to +1.5 m/s^2.');
assert(abs(baseline.thrustCommandUnclamped_N(commandIndex)- ...
    2626.9521725905024)<1e-9 && ...
    abs(baseline.thrustCommand_N(commandIndex)- ...
    2626.9521725905024)<1e-9 && ...
    abs(baseline.throttleCommand(commandIndex)- ...
    0.6567380431476256)<1e-12 && ...
    abs(baseline.throttleRate_per_s(commandIndex)-0.5625)<1e-12 && ...
    baseline.longitudinalAcceleration_mps2(commandIndex)==0, ...
    'Command must move before delivered throttle and acceleration.');
assert(abs(baseline.throttleActual(onePointFiveIndex)- ...
    0.4163656596679233)<1e-10 && ...
    abs(baseline.longitudinalAcceleration_mps2(onePointFiveIndex)- ...
    0.6974716229756095)<1e-10 && ...
    abs(baseline.trueAirspeed_mps(twoSecondIndex)- ...
    60.62890154528778)<1e-10 && ...
    abs(baseline.trueAirspeed_mps(fiveSecondIndex)- ...
    64.07175584861862)<1e-10 && ...
    abs(baseline.speedError_mps(tenSecondIndex)- ...
    2.509387815834927)<1e-10, ...
    'The signed baseline must retain throttle-leading-speed behavior.');

%% Correct-feedback causal order and monotonic capture
firstDeliveryIndex=commandIndex+1;
firstSpeedResponseIndex=commandIndex+2;
expectedFirstDeliveredThrottle=baseline.trimThrottle+ ...
    baseline.sampleTime_s*(baseline.throttleCommand(commandIndex)- ...
    baseline.trimThrottle)/baseline.throttleTimeConstant_s;
assert(baseline.throttleCommand(commandIndex)>baseline.trimThrottle && ...
    baseline.throttleActual(commandIndex)==baseline.trimThrottle && ...
    baseline.longitudinalAcceleration_mps2(commandIndex)==0 && ...
    baseline.trueAirspeed_mps(commandIndex)== ...
    baseline.initialTrueAirspeed_mps, ...
    'The command sample must change only the requested throttle.');
assert(abs(baseline.throttleActual(firstDeliveryIndex)- ...
    expectedFirstDeliveredThrottle)<1e-12 && ...
    baseline.trueAirspeed_mps(firstDeliveryIndex)== ...
    baseline.initialTrueAirspeed_mps && ...
    baseline.longitudinalAcceleration_mps2(firstDeliveryIndex)>0 && ...
    baseline.trueAirspeed_mps(firstSpeedResponseIndex)> ...
    baseline.initialTrueAirspeed_mps, ...
    ['Delivered throttle and acceleration must move one retained sample ' ...
    'before true airspeed responds.']);
assert(all(diff(baseline.trueAirspeed_mps(commandIndex:end))>=0) && ...
    all(diff(baseline.trueAirspeed_mps(firstDeliveryIndex:end))>0) && ...
    all(diff(baseline.speedError_mps(commandIndex:end))<=0) && ...
    all(diff(baseline.speedError_mps(firstDeliveryIndex:end))<0) && ...
    all(baseline.netForwardForce_N(commandIndex:end)>=-1e-12) && ...
    all(baseline.trueAirspeed_mps(commandIndex:end)< ...
    baseline.commandedTrueAirspeed_mps), ...
    ['Correct feedback must retain nonnegative net force and monotonic, ' ...
    'non-overshooting speed-error contraction after throttle delivery.']);
assert(abs(baseline.finalSpeedError_mps- ...
    0.0799245300887037)<1e-10 && ...
    abs(baseline.timeToNinetyPercent_s-14.34)<1e-12 && ...
    abs(baseline.settlingTime_s-23.68)<1e-12 && ...
    abs(baseline.throttleTrackingRMS- ...
    0.053024251502165075)<1e-10 && ...
    abs(baseline.speedTrackingRMS_mps- ...
    3.599524240497819)<1e-10 && ...
    abs(baseline.peakThrottleActual- ...
    0.5782756767990148)<1e-10 && ...
    baseline.reachedNinetyPercent && baseline.settledByEnd, ...
    'The retained baseline capture, settling, and tracking metrics changed.');

%% Independently reconstruct drag, controller, throttle, force, and acceleration
expectedParasiteDrag_N=baseline.parasiteDragScale_N_per_mps2* ...
    baseline.trueAirspeed_mps.^2;
expectedInducedDrag_N=baseline.inducedDragScale_N_mps2./ ...
    baseline.trueAirspeed_mps.^2;
expectedDrag_N=expectedParasiteDrag_N+expectedInducedDrag_N;
expectedSpeedError_mps= ...
    baseline.speedCommand_mps-baseline.trueAirspeed_mps;
expectedSpeedErrorUsed_mps= ...
    baseline.speedFeedbackSign*expectedSpeedError_mps;
expectedRequestedAcceleration_mps2= ...
    baseline.speedGain_per_s*expectedSpeedErrorUsed_mps;
expectedThrustCommandUnclamped_N=expectedDrag_N+ ...
    baseline.mass_kg*expectedRequestedAcceleration_mps2;
expectedThrustCommand_N=min(max( ...
    expectedThrustCommandUnclamped_N,0),baseline.maximumThrust_N);
expectedThrottleCommand= ...
    expectedThrustCommand_N/baseline.maximumThrust_N;
expectedThrottleRate_per_s=(expectedThrottleCommand- ...
    baseline.throttleActual)/baseline.throttleTimeConstant_s;
expectedThrustActual_N= ...
    baseline.maximumThrust_N*baseline.throttleActual;
expectedNetForwardForce_N=expectedThrustActual_N-expectedDrag_N;
expectedAcceleration_mps2= ...
    expectedNetForwardForce_N/baseline.mass_kg;
assert(max(abs(baseline.parasiteDrag_N-expectedParasiteDrag_N))<1e-10 && ...
    max(abs(baseline.inducedDrag_N-expectedInducedDrag_N))<1e-10 && ...
    max(abs(baseline.drag_N-expectedDrag_N))<1e-10, ...
    'Both drag terms and their sum must match independent reconstruction.');
assert(max(abs(baseline.speedError_mps- ...
    expectedSpeedError_mps))<1e-12 && ...
    max(abs(baseline.speedErrorUsed_mps- ...
    expectedSpeedErrorUsed_mps))<1e-12 && ...
    max(abs(baseline.requestedAcceleration_mps2- ...
    expectedRequestedAcceleration_mps2))<1e-12 && ...
    max(abs(baseline.thrustCommandUnclamped_N- ...
    expectedThrustCommandUnclamped_N))<1e-9 && ...
    max(abs(baseline.thrustCommand_N- ...
    expectedThrustCommand_N))<1e-9, ...
    'Speed feedback and bounded thrust request must match reconstruction.');
assert(max(abs(baseline.throttleCommand- ...
    expectedThrottleCommand))<1e-12 && ...
    max(abs(baseline.throttleRate_per_s- ...
    expectedThrottleRate_per_s))<1e-12 && ...
    max(abs(baseline.thrustActual_N- ...
    expectedThrustActual_N))<1e-10 && ...
    max(abs(baseline.netForwardForce_N- ...
    expectedNetForwardForce_N))<1e-10 && ...
    max(abs(baseline.longitudinalAcceleration_mps2- ...
    expectedAcceleration_mps2))<1e-12, ...
    'Throttle delivery, thrust, net force, and acceleration must match reconstruction.');

expectedSpeedNext_mps=baseline.trueAirspeed_mps(1:end-1)+ ...
    baseline.sampleTime_s* ...
    baseline.longitudinalAcceleration_mps2(1:end-1);
expectedThrottleNext=baseline.throttleActual(1:end-1)+ ...
    baseline.sampleTime_s*baseline.throttleRate_per_s(1:end-1);
assert(max(abs(baseline.trueAirspeed_mps(2:end)- ...
    expectedSpeedNext_mps))<1e-12, ...
    'Every speed update must use sample-k acceleration.');
assert(max(abs(baseline.throttleActual(2:end)- ...
    expectedThrottleNext))<1e-12, ...
    'Every delivered-throttle update must use sample-k throttle rate.');

%% Fixed-condition constants, force limits, and declared envelope
assert(abs(baseline.parasiteDragScale_N_per_mps2- ...
    0.14906339834832827)<1e-15 && ...
    abs(baseline.inducedDragScale_N_mps2- ...
    1045166.1787314755)<1e-8 && ...
    abs(baseline.initialDrag_N-826.9521725905026)<1e-9 && ...
    abs(baseline.commandedDrag_N-943.7098720560892)<1e-9 && ...
    abs(baseline.trimThrottle-0.20673804314762567)<1e-12 && ...
    abs(baseline.commandedEquilibriumThrottle- ...
    0.2359274680140223)<1e-12 && ...
    abs(baseline.stallSpeed_mps-37.546671093409294)<1e-10, ...
    'P04-consistent fixed-condition drag, trim, and stall references changed.');
assert(isequal(baseline.thrustCommandSaturated, ...
    baseline.thrustCommandUnclamped_N<0 | ...
    baseline.thrustCommandUnclamped_N>baseline.maximumThrust_N) && ...
    ~any(baseline.thrustCommandSaturated) && ...
    all(baseline.thrustCommand_N>=0) && ...
    all(baseline.thrustCommand_N<=baseline.maximumThrust_N) && ...
    all(baseline.throttleCommand>=0) && ...
    all(baseline.throttleCommand<=1) && ...
    all(baseline.throttleActual>=0) && ...
    all(baseline.throttleActual<=1), ...
    'Baseline thrust and throttle must remain inside their declared bounds.');
assert(baseline.sampleTime_s/baseline.throttleTimeConstant_s<=0.1 && ...
    baseline.minimumTrueAirspeed_mps==60 && ...
    baseline.minimumStallMargin_mps>22 && ...
    baseline.stallEnvelopeMaintained && ...
    baseline.peakSpeedOvershoot_mps==0 && ...
    abs(baseline.finalNetForwardForce_N- ...
    16.493726339144246)<1e-8, ...
    'Baseline must retain a bounded actuator update and above-stall speed envelope.');

%% Limiting case: zero speed gain preserves exact force trim
openSpeedLoop=model(0,0.8,1);
assert(all(openSpeedLoop.trueAirspeed_mps== ...
    openSpeedLoop.initialTrueAirspeed_mps) && ...
    all(openSpeedLoop.speedError_mps(preStepIndices)==0) && ...
    all(openSpeedLoop.speedError_mps(commandIndex:end)==10) && ...
    all(openSpeedLoop.requestedAcceleration_mps2==0) && ...
    max(abs(openSpeedLoop.thrustCommand_N- ...
    openSpeedLoop.initialDrag_N))<1e-12 && ...
    max(abs(openSpeedLoop.throttleCommand- ...
    openSpeedLoop.trimThrottle))<1e-15 && ...
    max(abs(openSpeedLoop.throttleActual- ...
    openSpeedLoop.trimThrottle))<1e-15 && ...
    max(abs(openSpeedLoop.netForwardForce_N))<1e-12 && ...
    max(abs(openSpeedLoop.longitudinalAcceleration_mps2))<1e-15, ...
    'Zero gain must be the exact feedback-open force-trim limit.');
assert(openSpeedLoop.finalSpeedError_mps==10 && ...
    ~openSpeedLoop.reachedNinetyPercent && ...
    ~openSpeedLoop.settledByEnd, ...
    'The open speed loop must retain the full command error.');

%% Two isolated parameter sweeps
speedGainSweep_per_s=[0 0.075 0.15 0.225 0.3];
gainSpeedAtFive_mps=zeros(size(speedGainSweep_per_s));
gainErrorAtTen_mps=zeros(size(speedGainSweep_per_s));
gainCaptureTime_s=zeros(size(speedGainSweep_per_s));
gainPeakThrottle=zeros(size(speedGainSweep_per_s));
gainSaturationFraction=zeros(size(speedGainSweep_per_s));
for k=1:numel(speedGainSweep_per_s)
    sample=model(speedGainSweep_per_s(k),0.8,1);
    gainSpeedAtFive_mps(k)=sample.speedAtFiveSeconds_mps;
    gainErrorAtTen_mps(k)=sample.speedErrorAtTenSeconds_mps;
    gainCaptureTime_s(k)=sample.timeToNinetyPercent_s;
    gainPeakThrottle(k)=sample.peakThrottleActual;
    gainSaturationFraction(k)=sample.thrustCommandSaturationFraction;
    assert(sample.throttleTimeConstant_s==0.8 && ...
        sample.speedFeedbackSign==1 && ...
        sample.mass_kg==baseline.mass_kg && ...
        sample.maximumThrust_N==baseline.maximumThrust_N && ...
        isequal(sample.time_s,baseline.time_s) && ...
        isequal(sample.speedCommand_mps,baseline.speedCommand_mps), ...
        'The speed-gain sweep must isolate only its selected public input.');
end
expectedGainSpeedAtFive_mps=[60 62.207733344641035 ...
    64.07175584861862 65.6318383365179 66.8066107392886];
expectedGainErrorAtTen_mps=[10 5.238802235073322 ...
    2.509387815834927 1.0411921959026245 0.3380680265113938];
expectedGainCaptureTime_s=[29 29 14.34 9.14 6.66];
expectedGainPeakThrottle=[0.20673804314762567 ...
    0.40629372002272696 0.5782756767990148 ...
    0.7348746781972777 0.8715061328423348];
assert(max(abs(gainSpeedAtFive_mps- ...
    expectedGainSpeedAtFive_mps))<1e-9 && ...
    max(abs(gainErrorAtTen_mps- ...
    expectedGainErrorAtTen_mps))<1e-9 && ...
    max(abs(gainCaptureTime_s- ...
    expectedGainCaptureTime_s))<1e-12 && ...
    max(abs(gainPeakThrottle-expectedGainPeakThrottle))<1e-9 && ...
    all(diff(gainSpeedAtFive_mps)>0) && ...
    all(diff(gainErrorAtTen_mps)<0) && ...
    all(diff(gainCaptureTime_s(2:end))<0), ...
    'Higher gain must improve retained early speed/error and capture.');
assert(all(gainSaturationFraction(1:4)==0) && ...
    abs(gainSaturationFraction(5)- ...
    0.03530979347101932)<1e-12, ...
    'The highest speed gain must expose the thrust-authority limit.');

throttleTimeSweep_s=[0.2 0.5 0.8 1.1 1.4];
timeSpeedAtTwo_mps=zeros(size(throttleTimeSweep_s));
timeTrackingRMS=zeros(size(throttleTimeSweep_s));
timePeakRate_per_s=zeros(size(throttleTimeSweep_s));
for k=1:numel(throttleTimeSweep_s)
    sample=model(0.15,throttleTimeSweep_s(k),1);
    timeSpeedAtTwo_mps(k)=sample.trueAirspeed_mps(twoSecondIndex);
    timeTrackingRMS(k)=sample.throttleTrackingRMS;
    timePeakRate_per_s(k)=sample.peakAbsoluteThrottleRate_per_s;
    assert(sample.speedGain_per_s==0.15 && ...
        sample.speedFeedbackSign==1 && ...
        sample.mass_kg==baseline.mass_kg && ...
        sample.maximumThrust_N==baseline.maximumThrust_N && ...
        sample.trimThrottle==baseline.trimThrottle && ...
        isequal(sample.speedCommand_mps,baseline.speedCommand_mps), ...
        'The throttle-time sweep must isolate only its selected public input.');
end
expectedTimeSpeedAtTwo_mps=[61.15429458821988 ...
    60.82932695729019 60.62890154528778 ...
    60.50331257970016 60.41865656026334];
expectedTimeTrackingRMS=[0.027113290496212472 ...
    0.04214430659160602 0.053024251502165075 ...
    0.06197382340441243 0.06973981035435724];
expectedTimePeakRate_per_s=[2.25 0.9 0.5625 ...
    0.409090909090909 0.3214285714285714];
assert(max(abs(timeSpeedAtTwo_mps- ...
    expectedTimeSpeedAtTwo_mps))<1e-9 && ...
    max(abs(timeTrackingRMS-expectedTimeTrackingRMS))<1e-9 && ...
    max(abs(timePeakRate_per_s- ...
    expectedTimePeakRate_per_s))<1e-9 && ...
    all(diff(timeSpeedAtTwo_mps)<0) && ...
    all(diff(timeTrackingRMS)>0) && ...
    all(diff(timePeakRate_per_s)<0), ...
    'Throttle lag must trade early delivery/tracking for throttle-rate demand.');

%% Broken feedback sign, continued tail failure, rollback, and recovery
broken=model(0.15,0.8,-1);
stateFields={'trueAirspeed_mps','throttleActual','thrustActual_N', ...
    'drag_N','netForwardForce_N','longitudinalAcceleration_mps2'};
for k=1:numel(stateFields)
    brokenState=broken.(stateFields{k});
    baselineState=baseline.(stateFields{k});
    assert(isequal(brokenState(1:commandIndex), ...
        baselineState(1:commandIndex)), ...
        'Correct and broken states must match through command onset.');
end
assert(broken.speedGain_per_s==baseline.speedGain_per_s && ...
    broken.throttleTimeConstant_s== ...
    baseline.throttleTimeConstant_s && ...
    broken.speedFeedbackSign==-1 && ...
    isequal(broken.time_s,baseline.time_s) && ...
    isequal(broken.speedCommand_mps,baseline.speedCommand_mps) && ...
    isequal(broken.speedError_mps(1:commandIndex), ...
    baseline.speedError_mps(1:commandIndex)), ...
    'The broken case must change only the selected feedback sign.');
assert(broken.speedErrorUsed_mps(commandIndex)==-10 && ...
    abs(broken.thrustCommandUnclamped_N(commandIndex)+ ...
    973.0478274094974)<1e-9 && ...
    broken.thrustCommand_N(commandIndex)==0 && ...
    broken.throttleCommand(commandIndex)==0 && ...
    baseline.thrustCommand_N(commandIndex)>2500, ...
    'Reversed feedback must command idle for the positive speed error.');
assert(all(diff(broken.trueAirspeed_mps(commandIndex:end))<=1e-12) && ...
    all(diff(broken.speedError_mps(commandIndex:end))>=-1e-12) && ...
    all(broken.throttleCommand(commandIndex:end)==0) && ...
    all(broken.thrustCommandSaturated(commandIndex:end)) && ...
    broken.finalSpeedError_mps>29 && ...
    ~broken.reachedNinetyPercent && ~broken.settledByEnd, ...
    'Broken speed must fall while proper error grows under idle saturation.');
assert(abs(broken.minimumTrueAirspeed_mps- ...
    40.98971839975168)<1e-8 && ...
    abs(broken.finalSpeedError_mps- ...
    29.01028160024832)<1e-8 && ...
    abs(broken.thrustCommandSaturationFraction- ...
    0.966688874083944)<1e-12 && ...
    broken.minimumStallMargin_mps>3.4 && ...
    broken.stallEnvelopeMaintained && ...
    all(isfinite(broken.trueAirspeed_mps)) && ...
    all(isfinite(broken.throttleActual)), ...
    'The retained broken signature, finite histories, and stall margin changed.');

brokenTailIndices=find(broken.time_s>=broken.timeHorizon_s-1);
brokenTailIntervals=brokenTailIndices(1:end-1);
assert(all(broken.thrustCommandSaturated(brokenTailIndices)) && ...
    all(broken.throttleCommand(brokenTailIndices)==0) && ...
    all(diff(broken.trueAirspeed_mps(brokenTailIndices))<0) && ...
    all(diff(broken.speedError_mps(brokenTailIndices))>0) && ...
    broken.trueAirspeed_mps(brokenTailIndices(1))- ...
    broken.trueAirspeed_mps(end)>0.72 && ...
    broken.speedError_mps(end)- ...
    broken.speedError_mps(brokenTailIndices(1))>0.72 && ...
    max(abs(diff(broken.trueAirspeed_mps(brokenTailIndices))- ...
    broken.sampleTime_s* ...
    broken.longitudinalAcceleration_mps2(brokenTailIntervals)))<1e-12 && ...
    broken.longitudinalAcceleration_mps2(end)<-0.72, ...
    ['Idle saturation must not masquerade as recovery: the broken speed ' ...
    'must keep falling through the retained tail.']);
rolledBackBaseline=model(0.15,0.8,1);
assert(isequaln(rolledBackBaseline,baseline), ...
    'Rollback from reversed feedback must reproduce baseline exactly.');

%% Malformed and rejected inputs do not poison deterministic recovery
assertRejects(@()model(-eps,0.8,1),'P15:model:SpeedGainRange');
assertRejects(@()model(0.3+eps,0.8,1),'P15:model:SpeedGainRange');
assertRejects(@()model(0.15,0.2-eps,1), ...
    'P15:model:ThrottleTimeConstantRange');
assertRejects(@()model(0.15,1.4+eps,1), ...
    'P15:model:ThrottleTimeConstantRange');
assertRejects(@()model(0.15,0.8,0),'P15:model:FeedbackSign');
assertRejects(@()model(0.15,0.8,2),'P15:model:FeedbackSign');
malformedCalls={ ...
    @()model([0.075 0.15],0.8,1), ...
    @()model(0.15,[0.5 0.8],1), ...
    @()model(0.15,0.8,[-1 1]), ...
    @()model(0.15+1i,0.8,1), ...
    @()model(0.15,0.8+1i,1), ...
    @()model(NaN,0.8,1), ...
    @()model(0.15,Inf,1), ...
    @()model(0.15,0.8,NaN)};
for k=1:numel(malformedCalls)
    assertRejects(malformedCalls{k},'');
end
recoveredBaseline=model();
assert(isequaln(recoveredBaseline,baseline), ...
    'A valid call after rejected inputs must recover the exact baseline.');

%% Accepted corners, representative grid, and resource bounds
acceptedCornerCount=0;
finiteFields={'trueAirspeed_mps','speedError_mps','parasiteDrag_N', ...
    'inducedDrag_N','drag_N','thrustCommand_N','throttleCommand', ...
    'throttleActual','throttleRate_per_s','thrustActual_N', ...
    'netForwardForce_N','longitudinalAcceleration_mps2'};
for speedGain_per_s=[0 0.3]
    for throttleTimeConstant_s=[0.2 1.4]
        for speedFeedbackSign=[-1 1]
            sample=model(speedGain_per_s, ...
                throttleTimeConstant_s,speedFeedbackSign);
            acceptedCornerCount=acceptedCornerCount+1;
            assert(sample.sampleCount==1501 && sample.intervalCount==1500, ...
                'Accepted corners may not change allocated history size.');
            for fieldIndex=1:numel(finiteFields)
                assert(all(isfinite(sample.(finiteFields{fieldIndex}))), ...
                    'Accepted corners must retain finite histories.');
            end
            assert(all(sample.trueAirspeed_mps>0) && ...
                sample.stallEnvelopeMaintained && ...
                all(sample.throttleCommand>=0) && ...
                all(sample.throttleCommand<=1) && ...
                all(sample.throttleActual>=0) && ...
                all(sample.throttleActual<=1), ...
                'Accepted corners must preserve speed and throttle envelopes.');
        end
    end
end
assert(acceptedCornerCount==8, ...
    'The accepted-corner check must remain capped at eight cases.');

representativeCaseCount=0;
for speedGain_per_s=[0 0.15 0.3]
    for throttleTimeConstant_s=[0.2 0.8 1.4]
        for speedFeedbackSign=[-1 1]
            sample=model(speedGain_per_s, ...
                throttleTimeConstant_s,speedFeedbackSign);
            representativeCaseCount=representativeCaseCount+1;
            assert(sample.sampleCount==baseline.sampleCount && ...
                sample.intervalCount==baseline.intervalCount && ...
                isequal(sample.time_s,baseline.time_s), ...
                'Representative cases must use the fixed synchronous grid.');
        end
    end
end
assert(representativeCaseCount==18, ...
    'The representative finite-resource grid must remain capped at 18 cases.');

%% Compatibility, timeout, cancellation, migration, and backup applicability
% P15 is a synchronous stateless base-MATLAB teaching calculation. It owns
% no file, network, device, process, timer, future, parallel worker, or
% background callback resource. There is therefore no asynchronous timeout
% or cancellation transition to exercise; fixed sample/interval counts, the
% bounded tau input, and capped case grid are the applicable resource limits.
% No learner data, service schema, scoring model, migration, database, or
% backup/restore path changes here. P14/P04/P10/P12 are conceptual
% prerequisites, not runtime compatibility adapters.

fprintf(['P15 checks passed: deterministic force/throttle/speed cascade, ' ...
    'every recurrence, isolated parameter sweeps, force-trim limit, ' ...
    'reversed-sign tail failure, malformed-input recovery, rollback, ' ...
    'compatibility, and resources.\n']);
end

function assertRejects(testCall,expectedIdentifier)
caught=false;
try
    unusedOutput=testCall(); %#ok<NASGU>
catch exception
    caught=true;
    if ~isempty(expectedIdentifier)
        assert(strcmp(exception.identifier,expectedIdentifier), ...
            'Rejected input raised an unexpected error identifier.');
    else
        assert(~isempty(exception.identifier), ...
            'Malformed input rejection must provide an error identifier.');
    end
end
assert(caught,'The malformed or out-of-range input must be rejected.');
end
