function out = model(cgPosition_percentMAC,tailAreaRatio_percent, ...
    angleOfAttackPerturbation_deg,elevatorPerturbation_deg)
%MODEL Stick-fixed incremental longitudinal static-stability model.
% Stations h are measured aft from the mean-aerodynamic-chord leading edge.
% Positive pitching moment is nose-up, positive elevator is trailing-edge
% down, and perturbations are measured from a locally retrimmed P04 reference.
% The learning domain is cg=[15,65] percent MAC, horizontal-tail area ratio
% St/S=[0,30] percent, delta alpha=[-5,5] deg, and delta elevator=[-15,15] deg.
arguments
    cgPosition_percentMAC (1,1) double {mustBeReal,mustBeFinite} = 30
    tailAreaRatio_percent (1,1) double {mustBeReal,mustBeFinite} = 20
    angleOfAttackPerturbation_deg (1,1) double {mustBeReal,mustBeFinite} = 2
    elevatorPerturbation_deg (1,1) double {mustBeReal,mustBeFinite} = 0
end

if cgPosition_percentMAC<15 || cgPosition_percentMAC>65
    error('P05:model:CgRange', ...
        'CG position must be between 15 and 65 percent MAC, inclusive.');
end
if tailAreaRatio_percent<0
    error('P05:model:NegativeTailAreaRatio', ...
        'Horizontal-tail area ratio must be nonnegative.');
end
if tailAreaRatio_percent>30
    error('P05:model:TailAreaRatioRange', ...
        'Horizontal-tail area ratio must not exceed 30 percent.');
end
if abs(angleOfAttackPerturbation_deg)>5
    error('P05:model:AlphaPerturbationRange', ...
        'Angle-of-attack perturbation must be between -5 and 5 deg, inclusive.');
end
if abs(elevatorPerturbation_deg)>15
    error('P05:model:ElevatorPerturbationRange', ...
        'Elevator perturbation must be between -15 and 15 deg, inclusive.');
end

referenceDynamicPressure_Pa=1325.00798531847;
referenceTrimAngleOfAttack_deg=3.41754527929804;
wingArea_m2=16.2;
meanAerodynamicChord_m=1.5;
wingAerodynamicCenter_fractionMAC=0.25;
tailAerodynamicCenter_xOverMAC=3.5;
wingLiftCurveSlope_perRad=5.0;
tailLiftCurveSlope_perRad=4.0;
tailDynamicPressureRatio=0.9;
downwashGradient=0.4;
elevatorEffectiveness=0.6;
stabilityTolerance_perRad=1e-12;

cgPosition_fractionMAC=cgPosition_percentMAC/100;
tailAreaRatio=tailAreaRatio_percent/100;
angleOfAttackPerturbation_rad=angleOfAttackPerturbation_deg*pi/180;
elevatorPerturbation_rad=elevatorPerturbation_deg*pi/180;
absoluteAngleOfAttack_deg=referenceTrimAngleOfAttack_deg+ ...
    angleOfAttackPerturbation_deg;

tailLiftContribution_perRad=tailDynamicPressureRatio*tailAreaRatio* ...
    tailLiftCurveSlope_perRad*(1-downwashGradient);
aircraftLiftCurveSlope_perRad=wingLiftCurveSlope_perRad+ ...
    tailLiftContribution_perRad;
neutralPoint_fractionMAC=(wingLiftCurveSlope_perRad* ...
    wingAerodynamicCenter_fractionMAC+tailLiftContribution_perRad* ...
    tailAerodynamicCenter_xOverMAC)/aircraftLiftCurveSlope_perRad;
neutralPoint_percentMAC=100*neutralPoint_fractionMAC;
staticMargin_fractionMAC=(neutralPoint_percentMAC- ...
    cgPosition_percentMAC)/100;
staticMargin_percentMAC=100*staticMargin_fractionMAC;

wingMomentSlope_perRad=wingLiftCurveSlope_perRad*( ...
    cgPosition_fractionMAC-wingAerodynamicCenter_fractionMAC);
tailMomentSlope_perRad=tailLiftContribution_perRad*( ...
    cgPosition_fractionMAC-tailAerodynamicCenter_xOverMAC);
pitchingMomentSlope_perRad=wingMomentSlope_perRad+tailMomentSlope_perRad;
neutralPointMomentSlope_perRad=-aircraftLiftCurveSlope_perRad* ...
    staticMargin_fractionMAC;
elevatorControlDerivative_perRad=-tailDynamicPressureRatio*tailAreaRatio* ...
    tailLiftCurveSlope_perRad*elevatorEffectiveness*( ...
    tailAerodynamicCenter_xOverMAC-cgPosition_fractionMAC);

alphaMomentCoefficient=pitchingMomentSlope_perRad* ...
    angleOfAttackPerturbation_rad;
elevatorMomentCoefficient=elevatorControlDerivative_perRad* ...
    elevatorPerturbation_rad;
pitchingMomentCoefficient=alphaMomentCoefficient+elevatorMomentCoefficient;
momentScale_Nm=referenceDynamicPressure_Pa*wingArea_m2* ...
    meanAerodynamicChord_m;
alphaMoment_Nm=momentScale_Nm*alphaMomentCoefficient;
elevatorMoment_Nm=momentScale_Nm*elevatorMomentCoefficient;
pitchingMoment_Nm=momentScale_Nm*pitchingMomentCoefficient;

isStaticallyStable=pitchingMomentSlope_perRad<-stabilityTolerance_perRad;
isNeutral=abs(pitchingMomentSlope_perRad)<=stabilityTolerance_perRad;
isStaticallyUnstable=pitchingMomentSlope_perRad>stabilityTolerance_perRad;
if isStaticallyStable
    stabilityLabel='stable: positive delta alpha creates nose-down restoring moment';
elseif isStaticallyUnstable
    stabilityLabel='unstable: positive delta alpha creates nose-up reinforcing moment';
else
    stabilityLabel='neutral: angle-of-attack perturbation creates no first-order moment';
end

out=struct( ...
    'cgPosition_percentMAC',cgPosition_percentMAC, ...
    'cgPosition_fractionMAC',cgPosition_fractionMAC, ...
    'tailAreaRatio_percent',tailAreaRatio_percent, ...
    'tailAreaRatio',tailAreaRatio, ...
    'angleOfAttackPerturbation_deg',angleOfAttackPerturbation_deg, ...
    'angleOfAttackPerturbation_rad',angleOfAttackPerturbation_rad, ...
    'elevatorPerturbation_deg',elevatorPerturbation_deg, ...
    'elevatorPerturbation_rad',elevatorPerturbation_rad, ...
    'absoluteAngleOfAttack_deg',absoluteAngleOfAttack_deg, ...
    'tailLiftContribution_perRad',tailLiftContribution_perRad, ...
    'aircraftLiftCurveSlope_perRad',aircraftLiftCurveSlope_perRad, ...
    'neutralPoint_fractionMAC',neutralPoint_fractionMAC, ...
    'neutralPoint_percentMAC',neutralPoint_percentMAC, ...
    'staticMargin_fractionMAC',staticMargin_fractionMAC, ...
    'staticMargin_percentMAC',staticMargin_percentMAC, ...
    'wingMomentSlope_perRad',wingMomentSlope_perRad, ...
    'tailMomentSlope_perRad',tailMomentSlope_perRad, ...
    'pitchingMomentSlope_perRad',pitchingMomentSlope_perRad, ...
    'neutralPointMomentSlope_perRad',neutralPointMomentSlope_perRad, ...
    'elevatorControlDerivative_perRad',elevatorControlDerivative_perRad, ...
    'alphaMomentCoefficient',alphaMomentCoefficient, ...
    'elevatorMomentCoefficient',elevatorMomentCoefficient, ...
    'pitchingMomentCoefficient',pitchingMomentCoefficient, ...
    'momentScale_Nm',momentScale_Nm, ...
    'alphaMoment_Nm',alphaMoment_Nm, ...
    'elevatorMoment_Nm',elevatorMoment_Nm, ...
    'pitchingMoment_Nm',pitchingMoment_Nm, ...
    'isStaticallyStable',isStaticallyStable, ...
    'isNeutral',isNeutral, ...
    'isStaticallyUnstable',isStaticallyUnstable, ...
    'stabilityLabel',stabilityLabel, ...
    'referenceDynamicPressure_Pa',referenceDynamicPressure_Pa, ...
    'referenceTrimAngleOfAttack_deg',referenceTrimAngleOfAttack_deg, ...
    'wingArea_m2',wingArea_m2, ...
    'meanAerodynamicChord_m',meanAerodynamicChord_m, ...
    'wingAerodynamicCenter_fractionMAC', ...
    wingAerodynamicCenter_fractionMAC, ...
    'tailAerodynamicCenter_xOverMAC',tailAerodynamicCenter_xOverMAC, ...
    'wingLiftCurveSlope_perRad',wingLiftCurveSlope_perRad, ...
    'tailLiftCurveSlope_perRad',tailLiftCurveSlope_perRad, ...
    'tailDynamicPressureRatio',tailDynamicPressureRatio, ...
    'downwashGradient',downwashGradient, ...
    'elevatorEffectiveness',elevatorEffectiveness, ...
    'stabilityTolerance_perRad',stabilityTolerance_perRad, ...
    'stationConvention','h measured aft from the MAC leading edge', ...
    'momentConvention','positive C_m and pitching moment are nose-up', ...
    'elevatorConvention','positive elevator is trailing-edge down', ...
    'analysisScope','linear stick-fixed increments about a locally retrimmed P04 reference');
end
