function run_checks
%RUN_CHECKS Independent analytic checks for the P05 static-stability model.
clear model;
tol=1e-10;

%% Determinism and fixed resource shape
first=model(30,20,2,0);
second=model(30,20,2,0);
assert(isequaln(first,second), ...
    'Identical stability inputs must produce identical outputs.');
scalarFields={'cgPosition_fractionMAC','tailAreaRatio', ...
    'angleOfAttackPerturbation_rad','elevatorPerturbation_rad', ...
    'absoluteAngleOfAttack_deg','tailLiftContribution_perRad', ...
    'aircraftLiftCurveSlope_perRad','neutralPoint_fractionMAC', ...
    'neutralPoint_percentMAC','staticMargin_fractionMAC', ...
    'staticMargin_percentMAC','wingMomentSlope_perRad', ...
    'tailMomentSlope_perRad','pitchingMomentSlope_perRad', ...
    'neutralPointMomentSlope_perRad','elevatorControlDerivative_perRad', ...
    'alphaMomentCoefficient','elevatorMomentCoefficient', ...
    'pitchingMomentCoefficient','momentScale_Nm','alphaMoment_Nm', ...
    'elevatorMoment_Nm','pitchingMoment_Nm'};
for k=1:numel(scalarFields)
    assert(isscalar(first.(scalarFields{k})) && isfinite(first.(scalarFields{k})), ...
        'Static-stability outputs must remain finite scalars.');
end

edgeCg_percentMAC=[15 65];
edgeTailArea_percent=[0 30];
edgeAlpha_deg=[-5 5];
edgeElevator_deg=[-15 15];
edgeCaseCount=0;
for cgIndex=1:numel(edgeCg_percentMAC)
    for tailIndex=1:numel(edgeTailArea_percent)
        for alphaIndex=1:numel(edgeAlpha_deg)
            for elevatorIndex=1:numel(edgeElevator_deg)
                edge=model(edgeCg_percentMAC(cgIndex), ...
                    edgeTailArea_percent(tailIndex),edgeAlpha_deg(alphaIndex), ...
                    edgeElevator_deg(elevatorIndex));
                edgeCaseCount=edgeCaseCount+1;
                for fieldIndex=1:numel(scalarFields)
                    assert(isfinite(edge.(scalarFields{fieldIndex})), ...
                        'Every accepted input corner must produce finite outputs.');
                end
            end
        end
    end
end
assert(edgeCaseCount==16,'The accepted-corner grid must stay fixed at 16 cases.');

%% Independent deterministic baseline and dimensional moment scale
expectedQ_Pa=1325.00798531847;
expectedReferenceTrimAlpha_deg=3.41754527929804;
expectedWingArea_m2=16.2;
expectedMeanChord_m=1.5;
expectedWingSlope_perRad=5.0;
expectedTailSlope_perRad=4.0;
expectedWingAc=0.25;
expectedTailStation=3.5;
expectedTailEfficiency=0.9;
expectedDownwashGradient=0.4;
expectedElevatorEffectiveness=0.6;
expectedCg=0.30;
expectedTailRatio=0.20;
expectedAlpha_rad=2*pi/180;

expectedTailLiftContribution_perRad=expectedTailEfficiency* ...
    expectedTailRatio*expectedTailSlope_perRad*(1-expectedDownwashGradient);
expectedAircraftLiftSlope_perRad=expectedWingSlope_perRad+ ...
    expectedTailLiftContribution_perRad;
expectedNeutralPoint=(expectedWingSlope_perRad*expectedWingAc+ ...
    expectedTailLiftContribution_perRad*expectedTailStation)/ ...
    expectedAircraftLiftSlope_perRad;
expectedStaticMargin=expectedNeutralPoint-expectedCg;
expectedWingMomentSlope_perRad=expectedWingSlope_perRad*( ...
    expectedCg-expectedWingAc);
expectedTailMomentSlope_perRad=expectedTailLiftContribution_perRad*( ...
    expectedCg-expectedTailStation);
expectedMomentSlope_perRad=expectedWingMomentSlope_perRad+ ...
    expectedTailMomentSlope_perRad;
expectedElevatorDerivative_perRad=-expectedTailEfficiency* ...
    expectedTailRatio*expectedTailSlope_perRad* ...
    expectedElevatorEffectiveness*(expectedTailStation-expectedCg);
expectedDeltaCm=expectedMomentSlope_perRad*expectedAlpha_rad;
expectedMomentScale_Nm=expectedQ_Pa*expectedWingArea_m2*expectedMeanChord_m;
expectedMoment_Nm=expectedMomentScale_Nm*expectedDeltaCm;

assert(abs(first.tailLiftContribution_perRad-0.432)<1e-14 && ...
    abs(first.aircraftLiftCurveSlope_perRad-5.432)<1e-14, ...
    'The baseline tail and total lift-curve contributions must remain recognizable.');
assert(abs(first.neutralPoint_fractionMAC-expectedNeutralPoint)<tol && ...
    abs(first.staticMargin_fractionMAC-expectedStaticMargin)<tol, ...
    'Neutral point and static margin must follow the independent component buildup.');
assert(abs(first.pitchingMomentSlope_perRad-expectedMomentSlope_perRad)<tol && ...
    abs(first.elevatorControlDerivative_perRad-expectedElevatorDerivative_perRad)<tol, ...
    'Alpha and elevator moment derivatives must follow the declared lever arms and signs.');
assert(abs(first.referenceTrimAngleOfAttack_deg- ...
    expectedReferenceTrimAlpha_deg)<tol && ...
    abs(first.absoluteAngleOfAttack_deg-( ...
    expectedReferenceTrimAlpha_deg+first.angleOfAttackPerturbation_deg))<tol, ...
    'The disturbed absolute alpha must offset, not overwrite, the fixed P04 reference alpha.');
assert(abs(first.momentScale_Nm-expectedMomentScale_Nm)<1e-8 && ...
    abs(first.pitchingMomentCoefficient-expectedDeltaCm)<tol && ...
    abs(first.pitchingMoment_Nm-expectedMoment_Nm)<1e-8, ...
    'The coefficient increment must scale to N*m with q*S*c_bar.');
assert(abs(first.neutralPoint_percentMAC-50.84683357879235)<1e-11 && ...
    abs(first.staticMargin_percentMAC-20.84683357879235)<1e-11 && ...
    abs(first.pitchingMomentSlope_perRad+1.1324)<1e-12 && ...
    abs(first.pitchingMoment_Nm+1272.71743379418)<1e-8, ...
    'The P04-reference baseline must remain numerically recognizable.');
assert(first.isStaticallyStable && ~first.isNeutral && ...
    ~first.isStaticallyUnstable && first.alphaMoment_Nm<0, ...
    'Positive delta alpha must create a nose-down restoring baseline moment.');

%% Component and neutral-point formulations agree independently
general=model(37,12,1.7,-3);
independentCg=general.cgPosition_percentMAC/100;
independentTailRatio=general.tailAreaRatio_percent/100;
independentTailLift=0.9*independentTailRatio*4.0*(1-0.4);
independentTotalLiftSlope=5.0+independentTailLift;
independentNeutralPoint=(5.0*0.25+independentTailLift*3.5)/ ...
    independentTotalLiftSlope;
independentStaticMargin=independentNeutralPoint-independentCg;
componentMomentSlope=5.0*(independentCg-0.25)+ ...
    independentTailLift*(independentCg-3.5);
neutralPointMomentSlope=-independentTotalLiftSlope* ...
    independentStaticMargin;
assert(abs(componentMomentSlope-neutralPointMomentSlope)<tol && ...
    abs(general.pitchingMomentSlope_perRad-componentMomentSlope)<tol && ...
    abs(general.neutralPointMomentSlope_perRad- ...
    neutralPointMomentSlope)<tol, ...
    'Component lever arms and the neutral-point identity must agree.');
independentElevatorDerivative=-0.9*independentTailRatio*4.0*0.6*( ...
    3.5-independentCg);
independentDeltaCm=componentMomentSlope*(1.7*pi/180)+ ...
    independentElevatorDerivative*(-3*pi/180);
assert(abs(general.elevatorControlDerivative_perRad- ...
    independentElevatorDerivative)<tol && ...
    abs(general.pitchingMomentCoefficient-independentDeltaCm)<tol, ...
    'Elevator and alpha moment increments must add without changing the slope.');

%% Local reference, alpha symmetry, and stability limiting cases
zeroPerturbation=model(45,7,0,0);
assert(zeroPerturbation.alphaMomentCoefficient==0 && ...
    zeroPerturbation.elevatorMomentCoefficient==0 && ...
    zeroPerturbation.pitchingMomentCoefficient==0 && ...
    zeroPerturbation.pitchingMoment_Nm==0, ...
    'Every geometry must have zero increment at its separately retrimmed local reference.');
positiveAlpha=model(30,20,2,0);
negativeAlpha=model(30,20,-2,0);
changedGeometryAlpha=model(45,5,2,0);
assert(abs(positiveAlpha.alphaMomentCoefficient+ ...
    negativeAlpha.alphaMomentCoefficient)<tol && ...
    abs(positiveAlpha.alphaMoment_Nm+negativeAlpha.alphaMoment_Nm)<1e-8, ...
    'Equal positive and negative alpha perturbations must give opposite linear moments.');
assert(positiveAlpha.referenceTrimAngleOfAttack_deg== ...
    negativeAlpha.referenceTrimAngleOfAttack_deg && ...
    positiveAlpha.referenceTrimAngleOfAttack_deg== ...
    changedGeometryAlpha.referenceTrimAngleOfAttack_deg && ...
    abs(positiveAlpha.absoluteAngleOfAttack_deg-( ...
    expectedReferenceTrimAlpha_deg+2))<tol && ...
    abs(negativeAlpha.absoluteAngleOfAttack_deg-( ...
    expectedReferenceTrimAlpha_deg-2))<tol && ...
    changedGeometryAlpha.absoluteAngleOfAttack_deg== ...
    positiveAlpha.absoluteAngleOfAttack_deg, ...
    'CG and tail levers must not relabel the fixed P04 alpha reference as the disturbed absolute alpha.');

neutralCg=model(first.neutralPoint_percentMAC,20,2,0);
forwardCg=model(20,20,2,0);
aftCg=model(56,20,2,0);
assert(neutralCg.isNeutral && abs(neutralCg.pitchingMomentSlope_perRad)<= ...
    neutralCg.stabilityTolerance_perRad && abs(neutralCg.alphaMoment_Nm)<1e-8, ...
    'CG at the neutral point must remove the first-order alpha moment.');
assert(forwardCg.isStaticallyStable && forwardCg.alphaMoment_Nm<0 && ...
    aftCg.isStaticallyUnstable && aftCg.alphaMoment_Nm>0, ...
    'CG forward and aft of the neutral point must have restoring and reinforcing tendencies.');
assert(abs(aftCg.pitchingMomentSlope_perRad-0.27992)<1e-12 && ...
    abs(aftCg.pitchingMoment_Nm-314.605319734782)<1e-8, ...
    'The aft-CG unstable limit must remain recognizable.');

noTail=model(30,0,2,5);
wingOnlyNeutral=model(25,0,2,5);
assert(abs(noTail.neutralPoint_percentMAC-25)<tol && ...
    abs(noTail.pitchingMomentSlope_perRad-0.25)<tol && ...
    noTail.elevatorControlDerivative_perRad==0 && ...
    noTail.elevatorMomentCoefficient==0 && noTail.isStaticallyUnstable, ...
    'Without a tail, h_n must equal the wing AC and elevator input must vanish.');
assert(wingOnlyNeutral.isNeutral && ...
    abs(wingOnlyNeutral.pitchingMomentSlope_perRad)<= ...
    wingOnlyNeutral.stabilityTolerance_perRad, ...
    'CG at the wing AC must be neutral in the no-tail limiting case.');

neutralTailArea_percent=100*5.0*(0.30-0.25)/( ...
    0.9*4.0*(1-0.4)*(3.5-0.30));
neutralTail=model(30,neutralTailArea_percent,2,0);
assert(abs(neutralTailArea_percent-3.616898148148147)<1e-12 && ...
    neutralTail.isNeutral && abs(neutralTail.alphaMoment_Nm)<1e-8, ...
    'The analytic tail-area limit must place h_n at the fixed CG.');

%% Elevator changes the input response, not static stability
elevatorDown=model(30,20,0,5);
elevatorUp=model(30,20,0,-5);
assert(elevatorDown.elevatorMoment_Nm<0 && elevatorUp.elevatorMoment_Nm>0 && ...
    abs(elevatorDown.elevatorMoment_Nm+elevatorUp.elevatorMoment_Nm)<1e-8, ...
    'Positive trailing-edge-down elevator must create the declared nose-down moment.');
assert(elevatorDown.pitchingMomentSlope_perRad== ...
    elevatorUp.pitchingMomentSlope_perRad && ...
    elevatorDown.staticMargin_percentMAC==elevatorUp.staticMargin_percentMAC, ...
    'Elevator perturbation must not alter stick-fixed slope or static margin.');

%% Sweep regressions keep the two design levers independent
cgSweep_percentMAC=[20 28 36 44 50.8468335787924 56];
cgNeutralPoint=zeros(size(cgSweep_percentMAC));
cgStaticMargin=zeros(size(cgSweep_percentMAC));
cgMomentSlope=zeros(size(cgSweep_percentMAC));
cgMoment_Nm=zeros(size(cgSweep_percentMAC));
for k=1:numel(cgSweep_percentMAC)
    sample=model(cgSweep_percentMAC(k),20,2,0);
    assert(sample.tailAreaRatio_percent==20 && ...
        sample.angleOfAttackPerturbation_deg==2 && ...
        sample.elevatorPerturbation_deg==0, ...
        'The CG sweep must hold tail area and both perturbations fixed.');
    cgNeutralPoint(k)=sample.neutralPoint_percentMAC;
    cgStaticMargin(k)=sample.staticMargin_percentMAC;
    cgMomentSlope(k)=sample.pitchingMomentSlope_perRad;
    cgMoment_Nm(k)=sample.pitchingMoment_Nm;
end
assert(max(cgNeutralPoint)-min(cgNeutralPoint)<tol && ...
    all(diff(cgStaticMargin)<0) && all(diff(cgMomentSlope)>0) && ...
    all(diff(cgMoment_Nm)>0), ...
    'Moving CG aft must reduce margin and turn restoring moment toward reinforcing moment.');

tailAreaSweep_percent=[0 3.61689814814815 5 10 15 20 25];
tailNeutralPoint=zeros(size(tailAreaSweep_percent));
tailStaticMargin=zeros(size(tailAreaSweep_percent));
tailMomentSlope=zeros(size(tailAreaSweep_percent));
tailMoment_Nm=zeros(size(tailAreaSweep_percent));
for k=1:numel(tailAreaSweep_percent)
    sample=model(30,tailAreaSweep_percent(k),2,0);
    assert(sample.cgPosition_percentMAC==30 && ...
        sample.angleOfAttackPerturbation_deg==2 && ...
        sample.elevatorPerturbation_deg==0, ...
        'The tail-area sweep must hold CG and both perturbations fixed.');
    tailNeutralPoint(k)=sample.neutralPoint_percentMAC;
    tailStaticMargin(k)=sample.staticMargin_percentMAC;
    tailMomentSlope(k)=sample.pitchingMomentSlope_perRad;
    tailMoment_Nm(k)=sample.pitchingMoment_Nm;
end
assert(all(diff(tailNeutralPoint)>0) && all(diff(tailStaticMargin)>0) && ...
    all(diff(tailMomentSlope)<0) && all(diff(tailMoment_Nm)<0), ...
    'Increasing tail area must move h_n aft and strengthen the restoring response.');

%% Deliberately broken static-margin subtraction
brokenStaticMargin_fractionMAC=(first.cgPosition_percentMAC- ...
    first.neutralPoint_percentMAC)/100;
brokenMomentSlope_perRad=-first.aircraftLiftCurveSlope_perRad* ...
    brokenStaticMargin_fractionMAC;
brokenAlphaMomentCoefficient=brokenMomentSlope_perRad* ...
    first.angleOfAttackPerturbation_rad;
brokenAlphaMoment_Nm=first.momentScale_Nm*brokenAlphaMomentCoefficient;
assert(abs(brokenMomentSlope_perRad+first.pitchingMomentSlope_perRad)<tol && ...
    abs(brokenAlphaMoment_Nm+first.alphaMoment_Nm)<1e-8 && ...
    first.alphaMoment_Nm<0 && brokenAlphaMoment_Nm>0, ...
    'Reversing h_n-h_cg must turn the restoring alpha moment into a reinforcing one.');

%% Malformed inputs fail clearly, then a valid call recovers
expectFailure(@() model(14.9,20,2,0), ...
    'P05:model:CgRange','CG below the learning range');
expectFailure(@() model(65.1,20,2,0), ...
    'P05:model:CgRange','CG above the learning range');
expectFailure(@() model(30,-0.1,2,0), ...
    'P05:model:NegativeTailAreaRatio','negative tail-area ratio');
expectFailure(@() model(30,30.1,2,0), ...
    'P05:model:TailAreaRatioRange','tail-area ratio above the learning range');
expectFailure(@() model(30,20,-5.1,0), ...
    'P05:model:AlphaPerturbationRange','alpha below the learning range');
expectFailure(@() model(30,20,5.1,0), ...
    'P05:model:AlphaPerturbationRange','alpha above the learning range');
expectFailure(@() model(30,20,2,-15.1), ...
    'P05:model:ElevatorPerturbationRange','elevator below the learning range');
expectFailure(@() model(30,20,2,15.1), ...
    'P05:model:ElevatorPerturbationRange','elevator above the learning range');
expectFailure(@() model([30 31],20,2,0),'','nonscalar CG');
expectFailure(@() model(30,20+1i,2,0),'','complex tail-area ratio');
expectFailure(@() model(30,20,NaN,0),'','nonfinite alpha perturbation');
expectFailure(@() model(30,20,2,Inf),'','nonfinite elevator perturbation');
afterFailure=model(30,20,2,0);
assert(isequaln(afterFailure,first), ...
    'Rejected inputs must not alter the next deterministic calculation.');

disp('P05 checks passed: static margin, limits, sweeps, malformed inputs, and broken sign.');
end

function expectFailure(action,expectedIdentifier,label)
didFail=false;
try
    action();
catch exception
    didFail=true;
    if ~isempty(expectedIdentifier)
        assert(strcmp(exception.identifier,expectedIdentifier), ...
            'Expected %s to raise %s, but received %s.', ...
            label,expectedIdentifier,exception.identifier);
    end
end
assert(didFail,'Expected model to reject %s.',label);
end
