function out = model(forcePulseScale,momentPulseScale)
%MODEL Integrate a transparent nonlinear rigid-body 6-DOF teaching case.
% The propagated state is [position_NED; velocity_body; q_NB; rates_body].
% Body axes are x forward, y right, z down. NED uses Down positive. The
% scalar-first unit quaternion q_NB rotates body components into NED. The
% prescribed non-gravity loads are teaching inputs, not an aircraft model.
arguments
    forcePulseScale (1,1) double {mustBeReal,mustBeFinite} = 1
    momentPulseScale (1,1) double {mustBeReal,mustBeFinite} = 1
end

if forcePulseScale<0 || forcePulseScale>1.5
    error('P09:model:ForcePulseScaleRange', ...
        'Force-pulse scale must be between 0 and 1.5, inclusive.');
end
if momentPulseScale<0 || momentPulseScale>1.5
    error('P09:model:MomentPulseScaleRange', ...
        'Moment-pulse scale must be between 0 and 1.5, inclusive.');
end

mass_kg=1200;
gravity_mps2=9.80665;
inertiaTensor_kgm2=diag([2500 3000 4000]);
initialForwardSpeed_mps=60;
forwardForceAmplitude_N=2400;
baseMomentAmplitude_Nm=[500;700;350];
forcePulseDuration_s=1.5;
momentPulseDuration_s=1.0;
integrationStep_s=0.02;
timeHorizon_s=6;
time_s=0:integrationStep_s:timeHorizon_s;
parameters=struct( ...
    'mass_kg',mass_kg, ...
    'gravityNED_mps2',[0;0;gravity_mps2], ...
    'inertiaTensor_kgm2',inertiaTensor_kgm2, ...
    'forwardForceAmplitude_N',forwardForceAmplitude_N, ...
    'baseMomentAmplitude_Nm',baseMomentAmplitude_Nm, ...
    'forcePulseDuration_s',forcePulseDuration_s, ...
    'momentPulseDuration_s',momentPulseDuration_s, ...
    'forcePulseScale',forcePulseScale, ...
    'momentPulseScale',momentPulseScale);

initialState=[zeros(3,1);initialForwardSpeed_mps;0;0;1;0;0;0;0;0;0];
[state,quaternionProjectionCorrection]=integrateFixedRk4( ...
    initialState,time_s,parameters,false);
[brokenState,brokenQuaternionProjectionCorrection]=integrateFixedRk4( ...
    initialState,time_s,parameters,true);

sampleCount=numel(time_s);
stateDerivative=zeros(13,sampleCount);
appliedForceBody_N=zeros(3,sampleCount);
appliedMomentBody_Nm=zeros(3,sampleCount);
inertialVelocityNED_mps=zeros(3,sampleCount);
angularMomentumNED_Nms=zeros(3,sampleCount);
translationalEquationResidual_mps2=zeros(3,sampleCount);
rotationalEquationResidual_Nm=zeros(3,sampleCount);
quaternionNorm=zeros(1,sampleCount);
dcmOrthonormalityError=zeros(1,sampleCount);
dcmDeterminantError=zeros(1,sampleCount);
brokenPhysicalTransportResidual_mps2=zeros(3,sampleCount);
brokenInertialVelocityNED_mps=zeros(3,sampleCount);

for k=1:sampleCount
    [stateDerivative(:,k),appliedForceBody_N(:,k), ...
        appliedMomentBody_Nm(:,k),bodyToNed]=rigidBodyDerivative( ...
        time_s(k),state(:,k),parameters,false);
    bodyVelocity=state(4:6,k);
    quaternion=state(7:10,k);
    angularVelocity=state(11:13,k);
    inertialVelocityNED_mps(:,k)=bodyToNed*bodyVelocity;
    angularMomentumNED_Nms(:,k)=bodyToNed* ...
        (inertiaTensor_kgm2*angularVelocity);
    translationalEquationResidual_mps2(:,k)= ...
        stateDerivative(4:6,k)+cross(angularVelocity,bodyVelocity)- ...
        appliedForceBody_N(:,k)/mass_kg- ...
        bodyToNed'*parameters.gravityNED_mps2;
    rotationalEquationResidual_Nm(:,k)= ...
        inertiaTensor_kgm2*stateDerivative(11:13,k)+ ...
        cross(angularVelocity,inertiaTensor_kgm2*angularVelocity)- ...
        appliedMomentBody_Nm(:,k);
    quaternionNorm(k)=norm(quaternion);
    orthogonalityResidual=bodyToNed'*bodyToNed-eye(3);
    dcmOrthonormalityError(k)=max(abs(orthogonalityResidual(:)));
    dcmDeterminantError(k)=abs(det(bodyToNed)-1);

    [brokenDerivative,~,~,brokenBodyToNed]=rigidBodyDerivative( ...
        time_s(k),brokenState(:,k),parameters,true);
    brokenBodyVelocity=brokenState(4:6,k);
    brokenAngularVelocity=brokenState(11:13,k);
    brokenInertialVelocityNED_mps(:,k)= ...
        brokenBodyToNed*brokenBodyVelocity;
    % Evaluate the broken derivative against the complete physical balance.
    % The residual is exactly the rotating-frame term that was omitted.
    brokenPhysicalTransportResidual_mps2(:,k)= ...
        brokenDerivative(4:6)+ ...
        cross(brokenAngularVelocity,brokenBodyVelocity)- ...
        appliedForceBody_N(:,k)/mass_kg- ...
        brokenBodyToNed'*parameters.gravityNED_mps2;
end

positionNED_m=state(1:3,:);
velocityBody_mps=state(4:6,:);
quaternionBodyToNED=state(7:10,:);
bodyRates_rad_s=state(11:13,:);
bodyRates_deg_s=bodyRates_rad_s*180/pi;
eulerAngles_deg=quaternionHistoryToEulerDeg(quaternionBodyToNED);
speed_mps=sqrt(sum(inertialVelocityNED_mps.^2,1));
bodyRateMagnitude_deg_s=sqrt(sum(bodyRates_deg_s.^2,1));
attitudeRotation_deg=2*acos(min(1,abs(quaternionBodyToNED(1,:))))*180/pi;
brokenPositionNED_m=brokenState(1:3,:);
brokenPositionError_m=sqrt(sum((brokenPositionNED_m-positionNED_m).^2,1));
brokenTransportResidualMagnitude_mps2=sqrt( ...
    sum(brokenPhysicalTransportResidual_mps2.^2,1));

postPulseIndices=find(time_s>=momentPulseDuration_s);
referenceAngularMomentum=angularMomentumNED_Nms(:,postPulseIndices(1));
referenceAngularMomentumNorm=norm(referenceAngularMomentum);
if referenceAngularMomentumNorm==0
    postPulseAngularMomentumRelativeDrift=0;
else
    angularMomentumDifference=angularMomentumNED_Nms(:,postPulseIndices)- ...
        referenceAngularMomentum;
    postPulseAngularMomentumRelativeDrift=max(sqrt( ...
        sum(angularMomentumDifference.^2,1)))/referenceAngularMomentumNorm;
end

out=struct( ...
    'forcePulseScale',forcePulseScale, ...
    'momentPulseScale',momentPulseScale, ...
    'time_s',time_s, ...
    'sampleCount',sampleCount, ...
    'integrationStep_s',integrationStep_s, ...
    'timeHorizon_s',timeHorizon_s, ...
    'integrationMethod','fixed-step explicit RK4 with quaternion projection', ...
    'state',state, ...
    'stateDerivative',stateDerivative, ...
    'positionNED_m',positionNED_m, ...
    'north_m',positionNED_m(1,:), ...
    'east_m',positionNED_m(2,:), ...
    'down_m',positionNED_m(3,:), ...
    'velocityBody_mps',velocityBody_mps, ...
    'inertialVelocityNED_mps',inertialVelocityNED_mps, ...
    'speed_mps',speed_mps, ...
    'quaternionBodyToNED',quaternionBodyToNED, ...
    'quaternionNorm',quaternionNorm, ...
    'quaternionProjectionCorrection',quaternionProjectionCorrection, ...
    'bodyRates_rad_s',bodyRates_rad_s, ...
    'bodyRates_deg_s',bodyRates_deg_s, ...
    'bodyRateMagnitude_deg_s',bodyRateMagnitude_deg_s, ...
    'eulerAngles_deg',eulerAngles_deg, ...
    'attitudeRotation_deg',attitudeRotation_deg, ...
    'appliedForceBody_N',appliedForceBody_N, ...
    'appliedMomentBody_Nm',appliedMomentBody_Nm, ...
    'angularMomentumNED_Nms',angularMomentumNED_Nms, ...
    'translationalEquationResidual_mps2', ...
    translationalEquationResidual_mps2, ...
    'rotationalEquationResidual_Nm',rotationalEquationResidual_Nm, ...
    'dcmOrthonormalityError',dcmOrthonormalityError, ...
    'dcmDeterminantError',dcmDeterminantError, ...
    'postPulseAngularMomentumRelativeDrift', ...
    postPulseAngularMomentumRelativeDrift, ...
    'finalPositionNED_m',positionNED_m(:,end), ...
    'finalSpeed_mps',speed_mps(end), ...
    'peakBodyRateMagnitude_deg_s',max(bodyRateMagnitude_deg_s), ...
    'peakAttitudeRotation_deg',max(attitudeRotation_deg), ...
    'mass_kg',mass_kg, ...
    'gravity_mps2',gravity_mps2, ...
    'inertiaTensor_kgm2',inertiaTensor_kgm2, ...
    'initialForwardSpeed_mps',initialForwardSpeed_mps, ...
    'forwardForceAmplitude_N',forwardForceAmplitude_N, ...
    'baseMomentAmplitude_Nm',baseMomentAmplitude_Nm, ...
    'forcePulseDuration_s',forcePulseDuration_s, ...
    'momentPulseDuration_s',momentPulseDuration_s, ...
    'brokenState',brokenState, ...
    'brokenPositionNED_m',brokenPositionNED_m, ...
    'brokenVelocityBody_mps',brokenState(4:6,:), ...
    'brokenInertialVelocityNED_mps',brokenInertialVelocityNED_mps, ...
    'brokenQuaternionProjectionCorrection', ...
    brokenQuaternionProjectionCorrection, ...
    'brokenPhysicalTransportResidual_mps2', ...
    brokenPhysicalTransportResidual_mps2, ...
    'brokenTransportResidualMagnitude_mps2', ...
    brokenTransportResidualMagnitude_mps2, ...
    'brokenPositionError_m',brokenPositionError_m, ...
    'brokenFinalPositionError_m',brokenPositionError_m(end), ...
    'stateOrder',[ ...
        '[north, east, down, u, v, w, q0, q1, q2, q3, p, q, r]'], ...
    'frameConvention',[ ...
        'body x forward, y right, z down; local navigation is NED; ' ...
        'q_NB and C_NB rotate body components into NED'], ...
    'loadConvention',[ ...
        'F_body excludes gravity; steady body -z force balances weight ' ...
        'only at the initial level attitude'], ...
    'analysisScope',[ ...
        'prescribed deterministic loads on a rigid body; no aerodynamics, ' ...
        'actuator dynamics, sensors, Earth rotation, or identified-aircraft fidelity']);
end

function [state,projectionCorrection] = integrateFixedRk4( ...
    initialState,time_s,parameters,omitTransportTerm)
%INTEGRATEFIXEDRK4 Propagate every state with a visible bounded recurrence.
state=zeros(13,numel(time_s));
projectionCorrection=zeros(1,numel(time_s));
state(:,1)=initialState;
for k=1:numel(time_s)-1
    step_s=time_s(k+1)-time_s(k);
    k1=rigidBodyDerivative(time_s(k),state(:,k),parameters, ...
        omitTransportTerm);
    k2=rigidBodyDerivative(time_s(k)+0.5*step_s, ...
        state(:,k)+0.5*step_s*k1,parameters,omitTransportTerm);
    k3=rigidBodyDerivative(time_s(k)+0.5*step_s, ...
        state(:,k)+0.5*step_s*k2,parameters,omitTransportTerm);
    k4=rigidBodyDerivative(time_s(k)+step_s, ...
        state(:,k)+step_s*k3,parameters,omitTransportTerm);
    nextState=state(:,k)+step_s/6*(k1+2*k2+2*k3+k4);
    candidateQuaternion=nextState(7:10);
    projectionCorrection(k+1)=abs(norm(candidateQuaternion)-1);
    nextState(7:10)=normalizeQuaternion(candidateQuaternion);
    state(:,k+1)=nextState;
end
end

function [stateDerivative,forceBody_N,momentBody_Nm,bodyToNed] = ...
    rigidBodyDerivative(time_s,state,parameters,omitTransportTerm)
%RIGIDBODYDERIVATIVE Evaluate the complete body-axis equations of motion.
bodyVelocity_mps=state(4:6);
quaternionBodyToNed=normalizeQuaternion(state(7:10));
angularVelocity_rad_s=state(11:13);
bodyToNed=quaternionToDcm(quaternionBodyToNed);
[forceBody_N,momentBody_Nm]=prescribedLoads(time_s,parameters);

positionDerivativeNED_mps=bodyToNed*bodyVelocity_mps;
gravityBody_mps2=bodyToNed'*parameters.gravityNED_mps2;
transportAcceleration_mps2=cross(angularVelocity_rad_s,bodyVelocity_mps);
velocityDerivativeBody_mps2=forceBody_N/parameters.mass_kg+ ...
    gravityBody_mps2-transportAcceleration_mps2;
if omitTransportTerm
    velocityDerivativeBody_mps2=forceBody_N/parameters.mass_kg+ ...
        gravityBody_mps2;
end

angularMomentumBody_Nms=parameters.inertiaTensor_kgm2* ...
    angularVelocity_rad_s;
angularAccelerationBody_rad_s2=parameters.inertiaTensor_kgm2\( ...
    momentBody_Nm-cross(angularVelocity_rad_s,angularMomentumBody_Nms));
q0=quaternionBodyToNed(1);
q1=quaternionBodyToNed(2);
q2=quaternionBodyToNed(3);
q3=quaternionBodyToNed(4);
p=angularVelocity_rad_s(1);
q=angularVelocity_rad_s(2);
r=angularVelocity_rad_s(3);
quaternionDerivative=0.5*[ ...
    -q1*p-q2*q-q3*r; ...
     q0*p+q2*r-q3*q; ...
     q0*q+q3*p-q1*r; ...
     q0*r+q1*q-q2*p];
stateDerivative=[positionDerivativeNED_mps; ...
    velocityDerivativeBody_mps2;quaternionDerivative; ...
    angularAccelerationBody_rad_s2];
end

function [forceBody_N,momentBody_Nm] = prescribedLoads(time_s,parameters)
%PRESCRIBEDLOADS Return deterministic non-gravity body loads.
forcePulse=halfSinePulse(time_s,parameters.forcePulseDuration_s);
momentPulse=halfSinePulse(time_s,parameters.momentPulseDuration_s);
forceBody_N=[ ...
    parameters.forwardForceAmplitude_N*parameters.forcePulseScale*forcePulse; ...
    0; ...
    -parameters.mass_kg*parameters.gravityNED_mps2(3)];
momentBody_Nm=parameters.baseMomentAmplitude_Nm* ...
    parameters.momentPulseScale*momentPulse;
end

function value = halfSinePulse(time_s,duration_s)
%HALFSINEPULSE A continuous finite-duration command with zero endpoints.
if time_s>=0 && time_s<duration_s
    value=sin(pi*time_s/duration_s);
else
    value=0;
end
end

function quaternion = normalizeQuaternion(quaternion)
%NORMALIZEQUATERNION Project the scalar-first attitude quaternion to unit norm.
quaternion=quaternion/norm(quaternion);
end

function bodyToNed = quaternionToDcm(quaternion)
%QUATERNIONTODCM Rotate body components into NED using scalar-first q_NB.
q0=quaternion(1);
q1=quaternion(2);
q2=quaternion(3);
q3=quaternion(4);
bodyToNed=[ ...
    q0^2+q1^2-q2^2-q3^2, 2*(q1*q2-q0*q3), 2*(q1*q3+q0*q2); ...
    2*(q1*q2+q0*q3), q0^2-q1^2+q2^2-q3^2, 2*(q2*q3-q0*q1); ...
    2*(q1*q3-q0*q2), 2*(q2*q3+q0*q1), q0^2-q1^2-q2^2+q3^2];
end

function eulerAngles_deg = quaternionHistoryToEulerDeg(quaternionHistory)
%QUATERNIONHISTORYTOEULERDEG Derive 3-2-1 angles for display only.
q0=quaternionHistory(1,:);
q1=quaternionHistory(2,:);
q2=quaternionHistory(3,:);
q3=quaternionHistory(4,:);
roll_rad=atan2(2*(q0.*q1+q2.*q3),1-2*(q1.^2+q2.^2));
pitchSine=2*(q0.*q2-q3.*q1);
pitchSine=max(-1,min(1,pitchSine));
pitch_rad=asin(pitchSine);
yaw_rad=atan2(2*(q0.*q3+q1.*q2),1-2*(q2.^2+q3.^2));
eulerAngles_deg=[roll_rad;pitch_rad;yaw_rad]*180/pi;
end
