function run_checks
%RUN_CHECKS Independent checks for the P09 nonlinear 6-DOF integrator.
clear model;
tol=1e-10;

%% Determinism, fixed shape, finite resources, and bounded accepted inputs
first=model(1,1);
second=model(1,1);
assert(isequaln(first,second), ...
    'Identical force and moment inputs must produce identical states.');
assert(first.sampleCount==301 && first.integrationStep_s==0.02 && ...
    first.timeHorizon_s==6 && isequal(size(first.time_s),[1 301]) && ...
    first.time_s(1)==0 && first.time_s(end)==6, ...
    'The synchronous resource boundary must remain 301 samples over 6 s.');

fixedShapeFields={ ...
    'positionNED_m',3;'velocityBody_mps',3; ...
    'inertialVelocityNED_mps',3;'bodyRates_rad_s',3; ...
    'bodyRates_deg_s',3;'eulerAngles_deg',3; ...
    'appliedForceBody_N',3;'appliedMomentBody_Nm',3; ...
    'angularMomentumNED_Nms',3; ...
    'translationalEquationResidual_mps2',3; ...
    'rotationalEquationResidual_Nm',3; ...
    'quaternionBodyToNED',4; ...
    'brokenPositionNED_m',3;'brokenVelocityBody_mps',3; ...
    'brokenInertialVelocityNED_mps',3; ...
    'brokenPhysicalTransportResidual_mps2',3};
for k=1:size(fixedShapeFields,1)
    value=first.(fixedShapeFields{k,1});
    assert(isequal(size(value),[fixedShapeFields{k,2} 301]) && ...
        isreal(value) && all(isfinite(value(:))), ...
        'Every matrix history must retain its declared finite shape.');
end
assert(isequal(size(first.state),[13 301]) && ...
    isequal(size(first.stateDerivative),[13 301]) && ...
    isequal(size(first.brokenState),[13 301]) && ...
    all(isfinite(first.state(:))) && ...
    all(isfinite(first.stateDerivative(:))) && ...
    all(isfinite(first.brokenState(:))), ...
    'Correct and broken state histories must remain finite 13-by-301 arrays.');

rowFields={'north_m','east_m','down_m','speed_mps','quaternionNorm', ...
    'quaternionProjectionCorrection','bodyRateMagnitude_deg_s', ...
    'attitudeRotation_deg','dcmOrthonormalityError', ...
    'dcmDeterminantError','brokenQuaternionProjectionCorrection', ...
    'brokenTransportResidualMagnitude_mps2','brokenPositionError_m'};
for k=1:numel(rowFields)
    value=first.(rowFields{k});
    assert(isequal(size(value),[1 301]) && isreal(value) && ...
        all(isfinite(value)), ...
        'Every scalar history must be a finite 1-by-301 row vector.');
end

edgeScales=[0 1.5];
edgeCaseCount=0;
for forceIndex=1:numel(edgeScales)
    for momentIndex=1:numel(edgeScales)
        edge=model(edgeScales(forceIndex),edgeScales(momentIndex));
        edgeCaseCount=edgeCaseCount+1;
        assert(edge.sampleCount==301 && all(isfinite(edge.state(:))) && ...
            all(isfinite(edge.brokenState(:))) && ...
            max(edge.speed_mps)<100 && ...
            edge.peakBodyRateMagnitude_deg_s<25 && ...
            edge.peakAttitudeRotation_deg<110 && ...
            max(sqrt(sum(edge.positionNED_m.^2,1)))<500 && ...
            max(sqrt(sum(edge.brokenPositionNED_m.^2,1)))<1000 && ...
            max(abs(edge.quaternionNorm-1))<1e-14 && ...
            max(edge.dcmOrthonormalityError)<1e-14, ...
            'Every accepted scale corner must remain finite and bounded.');
    end
end
assert(edgeCaseCount==4,'The accepted-corner check must stay fixed at 4 cases.');

representativeScales=[0 0.75 1.5];
representativeCaseCount=0;
for forceIndex=1:numel(representativeScales)
    for momentIndex=1:numel(representativeScales)
        sample=model(representativeScales(forceIndex), ...
            representativeScales(momentIndex));
        representativeCaseCount=representativeCaseCount+1;
        assert(sample.sampleCount==301 && ...
            isequal(size(sample.state),[13 301]) && ...
            all(isfinite(sample.state(:))), ...
            'The representative grid must retain bounded fixed work.');
    end
end
assert(representativeCaseCount==9 && representativeCaseCount<=10, ...
    'The representative resource grid must stay capped at 9 calls.');

%% Independent load reconstruction and all 13 state equations
expectedMass_kg=1200;
expectedGravityNED_mps2=[0;0;9.80665];
expectedInertia_kgm2=diag([2500 3000 4000]);
expectedForceAmplitude_N=2400;
expectedMomentAmplitude_Nm=[500;700;350];
expectedForce=zeros(3,first.sampleCount);
expectedMoment=zeros(3,first.sampleCount);
expectedDerivative=zeros(13,first.sampleCount);
for k=1:first.sampleCount
    time_s=first.time_s(k);
    forcePulse=independentHalfSine(time_s,1.5);
    momentPulse=independentHalfSine(time_s,1.0);
    expectedForce(:,k)=[expectedForceAmplitude_N*forcePulse;0; ...
        -expectedMass_kg*expectedGravityNED_mps2(3)];
    expectedMoment(:,k)=expectedMomentAmplitude_Nm*momentPulse;

    position=first.state(1:3,k); %#ok<NASGU>
    velocityBody=first.state(4:6,k);
    quaternion=first.state(7:10,k);
    angularVelocity=first.state(11:13,k);
    bodyToNed=independentQuaternionToDcm(quaternion);
    positionDot=bodyToNed*velocityBody;
    velocityDot=expectedForce(:,k)/expectedMass_kg+ ...
        bodyToNed'*expectedGravityNED_mps2- ...
        cross(angularVelocity,velocityBody);
    angularMomentum=expectedInertia_kgm2*angularVelocity;
    angularVelocityDot=expectedInertia_kgm2\(expectedMoment(:,k)- ...
        cross(angularVelocity,angularMomentum));
    quaternionDot=independentQuaternionDerivative(quaternion, ...
        angularVelocity);
    expectedDerivative(:,k)=[positionDot;velocityDot;quaternionDot; ...
        angularVelocityDot];
end
assert(max(abs(first.appliedForceBody_N(:)-expectedForce(:)))<tol && ...
    max(abs(first.appliedMomentBody_Nm(:)-expectedMoment(:)))<tol, ...
    'Stored body loads must match independent half-sine reconstruction.');
assert(max(abs(first.stateDerivative(:)-expectedDerivative(:)))<1e-12, ...
    'Position, translation, quaternion, and rotation derivatives must close.');
assert(max(abs(first.translationalEquationResidual_mps2(:)))<1e-12 && ...
    max(abs(first.rotationalEquationResidual_Nm(:)))<1e-10, ...
    'Independent translational and rotational residuals must close.');

quaternionTangent=sum(first.quaternionBodyToNED.* ...
    first.stateDerivative(7:10,:),1);
assert(max(abs(quaternionTangent))<1e-14, ...
    'Quaternion derivatives must remain tangent to the unit sphere.');

%% Quaternion/DCM direction, normalization, and frame signs
yaw90=[cos(pi/4);0;0;sin(pi/4)];
pitch30=[cos(pi/12);0;sin(pi/12);0];
roll30=[cos(pi/12);sin(pi/12);0;0];
yawForward=independentQuaternionToDcm(yaw90)*[1;0;0];
pitchForward=independentQuaternionToDcm(pitch30)*[1;0;0];
rollRight=independentQuaternionToDcm(roll30)*[0;1;0];
assert(max(abs(yawForward-[0;1;0]))<tol && ...
    pitchForward(1)>0 && pitchForward(3)<0 && ...
    rollRight(2)>0 && rollRight(3)>0, ...
    'Positive yaw, pitch, and roll must match body-to-NED signs.');
assert(max(abs(first.quaternionNorm-1))<1e-14 && ...
    max(first.quaternionProjectionCorrection)<1e-10 && ...
    max(first.dcmOrthonormalityError)<1e-14 && ...
    max(first.dcmDeterminantError)<1e-14, ...
    'Quaternion projection must retain a proper orthonormal DCM.');

%% Every stored state obeys the explicit projected RK4 recurrence
reproduced=zeros(13,first.sampleCount);
reproduced(:,1)=[zeros(3,1);60;0;0;1;0;0;0;0;0;0];
for k=1:first.sampleCount-1
    step_s=first.time_s(k+1)-first.time_s(k);
    k1=independentDerivative(first.time_s(k),reproduced(:,k),1,1,false);
    k2=independentDerivative(first.time_s(k)+0.5*step_s, ...
        reproduced(:,k)+0.5*step_s*k1,1,1,false);
    k3=independentDerivative(first.time_s(k)+0.5*step_s, ...
        reproduced(:,k)+0.5*step_s*k2,1,1,false);
    k4=independentDerivative(first.time_s(k)+step_s, ...
        reproduced(:,k)+step_s*k3,1,1,false);
    nextState=reproduced(:,k)+step_s/6*(k1+2*k2+2*k3+k4);
    nextState(7:10)=nextState(7:10)/norm(nextState(7:10));
    reproduced(:,k+1)=nextState;
end
assert(max(abs(first.state(:)-reproduced(:)))<1e-13, ...
    'All 13 states must obey the visible RK4 recurrence and q projection.');

%% Recognizable baseline, exact zero limit, and analytic force-only limit
assert(max(abs(first.finalPositionNED_m-[ ...
    328.491610431943;28.8297159145262;13.3621003362435]))<1e-9 && ...
    abs(first.finalSpeed_mps-43.2498154138247)<1e-10 && ...
    abs(first.peakBodyRateMagnitude_deg_s-11.6523195502974)<1e-10 && ...
    abs(first.peakAttitudeRotation_deg-63.9572808763137)<1e-10, ...
    'The deterministic baseline signature must remain recognizable.');

zero=model(0,0);
expectedStraightPosition=[60*zero.time_s; ...
    zeros(1,zero.sampleCount);zeros(1,zero.sampleCount)];
expectedStraightState=[expectedStraightPosition; ...
    repmat([60;0;0;1;0;0;0;0;0;0],1,zero.sampleCount)];
assert(max(abs(zero.state(:)-expectedStraightState(:)))<1e-12 && ...
    isequal(zero.brokenState,zero.state) && ...
    all(all(zero.stateDerivative(4:13,:)==0)) && ...
    zero.peakBodyRateMagnitude_deg_s==0 && ...
    zero.peakAttitudeRotation_deg==0 && ...
    zero.brokenFinalPositionError_m==0, ...
    'Zero pulses must give exact straight level motion in both propagators.');

forceOnly=model(1,0);
accelerationAmplitude_mps2=expectedForceAmplitude_N/expectedMass_kg;
expectedFinalForwardSpeed_mps=60+ ...
    2*accelerationAmplitude_mps2*1.5/pi;
expectedFinalNorth_m=60*6+accelerationAmplitude_mps2*1.5/pi* ...
    (2*6-1.5);
assert(abs(forceOnly.velocityBody_mps(1,end)- ...
    expectedFinalForwardSpeed_mps)<2e-8 && ...
    abs(forceOnly.finalPositionNED_m(1)-expectedFinalNorth_m)<2e-8 && ...
    all(all(forceOnly.positionNED_m(2:3,:)==0)) && ...
    all(forceOnly.bodyRates_rad_s(:)==0) && ...
    isequal(forceOnly.brokenState,forceOnly.state), ...
    'Force-only propagation must match its analytic straight-line limit.');

smallestPositiveMoment=model(1,eps(0));
assert(isfinite(smallestPositiveMoment.postPulseAngularMomentumRelativeDrift) && ...
    smallestPositiveMoment.postPulseAngularMomentumRelativeDrift==0, ...
    ['An accepted moment too small to produce representable angular momentum ' ...
    'must report zero drift rather than divide zero by zero.']);

%% Torque-free energy and inertial angular momentum after the pulse
postPulse=first.time_s>=first.momentPulseDuration_s;
omega=first.bodyRates_rad_s(:,postPulse);
rotationalEnergy_J=0.5*sum(omega.*(expectedInertia_kgm2*omega),1);
angularMomentum=first.angularMomentumNED_Nms(:,postPulse);
referenceEnergy=rotationalEnergy_J(1);
referenceMomentum=angularMomentum(:,1);
relativeEnergyDrift=max(abs(rotationalEnergy_J-referenceEnergy))/ ...
    referenceEnergy;
relativeMomentumDrift=max(sqrt(sum((angularMomentum- ...
    referenceMomentum).^2,1)))/norm(referenceMomentum);
assert(relativeEnergyDrift<1e-11 && relativeMomentumDrift<1e-11 && ...
    abs(first.postPulseAngularMomentumRelativeDrift- ...
    relativeMomentumDrift)<1e-15, ...
    'Torque-free energy and inertial angular momentum must remain constant.');

%% Two isolated physical sweeps
forceSweep=[0 0.5 1 1.25 1.5];
finalNorth=zeros(size(forceSweep));
finalSpeed=zeros(size(forceSweep));
for k=1:numel(forceSweep)
    sample=model(forceSweep(k),1);
    difference=sample.appliedForceBody_N-first.appliedForceBody_N;
    difference(1,:)=0;
    assert(all(difference(:)==0) && ...
        isequal(sample.appliedMomentBody_Nm,first.appliedMomentBody_Nm) && ...
        isequal(sample.quaternionBodyToNED,first.quaternionBodyToNED) && ...
        isequal(sample.bodyRates_rad_s,first.bodyRates_rad_s), ...
        'The force sweep may change only F_x and translational states.');
    finalNorth(k)=sample.finalPositionNED_m(1);
    finalSpeed(k)=sample.finalSpeed_mps;
end
assert(all(diff(finalNorth)>0) && all(diff(finalSpeed)>0), ...
    'Increasing forward impulse must increase final north and speed.');

momentSweep=[0 0.5 1 1.25 1.5];
peakRate=zeros(size(momentSweep));
peakAttitude=zeros(size(momentSweep));
for k=1:numel(momentSweep)
    sample=model(1,momentSweep(k));
    assert(isequal(sample.appliedForceBody_N,first.appliedForceBody_N) && ...
        max(abs(sample.appliedMomentBody_Nm(:)- ...
        momentSweep(k)*first.appliedMomentBody_Nm(:)))<tol, ...
        'The moment sweep must leave every force sample fixed.');
    peakRate(k)=sample.peakBodyRateMagnitude_deg_s;
    peakAttitude(k)=sample.peakAttitudeRotation_deg;
end
assert(peakRate(1)==0 && peakAttitude(1)==0 && ...
    all(diff(peakRate)>0) && all(diff(peakAttitude)>0), ...
    'Increasing angular impulse must increase peak rate and rotation.');

%% Deliberately broken rotating-frame transport term
assert(first.brokenFinalPositionError_m>100 && ...
    abs(first.brokenFinalPositionError_m-132.791783071938)<1e-9 && ...
    max(first.brokenTransportResidualMagnitude_mps2)>5 && ...
    isequal(first.brokenState(7:13,:),first.state(7:13,:)), ...
    'The broken case must isolate a large translational frame error.');
expectedBrokenResidual=zeros(3,first.sampleCount);
for k=1:first.sampleCount
    expectedBrokenResidual(:,k)=cross(first.brokenState(11:13,k), ...
        first.brokenState(4:6,k));
end
assert(max(abs(first.brokenPhysicalTransportResidual_mps2(:)- ...
    expectedBrokenResidual(:)))<1e-12, ...
    'The broken residual must equal the omitted omega-cross-v term.');

%% Malformed inputs fail clearly, then a valid call recovers
expectFailure(@() model(-0.001,1), ...
    'P09:model:ForcePulseScaleRange','force scale below range');
expectFailure(@() model(1.501,1), ...
    'P09:model:ForcePulseScaleRange','force scale above range');
expectFailure(@() model(1,-0.001), ...
    'P09:model:MomentPulseScaleRange','moment scale below range');
expectFailure(@() model(1,1.501), ...
    'P09:model:MomentPulseScaleRange','moment scale above range');
expectFailure(@() model([1 1],1),'','nonscalar force scale');
expectFailure(@() model(1,1+1i),'','complex moment scale');
expectFailure(@() model(NaN,1),'','nonfinite force scale');
expectFailure(@() model(1,Inf),'','nonfinite moment scale');
afterFailure=model(1,1);
assert(isequaln(afterFailure,first), ...
    'Rejected inputs must not poison deterministic recovery.');

disp(['P09 checks passed: 13-state RK4, force/moment closure, quaternion/DCM ' ...
    'invariants, limits, isolated sweeps, malformed-input recovery, and broken transport.']);
end

function derivative = independentDerivative(time_s,state,forceScale, ...
    momentScale,omitTransportTerm)
mass_kg=1200;
gravityNED_mps2=[0;0;9.80665];
inertia_kgm2=diag([2500 3000 4000]);
quaternion=state(7:10)/norm(state(7:10));
bodyToNed=independentQuaternionToDcm(quaternion);
velocityBody=state(4:6);
angularVelocity=state(11:13);
forceBody=[2400*forceScale*independentHalfSine(time_s,1.5); ...
    0;-mass_kg*gravityNED_mps2(3)];
momentBody=[500;700;350]*momentScale* ...
    independentHalfSine(time_s,1.0);
positionDot=bodyToNed*velocityBody;
velocityDot=forceBody/mass_kg+bodyToNed'*gravityNED_mps2- ...
    cross(angularVelocity,velocityBody);
if omitTransportTerm
    velocityDot=forceBody/mass_kg+bodyToNed'*gravityNED_mps2;
end
angularVelocityDot=inertia_kgm2\(momentBody- ...
    cross(angularVelocity,inertia_kgm2*angularVelocity));
quaternionDot=independentQuaternionDerivative(quaternion,angularVelocity);
derivative=[positionDot;velocityDot;quaternionDot;angularVelocityDot];
end

function value = independentHalfSine(time_s,duration_s)
if time_s>=0 && time_s<duration_s
    value=sin(pi*time_s/duration_s);
else
    value=0;
end
end

function derivative = independentQuaternionDerivative(quaternion,omega)
q0=quaternion(1); q1=quaternion(2);
q2=quaternion(3); q3=quaternion(4);
p=omega(1); q=omega(2); r=omega(3);
derivative=0.5*[ ...
    -q1*p-q2*q-q3*r; ...
     q0*p+q2*r-q3*q; ...
     q0*q+q3*p-q1*r; ...
     q0*r+q1*q-q2*p];
end

function bodyToNed = independentQuaternionToDcm(quaternion)
quaternion=quaternion/norm(quaternion);
q0=quaternion(1); q1=quaternion(2);
q2=quaternion(3); q3=quaternion(4);
bodyToNed=[ ...
    1-2*(q2^2+q3^2), 2*(q1*q2-q0*q3), 2*(q1*q3+q0*q2); ...
    2*(q1*q2+q0*q3), 1-2*(q1^2+q3^2), 2*(q2*q3-q0*q1); ...
    2*(q1*q3-q0*q2), 2*(q2*q3+q0*q1), 1-2*(q1^2+q2^2)];
end

function expectFailure(action,expectedIdentifier,label)
didFail=false;
try
    action();
catch exception
    didFail=true;
    if ~isempty(expectedIdentifier)
        assert(strcmp(exception.identifier,expectedIdentifier), ...
            'Expected %s to raise %s, but received %s.', ...
            label,expectedIdentifier,exception.identifier);
    end
end
assert(didFail,'Expected model to reject %s.',label);
end
