function out=model(altitudeGain_rad_per_m,pitchNaturalFrequency_radps,altitudeFeedbackSign)
%MODEL Deterministic reduced-order cascaded pitch/altitude hold.
% Positive pitch and flight-path angle are nose-up/climbing. Geometric
% altitude is h=-Down. Pitch and path angles are perturbations about level
% trim. The equivalent pitch-control command is positive nose-up; it is not
% a physical surface-hinge convention or an actuator adapter.
arguments
    altitudeGain_rad_per_m (1,1) double {mustBeReal,mustBeFinite}=0.004
    pitchNaturalFrequency_radps (1,1) double {mustBeReal,mustBeFinite}=2.4
    altitudeFeedbackSign (1,1) double {mustBeReal,mustBeFinite}=1
end

if altitudeGain_rad_per_m<0 || altitudeGain_rad_per_m>0.008
    error('P13:model:AltitudeGainRange', ...
        'Altitude-to-pitch gain must be between 0 and 0.008 rad/m inclusive.');
end
if pitchNaturalFrequency_radps<1.2 || pitchNaturalFrequency_radps>3.6
    error('P13:model:PitchFrequencyRange', ...
        'Pitch natural frequency must be between 1.2 and 3.6 rad/s inclusive.');
end
if altitudeFeedbackSign~=1 && altitudeFeedbackSign~=-1
    error('P13:model:FeedbackSign', ...
        'Altitude feedback sign must be +1 for correct feedback or -1 for the broken case.');
end

sampleTime_s=0.02;
timeHorizon_s=30;
time_s=0:sampleTime_s:timeHorizon_s;
sampleCount=numel(time_s);
initialAltitude_m=1000;
altitudeStep_m=30;
commandStepTime_s=1;
trueAirspeed_mps=60;
flightPathTimeConstant_s=1.5;
pitchDampingRatio=0.8;
pitchCommandLimit_rad=deg2rad(10);
pitchControlCommandLimit_rad=deg2rad(20);

% A transparent stable pitch plant receives a generalized nose-up control
% effect. The scheduled proportional, rate, and command-feedforward gains
% make the unsaturated inner loop
%   theta_ddot + 2*zeta*omega_n*theta_dot + omega_n^2*theta
%       = omega_n^2*theta_command.
pitchStiffness_per_s2=0.8;
pitchRateDamping_per_s=1.2;
pitchControlEffectiveness_per_s2=12;
pitchProportionalGain=(pitchNaturalFrequency_radps^2- ...
    pitchStiffness_per_s2)/pitchControlEffectiveness_per_s2;
pitchCommandFeedforwardGain= ...
    pitchStiffness_per_s2/pitchControlEffectiveness_per_s2;
pitchRateGain_s=(2*pitchDampingRatio*pitchNaturalFrequency_radps- ...
    pitchRateDamping_per_s)/pitchControlEffectiveness_per_s2;

altitudeCommand_m=initialAltitude_m+ ...
    altitudeStep_m*double(time_s>=commandStepTime_s);
altitude_m=zeros(1,sampleCount);
pitchAngle_rad=zeros(1,sampleCount);
pitchRate_radps=zeros(1,sampleCount);
flightPathAngle_rad=zeros(1,sampleCount);
altitudeError_m=zeros(1,sampleCount);
climbRate_mps=zeros(1,sampleCount);
pitchCommandUnclamped_rad=zeros(1,sampleCount);
pitchCommand_rad=zeros(1,sampleCount);
pitchControlCommandUnclamped_rad=zeros(1,sampleCount);
pitchControlCommand_rad=zeros(1,sampleCount);
pitchAcceleration_radps2=zeros(1,sampleCount);
flightPathRate_radps=zeros(1,sampleCount);

altitude_m(1)=initialAltitude_m;
for k=1:sampleCount
    altitudeError_m(k)=altitudeCommand_m(k)-altitude_m(k);
    climbRate_mps(k)=trueAirspeed_mps*sin(flightPathAngle_rad(k));

    % Outer loop: altitude error becomes a bounded pitch command. Reversing
    % only altitudeFeedbackSign is the deliberately broken P12 Down-sign case.
    pitchCommandUnclamped_rad(k)=altitudeFeedbackSign* ...
        altitudeGain_rad_per_m*altitudeError_m(k);
    pitchCommand_rad(k)=min(max(pitchCommandUnclamped_rad(k), ...
        -pitchCommandLimit_rad),pitchCommandLimit_rad);

    % Inner loop: pitch error and pitch rate become an equivalent pitch-control
    % command. The explicit plant equation remains visible below.
    pitchControlCommandUnclamped_rad(k)=pitchProportionalGain* ...
        (pitchCommand_rad(k)-pitchAngle_rad(k))+ ...
        pitchCommandFeedforwardGain*pitchCommand_rad(k)- ...
        pitchRateGain_s*pitchRate_radps(k);
    pitchControlCommand_rad(k)=min(max( ...
        pitchControlCommandUnclamped_rad(k), ...
        -pitchControlCommandLimit_rad),pitchControlCommandLimit_rad);
    pitchAcceleration_radps2(k)= ...
        -pitchStiffness_per_s2*pitchAngle_rad(k)- ...
        pitchRateDamping_per_s*pitchRate_radps(k)+ ...
        pitchControlEffectiveness_per_s2*pitchControlCommand_rad(k);

    % gamma is flight-path angle, not pitch. This visible first-order lift/path
    % response prevents the common shortcut h_dot=V*sin(theta).
    flightPathRate_radps(k)= ...
        (pitchAngle_rad(k)-flightPathAngle_rad(k))/ ...
        flightPathTimeConstant_s;

    % Fixed-step forward-Euler recurrence. The retained grid bounds work and
    % lets run_checks independently reconstruct every state update.
    if k<sampleCount
        altitude_m(k+1)=altitude_m(k)+sampleTime_s*climbRate_mps(k);
        pitchAngle_rad(k+1)=pitchAngle_rad(k)+ ...
            sampleTime_s*pitchRate_radps(k);
        pitchRate_radps(k+1)=pitchRate_radps(k)+ ...
            sampleTime_s*pitchAcceleration_radps2(k);
        flightPathAngle_rad(k+1)=flightPathAngle_rad(k)+ ...
            sampleTime_s*flightPathRate_radps(k);
    end
end

downCommand_m=-altitudeCommand_m;
downPosition_m=-altitude_m;
downError_m=downCommand_m-downPosition_m;
pitchCommandSaturated= ...
    abs(pitchCommandUnclamped_rad)>pitchCommandLimit_rad;
pitchControlCommandSaturated= ...
    abs(pitchControlCommandUnclamped_rad)>pitchControlCommandLimit_rad;
activeMask=time_s>=commandStepTime_s;
activeCount=sum(activeMask);
pitchTrackingError_deg=rad2deg( ...
    pitchCommand_rad-pitchAngle_rad);
pitchTrackingRMS_deg=sqrt(mean(pitchTrackingError_deg(activeMask).^2));
finalAltitudeError_m=altitudeError_m(end);
peakAltitudeOvershoot_m=max(max( ...
    altitude_m(activeMask)-altitudeCommand_m(end)),0);
captureThreshold_m=initialAltitude_m+0.9*altitudeStep_m;
captureIndex=find(activeMask & altitude_m>=captureThreshold_m,1,'first');
if isempty(captureIndex)
    reachedNinetyPercent=false;
    timeToNinetyPercent_s=timeHorizon_s-commandStepTime_s;
else
    reachedNinetyPercent=true;
    timeToNinetyPercent_s=time_s(captureIndex)-commandStepTime_s;
end
settlingTolerance_m=0.02*altitudeStep_m;
settledByEnd=abs(finalAltitudeError_m)<=settlingTolerance_m;
outsideTolerance=find(activeMask & ...
    abs(altitudeError_m)>settlingTolerance_m,1,'last');
if settledByEnd && ~isempty(outsideTolerance) && outsideTolerance<sampleCount
    settlingTime_s=time_s(outsideTolerance+1)-commandStepTime_s;
elseif settledByEnd && isempty(outsideTolerance)
    settlingTime_s=0;
else
    settlingTime_s=timeHorizon_s-commandStepTime_s;
end

out=struct( ...
    'altitudeGain_rad_per_m',altitudeGain_rad_per_m, ...
    'pitchNaturalFrequency_radps',pitchNaturalFrequency_radps, ...
    'altitudeFeedbackSign',altitudeFeedbackSign, ...
    'sampleTime_s',sampleTime_s, ...
    'timeHorizon_s',timeHorizon_s, ...
    'time_s',time_s, ...
    'sampleCount',sampleCount, ...
    'intervalCount',sampleCount-1, ...
    'initialAltitude_m',initialAltitude_m, ...
    'altitudeStep_m',altitudeStep_m, ...
    'commandStepTime_s',commandStepTime_s, ...
    'trueAirspeed_mps',trueAirspeed_mps, ...
    'flightPathTimeConstant_s',flightPathTimeConstant_s, ...
    'pitchDampingRatio',pitchDampingRatio, ...
    'pitchCommandLimit_deg',rad2deg(pitchCommandLimit_rad), ...
    'pitchControlCommandLimit_deg',rad2deg(pitchControlCommandLimit_rad), ...
    'pitchStiffness_per_s2',pitchStiffness_per_s2, ...
    'pitchRateDamping_per_s',pitchRateDamping_per_s, ...
    'pitchControlEffectiveness_per_s2', ...
    pitchControlEffectiveness_per_s2, ...
    'pitchProportionalGain',pitchProportionalGain, ...
    'pitchCommandFeedforwardGain',pitchCommandFeedforwardGain, ...
    'pitchRateGain_s',pitchRateGain_s, ...
    'altitudeCommand_m',altitudeCommand_m, ...
    'downCommand_m',downCommand_m, ...
    'altitude_m',altitude_m, ...
    'downPosition_m',downPosition_m, ...
    'downError_m',downError_m, ...
    'altitudeError_m',altitudeError_m, ...
    'pitchAngle_deg',rad2deg(pitchAngle_rad), ...
    'pitchRate_degps',rad2deg(pitchRate_radps), ...
    'flightPathAngle_deg',rad2deg(flightPathAngle_rad), ...
    'climbRate_mps',climbRate_mps, ...
    'pitchCommandUnclamped_deg',rad2deg(pitchCommandUnclamped_rad), ...
    'pitchCommand_deg',rad2deg(pitchCommand_rad), ...
    'pitchControlCommandUnclamped_deg', ...
    rad2deg(pitchControlCommandUnclamped_rad), ...
    'pitchControlCommand_deg',rad2deg(pitchControlCommand_rad), ...
    'pitchAcceleration_degps2',rad2deg(pitchAcceleration_radps2), ...
    'flightPathRate_degps',rad2deg(flightPathRate_radps), ...
    'pitchCommandSaturated',pitchCommandSaturated, ...
    'pitchControlCommandSaturated',pitchControlCommandSaturated, ...
    'pitchCommandSaturationFraction', ...
    sum(pitchCommandSaturated)/sampleCount, ...
    'pitchControlCommandSaturationFraction', ...
    sum(pitchControlCommandSaturated)/sampleCount, ...
    'activeSampleCount',activeCount, ...
    'pitchTrackingError_deg',pitchTrackingError_deg, ...
    'pitchTrackingRMS_deg',pitchTrackingRMS_deg, ...
    'finalAltitudeError_m',finalAltitudeError_m, ...
    'peakAltitudeOvershoot_m',peakAltitudeOvershoot_m, ...
    'reachedNinetyPercent',reachedNinetyPercent, ...
    'timeToNinetyPercent_s',timeToNinetyPercent_s, ...
    'settlingTolerance_m',settlingTolerance_m, ...
    'settledByEnd',settledByEnd, ...
    'settlingTime_s',settlingTime_s, ...
    'peakPitchAngle_deg',max(abs(rad2deg(pitchAngle_rad))), ...
    'peakFlightPathAngle_deg',max(abs(rad2deg(flightPathAngle_rad))), ...
    'peakPitchControlCommand_deg', ...
    max(abs(rad2deg(pitchControlCommand_rad))), ...
    'controllerEquation',[ ...
        'theta_c=sat(s*K_h*(h_c-h)); u_theta=sat(K_p*(theta_c-theta)+' ...
        'K_ff*theta_c-K_q*q); positive u_theta is nose-up equivalent control'], ...
    'plantEquation',[ ...
        'theta_dot=q; q_dot=-a_theta*theta-a_q*q+b_u*u_theta; ' ...
        'gamma_dot=(theta-gamma)/tau_gamma; h_dot=V*sin(gamma)'], ...
    'frameConvention',[ ...
        'geometric altitude h=-NED Down; theta and gamma are perturbations about level trim; ' ...
        'positive values are nose-up/climbing; correct feedback uses h_command-h'], ...
    'brokenCaseDefinition',[ ...
        'altitudeFeedbackSign=-1 uses command-minus-measurement Down as though it were ' ...
        'altitude error, reversing only the outer-loop feedback sign'], ...
    'analysisScope',[ ...
        'deterministic reduced-order fixed-speed longitudinal teaching model; ' ...
        'flight-path response is a declared first-order approximation; pitch-control command ' ...
        'has a static envelope; no identified aerodynamics, actuator dynamics, sensor error, ' ...
        'gust, propulsion, energy coupling, certification, hardware, or flight fidelity']);
end
