function run_checks
%RUN_CHECKS P13 independent cascade equations, limits, and recovery.
clear model;

%% Determinism, fixed shapes, and finite resources
baseline=model();
repeatedBaseline=model(0.004,2.4,1);
assert(isequaln(baseline,repeatedBaseline), ...
    'Repeated baseline calls must be deterministic and stateless.');
assert(baseline.sampleCount==1501, ...
    'P13 must retain exactly 1501 samples.');
assert(baseline.intervalCount==1500, ...
    'P13 must retain exactly 1500 update intervals.');
assert(baseline.activeSampleCount==1451, ...
    'The command-active segment must retain exactly 1451 samples.');
assert(baseline.time_s(1)==0 && baseline.time_s(end)==30 && ...
    max(abs(diff(baseline.time_s)-0.02))<1e-14, ...
    'The fixed 0:0.02:30 s resource grid changed.');
historyFields={ ...
    'altitudeCommand_m','downCommand_m','altitude_m','downPosition_m', ...
    'altitudeError_m','downError_m', ...
    'pitchAngle_deg','pitchRate_degps','flightPathAngle_deg', ...
    'climbRate_mps','pitchCommandUnclamped_deg','pitchCommand_deg', ...
    'pitchControlCommandUnclamped_deg','pitchControlCommand_deg', ...
    'pitchAcceleration_degps2','flightPathRate_degps', ...
    'pitchCommandSaturated','pitchControlCommandSaturated'};
for k=1:numel(historyFields)
    values=baseline.(historyFields{k});
    assert(isequal(size(values),[1 baseline.sampleCount]), ...
        'Every retained baseline history must be a fixed row vector.');
    assert(all(isfinite(double(values(:)))), ...
        'Every retained baseline history must be finite.');
end

%% Signed baseline and exact pre-step trim
commandIndex=find(baseline.time_s>=baseline.commandStepTime_s,1,'first');
onePointFiveIndex=find(baseline.time_s>=1.5,1,'first');
fiveSecondIndex=find(baseline.time_s>=5,1,'first');
preStepIndices=find(baseline.time_s<baseline.commandStepTime_s);
assert(all(baseline.altitudeCommand_m(preStepIndices)==1000) && ...
    all(baseline.altitude_m(preStepIndices)==1000), ...
    'Altitude command and state must remain exactly at trim before the step.');
assert(all(baseline.altitudeError_m(preStepIndices)==0) && ...
    all(baseline.pitchCommand_deg(preStepIndices)==0) && ...
    all(baseline.pitchControlCommand_deg(preStepIndices)==0) && ...
    all(baseline.pitchAngle_deg(preStepIndices)==0) && ...
    all(baseline.pitchRate_degps(preStepIndices)==0) && ...
    all(baseline.flightPathAngle_deg(preStepIndices)==0) && ...
    all(baseline.climbRate_mps(preStepIndices)==0), ...
    'Every controller, state, and output must be zero at pre-step trim.');
assert(commandIndex==51 && baseline.time_s(commandIndex)==1 && ...
    baseline.altitudeCommand_m(commandIndex)==1030 && ...
    baseline.altitudeError_m(commandIndex)==30 && ...
    baseline.pitchAngle_deg(commandIndex)==0 && ...
    baseline.flightPathAngle_deg(commandIndex)==0, ...
    'The retained command must begin at sample 51 from an unchanged state.');
assert(abs(baseline.pitchCommand_deg(commandIndex)- ...
    6.875493541569878)<1e-12, ...
    'The positive altitude error must create the pinned positive pitch command.');
assert(abs(baseline.pitchControlCommand_deg(commandIndex)- ...
    3.300236899953542)<1e-12, ...
    'The inner loop must create the pinned positive nose-up control effect.');
assert(abs(baseline.pitchAngle_deg(onePointFiveIndex)- ...
    2.590689002929238)<1e-10 && ...
    abs(baseline.flightPathAngle_deg(onePointFiveIndex)- ...
    0.292884513830748)<1e-10, ...
    'The signed baseline must retain pitch-leading-flight-path behavior.');
assert(abs(baseline.altitudeError_m(fiveSecondIndex)- ...
    16.547538451269475)<1e-9, ...
    'The signed baseline altitude error at 5 s changed.');
assert(abs(baseline.finalAltitudeError_m- ...
    0.010296431988536)<1e-9 && ...
    abs(baseline.peakAltitudeOvershoot_m- ...
    1.575586453233427)<1e-9 && ...
    abs(baseline.timeToNinetyPercent_s-7.28)<1e-12 && ...
    abs(baseline.pitchTrackingRMS_deg- ...
    0.932364804504502)<1e-9 && baseline.settledByEnd, ...
    'The retained baseline capture metrics changed.');

%% Independently reconstruct controller gains and every recurrence
expectedPitchProportionalGain=( ...
    baseline.pitchNaturalFrequency_radps^2- ...
    baseline.pitchStiffness_per_s2)/ ...
    baseline.pitchControlEffectiveness_per_s2;
expectedPitchCommandFeedforwardGain= ...
    baseline.pitchStiffness_per_s2/ ...
    baseline.pitchControlEffectiveness_per_s2;
expectedPitchRateGain_s=(2*baseline.pitchDampingRatio* ...
    baseline.pitchNaturalFrequency_radps- ...
    baseline.pitchRateDamping_per_s)/ ...
    baseline.pitchControlEffectiveness_per_s2;
assert(abs(baseline.pitchProportionalGain- ...
    expectedPitchProportionalGain)<1e-15 && ...
    abs(baseline.pitchCommandFeedforwardGain- ...
    expectedPitchCommandFeedforwardGain)<1e-15 && ...
    abs(baseline.pitchRateGain_s-expectedPitchRateGain_s)<1e-15, ...
    'The visible pitch gain schedule no longer closes.');

expectedAltitudeError_m=baseline.altitudeCommand_m-baseline.altitude_m;
expectedPitchCommandUnclamped_deg=rad2deg( ...
    baseline.altitudeFeedbackSign*baseline.altitudeGain_rad_per_m* ...
    expectedAltitudeError_m);
expectedPitchCommand_deg=min(max(expectedPitchCommandUnclamped_deg, ...
    -baseline.pitchCommandLimit_deg),baseline.pitchCommandLimit_deg);
expectedPitchControlUnclamped_deg=baseline.pitchProportionalGain* ...
    (expectedPitchCommand_deg-baseline.pitchAngle_deg)+ ...
    baseline.pitchCommandFeedforwardGain*expectedPitchCommand_deg- ...
    baseline.pitchRateGain_s*baseline.pitchRate_degps;
expectedPitchControl_deg=min(max(expectedPitchControlUnclamped_deg, ...
    -baseline.pitchControlCommandLimit_deg), ...
    baseline.pitchControlCommandLimit_deg);
expectedPitchAcceleration_degps2= ...
    -baseline.pitchStiffness_per_s2*baseline.pitchAngle_deg- ...
    baseline.pitchRateDamping_per_s*baseline.pitchRate_degps+ ...
    baseline.pitchControlEffectiveness_per_s2*expectedPitchControl_deg;
expectedFlightPathRate_degps=(baseline.pitchAngle_deg- ...
    baseline.flightPathAngle_deg)/baseline.flightPathTimeConstant_s;
expectedClimbRate_mps=baseline.trueAirspeed_mps*sin( ...
    deg2rad(baseline.flightPathAngle_deg));
assert(max(abs(baseline.altitudeError_m-expectedAltitudeError_m))<1e-12 && ...
    max(abs(baseline.pitchCommandUnclamped_deg- ...
    expectedPitchCommandUnclamped_deg))<1e-12 && ...
    max(abs(baseline.pitchCommand_deg-expectedPitchCommand_deg))<1e-12, ...
    'The independently reconstructed outer controller must match every sample.');
assert(max(abs(baseline.pitchControlCommandUnclamped_deg- ...
    expectedPitchControlUnclamped_deg))<1e-12 && ...
    max(abs(baseline.pitchControlCommand_deg-expectedPitchControl_deg))<1e-12 && ...
    max(abs(baseline.pitchAcceleration_degps2- ...
    expectedPitchAcceleration_degps2))<1e-11, ...
    'The independently reconstructed inner controller and plant must match.');
assert(max(abs(baseline.flightPathRate_degps- ...
    expectedFlightPathRate_degps))<1e-12 && ...
    max(abs(baseline.climbRate_mps-expectedClimbRate_mps))<1e-12, ...
    'The independently reconstructed flight-path and climb equations must match.');

expectedAltitudeNext_m=baseline.altitude_m(1:end-1)+ ...
    baseline.sampleTime_s*baseline.climbRate_mps(1:end-1);
expectedPitchNext_deg=baseline.pitchAngle_deg(1:end-1)+ ...
    baseline.sampleTime_s*baseline.pitchRate_degps(1:end-1);
expectedPitchRateNext_degps=baseline.pitchRate_degps(1:end-1)+ ...
    baseline.sampleTime_s*baseline.pitchAcceleration_degps2(1:end-1);
expectedFlightPathNext_deg=baseline.flightPathAngle_deg(1:end-1)+ ...
    baseline.sampleTime_s*baseline.flightPathRate_degps(1:end-1);
assert(max(abs(baseline.altitude_m(2:end)-expectedAltitudeNext_m))<1e-12, ...
    'Every altitude update must obey h_next=h+dt*V*sin(gamma).');
assert(max(abs(baseline.pitchAngle_deg(2:end)- ...
    expectedPitchNext_deg))<1e-12, ...
    'Every pitch-angle update must obey theta_next=theta+dt*q.');
assert(max(abs(baseline.pitchRate_degps(2:end)- ...
    expectedPitchRateNext_degps))<1e-11, ...
    'Every pitch-rate update must obey the explicit plant recurrence.');
assert(max(abs(baseline.flightPathAngle_deg(2:end)- ...
    expectedFlightPathNext_deg))<1e-12, ...
    'Every flight-path update must obey the declared first-order recurrence.');

%% P12 altitude/Down convention and bounded commands
downCommand_m=-baseline.altitudeCommand_m;
expectedAltitudeErrorFromDown_m=baseline.downPosition_m-downCommand_m;
wrongCommandMinusMeasurementDown_m=downCommand_m-baseline.downPosition_m;
assert(max(abs(baseline.downPosition_m+baseline.altitude_m))==0 && ...
    max(abs(baseline.downCommand_m+baseline.altitudeCommand_m))==0 && ...
    max(abs(baseline.downError_m- ...
    wrongCommandMinusMeasurementDown_m))==0 && ...
    max(abs(baseline.altitudeError_m+baseline.downError_m))==0 && ...
    max(abs(expectedAltitudeErrorFromDown_m- ...
    baseline.altitudeError_m))==0 && ...
    max(abs(wrongCommandMinusMeasurementDown_m+ ...
    baseline.altitudeError_m))==0, ...
    'Altitude h=-Down must set the signed outer-loop error exactly.');
assert(max(abs(baseline.pitchCommand_deg))<= ...
    baseline.pitchCommandLimit_deg && ...
    max(abs(baseline.pitchControlCommand_deg))<= ...
    baseline.pitchControlCommandLimit_deg, ...
    'Pitch and pitch-control commands must remain inside envelopes.');
assert(isequal(baseline.pitchCommandSaturated, ...
    abs(baseline.pitchCommandUnclamped_deg)> ...
    baseline.pitchCommandLimit_deg) && ...
    isequal(baseline.pitchControlCommandSaturated, ...
    abs(baseline.pitchControlCommandUnclamped_deg)> ...
    baseline.pitchControlCommandLimit_deg), ...
    'Saturation flags must identify exactly the unclamped envelope violations.');
assert(~any(baseline.pitchControlCommandSaturated), ...
    'The defensive pitch-control guard must remain inactive at baseline.');

%% Limiting case: zero altitude gain leaves the step uncorrected
openAltitudeLoop=model(0,2.4,1);
assert(all(openAltitudeLoop.altitude_m==1000) && ...
    all(openAltitudeLoop.downPosition_m==-1000) && ...
    all(openAltitudeLoop.pitchCommand_deg==0) && ...
    all(openAltitudeLoop.pitchControlCommand_deg==0) && ...
    all(openAltitudeLoop.pitchAngle_deg==0) && ...
    all(openAltitudeLoop.pitchRate_degps==0) && ...
    all(openAltitudeLoop.flightPathAngle_deg==0) && ...
    all(openAltitudeLoop.climbRate_mps==0), ...
    'Zero outer gain must be the exact open-altitude-loop trim limit.');
assert(openAltitudeLoop.finalAltitudeError_m==30 && ...
    ~openAltitudeLoop.reachedNinetyPercent && ...
    ~openAltitudeLoop.settledByEnd, ...
    'The open altitude loop must retain the full command error.');

%% Two isolated parameter sweeps
altitudeGainSweep_rad_per_m=[0 0.002 0.004 0.006 0.008];
gainErrorAtFiveSeconds_m=zeros(size(altitudeGainSweep_rad_per_m));
gainOvershoot_m=zeros(size(altitudeGainSweep_rad_per_m));
gainPitchSaturationFraction=zeros(size(altitudeGainSweep_rad_per_m));
for k=1:numel(altitudeGainSweep_rad_per_m)
    sample=model(altitudeGainSweep_rad_per_m(k),2.4,1);
    gainErrorAtFiveSeconds_m(k)=sample.altitudeError_m(fiveSecondIndex);
    gainOvershoot_m(k)=sample.peakAltitudeOvershoot_m;
    gainPitchSaturationFraction(k)=sample.pitchCommandSaturationFraction;
    assert(sample.pitchNaturalFrequency_radps==2.4 && ...
        sample.altitudeFeedbackSign==1 && ...
        isequal(sample.time_s,baseline.time_s) && ...
        isequal(sample.altitudeCommand_m,baseline.altitudeCommand_m), ...
        'The altitude-gain sweep must isolate only its selected public input.');
end
assert(all(diff(gainErrorAtFiveSeconds_m)<0), ...
    'Higher altitude gain must reduce retained early altitude error.');
assert(gainOvershoot_m(1)==0 && ...
    gainOvershoot_m(end)>gainOvershoot_m(3) && ...
    gainPitchSaturationFraction(1)==0 && ...
    gainPitchSaturationFraction(end)>0, ...
    'Outer gain must expose the overshoot and pitch-authority tradeoff.');

pitchFrequencySweep_radps=[1.2 1.8 2.4 3.0 3.6];
frequencyPitchAtOnePointFive_deg=zeros(size(pitchFrequencySweep_radps));
frequencyTrackingRMS_deg=zeros(size(pitchFrequencySweep_radps));
frequencyPeakControl_deg=zeros(size(pitchFrequencySweep_radps));
for k=1:numel(pitchFrequencySweep_radps)
    sample=model(0.004,pitchFrequencySweep_radps(k),1);
    frequencyPitchAtOnePointFive_deg(k)= ...
        sample.pitchAngle_deg(onePointFiveIndex);
    frequencyTrackingRMS_deg(k)=sample.pitchTrackingRMS_deg;
    frequencyPeakControl_deg(k)=sample.peakPitchControlCommand_deg;
    assert(sample.altitudeGain_rad_per_m==0.004 && ...
        sample.altitudeFeedbackSign==1 && ...
        sample.pitchDampingRatio==baseline.pitchDampingRatio && ...
        sample.flightPathTimeConstant_s== ...
        baseline.flightPathTimeConstant_s && ...
        isequal(sample.altitudeCommand_m,baseline.altitudeCommand_m), ...
        'The pitch-frequency sweep must isolate only its selected public input.');
end
assert(all(diff(frequencyPitchAtOnePointFive_deg)>0) && ...
    all(diff(frequencyTrackingRMS_deg)<0) && ...
    all(diff(frequencyPeakControl_deg)>0), ...
    'Faster pitch response must trade lower tracking error for more control demand.');

%% Broken altitude/Down sign, fixed-horizon failure, rollback, and recovery
broken=model(0.004,2.4,-1);
stateFields={ ...
    'altitude_m','pitchAngle_deg','pitchRate_degps','flightPathAngle_deg'};
for k=1:numel(stateFields)
    brokenState=broken.(stateFields{k});
    baselineState=baseline.(stateFields{k});
    assert(isequal(brokenState(1:commandIndex), ...
        baselineState(1:commandIndex)), ...
        'Correct and broken states must match through command onset.');
end
assert(broken.altitudeGain_rad_per_m==baseline.altitudeGain_rad_per_m && ...
    broken.pitchNaturalFrequency_radps== ...
    baseline.pitchNaturalFrequency_radps && ...
    broken.altitudeFeedbackSign==-1 && ...
    isequal(broken.time_s,baseline.time_s) && ...
    isequal(broken.altitudeCommand_m,baseline.altitudeCommand_m), ...
    'The broken case must reverse only the public outer feedback sign.');
assert(broken.pitchCommand_deg(commandIndex)== ...
    -baseline.pitchCommand_deg(commandIndex) && ...
    broken.pitchControlCommand_deg(commandIndex)== ...
    -baseline.pitchControlCommand_deg(commandIndex), ...
    'The first broken correction must have the exact opposite sign.');
assert(broken.altitude_m(commandIndex+4)<baseline.altitude_m(commandIndex+4) && ...
    broken.altitude_m(end)<750 && ...
    broken.finalAltitudeError_m>300 && ...
    broken.pitchCommandSaturationFraction>0.8, ...
    'Broken positive feedback must descend, grow error, and reach its envelope.');
assert(max(abs(broken.pitchCommand_deg))<= ...
    broken.pitchCommandLimit_deg && ...
    max(abs(broken.pitchControlCommand_deg))<= ...
    broken.pitchControlCommandLimit_deg && ...
    all(isfinite(broken.altitude_m)), ...
    ['The deliberately broken fixed-horizon trace must remain finite while ' ...
    'static envelopes bound its commands.']);

% Saturation limits the command but does not arrest the positive-feedback
% failure. Retain a nonzero tail behavior so a large finite endpoint cannot
% be mistaken for recovery or a bounded altitude error.
brokenTailIndices=find(broken.time_s>=broken.timeHorizon_s-1);
brokenTailIntervals=brokenTailIndices(1:end-1);
assert(all(diff(broken.altitudeError_m(commandIndex:end))>=0) && ...
    all(broken.pitchCommandSaturated(brokenTailIndices)) && ...
    all(diff(broken.altitudeError_m(brokenTailIndices))>0) && ...
    broken.altitudeError_m(end)- ...
    broken.altitudeError_m(brokenTailIndices(1))>10 && ...
    max(abs(diff(broken.altitudeError_m(brokenTailIndices))+ ...
    broken.sampleTime_s*broken.climbRate_mps(brokenTailIntervals)))<1e-10 && ...
    broken.climbRate_mps(end)<-10, ...
    ['Pitch-command saturation must not masquerade as stabilization: ' ...
    'the broken altitude error must keep growing through the retained tail.']);
rolledBackBaseline=model(0.004,2.4,1);
assert(isequaln(rolledBackBaseline,baseline), ...
    'Rollback from the broken sign must reproduce the correct baseline exactly.');

%% Malformed and rejected inputs do not poison deterministic recovery
assertRejects(@()model(-eps,2.4,1),'P13:model:AltitudeGainRange');
assertRejects(@()model(0.008+eps,2.4,1), ...
    'P13:model:AltitudeGainRange');
assertRejects(@()model(0.004,1.2-eps,1), ...
    'P13:model:PitchFrequencyRange');
assertRejects(@()model(0.004,3.6+eps,1), ...
    'P13:model:PitchFrequencyRange');
assertRejects(@()model(0.004,2.4,0),'P13:model:FeedbackSign');
assertRejects(@()model(0.004,2.4,2),'P13:model:FeedbackSign');
malformedCalls={ ...
    @()model([0.003 0.004],2.4,1), ...
    @()model(0.004,[2.0 2.4],1), ...
    @()model(0.004,2.4,[1 -1]), ...
    @()model(0.004+1i,2.4,1), ...
    @()model(0.004,2.4+1i,1), ...
    @()model(NaN,2.4,1), ...
    @()model(0.004,Inf,1), ...
    @()model(0.004,2.4,NaN)};
for k=1:numel(malformedCalls)
    assertRejects(malformedCalls{k},'');
end
recoveredBaseline=model();
assert(isequaln(recoveredBaseline,baseline), ...
    'A valid call after rejected inputs must recover the exact baseline.');

%% Accepted corners, representative grid, and resource bounds
acceptedCornerCount=0;
for altitudeGain_rad_per_m=[0 0.008]
    for pitchNaturalFrequency_radps=[1.2 3.6]
        for altitudeFeedbackSign=[-1 1]
            sample=model(altitudeGain_rad_per_m, ...
                pitchNaturalFrequency_radps,altitudeFeedbackSign);
            acceptedCornerCount=acceptedCornerCount+1;
            assert(sample.sampleCount==1501 && sample.intervalCount==1500, ...
                'Accepted corners may not change allocated history size.');
            assert(all(isfinite(sample.altitude_m)) && ...
                all(isfinite(sample.pitchAngle_deg)) && ...
                all(isfinite(sample.pitchRate_degps)) && ...
                all(isfinite(sample.flightPathAngle_deg)) && ...
                all(isfinite(sample.pitchControlCommand_deg)), ...
                'Accepted corners must retain finite states and commands.');
            assert(max(abs(sample.pitchCommand_deg))<=10 && ...
                max(abs(sample.pitchControlCommand_deg))<=20, ...
                'Accepted corners must preserve command envelopes.');
            assert(~any(sample.pitchControlCommandSaturated), ...
                ['The defensive pitch-control guard must remain inactive ' ...
                'throughout the accepted input domain.']);
        end
    end
end
assert(acceptedCornerCount==8, ...
    'The accepted-corner check must remain capped at eight cases.');

representativeCaseCount=0;
for altitudeGain_rad_per_m=[0 0.004 0.008]
    for pitchNaturalFrequency_radps=[1.2 2.4 3.6]
        for altitudeFeedbackSign=[-1 1]
            sample=model(altitudeGain_rad_per_m, ...
                pitchNaturalFrequency_radps,altitudeFeedbackSign);
            representativeCaseCount=representativeCaseCount+1;
            assert(sample.sampleCount==baseline.sampleCount && ...
                sample.intervalCount==baseline.intervalCount && ...
                isequal(sample.time_s,baseline.time_s), ...
                'Representative cases must use the fixed synchronous grid.');
        end
    end
end
assert(representativeCaseCount==18, ...
    'The representative finite-resource grid must remain capped at 18 cases.');

%% Compatibility, timeout, and cancellation applicability
% P13 is a synchronous stateless base-MATLAB teaching calculation. It owns
% no file, network, device, process, timer, future, parallel worker, or
% background callback resource. There is therefore no asynchronous timeout
% or cancellation transition to exercise; fixed sample/interval counts and
% the capped case grid are the applicable resource boundary. No learner data,
% service schema, migration, or backup/restore path changes in this module.
% P12 is a sign-convention prerequisite, not a runtime compatibility adapter.

fprintf(['P13 checks passed: deterministic cascade, every recurrence, ' ...
    'isolated parameter sweeps, open-loop limit, broken feedback sign, ' ...
    'malformed-input recovery, rollback, compatibility, and resources.\n']);
end

function assertRejects(testCall,expectedIdentifier)
caught=false;
try
    unusedOutput=testCall(); %#ok<NASGU>
catch exception
    caught=true;
    if ~isempty(expectedIdentifier)
        assert(strcmp(exception.identifier,expectedIdentifier), ...
            'Rejected input raised an unexpected error identifier.');
    else
        assert(~isempty(exception.identifier), ...
            'Malformed input rejection must provide an error identifier.');
    end
end
assert(caught,'The malformed or out-of-range input must be rejected.');
end
