function out = model(initialSideslip_deg,rollDampingDerivative_Cl_p, ...
    weathercockDerivative_Cn_beta_perRad)
%MODEL Map lateral stability derivatives into coupled small-disturbance motion.
% The state is [beta; p; r; phi]. Positive beta is air-relative velocity
% toward body right, positive p and phi are right-wing-down, and positive r
% is nose-right. Angles and rates are radians internally. The coefficient
% set is notional teaching data, not an identified aircraft model.
arguments
    initialSideslip_deg (1,1) double {mustBeReal,mustBeFinite} = 3
    rollDampingDerivative_Cl_p (1,1) double {mustBeReal,mustBeFinite} = -0.50
    weathercockDerivative_Cn_beta_perRad (1,1) double ...
        {mustBeReal,mustBeFinite} = 0.18
end

if abs(initialSideslip_deg)>4
    error('P08:model:InitialSideslipRange', ...
        'Initial sideslip must be between -4 and 4 deg, inclusive.');
end
if rollDampingDerivative_Cl_p<-0.8 || ...
        rollDampingDerivative_Cl_p>-0.3
    error('P08:model:RollDampingDerivativeRange', ...
        'C_l_p must be between -0.8 and -0.3, inclusive.');
end
if weathercockDerivative_Cn_beta_perRad<0 || ...
        weathercockDerivative_Cn_beta_perRad>0.24
    error('P08:model:WeathercockDerivativeRange', ...
        'C_n_beta must be between 0 and 0.24 per rad, inclusive.');
end

referenceTrueAirspeed_mps=60;
referenceDynamicPressure_Pa=1325.00798531847;
wingArea_m2=16.2;
wingSpan_m=10.9;
mass_kg=1200;
rollInertia_kgm2=2500;
yawInertia_kgm2=4000;
gravity_mps2=9.80665;

sideForceDerivative_CY_beta_perRad=-0.65;
sideForceRollRateDerivative_CY_p=-0.03;
sideForceYawRateDerivative_CY_r=0.25;
dihedralDerivative_Cl_beta_perRad=-0.12;
rollMomentYawRateDerivative_Cl_r=0.10;
yawMomentRollRateDerivative_Cn_p=-0.06;
yawDampingDerivative_Cn_r=-0.25;

sideslipLinearLimit_deg=5;
bankLinearLimit_deg=15;
bodyRateLearningLimit_deg_s=15;
rateNormalizationTime_s=wingSpan_m/(2*referenceTrueAirspeed_mps);
time_s=0:0.02:25;

% Dimensional derivative ledger. C_l_p, C_l_r, C_n_p, and C_n_r are
% derivatives with respect to p_hat or r_hat, not dimensional body rates.
sideForceScale_N=referenceDynamicPressure_Pa*wingArea_m2;
momentScale_Nm=sideForceScale_N*wingSpan_m;
sideForceBetaDerivative_N_per_rad=sideForceScale_N* ...
    sideForceDerivative_CY_beta_perRad;
sideForceRollRateDerivative_N_per_rad_s=sideForceScale_N* ...
    sideForceRollRateDerivative_CY_p*rateNormalizationTime_s;
sideForceYawRateDerivative_N_per_rad_s=sideForceScale_N* ...
    sideForceYawRateDerivative_CY_r*rateNormalizationTime_s;
rollMomentBetaDerivative_Nm_per_rad=momentScale_Nm* ...
    dihedralDerivative_Cl_beta_perRad;
rollMomentRollRateDerivative_Nm_per_rad_s=momentScale_Nm* ...
    rollDampingDerivative_Cl_p*rateNormalizationTime_s;
rollMomentYawRateDerivative_Nm_per_rad_s=momentScale_Nm* ...
    rollMomentYawRateDerivative_Cl_r*rateNormalizationTime_s;
yawMomentBetaDerivative_Nm_per_rad=momentScale_Nm* ...
    weathercockDerivative_Cn_beta_perRad;
yawMomentRollRateDerivative_Nm_per_rad_s=momentScale_Nm* ...
    yawMomentRollRateDerivative_Cn_p*rateNormalizationTime_s;
yawMomentYawRateDerivative_Nm_per_rad_s=momentScale_Nm* ...
    yawDampingDerivative_Cn_r*rateNormalizationTime_s;

% State rows are beta_dot, p_dot, r_dot, and phi_dot. The -r and g*phi/V
% entries are kinematic/gravity coupling rather than aerodynamic derivatives.
stateMatrix=zeros(4,4);
stateMatrix(1,:)=[ ...
    sideForceBetaDerivative_N_per_rad/(mass_kg*referenceTrueAirspeed_mps), ...
    sideForceRollRateDerivative_N_per_rad_s/(mass_kg*referenceTrueAirspeed_mps), ...
    sideForceYawRateDerivative_N_per_rad_s/(mass_kg*referenceTrueAirspeed_mps)-1, ...
    gravity_mps2/referenceTrueAirspeed_mps];
stateMatrix(2,:)=[ ...
    rollMomentBetaDerivative_Nm_per_rad/rollInertia_kgm2, ...
    rollMomentRollRateDerivative_Nm_per_rad_s/rollInertia_kgm2, ...
    rollMomentYawRateDerivative_Nm_per_rad_s/rollInertia_kgm2,0];
stateMatrix(3,:)=[ ...
    yawMomentBetaDerivative_Nm_per_rad/yawInertia_kgm2, ...
    yawMomentRollRateDerivative_Nm_per_rad_s/yawInertia_kgm2, ...
    yawMomentYawRateDerivative_Nm_per_rad_s/yawInertia_kgm2,0];
stateMatrix(4,:)=[0 1 0 0];

initialState=[initialSideslip_deg*pi/180;0;0;0];
state=integrateFixedRk4(stateMatrix,initialState,time_s);
sideslip_rad=state(1,:);
rollRate_rad_s=state(2,:);
yawRate_rad_s=state(3,:);
bankAngle_rad=state(4,:);
nondimensionalRollRate=rollRate_rad_s*rateNormalizationTime_s;
nondimensionalYawRate=yawRate_rad_s*rateNormalizationTime_s;

sideForceCoefficientFromBeta= ...
    sideForceDerivative_CY_beta_perRad*sideslip_rad;
sideForceCoefficientFromRollRate= ...
    sideForceRollRateDerivative_CY_p*nondimensionalRollRate;
sideForceCoefficientFromYawRate= ...
    sideForceYawRateDerivative_CY_r*nondimensionalYawRate;
sideForceCoefficient=sideForceCoefficientFromBeta+ ...
    sideForceCoefficientFromRollRate+sideForceCoefficientFromYawRate;

rollMomentCoefficientFromBeta= ...
    dihedralDerivative_Cl_beta_perRad*sideslip_rad;
rollMomentCoefficientFromRollRate= ...
    rollDampingDerivative_Cl_p*nondimensionalRollRate;
rollMomentCoefficientFromYawRate= ...
    rollMomentYawRateDerivative_Cl_r*nondimensionalYawRate;
rollMomentCoefficient=rollMomentCoefficientFromBeta+ ...
    rollMomentCoefficientFromRollRate+rollMomentCoefficientFromYawRate;

yawMomentCoefficientFromBeta= ...
    weathercockDerivative_Cn_beta_perRad*sideslip_rad;
yawMomentCoefficientFromRollRate= ...
    yawMomentRollRateDerivative_Cn_p*nondimensionalRollRate;
yawMomentCoefficientFromYawRate= ...
    yawDampingDerivative_Cn_r*nondimensionalYawRate;
yawMomentCoefficient=yawMomentCoefficientFromBeta+ ...
    yawMomentCoefficientFromRollRate+yawMomentCoefficientFromYawRate;

sideForce_N=sideForceScale_N*sideForceCoefficient;
rollMoment_Nm=momentScale_Nm*rollMomentCoefficient;
yawMoment_Nm=momentScale_Nm*yawMomentCoefficient;
ledgerStateDerivative=[ ...
    sideForce_N/(mass_kg*referenceTrueAirspeed_mps)-yawRate_rad_s+ ...
        gravity_mps2/referenceTrueAirspeed_mps*bankAngle_rad; ...
    rollMoment_Nm/rollInertia_kgm2; ...
    yawMoment_Nm/yawInertia_kgm2; ...
    rollRate_rad_s];
matrixStateDerivative=stateMatrix*state;
stateEquationResidual=matrixStateDerivative-ledgerStateDerivative;

sideslip_deg=sideslip_rad*180/pi;
rollRate_deg_s=rollRate_rad_s*180/pi;
yawRate_deg_s=yawRate_rad_s*180/pi;
bankAngle_deg=bankAngle_rad*180/pi;
sideslipRate_deg_s=ledgerStateDerivative(1,:)*180/pi;
rollAcceleration_deg_s2=ledgerStateDerivative(2,:)*180/pi;
yawAcceleration_deg_s2=ledgerStateDerivative(3,:)*180/pi;
bankRate_deg_s=ledgerStateDerivative(4,:)*180/pi;
[peakAbsRollRate_deg_s,peakRollRateIndex]=max(abs(rollRate_deg_s));
[peakAbsYawRate_deg_s,peakYawRateIndex]=max(abs(yawRate_deg_s));
[peakAbsBank_deg,peakBankIndex]=max(abs(bankAngle_deg));
peakAbsSideslip_deg=max(abs(sideslip_deg));
if initialSideslip_deg==0
    firstSideslipZeroCrossing_s=0;
else
    crossingIndex=find(sideslip_deg(2:end).*initialSideslip_deg<=0,1,'first');
    if isempty(crossingIndex)
        firstSideslipZeroCrossing_s=Inf;
    else
        firstSideslipZeroCrossing_s=time_s(crossingIndex+1);
    end
end

% Deliberately broken comparison: omit b/(2V) and treat C_l_p as though it
% were a derivative with respect to dimensional p. The resulting A(2,2)
% is unit-inconsistent but can still create a smooth, plausible trace.
brokenRollDampingNumeric_Nm=momentScale_Nm*rollDampingDerivative_Cl_p;
brokenStateMatrix=stateMatrix;
brokenStateMatrix(2,2)=brokenRollDampingNumeric_Nm/rollInertia_kgm2;
brokenState=integrateFixedRk4(brokenStateMatrix,initialState,time_s);
brokenRollRate_deg_s=brokenState(2,:)*180/pi;
brokenBankAngle_deg=brokenState(4,:)*180/pi;
brokenPeakAbsRollRate_deg_s=max(abs(brokenRollRate_deg_s));
brokenPeakAbsBank_deg=max(abs(brokenBankAngle_deg));
% This quotient compares SI numeric values only: broken A(2,2) carries
% 1/s^2 rather than 1/s, so the quotient has units 1/s and is not a
% dimensionless physical multiplier.
brokenA22NumericRatio_per_s=abs( ...
    brokenStateMatrix(2,2)/stateMatrix(2,2));

isWithinSideslipLinearRange= ...
    peakAbsSideslip_deg<=sideslipLinearLimit_deg;
isWithinBankLinearRange=peakAbsBank_deg<=bankLinearLimit_deg;
isWithinBodyRateLearningRange=max([peakAbsRollRate_deg_s ...
    peakAbsYawRate_deg_s])<=bodyRateLearningLimit_deg_s;

out=struct( ...
    'initialSideslip_deg',initialSideslip_deg, ...
    'rollDampingDerivative_Cl_p',rollDampingDerivative_Cl_p, ...
    'weathercockDerivative_Cn_beta_perRad', ...
    weathercockDerivative_Cn_beta_perRad, ...
    'time_s',time_s,'sampleCount',numel(time_s), ...
    'integrationStep_s',time_s(2)-time_s(1), ...
    'integrationMethod','fixed-step explicit RK4', ...
    'sideslip_deg',sideslip_deg, ...
    'rollRate_deg_s',rollRate_deg_s, ...
    'yawRate_deg_s',yawRate_deg_s, ...
    'bankAngle_deg',bankAngle_deg, ...
    'sideslipRate_deg_s',sideslipRate_deg_s, ...
    'rollAcceleration_deg_s2',rollAcceleration_deg_s2, ...
    'yawAcceleration_deg_s2',yawAcceleration_deg_s2, ...
    'bankRate_deg_s',bankRate_deg_s, ...
    'nondimensionalRollRate',nondimensionalRollRate, ...
    'nondimensionalYawRate',nondimensionalYawRate, ...
    'sideForceCoefficientFromBeta',sideForceCoefficientFromBeta, ...
    'sideForceCoefficientFromRollRate', ...
    sideForceCoefficientFromRollRate, ...
    'sideForceCoefficientFromYawRate',sideForceCoefficientFromYawRate, ...
    'sideForceCoefficient',sideForceCoefficient, ...
    'rollMomentCoefficientFromBeta',rollMomentCoefficientFromBeta, ...
    'rollMomentCoefficientFromRollRate', ...
    rollMomentCoefficientFromRollRate, ...
    'rollMomentCoefficientFromYawRate', ...
    rollMomentCoefficientFromYawRate, ...
    'rollMomentCoefficient',rollMomentCoefficient, ...
    'yawMomentCoefficientFromBeta',yawMomentCoefficientFromBeta, ...
    'yawMomentCoefficientFromRollRate', ...
    yawMomentCoefficientFromRollRate, ...
    'yawMomentCoefficientFromYawRate',yawMomentCoefficientFromYawRate, ...
    'yawMomentCoefficient',yawMomentCoefficient, ...
    'sideForce_N',sideForce_N, ...
    'rollMoment_Nm',rollMoment_Nm, ...
    'yawMoment_Nm',yawMoment_Nm, ...
    'stateEquationResidual',stateEquationResidual, ...
    'stateMatrix',stateMatrix, ...
    'initialStateDerivative',ledgerStateDerivative(:,1), ...
    'peakAbsSideslip_deg',peakAbsSideslip_deg, ...
    'peakAbsRollRate_deg_s',peakAbsRollRate_deg_s, ...
    'peakAbsYawRate_deg_s',peakAbsYawRate_deg_s, ...
    'peakAbsBank_deg',peakAbsBank_deg, ...
    'peakRollRateTime_s',time_s(peakRollRateIndex), ...
    'peakYawRateTime_s',time_s(peakYawRateIndex), ...
    'peakBankTime_s',time_s(peakBankIndex), ...
    'firstSideslipZeroCrossing_s',firstSideslipZeroCrossing_s, ...
    'referenceTrueAirspeed_mps',referenceTrueAirspeed_mps, ...
    'referenceDynamicPressure_Pa',referenceDynamicPressure_Pa, ...
    'wingArea_m2',wingArea_m2,'wingSpan_m',wingSpan_m, ...
    'mass_kg',mass_kg,'rollInertia_kgm2',rollInertia_kgm2, ...
    'yawInertia_kgm2',yawInertia_kgm2,'gravity_mps2',gravity_mps2, ...
    'rateNormalizationTime_s',rateNormalizationTime_s, ...
    'sideForceDerivative_CY_beta_perRad', ...
    sideForceDerivative_CY_beta_perRad, ...
    'sideForceRollRateDerivative_CY_p', ...
    sideForceRollRateDerivative_CY_p, ...
    'sideForceYawRateDerivative_CY_r', ...
    sideForceYawRateDerivative_CY_r, ...
    'dihedralDerivative_Cl_beta_perRad', ...
    dihedralDerivative_Cl_beta_perRad, ...
    'rollMomentYawRateDerivative_Cl_r', ...
    rollMomentYawRateDerivative_Cl_r, ...
    'yawMomentRollRateDerivative_Cn_p', ...
    yawMomentRollRateDerivative_Cn_p, ...
    'yawDampingDerivative_Cn_r',yawDampingDerivative_Cn_r, ...
    'sideForceBetaDerivative_N_per_rad', ...
    sideForceBetaDerivative_N_per_rad, ...
    'sideForceRollRateDerivative_N_per_rad_s', ...
    sideForceRollRateDerivative_N_per_rad_s, ...
    'sideForceYawRateDerivative_N_per_rad_s', ...
    sideForceYawRateDerivative_N_per_rad_s, ...
    'rollMomentBetaDerivative_Nm_per_rad', ...
    rollMomentBetaDerivative_Nm_per_rad, ...
    'rollMomentRollRateDerivative_Nm_per_rad_s', ...
    rollMomentRollRateDerivative_Nm_per_rad_s, ...
    'rollMomentYawRateDerivative_Nm_per_rad_s', ...
    rollMomentYawRateDerivative_Nm_per_rad_s, ...
    'yawMomentBetaDerivative_Nm_per_rad', ...
    yawMomentBetaDerivative_Nm_per_rad, ...
    'yawMomentRollRateDerivative_Nm_per_rad_s', ...
    yawMomentRollRateDerivative_Nm_per_rad_s, ...
    'yawMomentYawRateDerivative_Nm_per_rad_s', ...
    yawMomentYawRateDerivative_Nm_per_rad_s, ...
    'brokenStateMatrix',brokenStateMatrix, ...
    'brokenRollDampingNumeric_Nm',brokenRollDampingNumeric_Nm, ...
    'brokenRollRate_deg_s',brokenRollRate_deg_s, ...
    'brokenBankAngle_deg',brokenBankAngle_deg, ...
    'brokenPeakAbsRollRate_deg_s',brokenPeakAbsRollRate_deg_s, ...
    'brokenPeakAbsBank_deg',brokenPeakAbsBank_deg, ...
    'brokenA22NumericRatio_per_s',brokenA22NumericRatio_per_s, ...
    'sideslipLinearLimit_deg',sideslipLinearLimit_deg, ...
    'bankLinearLimit_deg',bankLinearLimit_deg, ...
    'bodyRateLearningLimit_deg_s',bodyRateLearningLimit_deg_s, ...
    'isWithinSideslipLinearRange',isWithinSideslipLinearRange, ...
    'isWithinBankLinearRange',isWithinBankLinearRange, ...
    'isWithinBodyRateLearningRange',isWithinBodyRateLearningRange, ...
    'stateOrder','[beta, p, r, phi]', ...
    'signConvention',[ ...
        'positive beta: velocity toward body right; positive p/phi: ' ...
        'right-wing-down; positive r: nose-right'], ...
    'rateDerivativeConvention',[ ...
        'C_l_p, C_l_r, C_n_p, and C_n_r multiply p_hat or r_hat, ' ...
        'where rate_hat=rate*b/(2*V0)'], ...
    'analysisScope',[ ...
        'constant-trim linear lateral perturbations with diagonal roll/yaw ' ...
        'inertia; not identified data, nonlinear 6-DOF, or handling qualities']);
end

function state = integrateFixedRk4(stateMatrix,initialState,time_s)
%INTEGRATEFIXEDRK4 Visible bounded propagation for x_dot=A*x.
state=zeros(4,numel(time_s));
state(:,1)=initialState;
for k=1:numel(time_s)-1
    step_s=time_s(k+1)-time_s(k);
    k1=stateMatrix*state(:,k);
    k2=stateMatrix*(state(:,k)+0.5*step_s*k1);
    k3=stateMatrix*(state(:,k)+0.5*step_s*k2);
    k4=stateMatrix*(state(:,k)+step_s*k3);
    state(:,k+1)=state(:,k)+step_s/6*(k1+2*k2+2*k3+k4);
end
end
