function run_checks
%RUN_CHECKS Independent checks for the P08 stability-derivative model.
clear model;
tol=1e-10;

%% Determinism, fixed shape, finite resources, and contracting late motion
first=model(3,-0.50,0.18);
second=model(3,-0.50,0.18);
assert(isequaln(first,second), ...
    'Identical derivative inputs must produce identical coupled motion.');
assert(first.sampleCount==1251 && first.integrationStep_s==0.02 && ...
    isequal(size(first.time_s),[1 1251]) && first.time_s(1)==0 && ...
    first.time_s(end)==25, ...
    'The fixed RK4 resource boundary must remain 1,251 samples over 25 s.');

vectorFields={'sideslip_deg','rollRate_deg_s','yawRate_deg_s', ...
    'bankAngle_deg','sideslipRate_deg_s','rollAcceleration_deg_s2', ...
    'yawAcceleration_deg_s2','bankRate_deg_s', ...
    'nondimensionalRollRate','nondimensionalYawRate', ...
    'sideForceCoefficientFromBeta','sideForceCoefficientFromRollRate', ...
    'sideForceCoefficientFromYawRate','sideForceCoefficient', ...
    'rollMomentCoefficientFromBeta','rollMomentCoefficientFromRollRate', ...
    'rollMomentCoefficientFromYawRate','rollMomentCoefficient', ...
    'yawMomentCoefficientFromBeta','yawMomentCoefficientFromRollRate', ...
    'yawMomentCoefficientFromYawRate','yawMomentCoefficient', ...
    'sideForce_N','rollMoment_Nm','yawMoment_Nm', ...
    'brokenRollRate_deg_s','brokenBankAngle_deg'};
for k=1:numel(vectorFields)
    value=first.(vectorFields{k});
    assert(isequal(size(value),[1 1251]) && isreal(value) && ...
        all(isfinite(value)), ...
        'Every P08 history must be a finite 1-by-1251 row vector.');
end
assert(isequal(size(first.stateEquationResidual),[4 1251]) && ...
    all(isfinite(first.stateEquationResidual(:))) && ...
    isequal(size(first.stateMatrix),[4 4]) && ...
    all(isfinite(first.stateMatrix(:))) && ...
    isequal(size(first.brokenStateMatrix),[4 4]) && ...
    all(isfinite(first.brokenStateMatrix(:))), ...
    'State matrices and residual histories must have fixed finite shapes.');

edgeSideslip_deg=[-4 4];
edgeRollDamping=[-0.8 -0.3];
edgeWeathercock=[0 0.24];
edgeCaseCount=0;
for betaIndex=1:numel(edgeSideslip_deg)
    for rollIndex=1:numel(edgeRollDamping)
        for yawIndex=1:numel(edgeWeathercock)
            edge=model(edgeSideslip_deg(betaIndex), ...
                edgeRollDamping(rollIndex),edgeWeathercock(yawIndex));
            edgeCaseCount=edgeCaseCount+1;
            assert(edge.sampleCount==1251 && ...
                edge.isWithinSideslipLinearRange && ...
                edge.isWithinBankLinearRange && ...
                edge.isWithinBodyRateLearningRange, ...
                'Every accepted input corner must stay inside learning limits.');
            for fieldIndex=1:numel(vectorFields)
                assert(all(isfinite(edge.(vectorFields{fieldIndex}))), ...
                    'Every accepted input corner must remain finite.');
            end
            edgeState=[edge.sideslip_deg;edge.rollRate_deg_s; ...
                edge.yawRate_deg_s;edge.bankAngle_deg];
            earlierLateWindow=edge.time_s>=15 & edge.time_s<20;
            laterLateWindow=edge.time_s>=20 & edge.time_s<=25;
            earlierLateEnvelope=max(abs(edgeState(:,earlierLateWindow)),[],2);
            laterLateEnvelope=max(abs(edgeState(:,laterLateWindow)),[],2);
            assert(all(earlierLateEnvelope>0) && ...
                all(laterLateEnvelope<0.99*earlierLateEnvelope), ...
                ['Every accepted derivative corner must contract each ' ...
                'state envelope from 15-20 s to 20-25 s.']);
        end
    end
end
assert(edgeCaseCount==8,'The accepted-corner check must remain bounded at 8 cases.');

representativeSideslip_deg=[-4 0 4];
representativeRollDamping=[-0.8 -0.5 -0.3];
representativeWeathercock=[0 0.18 0.24];
representativeCaseCount=0;
for betaIndex=1:numel(representativeSideslip_deg)
    for rollIndex=1:numel(representativeRollDamping)
        for yawIndex=1:numel(representativeWeathercock)
            sample=model(representativeSideslip_deg(betaIndex), ...
                representativeRollDamping(rollIndex), ...
                representativeWeathercock(yawIndex));
            representativeCaseCount=representativeCaseCount+1;
            assert(sample.sampleCount==1251 && ...
                sample.isWithinSideslipLinearRange && ...
                sample.isWithinBankLinearRange && ...
                sample.isWithinBodyRateLearningRange && ...
                all(isfinite(sample.stateEquationResidual(:))), ...
                'The representative derivative grid must remain bounded.');
        end
    end
end
assert(representativeCaseCount==27 && representativeCaseCount<=30, ...
    'The representative resource grid must stay fixed and capped.');

%% Independent nondimensional-to-dimensional derivative ledger
expectedV_mps=60;
expectedQbar_Pa=1325.00798531847;
expectedArea_m2=16.2;
expectedSpan_m=10.9;
expectedMass_kg=1200;
expectedIx_kgm2=2500;
expectedIz_kgm2=4000;
expectedGravity_mps2=9.80665;
expectedRateScale_s=expectedSpan_m/(2*expectedV_mps);
expectedForceScale_N=expectedQbar_Pa*expectedArea_m2;
expectedMomentScale_Nm=expectedForceScale_N*expectedSpan_m;

expectedYBeta_N_per_rad=expectedForceScale_N*(-0.65);
expectedYP_N_per_rad_s=expectedForceScale_N*(-0.03)*expectedRateScale_s;
expectedYR_N_per_rad_s=expectedForceScale_N*(0.25)*expectedRateScale_s;
expectedLBeta_Nm_per_rad=expectedMomentScale_Nm*(-0.12);
expectedLP_Nm_per_rad_s=expectedMomentScale_Nm*(-0.50)*expectedRateScale_s;
expectedLR_Nm_per_rad_s=expectedMomentScale_Nm*(0.10)*expectedRateScale_s;
expectedNBeta_Nm_per_rad=expectedMomentScale_Nm*(0.18);
expectedNP_Nm_per_rad_s=expectedMomentScale_Nm*(-0.06)*expectedRateScale_s;
expectedNR_Nm_per_rad_s=expectedMomentScale_Nm*(-0.25)*expectedRateScale_s;

assert(abs(first.rateNormalizationTime_s-expectedRateScale_s)<tol && ...
    abs(first.sideForceBetaDerivative_N_per_rad- ...
    expectedYBeta_N_per_rad)<tol && ...
    abs(first.sideForceRollRateDerivative_N_per_rad_s- ...
    expectedYP_N_per_rad_s)<tol && ...
    abs(first.sideForceYawRateDerivative_N_per_rad_s- ...
    expectedYR_N_per_rad_s)<tol, ...
    'Sideforce derivatives must include the correct b/(2*V0) rate scale.');
assert(abs(first.rollMomentBetaDerivative_Nm_per_rad- ...
    expectedLBeta_Nm_per_rad)<tol && ...
    abs(first.rollMomentRollRateDerivative_Nm_per_rad_s- ...
    expectedLP_Nm_per_rad_s)<tol && ...
    abs(first.rollMomentYawRateDerivative_Nm_per_rad_s- ...
    expectedLR_Nm_per_rad_s)<tol, ...
    'Roll-moment derivatives must dimensionalize independently.');
assert(abs(first.yawMomentBetaDerivative_Nm_per_rad- ...
    expectedNBeta_Nm_per_rad)<tol && ...
    abs(first.yawMomentRollRateDerivative_Nm_per_rad_s- ...
    expectedNP_Nm_per_rad_s)<tol && ...
    abs(first.yawMomentYawRateDerivative_Nm_per_rad_s- ...
    expectedNR_Nm_per_rad_s)<tol, ...
    'Yaw-moment derivatives must dimensionalize independently.');

expectedStateMatrix=[ ...
    expectedYBeta_N_per_rad/(expectedMass_kg*expectedV_mps), ...
    expectedYP_N_per_rad_s/(expectedMass_kg*expectedV_mps), ...
    expectedYR_N_per_rad_s/(expectedMass_kg*expectedV_mps)-1, ...
    expectedGravity_mps2/expectedV_mps; ...
    expectedLBeta_Nm_per_rad/expectedIx_kgm2, ...
    expectedLP_Nm_per_rad_s/expectedIx_kgm2, ...
    expectedLR_Nm_per_rad_s/expectedIx_kgm2,0; ...
    expectedNBeta_Nm_per_rad/expectedIz_kgm2, ...
    expectedNP_Nm_per_rad_s/expectedIz_kgm2, ...
    expectedNR_Nm_per_rad_s/expectedIz_kgm2,0; ...
    0,1,0,0];
assert(max(abs(first.stateMatrix(:)-expectedStateMatrix(:)))<tol, ...
    'The four coupled state-matrix rows must match the derivative ledger.');
assert(abs(first.stateMatrix(1,3)+1- ...
    expectedYR_N_per_rad_s/(expectedMass_kg*expectedV_mps))<tol && ...
    abs(first.stateMatrix(1,4)-expectedGravity_mps2/expectedV_mps)<tol && ...
    isequal(first.stateMatrix(4,:),[0 1 0 0]), ...
    'Kinematic -r, gravity coupling, and phi-dot=p must stay explicit.');

%% Baseline forces, tendencies, RK4 propagation, and recognizable motion
expectedInitialState=[3*pi/180;0;0;0];
expectedInitialDerivative=expectedStateMatrix*expectedInitialState;
expectedInitialSideForce_N=expectedYBeta_N_per_rad*expectedInitialState(1);
expectedInitialRollMoment_Nm=expectedLBeta_Nm_per_rad*expectedInitialState(1);
expectedInitialYawMoment_Nm=expectedNBeta_Nm_per_rad*expectedInitialState(1);
assert(abs(first.sideForce_N(1)-expectedInitialSideForce_N)<tol && ...
    abs(first.rollMoment_Nm(1)-expectedInitialRollMoment_Nm)<tol && ...
    abs(first.yawMoment_Nm(1)-expectedInitialYawMoment_Nm)<tol, ...
    'A positive beta release must create independently reconstructed loads.');
assert(max(abs(first.initialStateDerivative-expectedInitialDerivative))<tol && ...
    first.sideslipRate_deg_s(1)<0 && ...
    first.rollAcceleration_deg_s2(1)<0 && ...
    first.yawAcceleration_deg_s2(1)>0 && first.bankRate_deg_s(1)==0, ...
    'Stable derivative signs must create the expected initial tendencies.');
assert(abs(first.sideslipRate_deg_s(1)-(-0.581347253558479))<1e-12 && ...
    abs(first.rollAcceleration_deg_s2(1)-(-33.6916670468451))<1e-11 && ...
    abs(first.yawAcceleration_deg_s2(1)-31.5859378564173)<1e-11 && ...
    first.firstSideslipZeroCrossing_s==0.54 && ...
    abs(first.peakAbsRollRate_deg_s-3.901553273234694)<1e-12 && ...
    first.peakRollRateTime_s==0.26 && ...
    abs(first.peakAbsYawRate_deg_s-7.230284690111148)<1e-12 && ...
    first.peakYawRateTime_s==0.42 && ...
    abs(first.peakAbsBank_deg-1.643471405252225)<1e-12 && ...
    first.peakBankTime_s==0.66, ...
    'The baseline derivative-to-motion signature must remain recognizable.');

storedState=[first.sideslip_deg*pi/180; ...
    first.rollRate_deg_s*pi/180;first.yawRate_deg_s*pi/180; ...
    first.bankAngle_deg*pi/180];
expectedNextState=zeros(4,first.sampleCount);
expectedNextState(:,1)=expectedInitialState;
for k=1:first.sampleCount-1
    step_s=first.time_s(k+1)-first.time_s(k);
    k1=expectedStateMatrix*expectedNextState(:,k);
    k2=expectedStateMatrix*(expectedNextState(:,k)+0.5*step_s*k1);
    k3=expectedStateMatrix*(expectedNextState(:,k)+0.5*step_s*k2);
    k4=expectedStateMatrix*(expectedNextState(:,k)+step_s*k3);
    expectedNextState(:,k+1)=expectedNextState(:,k)+ ...
        step_s/6*(k1+2*k2+2*k3+k4);
end
assert(max(abs(storedState(:)-expectedNextState(:)))<1e-13, ...
    'Every stored state must satisfy the visible fixed-step RK4 recurrence.');
assert(max(abs(first.stateEquationResidual(:)))<1e-14, ...
    'The coefficient ledger and state-matrix derivatives must agree.');

%% Coefficient sums, normalized-rate identities, and dimensional closure
assert(max(abs(first.nondimensionalRollRate- ...
    first.rollRate_deg_s*pi/180*expectedRateScale_s))<tol && ...
    max(abs(first.nondimensionalYawRate- ...
    first.yawRate_deg_s*pi/180*expectedRateScale_s))<tol, ...
    'Body rates must be normalized by b/(2*V0) before rate derivatives.');
assert(max(abs(first.sideForceCoefficient-( ...
    first.sideForceCoefficientFromBeta+ ...
    first.sideForceCoefficientFromRollRate+ ...
    first.sideForceCoefficientFromYawRate)))<tol && ...
    max(abs(first.rollMomentCoefficient-( ...
    first.rollMomentCoefficientFromBeta+ ...
    first.rollMomentCoefficientFromRollRate+ ...
    first.rollMomentCoefficientFromYawRate)))<tol && ...
    max(abs(first.yawMomentCoefficient-( ...
    first.yawMomentCoefficientFromBeta+ ...
    first.yawMomentCoefficientFromRollRate+ ...
    first.yawMomentCoefficientFromYawRate)))<tol, ...
    'Every derivative contribution must sum to its total coefficient.');
assert(max(abs(first.sideForce_N- ...
    expectedForceScale_N*first.sideForceCoefficient))<tol && ...
    max(abs(first.rollMoment_Nm- ...
    expectedMomentScale_Nm*first.rollMomentCoefficient))<tol && ...
    max(abs(first.yawMoment_Nm- ...
    expectedMomentScale_Nm*first.yawMomentCoefficient))<tol, ...
    'Coefficient histories must close to dimensional force and moments.');

%% Limiting inputs, linear scaling, and sign symmetry
zeroRelease=model(0,-0.50,0.18);
for k=1:numel(vectorFields)
    assert(all(zeroRelease.(vectorFields{k})==0), ...
        'Zero release must produce exact zero histories, including the broken comparison.');
end
assert(all(zeroRelease.stateEquationResidual(:)==0) && ...
    zeroRelease.firstSideslipZeroCrossing_s==0 && ...
    zeroRelease.peakAbsRollRate_deg_s==0 && ...
    zeroRelease.peakAbsYawRate_deg_s==0 && ...
    zeroRelease.peakAbsBank_deg==0, ...
    'Zero initial sideslip is the exact no-motion limiting case.');

opposite=model(-3,-0.50,0.18);
half=model(1.5,-0.50,0.18);
signedFields={'sideslip_deg','rollRate_deg_s','yawRate_deg_s', ...
    'bankAngle_deg','sideForce_N','rollMoment_Nm','yawMoment_Nm', ...
    'brokenRollRate_deg_s','brokenBankAngle_deg'};
for k=1:numel(signedFields)
    fieldName=signedFields{k};
    assert(max(abs(opposite.(fieldName)+first.(fieldName)))<tol && ...
        max(abs(half.(fieldName)-0.5*first.(fieldName)))<tol, ...
        'The linear model must preserve sign reversal and half-scale response.');
end
assert(abs(opposite.peakAbsRollRate_deg_s-first.peakAbsRollRate_deg_s)<tol && ...
    abs(opposite.peakAbsYawRate_deg_s-first.peakAbsYawRate_deg_s)<tol && ...
    abs(opposite.peakAbsBank_deg-first.peakAbsBank_deg)<tol && ...
    abs(half.peakAbsRollRate_deg_s-0.5*first.peakAbsRollRate_deg_s)<tol, ...
    'Magnitude metrics must preserve linear sign and scale symmetry.');

noWeathercock=model(3,-0.50,0);
assert(noWeathercock.yawMomentCoefficientFromBeta(1)==0 && ...
    noWeathercock.yawMoment_Nm(1)==0 && ...
    noWeathercock.yawAcceleration_deg_s2(1)==0 && ...
    max(abs(noWeathercock.yawRate_deg_s(2:end)))>0.5, ...
    'C_n_beta=0 removes direct initial yaw but not later coupled C_n_p*p yaw.');

degreeMisuseRollAcceleration_deg_s2= ...
    expectedLBeta_Nm_per_rad/expectedIx_kgm2*3*180/pi;
assert(abs(degreeMisuseRollAcceleration_deg_s2/ ...
    first.rollAcceleration_deg_s2(1)-180/pi)<tol, ...
    'Using degree numbers in per-radian derivatives must expose the 180/pi error.');

%% Two isolated derivative sweeps change one matrix entry each
rollDampingSweep=[-0.30 -0.40 -0.50 -0.65 -0.80];
rollPeaks=zeros(size(rollDampingSweep));
bankPeaks=zeros(size(rollDampingSweep));
initialRollAccelerations=zeros(size(rollDampingSweep));
for k=1:numel(rollDampingSweep)
    sample=model(3,rollDampingSweep(k),0.18);
    difference=sample.stateMatrix-first.stateMatrix;
    difference(2,2)=0;
    assert(all(difference(:)==0) && ...
        sample.initialSideslip_deg==3 && ...
        sample.weathercockDerivative_Cn_beta_perRad==0.18, ...
        'C_l_p sweep isolation means only A(2,2) may change.');
    rollPeaks(k)=sample.peakAbsRollRate_deg_s;
    bankPeaks(k)=sample.peakAbsBank_deg;
    initialRollAccelerations(k)=sample.rollAcceleration_deg_s2(1);
end
assert(all(diff(rollPeaks)<0) && all(diff(bankPeaks)<0) && ...
    max(abs(initialRollAccelerations- ...
    initialRollAccelerations(1)))<tol, ...
    'More-negative C_l_p must lower rate/bank peaks but not initial p-dot.');
assert(max(abs(rollPeaks-[4.927271898192998 4.353351756176826 ...
    3.901553273234694 3.379513108837036 2.983204463014648]))<1e-11, ...
    'The C_l_p sweep regression must retain recognizable peak roll rates.');

weathercockSweep=[0 0.06 0.12 0.18 0.24];
initialYawAccelerations=zeros(size(weathercockSweep));
zeroCrossings=zeros(size(weathercockSweep));
yawPeaks=zeros(size(weathercockSweep));
for k=1:numel(weathercockSweep)
    sample=model(3,-0.50,weathercockSweep(k));
    difference=sample.stateMatrix-first.stateMatrix;
    difference(3,1)=0;
    assert(all(difference(:)==0) && ...
        sample.initialSideslip_deg==3 && ...
        sample.rollDampingDerivative_Cl_p==-0.50, ...
        'C_n_beta sweep isolation means only A(3,1) may change.');
    initialYawAccelerations(k)=sample.yawAcceleration_deg_s2(1);
    zeroCrossings(k)=sample.firstSideslipZeroCrossing_s;
    yawPeaks(k)=sample.peakAbsYawRate_deg_s;
end
assert(initialYawAccelerations(1)==0 && ...
    all(diff(initialYawAccelerations)>0) && ...
    all(diff(zeroCrossings)<0) && all(diff(yawPeaks)>0) && ...
    max(abs(zeroCrossings-[1.76 0.90 0.66 0.54 0.46]))<tol, ...
    'C_n_beta must linearly increase initial yaw and advance beta crossing.');

%% Deliberately broken roll-rate normalization
expectedBrokenNumeric_Nm=expectedMomentScale_Nm*(-0.50);
expectedBrokenA22=expectedBrokenNumeric_Nm/expectedIx_kgm2;
expectedNumericRatio_per_s=2*expectedV_mps/expectedSpan_m;
assert(abs(first.brokenRollDampingNumeric_Nm- ...
    expectedBrokenNumeric_Nm)<tol && ...
    abs(first.brokenStateMatrix(2,2)-expectedBrokenA22)<tol && ...
    max(abs(first.brokenStateMatrix([1:5 7:16])- ...
    first.stateMatrix([1:5 7:16])))==0 && ...
    abs(first.brokenA22NumericRatio_per_s- ...
    expectedNumericRatio_per_s)<tol, ...
    'The broken case must omit only b/(2*V0) from C_l_p.');
assert(abs(first.brokenPeakAbsRollRate_deg_s- ...
    0.647583354815180)<1e-12 && ...
    abs(first.brokenPeakAbsBank_deg-0.184170133062447)<1e-12 && ...
    first.peakAbsRollRate_deg_s>5*first.brokenPeakAbsRollRate_deg_s && ...
    first.peakAbsBank_deg>8*first.brokenPeakAbsBank_deg, ...
    'The smooth broken trace must exhibit excessive numeric roll damping.');

%% Malformed inputs fail clearly, then a valid call recovers
expectFailure(@() model(-4.01,-0.50,0.18), ...
    'P08:model:InitialSideslipRange','sideslip below range');
expectFailure(@() model(4.01,-0.50,0.18), ...
    'P08:model:InitialSideslipRange','sideslip above range');
expectFailure(@() model(3,-0.801,0.18), ...
    'P08:model:RollDampingDerivativeRange','C_l_p below range');
expectFailure(@() model(3,-0.299,0.18), ...
    'P08:model:RollDampingDerivativeRange','C_l_p above range');
expectFailure(@() model(3,-0.50,-0.001), ...
    'P08:model:WeathercockDerivativeRange','C_n_beta below range');
expectFailure(@() model(3,-0.50,0.241), ...
    'P08:model:WeathercockDerivativeRange','C_n_beta above range');
expectFailure(@() model([3 4],-0.50,0.18),'','nonscalar sideslip');
expectFailure(@() model(3,-0.50+1i,0.18),'','complex C_l_p');
expectFailure(@() model(3,-0.50,NaN),'','nonfinite C_n_beta');
expectFailure(@() model(Inf,-0.50,0.18),'','nonfinite sideslip');
afterFailure=model(3,-0.50,0.18);
assert(isequaln(afterFailure,first), ...
    'Rejected inputs must not poison the next deterministic model call.');

disp(['P08 checks passed: derivative ledger, coupled equations, RK4 recurrence, ' ...
    'limits, isolated sweeps, malformed-input recovery, and broken rate normalization.']);
end

function expectFailure(action,expectedIdentifier,label)
didFail=false;
try
    action();
catch exception
    didFail=true;
    if ~isempty(expectedIdentifier)
        assert(strcmp(exception.identifier,expectedIdentifier), ...
            'Expected %s to raise %s, but received %s.', ...
            label,expectedIdentifier,exception.identifier);
    end
end
assert(didFail,'Expected model to reject %s.',label);
end
