function out=model(insAccelerationBias_mps2,gpsPositionErrorRms_m,fusionMode)
%MODEL Fuse a high-rate one-dimensional INS prediction with GPS position.
% North position and velocity are positive North. The INS input is a
% gravity-compensated North acceleration supplied by an upstream attitude
% mechanization; this module isolates prediction, correction, and gating.
arguments
    insAccelerationBias_mps2 (1,1) double {mustBeReal,mustBeFinite}=0.04
    gpsPositionErrorRms_m (1,1) double {mustBeReal,mustBeFinite}=1
    fusionMode (1,1) double {mustBeReal,mustBeFinite}=1
end

minimumInsAccelerationBias_mps2=-0.08;
maximumInsAccelerationBias_mps2=0.08;
minimumGpsPositionErrorRms_m=0;
maximumGpsPositionErrorRms_m=4;
if insAccelerationBias_mps2<minimumInsAccelerationBias_mps2 || ...
        insAccelerationBias_mps2>maximumInsAccelerationBias_mps2
    error('P17:model:InsAccelerationBiasRange', ...
        'INS acceleration bias must be between -0.08 and 0.08 m/s^2 inclusive.');
end
if gpsPositionErrorRms_m<minimumGpsPositionErrorRms_m || ...
        gpsPositionErrorRms_m>maximumGpsPositionErrorRms_m
    error('P17:model:GpsPositionErrorRange', ...
        'GPS position-error RMS must be between 0 and 4 m inclusive.');
end
if fusionMode~=1 && fusionMode~=0 && fusionMode~=-1
    error('P17:model:FusionMode', ...
        ['Fusion mode must be +1 for gated fusion, 0 for INS-only, ' ...
        'or -1 for deliberately broken ungated fusion.']);
end

sampleTime_s=0.02;
timeHorizon_s=60;
time_s=0:sampleTime_s:timeHorizon_s;
sampleCount=numel(time_s);
intervalCount=sampleCount-1;
initialNorthPosition_m=0;
initialNorthVelocity_mps=20;
gpsUpdatePeriod_s=1;
gpsUpdateStepCount=round(gpsUpdatePeriod_s/sampleTime_s);
gpsUpdateIndices=1+gpsUpdateStepCount:gpsUpdateStepCount:sampleCount;
gpsUpdateMask=false(1,sampleCount);
gpsUpdateMask(gpsUpdateIndices)=true;
gpsUpdateCount=sum(gpsUpdateMask);
gpsPositionGain=0.45;
gpsVelocityGain=0.12;
innovationGate_m=25;
outlierTime_s=30;
outlierMagnitude_m=80;
outlierIndex=find(abs(time_s-outlierTime_s)<sampleTime_s/2,1,'first');

% Truth contains two bounded acceleration intervals. The second cancels the
% first velocity change, while position continues North. The signal is
% independent of both public sensor-error levers and fusion mode.
northAccelerationTruth_mps2=zeros(1,sampleCount);
northAccelerationTruth_mps2(time_s>=5 & time_s<15)=0.5;
northAccelerationTruth_mps2(time_s>=25 & time_s<35)=-0.5;
northVelocityTruth_mps=initialNorthVelocity_mps*ones(1,sampleCount);
northPositionTruth_m=initialNorthPosition_m*ones(1,sampleCount);
for k=1:intervalCount
    acceleration=northAccelerationTruth_mps2(k);
    northPositionTruth_m(k+1)=northPositionTruth_m(k)+ ...
        sampleTime_s*northVelocityTruth_mps(k)+ ...
        0.5*sampleTime_s^2*acceleration;
    northVelocityTruth_mps(k+1)=northVelocityTruth_mps(k)+ ...
        sampleTime_s*acceleration;
end

% The INS mechanization receives the same motion plus a constant residual
% acceleration bias. Its dead-reckoned limit is retained beside the fused
% state so drift and correction remain visually distinct.
northAccelerationINS_mps2=northAccelerationTruth_mps2+ ...
    insAccelerationBias_mps2;
northVelocityINSOnly_mps=initialNorthVelocity_mps*ones(1,sampleCount);
northPositionINSOnly_m=initialNorthPosition_m*ones(1,sampleCount);
for k=1:intervalCount
    acceleration=northAccelerationINS_mps2(k);
    northPositionINSOnly_m(k+1)=northPositionINSOnly_m(k)+ ...
        sampleTime_s*northVelocityINSOnly_mps(k)+ ...
        0.5*sampleTime_s^2*acceleration;
    northVelocityINSOnly_mps(k+1)=northVelocityINSOnly_mps(k)+ ...
        sampleTime_s*acceleration;
end

% GPS error is a replayable teaching waveform, not random or identified
% receiver noise. It is mean-removed and normalized over the 60 fix times,
% so the selected scalar is exactly its nominal RMS before the outlier.
gpsUpdateTime_s=time_s(gpsUpdateIndices);
rawGpsPositionErrorShape=sin(2*pi*gpsUpdateTime_s/17)+ ...
    0.35*cos(2*pi*gpsUpdateTime_s/7+0.2);
rawGpsPositionErrorShape=rawGpsPositionErrorShape- ...
    mean(rawGpsPositionErrorShape);
rawGpsPositionErrorRms=sqrt(mean(rawGpsPositionErrorShape.^2));
unitGpsPositionErrorShape= ...
    rawGpsPositionErrorShape/rawGpsPositionErrorRms;
gpsNominalPositionError_m=zeros(1,sampleCount);
gpsNominalPositionError_m(gpsUpdateIndices)= ...
    gpsPositionErrorRms_m*unitGpsPositionErrorShape;
gpsOutlier_m=zeros(1,sampleCount);
gpsOutlier_m(outlierIndex)=outlierMagnitude_m;
gpsPositionMeasurement_m=zeros(1,sampleCount);
gpsPositionMeasurement_m(gpsUpdateIndices)= ...
    northPositionTruth_m(gpsUpdateIndices)+ ...
    gpsNominalPositionError_m(gpsUpdateIndices)+ ...
    gpsOutlier_m(gpsUpdateIndices);

% Explicit alpha-beta correction. Prediction occurs at every INS sample;
% correction can occur only at a GPS fix. Correct mode rejects an innovation
% outside the inclusive gate. Broken mode changes only that gate decision.
northPositionPredicted_m=initialNorthPosition_m*ones(1,sampleCount);
northVelocityPredicted_mps=initialNorthVelocity_mps*ones(1,sampleCount);
northPositionFused_m=initialNorthPosition_m*ones(1,sampleCount);
northVelocityFused_mps=initialNorthVelocity_mps*ones(1,sampleCount);
gpsInnovation_m=zeros(1,sampleCount);
gpsPositionCorrection_m=zeros(1,sampleCount);
gpsVelocityCorrection_mps=zeros(1,sampleCount);
gpsAccepted=false(1,sampleCount);
gpsRejected=false(1,sampleCount);
gpsIgnored=false(1,sampleCount);
for k=2:sampleCount
    acceleration=northAccelerationINS_mps2(k-1);
    northPositionPredicted_m(k)=northPositionFused_m(k-1)+ ...
        sampleTime_s*northVelocityFused_mps(k-1)+ ...
        0.5*sampleTime_s^2*acceleration;
    northVelocityPredicted_mps(k)=northVelocityFused_mps(k-1)+ ...
        sampleTime_s*acceleration;

    if gpsUpdateMask(k)
        gpsInnovation_m(k)=gpsPositionMeasurement_m(k)- ...
            northPositionPredicted_m(k);
        if fusionMode==-1
            gpsAccepted(k)=true;
        elseif fusionMode==1
            gpsAccepted(k)=abs(gpsInnovation_m(k))<=innovationGate_m;
            gpsRejected(k)=~gpsAccepted(k);
        else
            gpsIgnored(k)=true;
        end
        if gpsAccepted(k)
            gpsPositionCorrection_m(k)= ...
                gpsPositionGain*gpsInnovation_m(k);
            gpsVelocityCorrection_mps(k)= ...
                (gpsVelocityGain/gpsUpdatePeriod_s)*gpsInnovation_m(k);
        end
    end

    northPositionFused_m(k)=northPositionPredicted_m(k)+ ...
        gpsPositionCorrection_m(k);
    northVelocityFused_mps(k)=northVelocityPredicted_mps(k)+ ...
        gpsVelocityCorrection_mps(k);
end

northPositionINSOnlyError_m= ...
    northPositionINSOnly_m-northPositionTruth_m;
northVelocityINSOnlyError_mps= ...
    northVelocityINSOnly_mps-northVelocityTruth_mps;
northPositionFusedError_m=northPositionFused_m-northPositionTruth_m;
northVelocityFusedError_mps=northVelocityFused_mps-northVelocityTruth_mps;
expectedINSOnlyPositionError_m= ...
    0.5*insAccelerationBias_mps2*time_s.^2;
expectedINSOnlyVelocityError_mps=insAccelerationBias_mps2*time_s;
gpsPositionErrorRmsMeasured_m=sqrt(mean( ...
    gpsNominalPositionError_m(gpsUpdateMask).^2));

if fusionMode==1
    fusionModeName='gated INS/GPS fusion';
elseif fusionMode==0
    fusionModeName='INS-only limiting case; GPS corrections ignored';
else
    fusionModeName='BROKEN ungated fusion; GPS outlier accepted';
end

out=struct( ...
    'insAccelerationBias_mps2',insAccelerationBias_mps2, ...
    'gpsPositionErrorRms_m',gpsPositionErrorRms_m, ...
    'fusionMode',fusionMode, ...
    'fusionModeName',fusionModeName, ...
    'minimumInsAccelerationBias_mps2', ...
    minimumInsAccelerationBias_mps2, ...
    'maximumInsAccelerationBias_mps2', ...
    maximumInsAccelerationBias_mps2, ...
    'minimumGpsPositionErrorRms_m',minimumGpsPositionErrorRms_m, ...
    'maximumGpsPositionErrorRms_m',maximumGpsPositionErrorRms_m, ...
    'sampleTime_s',sampleTime_s, ...
    'timeHorizon_s',timeHorizon_s, ...
    'time_s',time_s, ...
    'sampleCount',sampleCount, ...
    'intervalCount',intervalCount, ...
    'initialNorthPosition_m',initialNorthPosition_m, ...
    'initialNorthVelocity_mps',initialNorthVelocity_mps, ...
    'gpsUpdatePeriod_s',gpsUpdatePeriod_s, ...
    'gpsUpdateStepCount',gpsUpdateStepCount, ...
    'gpsUpdateIndices',gpsUpdateIndices, ...
    'gpsUpdateMask',gpsUpdateMask, ...
    'gpsUpdateCount',gpsUpdateCount, ...
    'gpsPositionGain',gpsPositionGain, ...
    'gpsVelocityGain',gpsVelocityGain, ...
    'innovationGate_m',innovationGate_m, ...
    'outlierTime_s',outlierTime_s, ...
    'outlierIndex',outlierIndex, ...
    'outlierMagnitude_m',outlierMagnitude_m, ...
    'northAccelerationTruth_mps2',northAccelerationTruth_mps2, ...
    'northVelocityTruth_mps',northVelocityTruth_mps, ...
    'northPositionTruth_m',northPositionTruth_m, ...
    'northAccelerationINS_mps2',northAccelerationINS_mps2, ...
    'northVelocityINSOnly_mps',northVelocityINSOnly_mps, ...
    'northPositionINSOnly_m',northPositionINSOnly_m, ...
    'northVelocityINSOnlyError_mps',northVelocityINSOnlyError_mps, ...
    'northPositionINSOnlyError_m',northPositionINSOnlyError_m, ...
    'expectedINSOnlyVelocityError_mps', ...
    expectedINSOnlyVelocityError_mps, ...
    'expectedINSOnlyPositionError_m', ...
    expectedINSOnlyPositionError_m, ...
    'unitGpsPositionErrorShape',unitGpsPositionErrorShape, ...
    'gpsNominalPositionError_m',gpsNominalPositionError_m, ...
    'gpsOutlier_m',gpsOutlier_m, ...
    'gpsPositionMeasurement_m',gpsPositionMeasurement_m, ...
    'gpsPositionErrorRmsMeasured_m',gpsPositionErrorRmsMeasured_m, ...
    'northPositionPredicted_m',northPositionPredicted_m, ...
    'northVelocityPredicted_mps',northVelocityPredicted_mps, ...
    'gpsInnovation_m',gpsInnovation_m, ...
    'gpsPositionCorrection_m',gpsPositionCorrection_m, ...
    'gpsVelocityCorrection_mps',gpsVelocityCorrection_mps, ...
    'gpsAccepted',gpsAccepted, ...
    'gpsRejected',gpsRejected, ...
    'gpsIgnored',gpsIgnored, ...
    'gpsAcceptedCount',sum(gpsAccepted), ...
    'gpsRejectedCount',sum(gpsRejected), ...
    'gpsIgnoredCount',sum(gpsIgnored), ...
    'northPositionFused_m',northPositionFused_m, ...
    'northVelocityFused_mps',northVelocityFused_mps, ...
    'northPositionFusedError_m',northPositionFusedError_m, ...
    'northVelocityFusedError_mps',northVelocityFusedError_mps, ...
    'insOnlyFinalPositionError_m',northPositionINSOnlyError_m(end), ...
    'insOnlyFinalVelocityError_mps',northVelocityINSOnlyError_mps(end), ...
    'maxINSOnlyPositionClosureError_m',max(abs( ...
    northPositionINSOnlyError_m-expectedINSOnlyPositionError_m)), ...
    'maxINSOnlyVelocityClosureError_mps',max(abs( ...
    northVelocityINSOnlyError_mps-expectedINSOnlyVelocityError_mps)), ...
    'fusedPositionRMS_m',sqrt(mean(northPositionFusedError_m.^2)), ...
    'fusedVelocityRMS_mps',sqrt(mean(northVelocityFusedError_mps.^2)), ...
    'fusedPeakAbsolutePositionError_m', ...
    max(abs(northPositionFusedError_m)), ...
    'fusedPeakAbsoluteVelocityError_mps', ...
    max(abs(northVelocityFusedError_mps)), ...
    'fusedFinalPositionError_m',northPositionFusedError_m(end), ...
    'fusedFinalVelocityError_mps',northVelocityFusedError_mps(end), ...
    'outlierInnovation_m',gpsInnovation_m(outlierIndex), ...
    'outlierPositionCorrection_m', ...
    gpsPositionCorrection_m(outlierIndex), ...
    'outlierVelocityCorrection_mps', ...
    gpsVelocityCorrection_mps(outlierIndex), ...
    'predictionEquation',[ ...
        'p_minus(k)=p_plus(k-1)+v_plus(k-1)*dt+' ...
        '0.5*a_INS(k-1)*dt^2; v_minus(k)=v_plus(k-1)+' ...
        'a_INS(k-1)*dt'], ...
    'innovationEquation','r_GPS=z_GPS-p_minus', ...
    'correctionEquation',[ ...
        'accepted fix: p_plus=p_minus+alpha*r_GPS; ' ...
        'v_plus=v_minus+(beta/T_GPS)*r_GPS'], ...
    'gateEquation','accept when abs(r_GPS)<=25 m; broken mode accepts all', ...
    'sensorDefinition',[ ...
        'INS uses truth North acceleration plus constant residual bias; ' ...
        'GPS uses fixed zero-mean unit-RMS teaching error plus one outlier'], ...
    'brokenCaseDefinition',[ ...
        'disable only the innovation gate so the fixed +80 m GPS outlier ' ...
        'is accepted while truth, INS, GPS data, gains, and grid stay fixed'], ...
    'analysisScope',[ ...
        'one-dimensional deterministic base-MATLAB alpha-beta teaching ' ...
        'filter; no attitude mechanization, covariance filter, clock, ' ...
        'geodesy, identified receiver, hardware, or aircraft fidelity']);
end
