function run_checks
%RUN_CHECKS P17 independent INS/GPS fusion and recovery checks.
clear model;
modelFcn=@model;
absoluteTolerance=1e-10;
trajectoryTolerance=1e-9;

%% Deterministic baseline identity, resources, and signed references
baseline=modelFcn(0.04,1,1);
repeat=modelFcn(0.04,1,1);
historyFields={'time_s','northAccelerationTruth_mps2', ...
    'northVelocityTruth_mps','northPositionTruth_m', ...
    'northAccelerationINS_mps2','northVelocityINSOnly_mps', ...
    'northPositionINSOnly_m','gpsUpdateMask', ...
    'gpsNominalPositionError_m','gpsOutlier_m', ...
    'gpsPositionMeasurement_m','northPositionPredicted_m', ...
    'northVelocityPredicted_mps','gpsInnovation_m', ...
    'gpsPositionCorrection_m','gpsVelocityCorrection_mps', ...
    'gpsAccepted','gpsRejected','gpsIgnored', ...
    'northPositionFused_m','northVelocityFused_mps'};
for k=1:numel(historyFields)
    field=historyFields{k};
    assert(isequal(baseline.(field),repeat.(field)), ...
        ['Repeated baseline calls must exactly reproduce ' field '.']);
end
assert(baseline.sampleCount==3001 && baseline.intervalCount==3000 && ...
    baseline.sampleTime_s==0.02 && baseline.timeHorizon_s==60 && ...
    isequal(size(baseline.time_s),[1 3001]), ...
    'The fixed INS grid and resource counts changed.');
assert(baseline.gpsUpdatePeriod_s==1 && ...
    baseline.gpsUpdateStepCount==50 && baseline.gpsUpdateCount==60 && ...
    isequal(baseline.gpsUpdateIndices,51:50:3001) && ...
    ~baseline.gpsUpdateMask(1) && ...
    isequal(baseline.time_s(baseline.gpsUpdateMask),1:60), ...
    'GPS must provide exactly 60 fixes at t=1:60 s and none at t=0.');
assert(baseline.insAccelerationBias_mps2==0.04 && ...
    baseline.gpsPositionErrorRms_m==1 && baseline.fusionMode==1 && ...
    baseline.gpsPositionGain==0.45 && ...
    baseline.gpsVelocityGain==0.12 && ...
    baseline.innovationGate_m==25 && ...
    baseline.outlierTime_s==30 && baseline.outlierMagnitude_m==80, ...
    'Baseline inputs, fusion gains, gate, or outlier changed.');

%% Independent truth, INS, GPS waveform, and measurement reconstruction
expectedAcceleration=zeros(1,baseline.sampleCount);
expectedAcceleration(baseline.time_s>=5 & baseline.time_s<15)=0.5;
expectedAcceleration(baseline.time_s>=25 & baseline.time_s<35)=-0.5;
expectedTruthPosition=zeros(1,baseline.sampleCount);
expectedTruthVelocity=20*ones(1,baseline.sampleCount);
expectedINSPosition=zeros(1,baseline.sampleCount);
expectedINSVelocity=20*ones(1,baseline.sampleCount);
for k=1:baseline.intervalCount
    expectedTruthPosition(k+1)=expectedTruthPosition(k)+ ...
        baseline.sampleTime_s*expectedTruthVelocity(k)+ ...
        0.5*baseline.sampleTime_s^2*expectedAcceleration(k);
    expectedTruthVelocity(k+1)=expectedTruthVelocity(k)+ ...
        baseline.sampleTime_s*expectedAcceleration(k);
    insAcceleration=expectedAcceleration(k)+ ...
        baseline.insAccelerationBias_mps2;
    expectedINSPosition(k+1)=expectedINSPosition(k)+ ...
        baseline.sampleTime_s*expectedINSVelocity(k)+ ...
        0.5*baseline.sampleTime_s^2*insAcceleration;
    expectedINSVelocity(k+1)=expectedINSVelocity(k)+ ...
        baseline.sampleTime_s*insAcceleration;
end
assert(isequal(baseline.northAccelerationTruth_mps2, ...
    expectedAcceleration) && ...
    max(abs(baseline.northPositionTruth_m-expectedTruthPosition))< ...
    trajectoryTolerance && ...
    max(abs(baseline.northVelocityTruth_mps-expectedTruthVelocity))< ...
    trajectoryTolerance && ...
    abs(baseline.northPositionTruth_m(end)-1300)<trajectoryTolerance && ...
    abs(baseline.northVelocityTruth_mps(end)-20)<absoluteTolerance, ...
    'Truth schedule, kinematics, or final North state changed.');
assert(max(abs(baseline.northAccelerationINS_mps2-( ...
    expectedAcceleration+0.04)))<absoluteTolerance && ...
    max(abs(baseline.northPositionINSOnly_m-expectedINSPosition))< ...
    trajectoryTolerance && ...
    max(abs(baseline.northVelocityINSOnly_mps-expectedINSVelocity))< ...
    trajectoryTolerance, ...
    'INS acceleration or dead-reckoning updates failed reconstruction.');

gpsTimes=1:60;
rawGpsShape=sin(2*pi*gpsTimes/17)+ ...
    0.35*cos(2*pi*gpsTimes/7+0.2);
rawGpsShape=rawGpsShape-mean(rawGpsShape);
unitGpsShape=rawGpsShape/sqrt(mean(rawGpsShape.^2));
expectedNominalGpsError=zeros(1,baseline.sampleCount);
expectedNominalGpsError(baseline.gpsUpdateIndices)=unitGpsShape;
expectedOutlier=zeros(1,baseline.sampleCount);
expectedOutlier(baseline.outlierIndex)=80;
expectedGpsMeasurement=zeros(1,baseline.sampleCount);
expectedGpsMeasurement(baseline.gpsUpdateIndices)= ...
    expectedTruthPosition(baseline.gpsUpdateIndices)+ ...
    expectedNominalGpsError(baseline.gpsUpdateIndices)+ ...
    expectedOutlier(baseline.gpsUpdateIndices);
assert(abs(mean(unitGpsShape))<absoluteTolerance && ...
    abs(sqrt(mean(unitGpsShape.^2))-1)<absoluteTolerance && ...
    max(abs(baseline.unitGpsPositionErrorShape-unitGpsShape))< ...
    trajectoryTolerance && ...
    max(abs(baseline.gpsNominalPositionError_m- ...
    expectedNominalGpsError))<trajectoryTolerance && ...
    isequal(baseline.gpsOutlier_m,expectedOutlier) && ...
    max(abs(baseline.gpsPositionMeasurement_m- ...
    expectedGpsMeasurement))<trajectoryTolerance && ...
    all(baseline.gpsPositionMeasurement_m(~baseline.gpsUpdateMask)==0) && ...
    abs(baseline.gpsPositionErrorRmsMeasured_m-1)<absoluteTolerance, ...
    'Nominal GPS normalization, fix masking, or outlier injection changed.');

%% Exact dead-reckoning limits and every prediction/correction update
expectedVelocityError=baseline.insAccelerationBias_mps2*baseline.time_s;
expectedPositionError=0.5*baseline.insAccelerationBias_mps2* ...
    baseline.time_s.^2;
assert(max(abs(baseline.northVelocityINSOnlyError_mps- ...
    expectedVelocityError))<trajectoryTolerance && ...
    max(abs(baseline.northPositionINSOnlyError_m- ...
    expectedPositionError))<trajectoryTolerance && ...
    max(abs(baseline.expectedINSOnlyVelocityError_mps- ...
    expectedVelocityError))<absoluteTolerance && ...
    max(abs(baseline.expectedINSOnlyPositionError_m- ...
    expectedPositionError))<absoluteTolerance && ...
    baseline.maxINSOnlyVelocityClosureError_mps<trajectoryTolerance && ...
    baseline.maxINSOnlyPositionClosureError_m<trajectoryTolerance && ...
    abs(baseline.insOnlyFinalVelocityError_mps-2.4)<trajectoryTolerance && ...
    abs(baseline.insOnlyFinalPositionError_m-72)<trajectoryTolerance, ...
    'INS-only bias integration must close to b*t and 0.5*b*t^2.');

expectedPredictedPosition=zeros(1,baseline.sampleCount);
expectedPredictedVelocity=20*ones(1,baseline.sampleCount);
expectedFusedPosition=zeros(1,baseline.sampleCount);
expectedFusedVelocity=20*ones(1,baseline.sampleCount);
expectedInnovation=zeros(1,baseline.sampleCount);
expectedPositionCorrection=zeros(1,baseline.sampleCount);
expectedVelocityCorrection=zeros(1,baseline.sampleCount);
expectedAccepted=false(1,baseline.sampleCount);
expectedRejected=false(1,baseline.sampleCount);
for k=2:baseline.sampleCount
    insAcceleration=expectedAcceleration(k-1)+0.04;
    expectedPredictedPosition(k)=expectedFusedPosition(k-1)+ ...
        baseline.sampleTime_s*expectedFusedVelocity(k-1)+ ...
        0.5*baseline.sampleTime_s^2*insAcceleration;
    expectedPredictedVelocity(k)=expectedFusedVelocity(k-1)+ ...
        baseline.sampleTime_s*insAcceleration;
    if baseline.gpsUpdateMask(k)
        expectedInnovation(k)=expectedGpsMeasurement(k)- ...
            expectedPredictedPosition(k);
        expectedAccepted(k)=abs(expectedInnovation(k))<=25;
        expectedRejected(k)=~expectedAccepted(k);
        if expectedAccepted(k)
            expectedPositionCorrection(k)=0.45*expectedInnovation(k);
            expectedVelocityCorrection(k)= ...
                (0.12/baseline.gpsUpdatePeriod_s)*expectedInnovation(k);
        end
    end
    expectedFusedPosition(k)=expectedPredictedPosition(k)+ ...
        expectedPositionCorrection(k);
    expectedFusedVelocity(k)=expectedPredictedVelocity(k)+ ...
        expectedVelocityCorrection(k);
end
assert(max(abs(baseline.northPositionPredicted_m- ...
    expectedPredictedPosition))<trajectoryTolerance && ...
    max(abs(baseline.northVelocityPredicted_mps- ...
    expectedPredictedVelocity))<trajectoryTolerance && ...
    max(abs(baseline.gpsInnovation_m-expectedInnovation))< ...
    trajectoryTolerance && ...
    isequal(baseline.gpsAccepted,expectedAccepted) && ...
    isequal(baseline.gpsRejected,expectedRejected) && ...
    ~any(baseline.gpsIgnored) && ...
    max(abs(baseline.gpsPositionCorrection_m- ...
    expectedPositionCorrection))<trajectoryTolerance && ...
    max(abs(baseline.gpsVelocityCorrection_mps- ...
    expectedVelocityCorrection))<trajectoryTolerance && ...
    max(abs(baseline.northPositionFused_m- ...
    expectedFusedPosition))<trajectoryTolerance && ...
    max(abs(baseline.northVelocityFused_mps- ...
    expectedFusedVelocity))<trajectoryTolerance, ...
    'Prediction, innovation, inclusive gate, or alpha-beta correction failed reconstruction.');

%% Independently reconstructed metrics and baseline signature
expectedPositionFusedError=expectedFusedPosition-expectedTruthPosition;
expectedVelocityFusedError=expectedFusedVelocity-expectedTruthVelocity;
expectedPositionRMS=sqrt(mean(expectedPositionFusedError.^2));
expectedVelocityRMS=sqrt(mean(expectedVelocityFusedError.^2));
assert(abs(baseline.fusedPositionRMS_m-expectedPositionRMS)< ...
    trajectoryTolerance && ...
    abs(baseline.fusedVelocityRMS_mps-expectedVelocityRMS)< ...
    trajectoryTolerance && ...
    abs(baseline.fusedPeakAbsolutePositionError_m- ...
    max(abs(expectedPositionFusedError)))<trajectoryTolerance && ...
    abs(baseline.fusedPeakAbsoluteVelocityError_mps- ...
    max(abs(expectedVelocityFusedError)))<trajectoryTolerance && ...
    abs(baseline.fusedFinalPositionError_m- ...
    expectedPositionFusedError(end))<trajectoryTolerance && ...
    abs(baseline.fusedFinalVelocityError_mps- ...
    expectedVelocityFusedError(end))<trajectoryTolerance, ...
    'Reported fused metrics must reconstruct from retained histories.');
assert(abs(baseline.fusedPositionRMS_m-1.180877601392873)<1e-9 && ...
    abs(baseline.fusedPeakAbsolutePositionError_m- ...
    2.385486692971881)<1e-9 && ...
    abs(baseline.fusedFinalPositionError_m-0.136263825022525)<1e-9 && ...
    abs(baseline.fusedFinalVelocityError_mps+ ...
    0.115398118713124)<1e-9 && ...
    baseline.gpsAcceptedCount==59 && baseline.gpsRejectedCount==1 && ...
    baseline.gpsIgnoredCount==0 && ...
    baseline.gpsRejected(baseline.outlierIndex) && ...
    abs(baseline.outlierInnovation_m-79.33779956347905)<1e-9 && ...
    baseline.outlierPositionCorrection_m==0 && ...
    baseline.outlierVelocityCorrection_mps==0, ...
    'The signed deterministic baseline or isolated outlier rejection changed.');

% The model uses an inclusive gate. The exact scalar boundary is accepted;
% the next representable value above it is not. No tolerance widens the gate.
gateBoundary=baseline.innovationGate_m;
assert(abs(gateBoundary)<=baseline.innovationGate_m && ...
    ~(abs(gateBoundary+eps(gateBoundary))<=baseline.innovationGate_m), ...
    'The innovation gate must remain inclusive without a hidden tolerance.');

%% Lever 1: bias sweep with GPS history and nonlever inputs isolated
insBiasSweep_mps2=[0 0.02 0.04 0.06 0.08];
expectedFinalPosition_m=0.5*insBiasSweep_mps2*60^2;
expectedFinalVelocity_mps=insBiasSweep_mps2*60;
expectedBiasFusedRMS_m=[ ...
    1.163493836900810 1.165304641533275 1.180877601392873 ...
    1.209681327532636 1.250802111330508];
observedBiasFusedRMS_m=zeros(size(insBiasSweep_mps2));
for k=1:numel(insBiasSweep_mps2)
    sample=modelFcn(insBiasSweep_mps2(k),1,1);
    observedBiasFusedRMS_m(k)=sample.fusedPositionRMS_m;
    assert(isequal(sample.northAccelerationTruth_mps2, ...
        baseline.northAccelerationTruth_mps2) && ...
        isequal(sample.northPositionTruth_m,baseline.northPositionTruth_m) && ...
        isequal(sample.gpsUpdateMask,baseline.gpsUpdateMask) && ...
        isequal(sample.gpsNominalPositionError_m, ...
        baseline.gpsNominalPositionError_m) && ...
        isequal(sample.gpsOutlier_m,baseline.gpsOutlier_m) && ...
        isequal(sample.gpsPositionMeasurement_m, ...
        baseline.gpsPositionMeasurement_m), ...
        'The INS-bias sweep must preserve truth and the complete GPS stream.');
    assert(abs(sample.insOnlyFinalPositionError_m- ...
        expectedFinalPosition_m(k))<trajectoryTolerance && ...
        abs(sample.insOnlyFinalVelocityError_mps- ...
        expectedFinalVelocity_mps(k))<trajectoryTolerance && ...
        abs(sample.fusedPositionRMS_m-sqrt(mean( ...
        sample.northPositionFusedError_m.^2)))<trajectoryTolerance && ...
        abs(sample.fusedPeakAbsolutePositionError_m-max(abs( ...
        sample.northPositionFusedError_m)))<trajectoryTolerance && ...
        sample.gpsRejectedCount==1, ...
        'Every bias-sweep metric and outlier decision must reconstruct.');
end
assert(max(abs(observedBiasFusedRMS_m-expectedBiasFusedRMS_m))<1e-9 && ...
    all(diff(observedBiasFusedRMS_m)>0), ...
    'The isolated bias sweep must retain its independently simulated trend.');

%% Lever 2: GPS error sweep with INS and truth histories isolated
gpsPositionErrorSweep_m=[0 0.5 1 2 4];
expectedGpsFusedRMS_m=[ ...
    0.254243988397741 0.625401055665580 1.180877601392873 ...
    2.330609283066586 4.650653988745627];
observedGpsFusedRMS_m=zeros(size(gpsPositionErrorSweep_m));
for k=1:numel(gpsPositionErrorSweep_m)
    sample=modelFcn(0.04,gpsPositionErrorSweep_m(k),1);
    observedGpsFusedRMS_m(k)=sample.fusedPositionRMS_m;
    assert(isequal(sample.northAccelerationTruth_mps2, ...
        baseline.northAccelerationTruth_mps2) && ...
        isequal(sample.northPositionTruth_m,baseline.northPositionTruth_m) && ...
        isequal(sample.northAccelerationINS_mps2, ...
        baseline.northAccelerationINS_mps2) && ...
        isequal(sample.northPositionINSOnly_m, ...
        baseline.northPositionINSOnly_m) && ...
        isequal(sample.northVelocityINSOnly_mps, ...
        baseline.northVelocityINSOnly_mps) && ...
        isequal(sample.gpsOutlier_m,baseline.gpsOutlier_m), ...
        'The GPS-error sweep must preserve truth, INS, and outlier histories.');
    assert(abs(sample.gpsPositionErrorRmsMeasured_m- ...
        gpsPositionErrorSweep_m(k))<trajectoryTolerance && ...
        max(abs(sample.gpsNominalPositionError_m- ...
        gpsPositionErrorSweep_m(k)*expectedNominalGpsError))< ...
        trajectoryTolerance && ...
        abs(sample.fusedPositionRMS_m-sqrt(mean( ...
        sample.northPositionFusedError_m.^2)))<trajectoryTolerance && ...
        sample.gpsRejectedCount==1, ...
        'Every GPS-error sweep scale, metric, and gate decision must reconstruct.');
end
assert(max(abs(observedGpsFusedRMS_m-expectedGpsFusedRMS_m))<1e-9 && ...
    all(diff(observedGpsFusedRMS_m)>0), ...
    'The isolated GPS-error sweep must retain its monotone fused-error trend.');

%% Ideal, INS-only, bias-sign, and broken-gate limits
ideal=modelFcn(0,0,1);
idealINSOnly=modelFcn(0,0,0);
assert(isequal(ideal.northPositionFused_m,ideal.northPositionTruth_m) && ...
    isequal(ideal.northVelocityFused_mps,ideal.northVelocityTruth_mps) && ...
    ideal.fusedPositionRMS_m==0 && ideal.fusedVelocityRMS_mps==0 && ...
    ideal.gpsAcceptedCount==59 && ideal.gpsRejectedCount==1 && ...
    ideal.outlierPositionCorrection_m==0 && ...
    isequal(idealINSOnly.northPositionFused_m, ...
    idealINSOnly.northPositionTruth_m) && ...
    isequal(idealINSOnly.northVelocityFused_mps, ...
    idealINSOnly.northVelocityTruth_mps) && ...
    idealINSOnly.gpsAcceptedCount==0 && ...
    idealINSOnly.gpsRejectedCount==0 && ...
    idealINSOnly.gpsIgnoredCount==60, ...
    'Ideal gated and INS-only limits must follow truth with distinct GPS dispositions.');

insOnly=modelFcn(0.04,1,0);
negativeBias=modelFcn(-0.04,1,0);
assert(isequal(insOnly.northPositionFused_m, ...
    insOnly.northPositionINSOnly_m) && ...
    isequal(insOnly.northVelocityFused_mps, ...
    insOnly.northVelocityINSOnly_mps) && ...
    insOnly.gpsAcceptedCount==0 && insOnly.gpsRejectedCount==0 && ...
    insOnly.gpsIgnoredCount==60 && ...
    max(abs(negativeBias.northPositionINSOnlyError_m+ ...
    insOnly.northPositionINSOnlyError_m))<trajectoryTolerance && ...
    max(abs(negativeBias.northVelocityINSOnlyError_mps+ ...
    insOnly.northVelocityINSOnlyError_mps))<trajectoryTolerance && ...
    isequal(negativeBias.northPositionTruth_m, ...
    insOnly.northPositionTruth_m) && ...
    isequal(negativeBias.gpsPositionMeasurement_m, ...
    insOnly.gpsPositionMeasurement_m), ...
    'INS-only equality and bias-sign symmetry changed.');

positiveNoiseFreeFusion=modelFcn(0.08,0,1);
negativeNoiseFreeFusion=modelFcn(-0.08,0,1);
nominalAcceptedMask=positiveNoiseFreeFusion.gpsAccepted;
positivePredictedError=positiveNoiseFreeFusion.northPositionPredicted_m- ...
    positiveNoiseFreeFusion.northPositionTruth_m;
negativePredictedError=negativeNoiseFreeFusion.northPositionPredicted_m- ...
    negativeNoiseFreeFusion.northPositionTruth_m;
assert(isequal(positiveNoiseFreeFusion.northPositionTruth_m, ...
    negativeNoiseFreeFusion.northPositionTruth_m) && ...
    isequal(positiveNoiseFreeFusion.gpsPositionMeasurement_m, ...
    negativeNoiseFreeFusion.gpsPositionMeasurement_m) && ...
    max(abs((positiveNoiseFreeFusion.northAccelerationINS_mps2- ...
    positiveNoiseFreeFusion.northAccelerationTruth_mps2)+( ...
    negativeNoiseFreeFusion.northAccelerationINS_mps2- ...
    negativeNoiseFreeFusion.northAccelerationTruth_mps2)))< ...
    trajectoryTolerance && ...
    max(abs(positiveNoiseFreeFusion.northPositionINSOnlyError_m+ ...
    negativeNoiseFreeFusion.northPositionINSOnlyError_m))< ...
    trajectoryTolerance && ...
    max(abs(positiveNoiseFreeFusion.northVelocityINSOnlyError_mps+ ...
    negativeNoiseFreeFusion.northVelocityINSOnlyError_mps))< ...
    trajectoryTolerance && ...
    max(abs(positiveNoiseFreeFusion.northPositionFusedError_m+ ...
    negativeNoiseFreeFusion.northPositionFusedError_m))< ...
    trajectoryTolerance && ...
    max(abs(positiveNoiseFreeFusion.northVelocityFusedError_mps+ ...
    negativeNoiseFreeFusion.northVelocityFusedError_mps))< ...
    trajectoryTolerance && ...
    max(abs(positiveNoiseFreeFusion.gpsPositionCorrection_m+ ...
    negativeNoiseFreeFusion.gpsPositionCorrection_m))< ...
    trajectoryTolerance && ...
    max(abs(positiveNoiseFreeFusion.gpsVelocityCorrection_mps+ ...
    negativeNoiseFreeFusion.gpsVelocityCorrection_mps))< ...
    trajectoryTolerance && ...
    isequal(positiveNoiseFreeFusion.gpsAccepted, ...
    negativeNoiseFreeFusion.gpsAccepted) && ...
    isequal(positiveNoiseFreeFusion.gpsRejected, ...
    negativeNoiseFreeFusion.gpsRejected) && ...
    sum(nominalAcceptedMask)==59 && ...
    positiveNoiseFreeFusion.gpsRejected( ...
    positiveNoiseFreeFusion.outlierIndex) && ...
    max(abs(positiveNoiseFreeFusion.gpsInnovation_m(nominalAcceptedMask)+ ...
    negativeNoiseFreeFusion.gpsInnovation_m(nominalAcceptedMask)))< ...
    trajectoryTolerance && ...
    all(abs(positiveNoiseFreeFusion.northPositionFusedError_m( ...
    nominalAcceptedMask))<abs(positivePredictedError(nominalAcceptedMask))) && ...
    all(abs(negativeNoiseFreeFusion.northPositionFusedError_m( ...
    nominalAcceptedMask))<abs(negativePredictedError(nominalAcceptedMask))) && ...
    max(abs(positiveNoiseFreeFusion.northPositionFusedError_m( ...
    nominalAcceptedMask)-(1-positiveNoiseFreeFusion.gpsPositionGain)* ...
    positivePredictedError(nominalAcceptedMask)))<trajectoryTolerance && ...
    max(abs(negativeNoiseFreeFusion.northPositionFusedError_m( ...
    nominalAcceptedMask)-(1-negativeNoiseFreeFusion.gpsPositionGain)* ...
    negativePredictedError(nominalAcceptedMask)))<trajectoryTolerance && ...
    positiveNoiseFreeFusion.fusedFinalPositionError_m>0 && ...
    negativeNoiseFreeFusion.fusedFinalPositionError_m<0 && ...
    abs(positiveNoiseFreeFusion.fusedPositionRMS_m- ...
    negativeNoiseFreeFusion.fusedPositionRMS_m)<trajectoryTolerance && ...
    abs(positiveNoiseFreeFusion.fusedVelocityRMS_mps- ...
    negativeNoiseFreeFusion.fusedVelocityRMS_mps)<trajectoryTolerance, ...
    ['Noise-free signed bias must reverse INS/fused errors and corrections; ' ...
    'every accepted fix must contract predicted position error.']);

broken=modelFcn(0.04,1,-1);
exogenousFields={'time_s','northAccelerationTruth_mps2', ...
    'northVelocityTruth_mps','northPositionTruth_m', ...
    'northAccelerationINS_mps2','northVelocityINSOnly_mps', ...
    'northPositionINSOnly_m','gpsUpdateMask', ...
    'gpsNominalPositionError_m','gpsOutlier_m', ...
    'gpsPositionMeasurement_m'};
for k=1:numel(exogenousFields)
    field=exogenousFields{k};
    assert(isequal(broken.(field),baseline.(field)), ...
        ['Broken mode must preserve exogenous field ' field '.']);
end
assert(isequal(broken.northPositionFused_m(1:baseline.outlierIndex-1), ...
    baseline.northPositionFused_m(1:baseline.outlierIndex-1)) && ...
    isequal(broken.northVelocityFused_mps(1:baseline.outlierIndex-1), ...
    baseline.northVelocityFused_mps(1:baseline.outlierIndex-1)) && ...
    broken.gpsAcceptedCount==60 && broken.gpsRejectedCount==0 && ...
    broken.gpsIgnoredCount==0 && broken.gpsAccepted(broken.outlierIndex) && ...
    abs(broken.outlierInnovation_m-baseline.outlierInnovation_m)< ...
    trajectoryTolerance && ...
    abs(broken.outlierPositionCorrection_m-35.70200980356557)<1e-9 && ...
    abs(broken.outlierVelocityCorrection_mps-9.520535947617486)<1e-9 && ...
    abs(broken.fusedPositionRMS_m-6.519034268309427)<1e-9 && ...
    abs(broken.fusedPeakAbsolutePositionError_m- ...
    43.95460633859625)<1e-9 && ...
    broken.fusedPeakAbsolutePositionError_m> ...
    baseline.fusedPeakAbsolutePositionError_m, ...
    'The accept-all outlier failure must remain isolated and recognizable.');
nextFixIndex=baseline.outlierIndex+baseline.gpsUpdateStepCount;
assert(max(abs(broken.northPositionFusedError_m( ...
    baseline.outlierIndex:nextFixIndex-1)))> ...
    abs(broken.northPositionFusedError_m(baseline.outlierIndex)), ...
    'Broken velocity correction must grow position error before the next fix.');
rollback=modelFcn(0.04,1,1);
assert(isequal(rollback.northPositionFused_m, ...
    baseline.northPositionFused_m) && ...
    isequal(rollback.northVelocityFused_mps, ...
    baseline.northVelocityFused_mps) && ...
    isequal(rollback.gpsAccepted,baseline.gpsAccepted), ...
    'Selecting gated mode after broken mode must be exact stateless rollback.');

%% Malformed input rejection and deterministic recovery
invalidCalls={ ...
    @() modelFcn(-0.0800001,1,1), ...
    @() modelFcn(0.0800001,1,1), ...
    @() modelFcn([0.04 0.05],1,1), ...
    @() modelFcn(0.04+1i,1,1), ...
    @() modelFcn(NaN,1,1), ...
    @() modelFcn(Inf,1,1), ...
    @() modelFcn(0.04,-1e-12,1), ...
    @() modelFcn(0.04,4.000001,1), ...
    @() modelFcn(0.04,[1 2],1), ...
    @() modelFcn(0.04,1+1i,1), ...
    @() modelFcn(0.04,NaN,1), ...
    @() modelFcn(0.04,Inf,1), ...
    @() modelFcn(0.04,1,-2), ...
    @() modelFcn(0.04,1,2), ...
    @() modelFcn(0.04,1,0.5), ...
    @() modelFcn(0.04,1,[1 0]), ...
    @() modelFcn(0.04,1,1+1i), ...
    @() modelFcn(0.04,1,NaN), ...
    @() modelFcn(0.04,1,Inf)};
for k=1:numel(invalidCalls)
    assertRejects(invalidCalls{k});
end
afterRejection=modelFcn(0.04,1,1);
assert(isequal(afterRejection.northPositionFused_m, ...
    baseline.northPositionFused_m) && ...
    isequal(afterRejection.northVelocityFused_mps, ...
    baseline.northVelocityFused_mps) && ...
    isequal(afterRejection.gpsInnovation_m,baseline.gpsInnovation_m), ...
    'Rejected calls must not poison deterministic baseline recovery.');

%% Accepted corners and capped representative grid bound work and outputs
acceptedCaseCount=0;
for insAccelerationBias_mps2=[-0.08 0.08]
    for gpsPositionErrorRms_m=[0 4]
        for fusionMode=[-1 0 1]
            sample=modelFcn(insAccelerationBias_mps2, ...
                gpsPositionErrorRms_m,fusionMode);
            acceptedCaseCount=acceptedCaseCount+1;
            assert(sample.sampleCount==3001 && ...
                sample.intervalCount==3000 && ...
                sample.gpsUpdateCount==60 && ...
                numel(sample.northPositionFused_m)==3001 && ...
                all(isfinite(sample.northPositionFused_m)) && ...
                all(isfinite(sample.northVelocityFused_mps)) && ...
                all(isfinite(sample.gpsPositionMeasurement_m)) && ...
                all(isfinite(sample.gpsInnovation_m)) && ...
                all(isfinite(sample.gpsPositionCorrection_m)) && ...
                all(isfinite(sample.gpsVelocityCorrection_mps)) && ...
                max(abs(sample.northPositionFusedError_m))<160 && ...
                max(abs(sample.gpsPositionCorrection_m))<50 && ...
                max(abs(sample.gpsVelocityCorrection_mps))<15, ...
                'Every accepted corner must remain finite, fixed, and bounded.');
            if fusionMode==1
                assert(sample.gpsAcceptedCount==59 && ...
                    sample.gpsRejectedCount==1, ...
                    'Every gated corner must reject only the fixed outlier.');
            end
        end
    end
end
assert(acceptedCaseCount==12, ...
    'The accepted-corner test matrix must remain capped at 12 calls.');

representativeCaseCount=0;
for insAccelerationBias_mps2=[-0.08 0 0.08]
    for gpsPositionErrorRms_m=[0 1 4]
        for fusionMode=[-1 0 1]
            sample=modelFcn(insAccelerationBias_mps2, ...
                gpsPositionErrorRms_m,fusionMode);
            representativeCaseCount=representativeCaseCount+1;
            assert(numel(sample.time_s)==3001 && ...
                numel(sample.northPositionFused_m)==3001 && ...
                numel(sample.gpsInnovation_m)==3001 && ...
                all(isfinite(sample.northPositionFusedError_m)) && ...
                all(isfinite(sample.northVelocityFusedError_mps)) && ...
                sample.gpsAcceptedCount+sample.gpsRejectedCount+ ...
                sample.gpsIgnoredCount==60, ...
                'The representative grid must retain bounded fixed-size work.');
        end
    end
end
assert(representativeCaseCount==27, ...
    'The representative resource grid must remain capped at 27 calls.');

%% Compatibility, timeout, cancellation, migration, and backup applicability
% MODEL is synchronous, deterministic, fixed-work, and stateless. It creates
% no timer, future, worker, file, network, device, process, or background
% callback resource, so runtime timeout and cancellation transitions are not
% applicable model semantics. The fixed 3001 samples, 60 GPS fixes, bounded
% inputs, and capped 12/27-case matrices are the applicable resource gates.
% P16, P11, and P12 are conceptual prerequisites, not API compatibility
% adapters. No learner state, score, database, service, schema, migration,
% or backup/restore path is read or changed by these checks.

fprintf(['P17 checks passed: truth and sensor reconstruction, every INS ' ...
    'prediction and GPS correction, two isolated sweeps, ideal and INS-only ' ...
    'limits, inclusive gating, broken outlier acceptance, malformed recovery, ' ...
    'rollback, compatibility, and bounded resources.\n']);
end

function assertRejects(callable)
didReject=false;
try
    callable();
catch
    didReject=true;
end
assert(didReject,'Malformed or out-of-range input must be rejected.');
end
