function out = model(pressureAltitude_m,temperatureOffset_K,trueAirspeed_mps)
%MODEL Transparent dry-air atmosphere from 0 to 20 km pressure altitude.
% pressureAltitude_m is positive-up geopotential pressure altitude. Pressure
% follows the standard atmosphere. temperatureOffset_K is a local departure
% from standard temperature at that pressure altitude; it changes density
% and speed of sound but does not redefine the pressure-altitude surface.
% The learning domain is h=[0,20000] m, DeltaT=[-100,100] K, and
% true airspeed=[0,1000] m/s so all accepted outputs remain finite.
arguments
    pressureAltitude_m (1,1) double {mustBeReal,mustBeFinite} = 5000
    temperatureOffset_K (1,1) double {mustBeReal,mustBeFinite} = 0
    trueAirspeed_mps (1,1) double {mustBeReal,mustBeFinite} = 150
end

if pressureAltitude_m<0 || pressureAltitude_m>20000
    error('P03:model:AltitudeRange', ...
        'Pressure altitude must be between 0 and 20000 m, inclusive.');
end
if temperatureOffset_K<-100 || temperatureOffset_K>100
    error('P03:model:TemperatureOffsetRange', ...
        'Local temperature offset must be between -100 and 100 K, inclusive.');
end
if trueAirspeed_mps<0
    error('P03:model:NegativeAirspeed', ...
        'True airspeed must be nonnegative.');
end
if trueAirspeed_mps>1000
    error('P03:model:AirspeedRange', ...
        'True airspeed must not exceed 1000 m/s in this learning model.');
end

seaLevelTemperature_K=288.15;
seaLevelPressure_Pa=101325;
gravity_mps2=9.80665;
gasConstant_JpkgK=287.05287;
heatCapacityRatio=1.4;
lapseRate_Kpm=-0.0065;
tropopauseAltitude_m=11000;
tropopauseTemperature_K=seaLevelTemperature_K+ ...
    lapseRate_Kpm*tropopauseAltitude_m;
tropopausePressure_Pa=seaLevelPressure_Pa* ...
    (tropopauseTemperature_K/seaLevelTemperature_K)^ ...
    (-gravity_mps2/(lapseRate_Kpm*gasConstant_JpkgK));

if pressureAltitude_m<=tropopauseAltitude_m
    standardTemperature_K=seaLevelTemperature_K+ ...
        lapseRate_Kpm*pressureAltitude_m;
    pressure_Pa=seaLevelPressure_Pa* ...
        (standardTemperature_K/seaLevelTemperature_K)^ ...
        (-gravity_mps2/(lapseRate_Kpm*gasConstant_JpkgK));
    layer='gradient troposphere';
else
    standardTemperature_K=tropopauseTemperature_K;
    pressure_Pa=tropopausePressure_Pa*exp( ...
        -gravity_mps2*(pressureAltitude_m-tropopauseAltitude_m)/ ...
        (gasConstant_JpkgK*tropopauseTemperature_K));
    layer='isothermal lower stratosphere';
end

temperature_K=standardTemperature_K+temperatureOffset_K;
if temperature_K<=0
    error('P03:model:AbsoluteTemperature', ...
        'Temperature offset must leave absolute temperature greater than 0 K.');
end

density_kgpm3=pressure_Pa/(gasConstant_JpkgK*temperature_K);
speedOfSound_mps=sqrt(heatCapacityRatio*gasConstant_JpkgK*temperature_K);
mach=trueAirspeed_mps/speedOfSound_mps;
dynamicPressure_Pa=0.5*density_kgpm3*trueAirspeed_mps^2;
seaLevelDensity_kgpm3=seaLevelPressure_Pa/ ...
    (gasConstant_JpkgK*seaLevelTemperature_K);
equivalentAirspeed_mps=trueAirspeed_mps*sqrt( ...
    density_kgpm3/seaLevelDensity_kgpm3);

out=struct( ...
    'pressureAltitude_m',pressureAltitude_m, ...
    'temperatureOffset_K',temperatureOffset_K, ...
    'trueAirspeed_mps',trueAirspeed_mps, ...
    'standardTemperature_K',standardTemperature_K, ...
    'temperature_K',temperature_K, ...
    'pressure_Pa',pressure_Pa, ...
    'density_kgpm3',density_kgpm3, ...
    'speedOfSound_mps',speedOfSound_mps, ...
    'mach',mach, ...
    'dynamicPressure_Pa',dynamicPressure_Pa, ...
    'equivalentAirspeed_mps',equivalentAirspeed_mps, ...
    'temperatureRatio',temperature_K/seaLevelTemperature_K, ...
    'pressureRatio',pressure_Pa/seaLevelPressure_Pa, ...
    'densityRatio',density_kgpm3/seaLevelDensity_kgpm3, ...
    'layer',layer, ...
    'seaLevelTemperature_K',seaLevelTemperature_K, ...
    'seaLevelPressure_Pa',seaLevelPressure_Pa, ...
    'seaLevelDensity_kgpm3',seaLevelDensity_kgpm3, ...
    'gravity_mps2',gravity_mps2, ...
    'gasConstant_JpkgK',gasConstant_JpkgK, ...
    'heatCapacityRatio',heatCapacityRatio, ...
    'lapseRate_Kpm',lapseRate_Kpm, ...
    'tropopauseAltitude_m',tropopauseAltitude_m, ...
    'tropopauseTemperature_K',tropopauseTemperature_K, ...
    'tropopausePressure_Pa',tropopausePressure_Pa, ...
    'altitudeConvention','positive-up geopotential pressure altitude', ...
    'temperatureOffsetConvention', ...
    'local departure at fixed standard-atmosphere pressure');
end
