function run_checks
%RUN_CHECKS Independent analytic checks for the P03 atmosphere model.
clear model;
tol=1e-9;

%% Determinism and fixed resource shape
first=model(5000,0,150);
second=model(5000,0,150);
assert(isequaln(first,second), ...
    'Identical atmosphere inputs must produce identical outputs.');
scalarFields={'temperature_K','pressure_Pa','density_kgpm3', ...
    'speedOfSound_mps','mach','dynamicPressure_Pa','equivalentAirspeed_mps'};
for k=1:numel(scalarFields)
    assert(isscalar(first.(scalarFields{k})) && isfinite(first.(scalarFields{k})), ...
        'Atmosphere outputs must remain finite scalars.');
end
boundedEdge=model(20000,-100,1000);
for k=1:numel(scalarFields)
    assert(isfinite(boundedEdge.(scalarFields{k})), ...
        'Every accepted boundary input must produce finite scalar outputs.');
end

%% Independent sea-level and zero-speed limits
seaLevel=model(0,0,0);
assert(abs(seaLevel.temperature_K-288.15)<tol, ...
    'Standard sea-level temperature must be 288.15 K.');
assert(abs(seaLevel.pressure_Pa-101325)<tol, ...
    'Standard sea-level pressure must be 101325 Pa.');
assert(abs(seaLevel.density_kgpm3-1.2250000181)<1e-9, ...
    'Sea-level density must follow p/(R*T).');
assert(abs(seaLevel.speedOfSound_mps-340.2939880)<1e-6, ...
    'Sea-level speed of sound must follow sqrt(gamma*R*T).');
assert(seaLevel.mach==0 && seaLevel.dynamicPressure_Pa==0 && ...
    seaLevel.equivalentAirspeed_mps==0, ...
    'Zero true airspeed must give zero Mach, dynamic pressure, and EAS.');
seaLevelMoving=model(0,0,150);
assert(abs(seaLevelMoving.equivalentAirspeed_mps- ...
    seaLevelMoving.trueAirspeed_mps)<tol, ...
    'At standard sea-level density, equivalent and true airspeed must match.');

%% Troposphere exponent, tropopause, and upper-bound limits
atTenKm=model(10000,0,150);
expectedTemperature_K=288.15-0.0065*10000;
expectedPressure_Pa=101325*(expectedTemperature_K/288.15)^ ...
    (9.80665/(287.05287*0.0065));
assert(abs(atTenKm.temperature_K-expectedTemperature_K)<tol && ...
    abs(atTenKm.pressure_Pa-expectedPressure_Pa)<1e-6, ...
    'Troposphere lapse rate and hydrostatic exponent must retain their signs.');
assert(abs(atTenKm.pressure_Pa-26436.2426)<0.01, ...
    'The 10 km pressure limiting value must remain recognizable.');

tropopause=model(11000,0,150);
assert(abs(tropopause.temperature_K-216.65)<tol && ...
    abs(tropopause.pressure_Pa-22632.0401)<0.01 && ...
    abs(tropopause.density_kgpm3-0.3639176481)<1e-9, ...
    'The 11 km layer boundary must match the standard-atmosphere limit.');
justBelow=model(11000-1e-3,0,150);
justAbove=model(11000+1e-3,0,150);
assert(abs(justBelow.pressure_Pa-justAbove.pressure_Pa)<0.01 && ...
    abs(justBelow.temperature_K-justAbove.temperature_K)<1e-5, ...
    'Temperature and pressure must remain continuous at 11 km.');

atTwentyKm=model(20000,0,150);
assert(abs(atTwentyKm.pressure_Pa-5474.8774)<0.01 && ...
    abs(atTwentyKm.density_kgpm3-0.0880346848)<1e-9, ...
    'The 20 km upper bound must use the isothermal-layer equation.');
assert(strcmp(tropopause.layer,'gradient troposphere') && ...
    strcmp(atTwentyKm.layer,'isothermal lower stratosphere'), ...
    'The 11 km boundary must select the declared atmosphere layers.');

%% Thermodynamic and air-data identities
general=model(7350,12,183);
assert(abs(general.pressure_Pa- ...
    general.density_kgpm3*general.gasConstant_JpkgK*general.temperature_K)<1e-8, ...
    'Pressure, density, and absolute temperature must satisfy p=rho*R*T.');
assert(abs(general.speedOfSound_mps^2- ...
    general.heatCapacityRatio*general.gasConstant_JpkgK*general.temperature_K)<1e-8, ...
    'Speed of sound must satisfy a^2=gamma*R*T.');
assert(abs(general.dynamicPressure_Pa- ...
    0.5*general.density_kgpm3*general.trueAirspeed_mps^2)<1e-10, ...
    'Dynamic pressure must satisfy q=0.5*rho*V^2.');
assert(abs(general.mach-general.trueAirspeed_mps/general.speedOfSound_mps)<tol, ...
    'Mach must be true airspeed divided by local speed of sound.');
equivalentDynamicPressure_Pa=0.5*general.seaLevelDensity_kgpm3* ...
    general.equivalentAirspeed_mps^2;
assert(abs(general.dynamicPressure_Pa-equivalentDynamicPressure_Pa)<1e-8 && ...
    general.equivalentAirspeed_mps<general.trueAirspeed_mps, ...
    'EAS at sea-level density must preserve q and fall below TAS in thinner air.');

%% Sweep 1 regression - altitude changes atmosphere at fixed weather and speed
altitudeSweep_m=[0 3000 6000 9000 11000 15000 20000];
temperatureSweep_K=zeros(size(altitudeSweep_m));
pressureSweep_Pa=zeros(size(altitudeSweep_m));
densitySweep_kgpm3=zeros(size(altitudeSweep_m));
dynamicPressureSweep_Pa=zeros(size(altitudeSweep_m));
for k=1:numel(altitudeSweep_m)
    sample=model(altitudeSweep_m(k),0,150);
    temperatureSweep_K(k)=sample.temperature_K;
    pressureSweep_Pa(k)=sample.pressure_Pa;
    densitySweep_kgpm3(k)=sample.density_kgpm3;
    dynamicPressureSweep_Pa(k)=sample.dynamicPressure_Pa;
end
assert(all(diff(pressureSweep_Pa)<0) && all(diff(densitySweep_kgpm3)<0), ...
    'Pressure and density must decrease through the altitude sweep.');
assert(all(diff(temperatureSweep_K(1:5))<0) && ...
    all(abs(diff(temperatureSweep_K(5:end)))<tol), ...
    'Temperature must lapse to 11 km and remain constant above it.');
assert(all(diff(dynamicPressureSweep_Pa)<0), ...
    'At fixed true airspeed, dynamic pressure must fall with density.');

%% Sweep 2 regression - temperature offset at fixed pressure altitude
temperatureOffsetSweep_K=[-30 -15 0 15 30];
offsetPressure_Pa=zeros(size(temperatureOffsetSweep_K));
offsetDensity_kgpm3=zeros(size(temperatureOffsetSweep_K));
offsetSoundSpeed_mps=zeros(size(temperatureOffsetSweep_K));
offsetMach=zeros(size(temperatureOffsetSweep_K));
for k=1:numel(temperatureOffsetSweep_K)
    sample=model(5000,temperatureOffsetSweep_K(k),150);
    offsetPressure_Pa(k)=sample.pressure_Pa;
    offsetDensity_kgpm3(k)=sample.density_kgpm3;
    offsetSoundSpeed_mps(k)=sample.speedOfSound_mps;
    offsetMach(k)=sample.mach;
end
assert(max(offsetPressure_Pa)-min(offsetPressure_Pa)<tol, ...
    'Temperature offset must not move a fixed pressure-altitude surface.');
assert(all(diff(offsetDensity_kgpm3)<0), ...
    'At fixed pressure altitude, warmer air must be less dense.');
assert(all(diff(offsetSoundSpeed_mps)>0) && all(diff(offsetMach)<0), ...
    'Warming must raise sound speed and lower Mach at fixed true airspeed.');

%% Airspeed limit and deliberately broken constant-density regression
slow=model(5000,0,75);
fast=model(5000,0,150);
assert(abs(fast.dynamicPressure_Pa/slow.dynamicPressure_Pa-4)<tol && ...
    abs(fast.mach/slow.mach-2)<tol, ...
    'Doubling true airspeed must quadruple q and double Mach.');
brokenDynamicPressure_Pa=0.5*seaLevel.density_kgpm3* ...
    tropopause.trueAirspeed_mps^2;
assert(brokenDynamicPressure_Pa/tropopause.dynamicPressure_Pa>3.3, ...
    'Freezing sea-level density at 11 km must expose a large q overprediction.');

%% Malformed inputs fail clearly, then a valid call recovers
expectFailure(@() model(-1,0,150), ...
    'P03:model:AltitudeRange','negative altitude');
expectFailure(@() model(20001,0,150), ...
    'P03:model:AltitudeRange','altitude above the model ceiling');
expectFailure(@() model(5000,0,-1), ...
    'P03:model:NegativeAirspeed','negative true airspeed');
expectFailure(@() model(5000,-101,150), ...
    'P03:model:TemperatureOffsetRange','temperature offset below the learning range');
expectFailure(@() model(5000,101,150), ...
    'P03:model:TemperatureOffsetRange','temperature offset above the learning range');
expectFailure(@() model(5000,0,1001), ...
    'P03:model:AirspeedRange','true airspeed above the learning range');
expectFailure(@() model([0 1000],0,150),'','nonscalar altitude');
expectFailure(@() model(5000+1i,0,150),'','complex altitude');
expectFailure(@() model(5000,NaN,150),'','nonfinite temperature offset');
expectFailure(@() model(5000,0,Inf),'','nonfinite true airspeed');
afterFailure=model(5000,0,150);
assert(isequaln(afterFailure,first), ...
    'Rejected inputs must not alter the next deterministic calculation.');

disp('P03 checks passed: atmosphere limits, equations, sweeps, malformed inputs, and broken density case.');
end

function expectFailure(action,expectedIdentifier,label)
didFail=false;
try
    action();
catch exception
    didFail=true;
    if ~isempty(expectedIdentifier)
        assert(strcmp(exception.identifier,expectedIdentifier), ...
            'Expected %s to raise %s, but received %s.', ...
            label,expectedIdentifier,exception.identifier);
    end
end
assert(didFail,'Expected model to reject %s.',label);
end
