function out = model(elevatorPulse_deg,airspeedKick_mps, ...
    shortPeriodDampingRatio,phugoidDampingRatio)
%MODEL Decoupled analytic short-period and phugoid teaching responses.
% Positive elevator is trailing-edge down and positive pitch rate is
% nose-up. The elevator pulse is represented by a fixed 0.18 s angular
% impulse. For the fast mode, nearly frozen flight path makes alpha_dot
% approximately q; this is not an exact kinematic identity. The airspeed
% kick is a perturbation from the P04/P05 60 m/s reference. This reduced
% modal model is not a full longitudinal model.
arguments
    elevatorPulse_deg (1,1) double {mustBeReal,mustBeFinite} = -2
    airspeedKick_mps (1,1) double {mustBeReal,mustBeFinite} = 5
    shortPeriodDampingRatio (1,1) double {mustBeReal,mustBeFinite} = 0.35
    phugoidDampingRatio (1,1) double {mustBeReal,mustBeFinite} = 0.08
end

if abs(elevatorPulse_deg)>5
    error('P06:model:ElevatorPulseRange', ...
        'Elevator pulse must be between -5 and 5 deg, inclusive.');
end
if abs(airspeedKick_mps)>10
    error('P06:model:AirspeedKickRange', ...
        'Airspeed kick must be between -10 and 10 m/s, inclusive.');
end
if shortPeriodDampingRatio<0
    error('P06:model:NegativeShortPeriodDamping', ...
        'Short-period damping ratio must be nonnegative.');
end
if shortPeriodDampingRatio>0.8
    error('P06:model:ShortPeriodDampingRange', ...
        'Short-period damping ratio must not exceed 0.8.');
end
if phugoidDampingRatio<0
    error('P06:model:NegativePhugoidDamping', ...
        'Phugoid damping ratio must be nonnegative.');
end
if phugoidDampingRatio>0.3
    error('P06:model:PhugoidDampingRange', ...
        'Phugoid damping ratio must not exceed 0.3.');
end

referenceTrueAirspeed_mps=60;
referenceDynamicPressure_Pa=1325.00798531847;
wingArea_m2=16.2;
meanAerodynamicChord_m=1.5;
referenceStaticMargin_percentMAC=20.84683357879235;
pitchingMomentSlope_perRad=-1.1324;
elevatorControlDerivative_perRad=-1.3824;
pitchInertia_kgm2=1800;
elevatorPulseDuration_s=0.18;
gravity_mps2=9.80665;
shortPeriodLinearAlphaLimit_deg=5;
phugoidLiftSpeedGain=2;

fastTime_s=0:0.02:8;
slowTime_s=0:0.25:120;
momentScale_Nm=referenceDynamicPressure_Pa*wingArea_m2* ...
    meanAerodynamicChord_m;
dimensionalPitchStiffness_NmPerRad=momentScale_Nm* ...
    pitchingMomentSlope_perRad;
dimensionalElevatorDerivative_NmPerRad=momentScale_Nm* ...
    elevatorControlDerivative_perRad;

% P05 supplies restoring stiffness. Inertia converts that stiffness to the
% short-period teaching frequency; damping remains an explicit P06 input.
shortPeriodNaturalFrequency_rad_s=sqrt( ...
    -dimensionalPitchStiffness_NmPerRad/pitchInertia_kgm2);
shortPeriodBeta=sqrt(1-shortPeriodDampingRatio^2);
shortPeriodDampedFrequency_rad_s= ...
    shortPeriodNaturalFrequency_rad_s*shortPeriodBeta;
shortPeriodDecayRate_per_s=shortPeriodDampingRatio* ...
    shortPeriodNaturalFrequency_rad_s;
shortPeriodDampedPeriod_s=2*pi/shortPeriodDampedFrequency_rad_s;
shortPeriodDecayPerPeriod_ratio=exp(-shortPeriodDecayRate_per_s* ...
    shortPeriodDampedPeriod_s);

elevatorPulse_rad=elevatorPulse_deg*pi/180;
elevatorMoment_Nm=dimensionalElevatorDerivative_NmPerRad* ...
    elevatorPulse_rad;
initialPitchRate_rad_s=elevatorMoment_Nm*elevatorPulseDuration_s/ ...
    pitchInertia_kgm2;
shortPeriodExponential=exp(-shortPeriodDecayRate_per_s*fastTime_s);
shortPeriodAlpha_rad=(initialPitchRate_rad_s/ ...
    shortPeriodDampedFrequency_rad_s).*shortPeriodExponential.* ...
    sin(shortPeriodDampedFrequency_rad_s*fastTime_s);
shortPeriodPitchRate_rad_s=initialPitchRate_rad_s* ...
    shortPeriodExponential.*( ...
    cos(shortPeriodDampedFrequency_rad_s*fastTime_s)- ...
    (shortPeriodDecayRate_per_s/shortPeriodDampedFrequency_rad_s).* ...
    sin(shortPeriodDampedFrequency_rad_s*fastTime_s));
shortPeriodAlpha_deg=shortPeriodAlpha_rad*180/pi;
shortPeriodPitchRate_deg_s=shortPeriodPitchRate_rad_s*180/pi;
shortPeriodAlphaEnvelope_deg=abs(initialPitchRate_rad_s)/ ...
    shortPeriodDampedFrequency_rad_s*180/pi.*shortPeriodExponential;

% The standard constant-CL point-mass approximation uses
% u_dot=-2*zeta*omega*u-g*gamma and gamma_dot=2*g*u/V0^2.
% Combining them gives u_ddot+2*zeta*omega*u_dot+omega^2*u=0.
phugoidNaturalFrequency_rad_s=sqrt(phugoidLiftSpeedGain)* ...
    gravity_mps2/referenceTrueAirspeed_mps;
phugoidBeta=sqrt(1-phugoidDampingRatio^2);
phugoidDampedFrequency_rad_s=phugoidNaturalFrequency_rad_s*phugoidBeta;
phugoidDecayRate_per_s=phugoidDampingRatio* ...
    phugoidNaturalFrequency_rad_s;
phugoidDampedPeriod_s=2*pi/phugoidDampedFrequency_rad_s;
phugoidDecayPerPeriod_ratio=exp(-phugoidDecayRate_per_s* ...
    phugoidDampedPeriod_s);

phugoidExponential=exp(-phugoidDecayRate_per_s*slowTime_s);
phugoidSpeedPerturbation_mps=airspeedKick_mps*phugoidExponential.*( ...
    cos(phugoidDampedFrequency_rad_s*slowTime_s)- ...
    (phugoidDecayRate_per_s/phugoidDampedFrequency_rad_s).* ...
    sin(phugoidDampedFrequency_rad_s*slowTime_s));
phugoidSpeedRate_mps2=airspeedKick_mps*phugoidExponential.*( ...
    -2*phugoidDecayRate_per_s* ...
    cos(phugoidDampedFrequency_rad_s*slowTime_s)+( ...
    phugoidDecayRate_per_s^2/phugoidDampedFrequency_rad_s- ...
    phugoidDampedFrequency_rad_s).* ...
    sin(phugoidDampedFrequency_rad_s*slowTime_s));
phugoidFlightPathAngle_rad=airspeedKick_mps* ...
    phugoidNaturalFrequency_rad_s^2/(gravity_mps2* ...
    phugoidDampedFrequency_rad_s).*phugoidExponential.* ...
    sin(phugoidDampedFrequency_rad_s*slowTime_s);
phugoidFlightPathAngle_deg=phugoidFlightPathAngle_rad*180/pi;
phugoidAltitudeFromInitial_m=referenceTrueAirspeed_mps* ...
    airspeedKick_mps/gravity_mps2*(1-phugoidExponential.*( ...
    cos(phugoidDampedFrequency_rad_s*slowTime_s)+ ...
    (phugoidDecayRate_per_s/phugoidDampedFrequency_rad_s).* ...
    sin(phugoidDampedFrequency_rad_s*slowTime_s)));
phugoidSpeedEquationResidual_mps2=phugoidSpeedRate_mps2+ ...
    2*phugoidDecayRate_per_s*phugoidSpeedPerturbation_mps+ ...
    gravity_mps2*phugoidFlightPathAngle_rad;

shortPeriodPeakAlpha_deg=max(abs(shortPeriodAlpha_deg));
shortPeriodPeakPitchRate_deg_s=max(abs(shortPeriodPitchRate_deg_s));
phugoidPeakSpeed_mps=max(abs(phugoidSpeedPerturbation_mps));
phugoidPeakFlightPathAngle_deg=max(abs(phugoidFlightPathAngle_deg));
phugoidAltitudeRange_m=max(phugoidAltitudeFromInitial_m)- ...
    min(phugoidAltitudeFromInitial_m);
modePeriodRatio=phugoidDampedPeriod_s/shortPeriodDampedPeriod_s;
isWithinShortPeriodLinearRange= ...
    shortPeriodPeakAlpha_deg<=shortPeriodLinearAlphaLimit_deg;

if shortPeriodDampingRatio==0
    shortPeriodDampingLabel='undamped: amplitude does not decay';
else
    shortPeriodDampingLabel='damped: the short-period envelope decays';
end
if phugoidDampingRatio==0
    phugoidDampingLabel='undamped: speed and path angle keep exchanging';
else
    phugoidDampingLabel='damped: the phugoid envelope decays';
end

out=struct( ...
    'elevatorPulse_deg',elevatorPulse_deg, ...
    'elevatorPulse_rad',elevatorPulse_rad, ...
    'airspeedKick_mps',airspeedKick_mps, ...
    'shortPeriodDampingRatio',shortPeriodDampingRatio, ...
    'phugoidDampingRatio',phugoidDampingRatio, ...
    'fastTime_s',fastTime_s, ...
    'slowTime_s',slowTime_s, ...
    'fastSampleCount',numel(fastTime_s), ...
    'slowSampleCount',numel(slowTime_s), ...
    'shortPeriodAlpha_deg',shortPeriodAlpha_deg, ...
    'shortPeriodPitchRate_deg_s',shortPeriodPitchRate_deg_s, ...
    'shortPeriodAlphaEnvelope_deg',shortPeriodAlphaEnvelope_deg, ...
    'phugoidSpeedPerturbation_mps',phugoidSpeedPerturbation_mps, ...
    'phugoidSpeedRate_mps2',phugoidSpeedRate_mps2, ...
    'phugoidFlightPathAngle_deg',phugoidFlightPathAngle_deg, ...
    'phugoidAltitudeFromInitial_m',phugoidAltitudeFromInitial_m, ...
    'phugoidSpeedEquationResidual_mps2', ...
    phugoidSpeedEquationResidual_mps2, ...
    'shortPeriodNaturalFrequency_rad_s', ...
    shortPeriodNaturalFrequency_rad_s, ...
    'shortPeriodDampedFrequency_rad_s', ...
    shortPeriodDampedFrequency_rad_s, ...
    'shortPeriodDecayRate_per_s',shortPeriodDecayRate_per_s, ...
    'shortPeriodDampedPeriod_s',shortPeriodDampedPeriod_s, ...
    'shortPeriodDecayPerPeriod_ratio', ...
    shortPeriodDecayPerPeriod_ratio, ...
    'phugoidNaturalFrequency_rad_s',phugoidNaturalFrequency_rad_s, ...
    'phugoidDampedFrequency_rad_s',phugoidDampedFrequency_rad_s, ...
    'phugoidDecayRate_per_s',phugoidDecayRate_per_s, ...
    'phugoidDampedPeriod_s',phugoidDampedPeriod_s, ...
    'phugoidDecayPerPeriod_ratio',phugoidDecayPerPeriod_ratio, ...
    'initialPitchRate_rad_s',initialPitchRate_rad_s, ...
    'initialPitchRate_deg_s',initialPitchRate_rad_s*180/pi, ...
    'elevatorMoment_Nm',elevatorMoment_Nm, ...
    'momentScale_Nm',momentScale_Nm, ...
    'dimensionalPitchStiffness_NmPerRad', ...
    dimensionalPitchStiffness_NmPerRad, ...
    'dimensionalElevatorDerivative_NmPerRad', ...
    dimensionalElevatorDerivative_NmPerRad, ...
    'shortPeriodPeakAlpha_deg',shortPeriodPeakAlpha_deg, ...
    'shortPeriodPeakPitchRate_deg_s',shortPeriodPeakPitchRate_deg_s, ...
    'phugoidPeakSpeed_mps',phugoidPeakSpeed_mps, ...
    'phugoidPeakFlightPathAngle_deg', ...
    phugoidPeakFlightPathAngle_deg, ...
    'phugoidAltitudeRange_m',phugoidAltitudeRange_m, ...
    'modePeriodRatio',modePeriodRatio, ...
    'shortPeriodLinearAlphaLimit_deg', ...
    shortPeriodLinearAlphaLimit_deg, ...
    'isWithinShortPeriodLinearRange', ...
    isWithinShortPeriodLinearRange, ...
    'referenceTrueAirspeed_mps',referenceTrueAirspeed_mps, ...
    'referenceDynamicPressure_Pa',referenceDynamicPressure_Pa, ...
    'wingArea_m2',wingArea_m2, ...
    'meanAerodynamicChord_m',meanAerodynamicChord_m, ...
    'referenceStaticMargin_percentMAC', ...
    referenceStaticMargin_percentMAC, ...
    'pitchingMomentSlope_perRad',pitchingMomentSlope_perRad, ...
    'elevatorControlDerivative_perRad', ...
    elevatorControlDerivative_perRad, ...
    'pitchInertia_kgm2',pitchInertia_kgm2, ...
    'elevatorPulseDuration_s',elevatorPulseDuration_s, ...
    'gravity_mps2',gravity_mps2, ...
    'phugoidLiftSpeedGain',phugoidLiftSpeedGain, ...
    'shortPeriodDampingLabel',shortPeriodDampingLabel, ...
    'phugoidDampingLabel',phugoidDampingLabel, ...
    'elevatorConvention','positive elevator is trailing-edge down', ...
    'pitchConvention','positive pitch rate is nose-up', ...
    'shortPeriodKinematicApproximation', ...
    'gamma_dot approximately zero, so alpha_dot approximately q', ...
    'analysisScope',['decoupled linear underdamped teaching modes; ' ...
    'not identified aircraft data or a full longitudinal model']);
end
