function run_checks
%RUN_CHECKS Independent analytic checks for the P06 modal teaching model.
clear model;
tol=1e-10;

%% Determinism, fixed vector shape, and finite resources
first=model(-2,5,0.35,0.08);
second=model(-2,5,0.35,0.08);
assert(isequaln(first,second), ...
    'Identical modal inputs must produce identical outputs.');
assert(first.fastSampleCount==401 && first.slowSampleCount==481, ...
    'Fast and slow response grids must remain fixed and bounded.');
assert(isequal(size(first.fastTime_s),[1 401]) && ...
    isequal(size(first.slowTime_s),[1 481]), ...
    'Time grids must remain fixed row vectors.');

fastFields={'shortPeriodAlpha_deg','shortPeriodPitchRate_deg_s', ...
    'shortPeriodAlphaEnvelope_deg'};
slowFields={'phugoidSpeedPerturbation_mps', ...
    'phugoidSpeedRate_mps2','phugoidFlightPathAngle_deg', ...
    'phugoidAltitudeFromInitial_m', ...
    'phugoidSpeedEquationResidual_mps2'};
scalarFields={'shortPeriodNaturalFrequency_rad_s', ...
    'shortPeriodDampedFrequency_rad_s','shortPeriodDecayRate_per_s', ...
    'shortPeriodDampedPeriod_s','shortPeriodDecayPerPeriod_ratio', ...
    'phugoidNaturalFrequency_rad_s','phugoidDampedFrequency_rad_s', ...
    'phugoidDecayRate_per_s','phugoidDampedPeriod_s', ...
    'phugoidDecayPerPeriod_ratio','initialPitchRate_rad_s', ...
    'elevatorMoment_Nm','momentScale_Nm', ...
    'dimensionalPitchStiffness_NmPerRad', ...
    'dimensionalElevatorDerivative_NmPerRad', ...
    'shortPeriodPeakAlpha_deg','shortPeriodPeakPitchRate_deg_s', ...
    'phugoidPeakSpeed_mps','phugoidPeakFlightPathAngle_deg', ...
    'phugoidAltitudeRange_m','modePeriodRatio', ...
    'shortPeriodLinearAlphaLimit_deg','phugoidLiftSpeedGain'};
for k=1:numel(fastFields)
    value=first.(fastFields{k});
    assert(isequal(size(value),[1 401]) && isreal(value) && ...
        all(isfinite(value)), ...
        'Every fast-mode output must be a finite fixed-size row vector.');
end
for k=1:numel(slowFields)
    value=first.(slowFields{k});
    assert(isequal(size(value),[1 481]) && isreal(value) && ...
        all(isfinite(value)), ...
        'Every slow-mode output must be a finite fixed-size row vector.');
end
for k=1:numel(scalarFields)
    value=first.(scalarFields{k});
    assert(isscalar(value) && isreal(value) && isfinite(value), ...
        'Every modal metric must be a finite real scalar.');
end

edgeElevator_deg=[-5 5];
edgeAirspeed_mps=[-10 10];
edgeShortDamping=[0 0.8];
edgePhugoidDamping=[0 0.3];
edgeCaseCount=0;
for elevatorIndex=1:numel(edgeElevator_deg)
    for airspeedIndex=1:numel(edgeAirspeed_mps)
        for shortIndex=1:numel(edgeShortDamping)
            for phugoidIndex=1:numel(edgePhugoidDamping)
                edge=model(edgeElevator_deg(elevatorIndex), ...
                    edgeAirspeed_mps(airspeedIndex), ...
                    edgeShortDamping(shortIndex), ...
                    edgePhugoidDamping(phugoidIndex));
                edgeCaseCount=edgeCaseCount+1;
                assert(edge.fastSampleCount==401 && ...
                    edge.slowSampleCount==481 && ...
                    edge.isWithinShortPeriodLinearRange && ...
                    edge.shortPeriodPeakAlpha_deg<= ...
                    edge.shortPeriodLinearAlphaLimit_deg, ...
                    'Accepted input corners must preserve response shape.');
                for fieldIndex=1:numel(fastFields)
                    assert(all(isfinite(edge.(fastFields{fieldIndex}))), ...
                        'Accepted corners must keep fast outputs finite.');
                end
                for fieldIndex=1:numel(slowFields)
                    assert(all(isfinite(edge.(slowFields{fieldIndex}))), ...
                        'Accepted corners must keep slow outputs finite.');
                end
            end
        end
    end
end
assert(edgeCaseCount==16,'The accepted-corner grid must stay fixed at 16 cases.');

%% Independent P05-to-P06 baseline buildup
expectedQbar_Pa=1325.00798531847;
expectedWingArea_m2=16.2;
expectedChord_m=1.5;
expectedCmAlpha_perRad=-1.1324;
expectedCmElevator_perRad=-1.3824;
expectedPitchInertia_kgm2=1800;
expectedPulseDuration_s=0.18;
expectedTrueAirspeed_mps=60;
expectedGravity_mps2=9.80665;
expectedShortDamping=0.35;
expectedPhugoidDamping=0.08;
expectedElevator_rad=-2*pi/180;

expectedMomentScale_Nm=expectedQbar_Pa*expectedWingArea_m2* ...
    expectedChord_m;
expectedPitchStiffness_NmPerRad=expectedMomentScale_Nm* ...
    expectedCmAlpha_perRad;
expectedElevatorDerivative_NmPerRad=expectedMomentScale_Nm* ...
    expectedCmElevator_perRad;
expectedShortNatural_rad_s=sqrt(-expectedPitchStiffness_NmPerRad/ ...
    expectedPitchInertia_kgm2);
expectedShortDamped_rad_s=expectedShortNatural_rad_s* ...
    sqrt(1-expectedShortDamping^2);
expectedShortDecay_per_s=expectedShortDamping*expectedShortNatural_rad_s;
expectedShortPeriod_s=2*pi/expectedShortDamped_rad_s;
expectedShortDecayRatio=exp(-expectedShortDecay_per_s* ...
    expectedShortPeriod_s);
expectedElevatorMoment_Nm=expectedElevatorDerivative_NmPerRad* ...
    expectedElevator_rad;
expectedInitialPitchRate_rad_s=expectedElevatorMoment_Nm* ...
    expectedPulseDuration_s/expectedPitchInertia_kgm2;

expectedPhugoidNatural_rad_s=sqrt(2)*expectedGravity_mps2/ ...
    expectedTrueAirspeed_mps;
expectedPhugoidDamped_rad_s=expectedPhugoidNatural_rad_s* ...
    sqrt(1-expectedPhugoidDamping^2);
expectedPhugoidDecay_per_s=expectedPhugoidDamping* ...
    expectedPhugoidNatural_rad_s;
expectedPhugoidPeriod_s=2*pi/expectedPhugoidDamped_rad_s;
expectedPhugoidDecayRatio=exp(-expectedPhugoidDecay_per_s* ...
    expectedPhugoidPeriod_s);

assert(abs(first.momentScale_Nm-expectedMomentScale_Nm)<1e-8 && ...
    abs(first.dimensionalPitchStiffness_NmPerRad- ...
    expectedPitchStiffness_NmPerRad)<1e-8 && ...
    abs(first.dimensionalElevatorDerivative_NmPerRad- ...
    expectedElevatorDerivative_NmPerRad)<1e-8, ...
    'P05 coefficient slopes must scale visibly with qbar*S*cbar.');
assert(abs(first.shortPeriodNaturalFrequency_rad_s- ...
    expectedShortNatural_rad_s)<tol && ...
    abs(first.shortPeriodDampedFrequency_rad_s- ...
    expectedShortDamped_rad_s)<tol && ...
    abs(first.initialPitchRate_rad_s-expectedInitialPitchRate_rad_s)<tol, ...
    'Restoring stiffness, inertia, and elevator impulse must set the fast response.');
assert(abs(first.phugoidNaturalFrequency_rad_s- ...
    expectedPhugoidNatural_rad_s)<tol && ...
    abs(first.phugoidDampedFrequency_rad_s- ...
    expectedPhugoidDamped_rad_s)<tol, ...
    'Gravity and reference speed must set the slow response.');
assert(abs(first.shortPeriodDampedPeriod_s-expectedShortPeriod_s)<tol && ...
    abs(first.shortPeriodDecayPerPeriod_ratio- ...
    expectedShortDecayRatio)<tol && ...
    abs(first.phugoidDampedPeriod_s-expectedPhugoidPeriod_s)<tol && ...
    abs(first.phugoidDecayPerPeriod_ratio- ...
    expectedPhugoidDecayRatio)<tol, ...
    'Periods and exponential decay ratios must follow independent formulas.');
assert(abs(first.shortPeriodNaturalFrequency_rad_s- ...
    4.500658515679408)<1e-12 && ...
    abs(first.shortPeriodDampedPeriod_s-1.490322449109481)<1e-12 && ...
    abs(first.phugoidDampedPeriod_s-27.27028356627409)<1e-11 && ...
    abs(first.modePeriodRatio-18.29824383479497)<1e-11, ...
    'The deterministic modal time-scale separation must remain recognizable.');
assert(first.modePeriodRatio>15 && ...
    first.shortPeriodNaturalFrequency_rad_s> ...
    15*first.phugoidNaturalFrequency_rad_s, ...
    'Short period must remain materially faster than phugoid.');

%% Closed-form response, pole identities, and initial conditions
expectedShortAlpha_rad=expectedInitialPitchRate_rad_s/ ...
    expectedShortDamped_rad_s.*exp(-expectedShortDecay_per_s* ...
    first.fastTime_s).*sin(expectedShortDamped_rad_s*first.fastTime_s);
expectedShortPitchRate_rad_s=expectedInitialPitchRate_rad_s* ...
    exp(-expectedShortDecay_per_s*first.fastTime_s).*( ...
    cos(expectedShortDamped_rad_s*first.fastTime_s)- ...
    expectedShortDecay_per_s/expectedShortDamped_rad_s.* ...
    sin(expectedShortDamped_rad_s*first.fastTime_s));
expectedPhugoidSpeed_mps=5*exp(-expectedPhugoidDecay_per_s* ...
    first.slowTime_s).*(cos(expectedPhugoidDamped_rad_s*first.slowTime_s)- ...
    expectedPhugoidDecay_per_s/expectedPhugoidDamped_rad_s.* ...
    sin(expectedPhugoidDamped_rad_s*first.slowTime_s));
expectedPhugoidSpeedRate_mps2=5*exp(-expectedPhugoidDecay_per_s* ...
    first.slowTime_s).*(-2*expectedPhugoidDecay_per_s* ...
    cos(expectedPhugoidDamped_rad_s*first.slowTime_s)+( ...
    expectedPhugoidDecay_per_s^2/expectedPhugoidDamped_rad_s- ...
    expectedPhugoidDamped_rad_s).* ...
    sin(expectedPhugoidDamped_rad_s*first.slowTime_s));
expectedPhugoidGamma_rad=5*expectedPhugoidNatural_rad_s^2/( ...
    expectedGravity_mps2*expectedPhugoidDamped_rad_s).* ...
    exp(-expectedPhugoidDecay_per_s*first.slowTime_s).* ...
    sin(expectedPhugoidDamped_rad_s*first.slowTime_s);
expectedPhugoidAltitude_m=expectedTrueAirspeed_mps*5/ ...
    expectedGravity_mps2*(1-exp(-expectedPhugoidDecay_per_s* ...
    first.slowTime_s).*(cos(expectedPhugoidDamped_rad_s*first.slowTime_s)+ ...
    expectedPhugoidDecay_per_s/expectedPhugoidDamped_rad_s.* ...
    sin(expectedPhugoidDamped_rad_s*first.slowTime_s)));

assert(max(abs(first.shortPeriodAlpha_deg- ...
    expectedShortAlpha_rad*180/pi))<tol && ...
    max(abs(first.shortPeriodPitchRate_deg_s- ...
    expectedShortPitchRate_rad_s*180/pi))<tol, ...
    'Short-period vectors must match the analytic initial-rate response.');
assert(max(abs(first.phugoidSpeedPerturbation_mps- ...
    expectedPhugoidSpeed_mps))<tol && ...
    max(abs(first.phugoidSpeedRate_mps2- ...
    expectedPhugoidSpeedRate_mps2))<tol && ...
    max(abs(first.phugoidFlightPathAngle_deg- ...
    expectedPhugoidGamma_rad*180/pi))<tol && ...
    max(abs(first.phugoidAltitudeFromInitial_m- ...
    expectedPhugoidAltitude_m))<tol, ...
    'Phugoid vectors must match the analytic speed-displacement response.');
assert(first.shortPeriodAlpha_deg(1)==0 && ...
    abs(first.shortPeriodPitchRate_deg_s(1)- ...
    first.initialPitchRate_deg_s)<tol && ...
    first.phugoidSpeedPerturbation_mps(1)==5 && ...
    abs(first.phugoidSpeedRate_mps2(1)+ ...
    2*first.phugoidDecayRate_per_s*5)<tol && ...
    first.phugoidFlightPathAngle_deg(1)==0 && ...
    first.phugoidAltitudeFromInitial_m(1)==0, ...
    'Modal initial conditions must expose which input excites each response.');
assert(abs(first.shortPeriodDampedFrequency_rad_s^2+ ...
    first.shortPeriodDecayRate_per_s^2- ...
    first.shortPeriodNaturalFrequency_rad_s^2)<tol && ...
    abs(first.phugoidDampedFrequency_rad_s^2+ ...
    first.phugoidDecayRate_per_s^2- ...
    first.phugoidNaturalFrequency_rad_s^2)<tol, ...
    'Each damped frequency and decay rate must recover omega_n squared.');
assert(max(abs(first.phugoidSpeedEquationResidual_mps2))<tol, ...
    'u_dot+2*zeta*omega*u+g*gamma must close for the phugoid view.');
assert(first.phugoidLiftSpeedGain==2, ...
    'The constant-CL phugoid restoring term must retain lift''s V^2 factor.');
slowTimeStep_s=first.slowTime_s(2)-first.slowTime_s(1);
centeredAltitudeRate_mps=(first.phugoidAltitudeFromInitial_m(3:end)- ...
    first.phugoidAltitudeFromInitial_m(1:end-2))/(2*slowTimeStep_s);
kinematicAltitudeRate_mps=first.referenceTrueAirspeed_mps* ...
    first.phugoidFlightPathAngle_deg(2:end-1)*pi/180;
assert(max(abs(kinematicAltitudeRate_mps))>1 && ...
    max(abs(centeredAltitudeRate_mps-kinematicAltitudeRate_mps))<4e-3, ...
    'The altitude history must obey h_dot = V0 gamma on the fixed slow grid.');
assert(abs(first.phugoidAltitudeRange_m-( ...
    max(first.phugoidAltitudeFromInitial_m)- ...
    min(first.phugoidAltitudeFromInitial_m)))<tol && ...
    abs(first.phugoidAltitudeRange_m-54.35696957803992)<1e-11, ...
    'The reported phugoid altitude range must match the signed history.');
assert(abs(first.shortPeriodPeakAlpha_deg-1.256258562150511)<1e-12 && ...
    abs(first.phugoidPeakFlightPathAngle_deg- ...
    5.990827333876157)<1e-12 && ...
    first.isWithinShortPeriodLinearRange, ...
    'Baseline fast and slow peak observables must remain recognizable.');

%% Zero-input isolation and sign symmetry
noElevator=model(0,5,0.35,0.08);
noAirspeed=model(-2,0,0.35,0.08);
noExcitation=model(0,0,0.35,0.08);
assert(all(noElevator.shortPeriodAlpha_deg==0) && ...
    all(noElevator.shortPeriodPitchRate_deg_s==0) && ...
    isequaln(noElevator.phugoidSpeedPerturbation_mps, ...
    first.phugoidSpeedPerturbation_mps), ...
    'Zero elevator pulse must remove only the short-period response.');
assert(all(noAirspeed.phugoidSpeedPerturbation_mps==0) && ...
    all(noAirspeed.phugoidSpeedRate_mps2==0) && ...
    all(noAirspeed.phugoidFlightPathAngle_deg==0) && ...
    all(noAirspeed.phugoidAltitudeFromInitial_m==0) && ...
    isequaln(noAirspeed.shortPeriodAlpha_deg, ...
    first.shortPeriodAlpha_deg), ...
    'Zero airspeed kick must remove only the phugoid response.');
assert(all(noExcitation.shortPeriodAlpha_deg==0) && ...
    all(noExcitation.shortPeriodPitchRate_deg_s==0) && ...
    all(noExcitation.phugoidSpeedPerturbation_mps==0) && ...
    all(noExcitation.phugoidFlightPathAngle_deg==0), ...
    'With both excitation inputs zero, every modal response must be zero.');

positiveElevator=model(2,5,0.35,0.08);
negativeAirspeed=model(-2,-5,0.35,0.08);
assert(max(abs(positiveElevator.shortPeriodAlpha_deg+ ...
    first.shortPeriodAlpha_deg))<tol && ...
    max(abs(positiveElevator.shortPeriodPitchRate_deg_s+ ...
    first.shortPeriodPitchRate_deg_s))<tol && ...
    positiveElevator.initialPitchRate_rad_s<0 && ...
    first.initialPitchRate_rad_s>0, ...
    'Opposite elevator pulses must produce opposite fast responses and signs.');
assert(max(abs(negativeAirspeed.phugoidSpeedPerturbation_mps+ ...
    first.phugoidSpeedPerturbation_mps))<tol && ...
    max(abs(negativeAirspeed.phugoidSpeedRate_mps2+ ...
    first.phugoidSpeedRate_mps2))<tol && ...
    max(abs(negativeAirspeed.phugoidFlightPathAngle_deg+ ...
    first.phugoidFlightPathAngle_deg))<tol && ...
    max(abs(negativeAirspeed.phugoidAltitudeFromInitial_m+ ...
    first.phugoidAltitudeFromInitial_m))<tol && ...
    abs(negativeAirspeed.phugoidAltitudeRange_m- ...
    first.phugoidAltitudeRange_m)<tol && ...
    max(negativeAirspeed.phugoidAltitudeFromInitial_m)==0 && ...
    min(negativeAirspeed.phugoidAltitudeFromInitial_m)<0, ...
    'Opposite airspeed kicks must produce opposite slow responses.');

%% Damping limiting cases and two isolated sweep regressions
undamped=model(-2,5,0,0);
assert(undamped.shortPeriodDecayRate_per_s==0 && ...
    undamped.phugoidDecayRate_per_s==0 && ...
    undamped.shortPeriodDecayPerPeriod_ratio==1 && ...
    undamped.phugoidDecayPerPeriod_ratio==1 && ...
    max(undamped.shortPeriodAlphaEnvelope_deg)- ...
    min(undamped.shortPeriodAlphaEnvelope_deg)<tol, ...
    'Zero damping must preserve each modal envelope.');
assert(all(diff(first.shortPeriodAlphaEnvelope_deg)<=tol) && ...
    first.shortPeriodAlphaEnvelope_deg(end)< ...
    first.shortPeriodAlphaEnvelope_deg(1), ...
    'Positive short-period damping must produce a monotonically decaying envelope.');

shortPeriodDampingSweep=[0.10 0.20 0.35 0.50 0.65];
shortDecay=zeros(size(shortPeriodDampingSweep));
shortPeriods=zeros(size(shortPeriodDampingSweep));
for k=1:numel(shortPeriodDampingSweep)
    sample=model(-2,5,shortPeriodDampingSweep(k),0.08);
    assert(sample.elevatorPulse_deg==-2 && sample.airspeedKick_mps==5 && ...
        sample.phugoidDampingRatio==0.08 && ...
        isequaln(sample.phugoidSpeedPerturbation_mps, ...
        first.phugoidSpeedPerturbation_mps) && ...
        isequaln(sample.phugoidSpeedRate_mps2, ...
        first.phugoidSpeedRate_mps2) && ...
        isequaln(sample.phugoidFlightPathAngle_deg, ...
        first.phugoidFlightPathAngle_deg) && ...
        isequaln(sample.phugoidAltitudeFromInitial_m, ...
        first.phugoidAltitudeFromInitial_m) && ...
        sample.phugoidDampedPeriod_s==first.phugoidDampedPeriod_s && ...
        sample.phugoidDecayPerPeriod_ratio== ...
        first.phugoidDecayPerPeriod_ratio, ...
        'Short-period sweep must hold both excitations and phugoid fixed.');
    shortDecay(k)=sample.shortPeriodDecayPerPeriod_ratio;
    shortPeriods(k)=sample.shortPeriodDampedPeriod_s;
end
assert(all(diff(shortDecay)<0) && all(diff(shortPeriods)>0), ...
    'More short-period damping must reduce decay ratio and lower damped frequency.');

phugoidDampingSweep=[0.00 0.04 0.08 0.12 0.20];
phugoidDecay=zeros(size(phugoidDampingSweep));
phugoidPeriods=zeros(size(phugoidDampingSweep));
for k=1:numel(phugoidDampingSweep)
    sample=model(-2,5,0.35,phugoidDampingSweep(k));
    assert(sample.elevatorPulse_deg==-2 && sample.airspeedKick_mps==5 && ...
        sample.shortPeriodDampingRatio==0.35 && ...
        isequaln(sample.shortPeriodAlpha_deg, ...
        first.shortPeriodAlpha_deg) && ...
        isequaln(sample.shortPeriodPitchRate_deg_s, ...
        first.shortPeriodPitchRate_deg_s) && ...
        isequaln(sample.shortPeriodAlphaEnvelope_deg, ...
        first.shortPeriodAlphaEnvelope_deg) && ...
        sample.shortPeriodDampedPeriod_s== ...
        first.shortPeriodDampedPeriod_s && ...
        sample.shortPeriodDecayPerPeriod_ratio== ...
        first.shortPeriodDecayPerPeriod_ratio, ...
        'Phugoid sweep must hold both excitations and short period fixed.');
    phugoidDecay(k)=sample.phugoidDecayPerPeriod_ratio;
    phugoidPeriods(k)=sample.phugoidDampedPeriod_s;
end
assert(phugoidDecay(1)==1 && all(diff(phugoidDecay)<0) && ...
    all(diff(phugoidPeriods)>0), ...
    'More phugoid damping must reduce decay ratio and lower damped frequency.');

%% Deliberately broken damping sign
brokenWindow=first.fastTime_s<=2.5;
brokenTime_s=first.fastTime_s(brokenWindow);
brokenShortPeriodAlpha_deg=first.initialPitchRate_rad_s/ ...
    first.shortPeriodDampedFrequency_rad_s.* ...
    exp(+first.shortPeriodDecayRate_per_s*brokenTime_s).* ...
    sin(first.shortPeriodDampedFrequency_rad_s*brokenTime_s)*180/pi;
correctWindowPeak_deg=max(abs(first.shortPeriodAlpha_deg(brokenWindow)));
brokenWindowPeak_deg=max(abs(brokenShortPeriodAlpha_deg));
assert(brokenWindowPeak_deg>20*correctWindowPeak_deg && ...
    brokenWindowPeak_deg>50, ...
    'Reversing the damping sign must create an unmistakably growing response.');
assert(abs(brokenWindowPeak_deg-97.30810844411067)<1e-10, ...
    'The broken negative-damping symptom must remain numerically recognizable.');

%% Malformed inputs fail clearly, then a valid call recovers
expectFailure(@() model(-5.1,5,0.35,0.08), ...
    'P06:model:ElevatorPulseRange','elevator pulse below the learning range');
expectFailure(@() model(5.1,5,0.35,0.08), ...
    'P06:model:ElevatorPulseRange','elevator pulse above the learning range');
expectFailure(@() model(-2,-10.1,0.35,0.08), ...
    'P06:model:AirspeedKickRange','airspeed kick below the learning range');
expectFailure(@() model(-2,10.1,0.35,0.08), ...
    'P06:model:AirspeedKickRange','airspeed kick above the learning range');
expectFailure(@() model(-2,5,-0.01,0.08), ...
    'P06:model:NegativeShortPeriodDamping','negative short-period damping');
expectFailure(@() model(-2,5,0.81,0.08), ...
    'P06:model:ShortPeriodDampingRange','short-period damping above range');
expectFailure(@() model(-2,5,0.35,-0.01), ...
    'P06:model:NegativePhugoidDamping','negative phugoid damping');
expectFailure(@() model(-2,5,0.35,0.31), ...
    'P06:model:PhugoidDampingRange','phugoid damping above range');
expectFailure(@() model([-2 -1],5,0.35,0.08),'','nonscalar elevator pulse');
expectFailure(@() model(-2,5+1i,0.35,0.08),'','complex airspeed kick');
expectFailure(@() model(-2,5,NaN,0.08),'','nonfinite short-period damping');
expectFailure(@() model(-2,5,0.35,Inf),'','nonfinite phugoid damping');
afterFailure=model(-2,5,0.35,0.08);
assert(isequaln(afterFailure,first), ...
    'Rejected inputs must not alter the next deterministic calculation.');

disp(['P06 checks passed: modal identities, time scales, damping sweeps, ' ...
    'input isolation, malformed inputs, recovery, and broken damping sign.']);
end

function expectFailure(action,expectedIdentifier,label)
didFail=false;
try
    action();
catch exception
    didFail=true;
    if ~isempty(expectedIdentifier)
        assert(strcmp(exception.identifier,expectedIdentifier), ...
            'Expected %s to raise %s, but received %s.', ...
            label,expectedIdentifier,exception.identifier);
    end
end
assert(didFail,'Expected model to reject %s.',label);
end
