function out=model(trueAirspeed_mps,airDensity_kgpm3,scheduleMode)
%MODEL Deterministic roll-loop gain scheduling across frozen conditions.
% Positive roll angle, roll rate, and equivalent aileron command are right
% wing down. Dynamic pressure scales only the declared control effectiveness.
arguments
    trueAirspeed_mps (1,1) double {mustBeReal,mustBeFinite}=60
    airDensity_kgpm3 (1,1) double {mustBeReal,mustBeFinite}=0.736115547399152
    scheduleMode (1,1) double {mustBeReal,mustBeFinite}=1
end

referenceTrueAirspeed_mps=60;
referenceAirDensity_kgpm3=0.736115547399152;
minimumTrueAirspeed_mps=45;
maximumTrueAirspeed_mps=75;
minimumAirDensity_kgpm3=0.5*referenceAirDensity_kgpm3;
maximumAirDensity_kgpm3=1.5*referenceAirDensity_kgpm3;

if trueAirspeed_mps<minimumTrueAirspeed_mps || ...
        trueAirspeed_mps>maximumTrueAirspeed_mps
    error('P16:model:TrueAirspeedRange', ...
        'True airspeed must be between 45 and 75 m/s inclusive.');
end
if airDensity_kgpm3<minimumAirDensity_kgpm3 || ...
        airDensity_kgpm3>maximumAirDensity_kgpm3
    error('P16:model:AirDensityRange', ...
        ['Air density must be between 0.5 and 1.5 times the declared ' ...
        'reference density inclusive.']);
end
if scheduleMode~=1 && scheduleMode~=0 && scheduleMode~=-1
    error('P16:model:ScheduleMode', ...
        ['Schedule mode must be +1 for dynamic-pressure scheduling, 0 for ' ...
        'fixed reference gains, or -1 for the broken true-airspeed-only lookup.']);
end

sampleTime_s=0.01;
timeHorizon_s=8;
time_s=0:sampleTime_s:timeHorizon_s;
sampleCount=numel(time_s);
commandStepTime_s=0.5;
rollCommandStep_deg=10;
rollCommandStep_rad=deg2rad(rollCommandStep_deg);
aileronCommandLimit_deg=15;
aileronCommandLimit_rad=deg2rad(aileronCommandLimit_deg);

referenceDynamicPressure_Pa=0.5*referenceAirDensity_kgpm3* ...
    referenceTrueAirspeed_mps^2;
actualDynamicPressure_Pa=0.5*airDensity_kgpm3*trueAirspeed_mps^2;
actualDynamicPressureRatio= ...
    actualDynamicPressure_Pa/referenceDynamicPressure_Pa;

% The plant is a transparent roll double integrator whose equivalent
% aileron-to-roll-acceleration effectiveness scales with qbar.
referenceControlEffectiveness_per_s2=12;
actualControlEffectiveness_per_s2= ...
    referenceControlEffectiveness_per_s2*actualDynamicPressureRatio;
targetNaturalFrequency_radps=2.4;
targetDampingRatio=0.8;

% The five entries are exact pole-placement gains at their knots. Manual
% bracketing and linear interpolation keep lookup mechanics visible.
dynamicPressureRatioKnots=[0.5 0.75 1 1.25 1.5];
rollAngleGainTable=targetNaturalFrequency_radps^2./( ...
    referenceControlEffectiveness_per_s2*dynamicPressureRatioKnots);
rollRateGainTable_s=2*targetDampingRatio*targetNaturalFrequency_radps./( ...
    referenceControlEffectiveness_per_s2*dynamicPressureRatioKnots);

if scheduleMode==1
    lookupDynamicPressureRatioRaw=actualDynamicPressureRatio;
    scheduleSource='computed dynamic pressure from declared rho and V';
elseif scheduleMode==0
    lookupDynamicPressureRatioRaw=1;
    scheduleSource='fixed reference gains at qbar/qbar_ref=1';
else
    % Deliberately broken: true airspeed alone is treated as though it
    % uniquely determined dynamic pressure. Density is omitted only here.
    lookupDynamicPressureRatioRaw= ...
        (trueAirspeed_mps/referenceTrueAirspeed_mps)^2;
    scheduleSource='BROKEN true-airspeed-only ratio; density omitted';
end

lookupDynamicPressureRatio=min(max(lookupDynamicPressureRatioRaw, ...
    dynamicPressureRatioKnots(1)),dynamicPressureRatioKnots(end));
lookupClamped=lookupDynamicPressureRatio~=lookupDynamicPressureRatioRaw;
upperKnotIndex=find(dynamicPressureRatioKnots>= ...
    lookupDynamicPressureRatio,1,'first');
if upperKnotIndex==1
    lowerKnotIndex=1;
    interpolationWeight=0;
else
    lowerKnotIndex=upperKnotIndex-1;
    interpolationWeight=(lookupDynamicPressureRatio- ...
        dynamicPressureRatioKnots(lowerKnotIndex))/( ...
        dynamicPressureRatioKnots(upperKnotIndex)- ...
        dynamicPressureRatioKnots(lowerKnotIndex));
end

rollAngleGain=(1-interpolationWeight)* ...
    rollAngleGainTable(lowerKnotIndex)+interpolationWeight* ...
    rollAngleGainTable(upperKnotIndex);
rollRateGain_s=(1-interpolationWeight)* ...
    rollRateGainTable_s(lowerKnotIndex)+interpolationWeight* ...
    rollRateGainTable_s(upperKnotIndex);
idealRollAngleGain=targetNaturalFrequency_radps^2/( ...
    referenceControlEffectiveness_per_s2*lookupDynamicPressureRatio);
idealRollRateGain_s=2*targetDampingRatio*targetNaturalFrequency_radps/( ...
    referenceControlEffectiveness_per_s2*lookupDynamicPressureRatio);
rollAngleGainInterpolationErrorFraction= ...
    (rollAngleGain-idealRollAngleGain)/idealRollAngleGain;
rollRateGainInterpolationErrorFraction= ...
    (rollRateGain_s-idealRollRateGain_s)/idealRollRateGain_s;
actualConditionIdealRollAngleGain=targetNaturalFrequency_radps^2/( ...
    referenceControlEffectiveness_per_s2*actualDynamicPressureRatio);
actualConditionIdealRollRateGain_s= ...
    2*targetDampingRatio*targetNaturalFrequency_radps/( ...
    referenceControlEffectiveness_per_s2*actualDynamicPressureRatio);
rollAngleGainActualConditionMismatchFraction= ...
    (rollAngleGain-actualConditionIdealRollAngleGain)/ ...
    actualConditionIdealRollAngleGain;
rollRateGainActualConditionMismatchFraction= ...
    (rollRateGain_s-actualConditionIdealRollRateGain_s)/ ...
    actualConditionIdealRollRateGain_s;

rollCommand_rad=rollCommandStep_rad*double(time_s>=commandStepTime_s);
rollAngle_rad=zeros(1,sampleCount);
rollRate_radps=zeros(1,sampleCount);
rollError_rad=zeros(1,sampleCount);
aileronCommandUnclamped_rad=zeros(1,sampleCount);
aileronCommand_rad=zeros(1,sampleCount);
rollAcceleration_radps2=zeros(1,sampleCount);

for k=1:sampleCount
    rollError_rad(k)=rollCommand_rad(k)-rollAngle_rad(k);
    aileronCommandUnclamped_rad(k)=rollAngleGain*rollError_rad(k)- ...
        rollRateGain_s*rollRate_radps(k);
    aileronCommand_rad(k)=min(max(aileronCommandUnclamped_rad(k), ...
        -aileronCommandLimit_rad),aileronCommandLimit_rad);
    rollAcceleration_radps2(k)= ...
        actualControlEffectiveness_per_s2*aileronCommand_rad(k);

    % Fixed-step forward Euler makes every transition reconstructable.
    if k<sampleCount
        rollAngle_rad(k+1)=rollAngle_rad(k)+ ...
            sampleTime_s*rollRate_radps(k);
        rollRate_radps(k+1)=rollRate_radps(k)+ ...
            sampleTime_s*rollAcceleration_radps2(k);
    end
end

aileronCommandSaturated= ...
    abs(aileronCommandUnclamped_rad)>aileronCommandLimit_rad;
activeMask=time_s>=commandStepTime_s;
activeSampleCount=sum(activeMask);
rollError_deg=rad2deg(rollError_rad);
rollTrackingRMS_deg=sqrt(mean(rollError_deg(activeMask).^2));
finalRollError_deg=rollError_deg(end);
peakRollOvershoot_deg=max(max(rad2deg(rollAngle_rad(activeMask)))- ...
    rollCommandStep_deg,0);
captureTolerance_deg=0.1*rollCommandStep_deg;
captureIndex=find(activeMask & abs(rollError_deg)<=captureTolerance_deg, ...
    1,'first');
if isempty(captureIndex)
    reachedNinetyPercent=false;
    timeToNinetyPercent_s=timeHorizon_s-commandStepTime_s;
else
    reachedNinetyPercent=true;
    timeToNinetyPercent_s=time_s(captureIndex)-commandStepTime_s;
end
settlingTolerance_deg=0.02*rollCommandStep_deg;
settledByEnd=abs(finalRollError_deg)<=settlingTolerance_deg;
outsideTolerance=find(activeMask & ...
    abs(rollError_deg)>settlingTolerance_deg,1,'last');
if settledByEnd && ~isempty(outsideTolerance) && outsideTolerance<sampleCount
    settlingTime_s=time_s(outsideTolerance+1)-commandStepTime_s;
elseif settledByEnd && isempty(outsideTolerance)
    settlingTime_s=0;
else
    settlingTime_s=timeHorizon_s-commandStepTime_s;
end

effectiveNaturalFrequency_radps=sqrt( ...
    actualControlEffectiveness_per_s2*rollAngleGain);
effectiveDampingRatio=actualControlEffectiveness_per_s2* ...
    rollRateGain_s/(2*effectiveNaturalFrequency_radps);

out=struct( ...
    'trueAirspeed_mps',trueAirspeed_mps, ...
    'airDensity_kgpm3',airDensity_kgpm3, ...
    'scheduleMode',scheduleMode, ...
    'sampleTime_s',sampleTime_s, ...
    'timeHorizon_s',timeHorizon_s, ...
    'time_s',time_s, ...
    'sampleCount',sampleCount, ...
    'intervalCount',sampleCount-1, ...
    'activeSampleCount',activeSampleCount, ...
    'commandStepTime_s',commandStepTime_s, ...
    'rollCommandStep_deg',rollCommandStep_deg, ...
    'aileronCommandLimit_deg',aileronCommandLimit_deg, ...
    'referenceTrueAirspeed_mps',referenceTrueAirspeed_mps, ...
    'referenceAirDensity_kgpm3',referenceAirDensity_kgpm3, ...
    'minimumTrueAirspeed_mps',minimumTrueAirspeed_mps, ...
    'maximumTrueAirspeed_mps',maximumTrueAirspeed_mps, ...
    'minimumAirDensity_kgpm3',minimumAirDensity_kgpm3, ...
    'maximumAirDensity_kgpm3',maximumAirDensity_kgpm3, ...
    'referenceDynamicPressure_Pa',referenceDynamicPressure_Pa, ...
    'actualDynamicPressure_Pa',actualDynamicPressure_Pa, ...
    'actualDynamicPressureRatio',actualDynamicPressureRatio, ...
    'referenceControlEffectiveness_per_s2', ...
    referenceControlEffectiveness_per_s2, ...
    'actualControlEffectiveness_per_s2', ...
    actualControlEffectiveness_per_s2, ...
    'targetNaturalFrequency_radps',targetNaturalFrequency_radps, ...
    'targetDampingRatio',targetDampingRatio, ...
    'dynamicPressureRatioKnots',dynamicPressureRatioKnots, ...
    'rollAngleGainTable',rollAngleGainTable, ...
    'rollRateGainTable_s',rollRateGainTable_s, ...
    'lookupDynamicPressureRatioRaw',lookupDynamicPressureRatioRaw, ...
    'lookupDynamicPressureRatio',lookupDynamicPressureRatio, ...
    'lookupClamped',lookupClamped, ...
    'lowerKnotIndex',lowerKnotIndex, ...
    'upperKnotIndex',upperKnotIndex, ...
    'interpolationWeight',interpolationWeight, ...
    'scheduleSource',scheduleSource, ...
    'rollAngleGain',rollAngleGain, ...
    'rollRateGain_s',rollRateGain_s, ...
    'idealRollAngleGain',idealRollAngleGain, ...
    'idealRollRateGain_s',idealRollRateGain_s, ...
    'rollAngleGainInterpolationErrorFraction', ...
    rollAngleGainInterpolationErrorFraction, ...
    'rollRateGainInterpolationErrorFraction', ...
    rollRateGainInterpolationErrorFraction, ...
    'actualConditionIdealRollAngleGain', ...
    actualConditionIdealRollAngleGain, ...
    'actualConditionIdealRollRateGain_s', ...
    actualConditionIdealRollRateGain_s, ...
    'rollAngleGainActualConditionMismatchFraction', ...
    rollAngleGainActualConditionMismatchFraction, ...
    'rollRateGainActualConditionMismatchFraction', ...
    rollRateGainActualConditionMismatchFraction, ...
    'rollCommand_deg',rad2deg(rollCommand_rad), ...
    'rollAngle_deg',rad2deg(rollAngle_rad), ...
    'rollRate_degps',rad2deg(rollRate_radps), ...
    'rollError_deg',rollError_deg, ...
    'aileronCommandUnclamped_deg', ...
    rad2deg(aileronCommandUnclamped_rad), ...
    'aileronCommand_deg',rad2deg(aileronCommand_rad), ...
    'rollAcceleration_degps2',rad2deg(rollAcceleration_radps2), ...
    'aileronCommandSaturated',aileronCommandSaturated, ...
    'aileronCommandSaturationFraction', ...
    sum(aileronCommandSaturated)/sampleCount, ...
    'rollTrackingRMS_deg',rollTrackingRMS_deg, ...
    'finalRollError_deg',finalRollError_deg, ...
    'peakRollOvershoot_deg',peakRollOvershoot_deg, ...
    'captureTolerance_deg',captureTolerance_deg, ...
    'reachedNinetyPercent',reachedNinetyPercent, ...
    'timeToNinetyPercent_s',timeToNinetyPercent_s, ...
    'settlingTolerance_deg',settlingTolerance_deg, ...
    'settledByEnd',settledByEnd, ...
    'settlingTime_s',settlingTime_s, ...
    'peakAbsoluteRollRate_degps',max(abs(rad2deg(rollRate_radps))), ...
    'peakAbsoluteAileronCommand_deg', ...
    max(abs(rad2deg(aileronCommand_rad))), ...
    'effectiveNaturalFrequency_radps', ...
    effectiveNaturalFrequency_radps, ...
    'effectiveDampingRatio',effectiveDampingRatio, ...
    'scheduleEquation',[ ...
        'qbar=0.5*rho*V^2; b=b_ref*qbar/qbar_ref; ' ...
        'linearly interpolate K_phi and K_p versus clamped qbar/qbar_ref'], ...
    'controllerEquation',[ ...
        'delta_a=sat(K_phi*(phi_command-phi)-K_p*p,+/-delta_max)'], ...
    'plantEquation','phi_dot=p; p_dot=b(qbar)*delta_a', ...
    'brokenCaseDefinition',[ ...
        'scheduleMode=-1 omits density and looks up gains with (V/V_ref)^2; ' ...
        'equal-qbar conditions can then receive different gains'], ...
    'analysisScope',[ ...
        'deterministic frozen-condition reduced-order roll teaching model; ' ...
        'dynamic pressure scales only equivalent control effectiveness; no ' ...
        'Mach, Reynolds number, mass, CG, configuration, actuator, sensor, ' ...
        'robustness-margin, full-aircraft, certification, hardware, HIL, or field fidelity']);
end
