function run_checks
%RUN_CHECKS P16 independent gain-table, roll-loop, and recovery checks.
clear model;
modelFcn=@model;
absoluteTolerance=1e-11;
trajectoryTolerance=1e-10;
referenceDensity=0.736115547399152;

%% Deterministic baseline identity, resources, and signed references
baseline=modelFcn(60,referenceDensity,1);
repeat=modelFcn(60,referenceDensity,1);
historyFields={'time_s','rollCommand_deg','rollAngle_deg', ...
    'rollRate_degps','rollError_deg','aileronCommandUnclamped_deg', ...
    'aileronCommand_deg','rollAcceleration_degps2'};
for k=1:numel(historyFields)
    field=historyFields{k};
    assert(isequal(baseline.(field),repeat.(field)), ...
        ['Repeated baseline calls must exactly reproduce ' field '.']);
end
assert(baseline.sampleCount==801 && baseline.intervalCount==800 && ...
    baseline.activeSampleCount==751 && ...
    isequal(size(baseline.time_s),[1 801]) && ...
    baseline.sampleTime_s==0.01 && baseline.timeHorizon_s==8 && ...
    baseline.commandStepTime_s==0.5, ...
    'The baseline grid and resource counts must stay fixed.');
assert(baseline.trueAirspeed_mps==60 && ...
    baseline.airDensity_kgpm3==referenceDensity && ...
    baseline.scheduleMode==1 && ...
    baseline.rollCommandStep_deg==10 && ...
    baseline.aileronCommandLimit_deg==15, ...
    'The baseline condition, mode, step, and command envelope changed.');

%% Independent dynamic-pressure, table, bracket, and gain reconstruction
expectedReferenceQ_Pa=0.5*referenceDensity*60^2;
expectedActualQ_Pa=0.5*baseline.airDensity_kgpm3* ...
    baseline.trueAirspeed_mps^2;
expectedRatio=expectedActualQ_Pa/expectedReferenceQ_Pa;
expectedKnots=[0.5 0.75 1 1.25 1.5];
expectedAngleTable=2.4^2./(12*expectedKnots);
expectedRateTable=2*0.8*2.4./(12*expectedKnots);
assert(abs(baseline.referenceDynamicPressure_Pa- ...
    expectedReferenceQ_Pa)<absoluteTolerance && ...
    abs(baseline.actualDynamicPressure_Pa-expectedActualQ_Pa)< ...
    absoluteTolerance && ...
    abs(baseline.actualDynamicPressureRatio-expectedRatio)< ...
    absoluteTolerance, ...
    'Dynamic pressure and its normalized plant condition must close independently.');
assert(isequal(baseline.dynamicPressureRatioKnots,expectedKnots) && ...
    max(abs(baseline.rollAngleGainTable-expectedAngleTable))< ...
    absoluteTolerance && ...
    max(abs(baseline.rollRateGainTable_s-expectedRateTable))< ...
    absoluteTolerance && all(diff(baseline.rollAngleGainTable)<0) && ...
    all(diff(baseline.rollRateGainTable_s)<0), ...
    'The ordered five-knot inverse-effectiveness gain tables changed.');

[expectedLookup,expectedClamped,expectedLower,expectedUpper, ...
    expectedWeight,expectedAngleGain,expectedRateGain]= ...
    independentLookup(expectedRatio,expectedKnots,expectedAngleTable, ...
    expectedRateTable);
assert(baseline.lookupDynamicPressureRatioRaw==expectedRatio && ...
    baseline.lookupDynamicPressureRatio==expectedLookup && ...
    baseline.lookupClamped==expectedClamped && ...
    baseline.lowerKnotIndex==expectedLower && ...
    baseline.upperKnotIndex==expectedUpper && ...
    baseline.interpolationWeight==expectedWeight && ...
    abs(baseline.rollAngleGain-expectedAngleGain)<absoluteTolerance && ...
    abs(baseline.rollRateGain_s-expectedRateGain)<absoluteTolerance, ...
    'Raw lookup, endpoint hold, bracket, weight, or interpolated gains changed.');
assert(abs(baseline.idealRollAngleGain-2.4^2/(12*expectedLookup))< ...
    absoluteTolerance && ...
    abs(baseline.idealRollRateGain_s-2*0.8*2.4/(12*expectedLookup))< ...
    absoluteTolerance && ...
    baseline.rollAngleGainInterpolationErrorFraction==0 && ...
    baseline.rollRateGainInterpolationErrorFraction==0, ...
    'The center knot must equal the independent analytic gains exactly.');
assert(abs(baseline.actualControlEffectiveness_per_s2- ...
    12*expectedRatio)<absoluteTolerance, ...
    'Only actual dynamic pressure may scale the declared plant effectiveness.');

% A fractional point checks the interpolation calculation rather than only
% exact knots. Because correct mode uses actual qbar for lookup, its
% selected-versus-actual mismatch equals its table approximation error.
midpoint=modelFcn(60,0.875*referenceDensity,1);
expectedMidpointAngleGain=0.5*(expectedAngleTable(2)+ ...
    expectedAngleTable(3));
expectedMidpointRateGain=0.5*(expectedRateTable(2)+ ...
    expectedRateTable(3));
assert(abs(midpoint.actualDynamicPressureRatio-0.875)< ...
    absoluteTolerance && midpoint.lowerKnotIndex==2 && ...
    midpoint.upperKnotIndex==3 && ...
    abs(midpoint.interpolationWeight-0.5)<absoluteTolerance && ...
    abs(midpoint.rollAngleGain-expectedMidpointAngleGain)< ...
    absoluteTolerance && ...
    abs(midpoint.rollRateGain_s-expectedMidpointRateGain)< ...
    absoluteTolerance && ...
    midpoint.rollAngleGainInterpolationErrorFraction>0 && ...
    midpoint.rollRateGainInterpolationErrorFraction>0 && ...
    abs(midpoint.rollAngleGainInterpolationErrorFraction- ...
    midpoint.rollRateGainInterpolationErrorFraction)<absoluteTolerance && ...
    abs(midpoint.rollAngleGainActualConditionMismatchFraction- ...
    midpoint.rollAngleGainInterpolationErrorFraction)<absoluteTolerance && ...
    abs(midpoint.rollRateGainActualConditionMismatchFraction- ...
    midpoint.rollRateGainInterpolationErrorFraction)<absoluteTolerance, ...
    'The midpoint must independently close its bracket, weight, gains, and interpolation error.');

%% Independent controller, saturation, plant, and every Euler update
rollCommand_rad=deg2rad(baseline.rollCommand_deg);
rollAngle_rad=deg2rad(baseline.rollAngle_deg);
rollRate_radps=deg2rad(baseline.rollRate_degps);
expectedError_rad=rollCommand_rad-rollAngle_rad;
expectedUnclamped_rad=baseline.rollAngleGain*expectedError_rad- ...
    baseline.rollRateGain_s*rollRate_radps;
limit_rad=deg2rad(baseline.aileronCommandLimit_deg);
expectedControl_rad=min(max(expectedUnclamped_rad,-limit_rad),limit_rad);
expectedAcceleration_radps2= ...
    baseline.actualControlEffectiveness_per_s2*expectedControl_rad;
assert(max(abs(rad2deg(expectedError_rad)-baseline.rollError_deg))< ...
    trajectoryTolerance && ...
    max(abs(rad2deg(expectedUnclamped_rad)- ...
    baseline.aileronCommandUnclamped_deg))<trajectoryTolerance && ...
    max(abs(rad2deg(expectedControl_rad)- ...
    baseline.aileronCommand_deg))<trajectoryTolerance && ...
    max(abs(rad2deg(expectedAcceleration_radps2)- ...
    baseline.rollAcceleration_degps2))<trajectoryTolerance, ...
    'Error, feedback, saturation, or roll acceleration failed reconstruction.');
assert(isequal(abs(expectedUnclamped_rad)>limit_rad, ...
    baseline.aileronCommandSaturated) && ...
    baseline.aileronCommandSaturationFraction==0 && ...
    max(abs(baseline.aileronCommand_deg))<= ...
    baseline.aileronCommandLimit_deg, ...
    'Equivalent aileron saturation flags and envelope must remain exact.');

expectedNextAngle=rollAngle_rad(1:end-1)+ ...
    baseline.sampleTime_s*rollRate_radps(1:end-1);
expectedNextRate=rollRate_radps(1:end-1)+ ...
    baseline.sampleTime_s*expectedAcceleration_radps2(1:end-1);
assert(max(abs(rollAngle_rad(2:end)-expectedNextAngle))< ...
    trajectoryTolerance && ...
    max(abs(rollRate_radps(2:end)-expectedNextRate))< ...
    trajectoryTolerance, ...
    'Every retained roll-angle and roll-rate update must obey forward Euler.');

%% Command-onset causality and independently derived baseline metrics
commandIndex=find(baseline.time_s>=baseline.commandStepTime_s,1,'first');
assert(all(baseline.rollCommand_deg(1:commandIndex-1)==0) && ...
    all(baseline.rollAngle_deg(1:commandIndex)==0) && ...
    all(baseline.rollRate_degps(1:commandIndex)==0) && ...
    all(baseline.aileronCommand_deg(1:commandIndex-1)==0) && ...
    baseline.rollCommand_deg(commandIndex)==10 && ...
    abs(baseline.aileronCommand_deg(commandIndex)-4.8)< ...
    absoluteTolerance && ...
    baseline.rollAcceleration_degps2(commandIndex)>0 && ...
    baseline.rollRate_degps(commandIndex+1)>0 && ...
    baseline.rollAngle_deg(commandIndex+1)==0 && ...
    baseline.rollAngle_deg(commandIndex+2)>0, ...
    'Request, acceleration, rate, and angle must move in causal sample order.');

activeMask=baseline.time_s>=baseline.commandStepTime_s;
expectedRMS=sqrt(mean(baseline.rollError_deg(activeMask).^2));
expectedCaptureIndex=find(activeMask & ...
    abs(baseline.rollError_deg)<=1,1,'first');
expectedCaptureTime=baseline.time_s(expectedCaptureIndex)- ...
    baseline.commandStepTime_s;
expectedOutside=find(activeMask & ...
    abs(baseline.rollError_deg)>0.2,1,'last');
expectedSettlingTime=baseline.time_s(expectedOutside+1)- ...
    baseline.commandStepTime_s;
expectedOvershoot=max(max(baseline.rollAngle_deg(activeMask))-10,0);
assert(abs(baseline.rollTrackingRMS_deg-expectedRMS)< ...
    trajectoryTolerance && baseline.reachedNinetyPercent && ...
    abs(baseline.timeToNinetyPercent_s-expectedCaptureTime)< ...
    absoluteTolerance && baseline.settledByEnd && ...
    abs(baseline.settlingTime_s-expectedSettlingTime)< ...
    absoluteTolerance && ...
    abs(baseline.peakRollOvershoot_deg-expectedOvershoot)< ...
    trajectoryTolerance && ...
    abs(baseline.timeToNinetyPercent_s-1.23)<absoluteTolerance && ...
    abs(baseline.settlingTime_s-1.55)<absoluteTolerance && ...
    abs(baseline.peakRollOvershoot_deg-0.1615456758015)<1e-10 && ...
    abs(baseline.finalRollError_deg+0.000006924730282520386)<1e-10, ...
    'Baseline capture, settling, overshoot, RMS, or final error changed.');
assert(abs(baseline.effectiveNaturalFrequency_radps-2.4)< ...
    absoluteTolerance && ...
    abs(baseline.effectiveDampingRatio-0.8)<absoluteTolerance, ...
    'Center-knot closed-loop coefficients must match the targets.');

%% Reference fixed-gain limit and equal-dynamic-pressure invariance
fixedReference=modelFcn(60,referenceDensity,0);
assert(fixedReference.lookupDynamicPressureRatioRaw==1 && ...
    fixedReference.lookupDynamicPressureRatio==1 && ...
    fixedReference.rollAngleGain==baseline.rollAngleGain && ...
    fixedReference.rollRateGain_s==baseline.rollRateGain_s && ...
    isequal(fixedReference.rollAngle_deg,baseline.rollAngle_deg) && ...
    isequal(fixedReference.rollRate_degps,baseline.rollRate_degps) && ...
    isequal(fixedReference.aileronCommand_deg, ...
    baseline.aileronCommand_deg), ...
    'Scheduled and fixed modes must coincide at the reference knot.');

pairedAirspeed=75;
pairedDensity=referenceDensity*(60/pairedAirspeed)^2;
equalQ=modelFcn(pairedAirspeed,pairedDensity,1);
assert(abs(equalQ.actualDynamicPressure_Pa- ...
    baseline.actualDynamicPressure_Pa)<1e-9 && ...
    abs(equalQ.actualControlEffectiveness_per_s2- ...
    baseline.actualControlEffectiveness_per_s2)<absoluteTolerance && ...
    max(abs(equalQ.rollAngle_deg-baseline.rollAngle_deg))< ...
    trajectoryTolerance && ...
    max(abs(equalQ.rollRate_degps-baseline.rollRate_degps))< ...
    trajectoryTolerance && ...
    max(abs(equalQ.aileronCommand_deg-baseline.aileronCommand_deg))< ...
    trajectoryTolerance, ...
    'Equal actual dynamic pressure must produce equal correct-schedule histories.');

%% Lever 1: true-airspeed sweep with density and comparison isolated
airspeedSweep_mps=[45 52.5 60 67.5 72];
scheduledSettling_s=zeros(size(airspeedSweep_mps));
fixedSettling_s=zeros(size(airspeedSweep_mps));
scheduledOvershoot_deg=zeros(size(airspeedSweep_mps));
fixedOvershoot_deg=zeros(size(airspeedSweep_mps));
scheduledPeakAileron_deg=zeros(size(airspeedSweep_mps));
for k=1:numel(airspeedSweep_mps)
    scheduled=modelFcn(airspeedSweep_mps(k),referenceDensity,1);
    fixed=modelFcn(airspeedSweep_mps(k),referenceDensity,0);
    scheduledSettling_s(k)=scheduled.settlingTime_s;
    fixedSettling_s(k)=fixed.settlingTime_s;
    scheduledOvershoot_deg(k)=scheduled.peakRollOvershoot_deg;
    fixedOvershoot_deg(k)=fixed.peakRollOvershoot_deg;
    scheduledPeakAileron_deg(k)= ...
        scheduled.peakAbsoluteAileronCommand_deg;
    assert(abs(scheduledPeakAileron_deg(k)- ...
        max(abs(scheduled.aileronCommand_deg)))<absoluteTolerance, ...
        'Reported airspeed-sweep peak demand must match its control history.');
    assert(scheduled.airDensity_kgpm3==referenceDensity && ...
        fixed.airDensity_kgpm3==referenceDensity && ...
        scheduled.scheduleMode==1 && fixed.scheduleMode==0 && ...
        isequal(scheduled.time_s,baseline.time_s) && ...
        isequal(scheduled.rollCommand_deg,baseline.rollCommand_deg), ...
        'The airspeed sweep changed density, mode, grid, or command.');
end
assert(max(scheduledSettling_s)-min(scheduledSettling_s)<=0.02 && ...
    max(fixedSettling_s)-min(fixedSettling_s)>1.5 && ...
    all(diff(scheduledPeakAileron_deg)<0) && ...
    abs(scheduledPeakAileron_deg(1)-8.8)<1e-10 && ...
    abs(scheduledPeakAileron_deg(end)-3.3536)<1e-10 && ...
    abs(fixedSettling_s(1)-3.29)<absoluteTolerance && ...
    fixedOvershoot_deg(1)>scheduledOvershoot_deg(1)+0.8, ...
    'Airspeed scheduling must preserve timing and expose gain/control tradeoffs.');

%% Lever 2: density sweep lands on exact table knots
densityRatioSweep=[0.5 0.75 1 1.25 1.5];
peakAileronByDensity_deg=zeros(size(densityRatioSweep));
for k=1:numel(densityRatioSweep)
    sample=modelFcn(60,referenceDensity*densityRatioSweep(k),1);
    assert(abs(sample.actualDynamicPressureRatio-densityRatioSweep(k))< ...
        absoluteTolerance && ~sample.lookupClamped && ...
        abs(sample.actualControlEffectiveness_per_s2* ...
        sample.rollAngleGain-2.4^2)<trajectoryTolerance && ...
        abs(sample.actualControlEffectiveness_per_s2* ...
        sample.rollRateGain_s-2*0.8*2.4)<trajectoryTolerance && ...
        abs(sample.effectiveNaturalFrequency_radps-2.4)< ...
        trajectoryTolerance && ...
        abs(sample.effectiveDampingRatio-0.8)<trajectoryTolerance && ...
        max(abs(sample.rollAngle_deg-baseline.rollAngle_deg))< ...
        trajectoryTolerance && ...
        max(abs(sample.rollRate_degps-baseline.rollRate_degps))< ...
        trajectoryTolerance, ...
        'Every density knot must close to the target poles and baseline states.');
    peakAileronByDensity_deg(k)=sample.peakAbsoluteAileronCommand_deg;
    assert(abs(peakAileronByDensity_deg(k)- ...
        max(abs(sample.aileronCommand_deg)))<absoluteTolerance, ...
        'Reported density-sweep peak demand must match its control history.');
end
assert(all(diff(peakAileronByDensity_deg)<0) && ...
    abs(peakAileronByDensity_deg(1)-9.6)<absoluteTolerance && ...
    abs(peakAileronByDensity_deg(end)-3.2)<absoluteTolerance, ...
    'Density-knot compensation must reduce command demand monotonically.');

%% Broken TAS-only lookup, failure isolation, rollback, and recovery
broken=modelFcn(pairedAirspeed,pairedDensity,-1);
assert(abs(broken.actualDynamicPressure_Pa-equalQ.actualDynamicPressure_Pa)< ...
    absoluteTolerance && ...
    broken.actualControlEffectiveness_per_s2== ...
    equalQ.actualControlEffectiveness_per_s2 && ...
    isequal(broken.time_s,equalQ.time_s) && ...
    isequal(broken.rollCommand_deg,equalQ.rollCommand_deg) && ...
    broken.aileronCommandLimit_deg==equalQ.aileronCommandLimit_deg && ...
    max(abs(broken.rollAngle_deg(1:commandIndex)- ...
    equalQ.rollAngle_deg(1:commandIndex)))==0 && ...
    max(abs(broken.rollRate_degps(1:commandIndex)- ...
    equalQ.rollRate_degps(1:commandIndex)))==0, ...
    'The broken case may change only schedule lookup, not plant, grid, command, limit, or onset states.');
assert(abs(broken.lookupDynamicPressureRatioRaw-1.5625)< ...
    absoluteTolerance && broken.lookupDynamicPressureRatio==1.5 && ...
    broken.lookupClamped && broken.lowerKnotIndex==4 && ...
    broken.upperKnotIndex==5 && broken.interpolationWeight==1 && ...
    abs(broken.rollAngleGain-0.32)<absoluteTolerance && ...
    abs(broken.rollRateGain_s-0.2133333333333333)< ...
    absoluteTolerance && ...
    broken.aileronCommand_deg(commandIndex)< ...
    equalQ.aileronCommand_deg(commandIndex), ...
    'The TAS-only raw lookup must hold the high endpoint and under-command the unchanged plant.');
assert(abs(broken.actualConditionIdealRollAngleGain-0.48)< ...
    absoluteTolerance && ...
    abs(broken.actualConditionIdealRollRateGain_s-0.32)< ...
    absoluteTolerance && ...
    abs(broken.rollAngleGainActualConditionMismatchFraction+1/3)< ...
    absoluteTolerance && ...
    abs(broken.rollRateGainActualConditionMismatchFraction+1/3)< ...
    absoluteTolerance, ...
    'The broken lookup must expose a one-third gain shortfall versus the actual-condition ideal.');
assert(abs(broken.effectiveNaturalFrequency_radps- ...
    1.959591794226543)<1e-10 && ...
    abs(broken.effectiveDampingRatio-0.653197264742181)<1e-10 && ...
    abs(broken.settlingTime_s-3.06)<absoluteTolerance && ...
    abs(broken.peakRollOvershoot_deg-0.693006045035762)<1e-10 && ...
    broken.settlingTime_s>equalQ.settlingTime_s+1.4 && ...
    broken.peakRollOvershoot_deg>equalQ.peakRollOvershoot_deg+0.5 && ...
    broken.settledByEnd && broken.aileronCommandSaturationFraction==0, ...
    'The broken schedule must remain finite but visibly slower and less damped.');

rollback=modelFcn(pairedAirspeed,pairedDensity,1);
recoveredBaseline=modelFcn(60,referenceDensity,1);
assert(isequal(rollback.rollAngle_deg,equalQ.rollAngle_deg) && ...
    isequal(rollback.aileronCommand_deg,equalQ.aileronCommand_deg) && ...
    isequal(recoveredBaseline.rollAngle_deg,baseline.rollAngle_deg) && ...
    isequal(recoveredBaseline.aileronCommand_deg, ...
    baseline.aileronCommand_deg), ...
    'Stateless rollback from broken mode must reproduce correct traces exactly.');

%% Endpoint hold preserves a distinct actual plant outside table knots
lowCorner=modelFcn(45,0.5*referenceDensity,1);
highCorner=modelFcn(75,1.5*referenceDensity,1);
assert(lowCorner.actualDynamicPressureRatio<0.5 && ...
    lowCorner.lookupDynamicPressureRatioRaw== ...
    lowCorner.actualDynamicPressureRatio && ...
    lowCorner.lookupDynamicPressureRatio==0.5 && ...
    lowCorner.lookupClamped && lowCorner.lowerKnotIndex==1 && ...
    lowCorner.upperKnotIndex==1 && lowCorner.interpolationWeight==0 && ...
    lowCorner.actualControlEffectiveness_per_s2< ...
    baseline.actualControlEffectiveness_per_s2, ...
    'The low condition must hold the first gain knot without clamping the plant.');
assert(highCorner.actualDynamicPressureRatio>1.5 && ...
    highCorner.lookupDynamicPressureRatioRaw== ...
    highCorner.actualDynamicPressureRatio && ...
    highCorner.lookupDynamicPressureRatio==1.5 && ...
    highCorner.lookupClamped && highCorner.lowerKnotIndex==4 && ...
    highCorner.upperKnotIndex==5 && highCorner.interpolationWeight==1 && ...
    highCorner.actualControlEffectiveness_per_s2> ...
    baseline.actualControlEffectiveness_per_s2, ...
    'The high condition must hold the last gain knot without clamping the plant.');
assert(all(isfinite(lowCorner.rollAngle_deg)) && ...
    all(isfinite(highCorner.rollAngle_deg)) && ...
    max(abs(lowCorner.aileronCommand_deg))<=15 && ...
    max(abs(highCorner.aileronCommand_deg))<=15, ...
    'Accepted outside-table conditions must stay finite and command bounded.');

%% Malformed and rejected inputs do not poison deterministic recovery
invalidCalls={ ...
    @() modelFcn(44.999,referenceDensity,1), ...
    @() modelFcn(75.001,referenceDensity,1), ...
    @() modelFcn([60 61],referenceDensity,1), ...
    @() modelFcn(60+1i,referenceDensity,1), ...
    @() modelFcn(NaN,referenceDensity,1), ...
    @() modelFcn(Inf,referenceDensity,1), ...
    @() modelFcn(60,0.5*referenceDensity-1e-12,1), ...
    @() modelFcn(60,1.5*referenceDensity+1e-12,1), ...
    @() modelFcn(60,[referenceDensity referenceDensity],1), ...
    @() modelFcn(60,referenceDensity+1i,1), ...
    @() modelFcn(60,NaN,1), ...
    @() modelFcn(60,Inf,1), ...
    @() modelFcn(60,referenceDensity,-2), ...
    @() modelFcn(60,referenceDensity,2), ...
    @() modelFcn(60,referenceDensity,0.5), ...
    @() modelFcn(60,referenceDensity,[1 0]), ...
    @() modelFcn(60,referenceDensity,1+1i), ...
    @() modelFcn(60,referenceDensity,NaN), ...
    @() modelFcn(60,referenceDensity,Inf)};
for k=1:numel(invalidCalls)
    assertRejects(invalidCalls{k});
end
afterRejection=modelFcn(60,referenceDensity,1);
assert(isequal(afterRejection.rollAngle_deg,baseline.rollAngle_deg) && ...
    isequal(afterRejection.rollRate_degps,baseline.rollRate_degps) && ...
    isequal(afterRejection.aileronCommand_deg, ...
    baseline.aileronCommand_deg), ...
    'Rejected inputs must not poison a later valid baseline call.');

%% Accepted corners and capped representative grid bound work and outputs
acceptedCaseCount=0;
for trueAirspeed_mps=[45 75]
    for airDensity_kgpm3=referenceDensity*[0.5 1.5]
        for scheduleMode=[-1 0 1]
            sample=modelFcn(trueAirspeed_mps,airDensity_kgpm3, ...
                scheduleMode);
            acceptedCaseCount=acceptedCaseCount+1;
            assert(sample.sampleCount==801 && sample.intervalCount==800 && ...
                all(isfinite(sample.rollAngle_deg)) && ...
                all(isfinite(sample.rollRate_degps)) && ...
                all(isfinite(sample.aileronCommand_deg)) && ...
                all(isfinite(sample.rollAcceleration_degps2)) && ...
                isfinite(sample.rollAngleGain) && ...
                isfinite(sample.rollRateGain_s) && ...
                max(abs(sample.aileronCommand_deg))<=15, ...
                'Every accepted input corner must remain finite, fixed, and bounded.');
        end
    end
end
assert(acceptedCaseCount==12, ...
    'The accepted-corner test matrix must remain capped at 12 calls.');

representativeCaseCount=0;
for trueAirspeed_mps=[45 60 75]
    for airDensity_kgpm3=referenceDensity*[0.5 1 1.5]
        for scheduleMode=[-1 0 1]
            sample=modelFcn(trueAirspeed_mps,airDensity_kgpm3, ...
                scheduleMode);
            representativeCaseCount=representativeCaseCount+1;
            assert(numel(sample.time_s)==801 && ...
                numel(sample.rollAngle_deg)==801 && ...
                numel(sample.aileronCommand_deg)==801 && ...
                all(isfinite(sample.rollAngle_deg)) && ...
                max(abs(sample.aileronCommand_deg))<=15, ...
                'The representative grid must retain bounded fixed-size work.');
        end
    end
end
assert(representativeCaseCount==27, ...
    'The representative resource grid must remain capped at 27 calls.');

%% Compatibility, timeout, cancellation, migration, and backup applicability
% MODEL is synchronous, deterministic, and stateless. It creates no timer,
% future, worker, file, network, device, process, or background callback
% resource, so asynchronous timeout and cancellation are not model API
% semantics. The fixed 801 samples, five knots, bounded input ranges,
% endpoint hold, and capped test matrices are the applicable resource limits.
% P14 and P15 are conceptual prerequisites, not compatibility adapters.
% No learner state, score, database, service, schema, migration, or
% backup/restore path is read or changed by these checks.

fprintf(['P16 checks passed: dynamic-pressure reconstruction, five-knot ' ...
    'interpolation, every state update, two isolated sweeps, reference and ' ...
    'equal-pressure limits, endpoint hold, broken TAS-only lookup, malformed ' ...
    'recovery, rollback, compatibility, and bounded resources.\n']);
end

function [used,clamped,lower,upper,weight,angleGain,rateGain]= ...
        independentLookup(raw,knots,angleTable,rateTable)
used=min(max(raw,knots(1)),knots(end));
clamped=used~=raw;
upper=find(knots>=used,1,'first');
if upper==1
    lower=1;
    weight=0;
else
    lower=upper-1;
    weight=(used-knots(lower))/(knots(upper)-knots(lower));
end
angleGain=(1-weight)*angleTable(lower)+weight*angleTable(upper);
rateGain=(1-weight)*rateTable(lower)+weight*rateTable(upper);
end

function assertRejects(callable)
didReject=false;
try
    callable();
catch
    didReject=true;
end
assert(didReject,'Malformed or out-of-range input must be rejected.');
end
