function out = model(aileronPulse_deg,bankRelease_deg,rudderPulse_deg, ...
    rollDecayRate_per_s,spiralDecayRate_per_s,dutchRollDampingRatio)
%MODEL Closed-form roll, spiral, and Dutch-roll teaching responses.
% Positive roll rate and bank angle are right-wing-down. Positive yaw rate
% and heading are nose-right. Positive beta is air-relative velocity toward
% body right, so beta_dot is approximately -r only when the inertial
% flight-path direction is nearly frozen. Positive aileron and rudder inputs
% are operational commands that produce positive roll and yaw moments; no
% trailing-edge convention is implied. The modes are intentionally
% decoupled and are not an identified lateral-directional aircraft model.
arguments
    aileronPulse_deg (1,1) double {mustBeReal,mustBeFinite} = 2
    bankRelease_deg (1,1) double {mustBeReal,mustBeFinite} = 5
    rudderPulse_deg (1,1) double {mustBeReal,mustBeFinite} = 3
    rollDecayRate_per_s (1,1) double {mustBeReal,mustBeFinite} = 2.5
    spiralDecayRate_per_s (1,1) double {mustBeReal,mustBeFinite} = 0.025
    dutchRollDampingRatio (1,1) double {mustBeReal,mustBeFinite} = 0.18
end

if abs(aileronPulse_deg)>5
    error('P07:model:AileronPulseRange', ...
        'Aileron pulse must be between -5 and 5 deg, inclusive.');
end
if abs(bankRelease_deg)>10
    error('P07:model:BankReleaseRange', ...
        'Bank release must be between -10 and 10 deg, inclusive.');
end
if abs(rudderPulse_deg)>5
    error('P07:model:RudderPulseRange', ...
        'Rudder pulse must be between -5 and 5 deg, inclusive.');
end
if rollDecayRate_per_s<0.8 || rollDecayRate_per_s>5
    error('P07:model:RollDecayRateRange', ...
        'Roll decay rate must be between 0.8 and 5 1/s, inclusive.');
end
if spiralDecayRate_per_s<0
    error('P07:model:NegativeSpiralDecayRate', ...
        'Spiral decay rate must be nonnegative.');
end
if spiralDecayRate_per_s>0.05
    error('P07:model:SpiralDecayRateRange', ...
        'Spiral decay rate must not exceed 0.05 1/s.');
end
if dutchRollDampingRatio<0
    error('P07:model:NegativeDutchRollDamping', ...
        'Dutch-roll damping ratio must be nonnegative.');
end
if dutchRollDampingRatio>0.6
    error('P07:model:DutchRollDampingRange', ...
        'Dutch-roll damping ratio must not exceed 0.6.');
end

referenceTrueAirspeed_mps=60;
referenceDynamicPressure_Pa=1325.00798531847;
wingArea_m2=16.2;
wingSpan_m=10.9;
rollInertia_kgm2=2500;
yawInertia_kgm2=4000;
aileronControlDerivative_perRad=0.08;
rudderControlDerivative_perRad=0.10;
controlPulseDuration_s=0.18;
dutchRollNaturalFrequency_rad_s=1.15;
gravity_mps2=9.80665;
bankLinearLimit_deg=15;
sideslipLinearLimit_deg=5;

rollTime_s=0:0.02:5;
dutchRollTime_s=0:0.05:25;
spiralTime_s=0:0.25:120;
rollMomentScale_Nm=referenceDynamicPressure_Pa*wingArea_m2*wingSpan_m;

% Roll subsidence: an idealized aileron pulse establishes p(0+), then
% aerodynamic roll damping removes roll rate without restoring bank angle.
aileronPulse_rad=aileronPulse_deg*pi/180;
aileronMoment_Nm=rollMomentScale_Nm*aileronControlDerivative_perRad* ...
    aileronPulse_rad;
initialRollRate_rad_s=aileronMoment_Nm*controlPulseDuration_s/ ...
    rollInertia_kgm2;
rollExponential=exp(-rollDecayRate_per_s*rollTime_s);
rollRate_rad_s=initialRollRate_rad_s*rollExponential;
rollRateDerivative_rad_s2=-rollDecayRate_per_s*rollRate_rad_s;
rollBankChange_rad=initialRollRate_rad_s/rollDecayRate_per_s* ...
    (1-rollExponential);
rollRate_deg_s=rollRate_rad_s*180/pi;
rollBankChange_deg=rollBankChange_rad*180/pi;
rollAsymptoticBankChange_deg=initialRollRate_rad_s/ ...
    rollDecayRate_per_s*180/pi;
rollTimeConstant_s=1/rollDecayRate_per_s;
rollHalfLife_s=log(2)/rollDecayRate_per_s;
rollTwoPercentSettlingTime_s=-log(0.02)/rollDecayRate_per_s;

% Spiral mode: a bank-angle initial condition decays slowly. The heading
% view uses the P01 small-angle coordinated-turn proxy psi_dot=(g/V0)*phi;
% it is an observable aid, not the spiral eigenvector.
bankRelease_rad=bankRelease_deg*pi/180;
spiralExponential=exp(-spiralDecayRate_per_s*spiralTime_s);
spiralBank_rad=bankRelease_rad*spiralExponential;
spiralRollRate_rad_s=-spiralDecayRate_per_s*spiralBank_rad;
spiralHeadingRate_rad_s=gravity_mps2/referenceTrueAirspeed_mps* ...
    spiralBank_rad;
if spiralDecayRate_per_s==0
    spiralIntegralTime_s=spiralTime_s;
    spiralTimeConstant_s=Inf;
    spiralHalfLife_s=Inf;
    spiralTimeScaleIsRepresentable=false;
    spiralStabilityLabel='neutral spiral: bank persists';
else
    % Avoid cancellation in 1-exp(-lambda*t), and avoid underflow of
    % lambda*t for accepted subnormal positive rates. Those rates are
    % physically stable but indistinguishable from neutral on this window.
    if spiralDecayRate_per_s*spiralTime_s(end)<sqrt(eps)
        spiralIntegralTime_s=spiralTime_s-0.5*spiralDecayRate_per_s* ...
            spiralTime_s.^2;
    else
        spiralIntegralTime_s=-expm1(-spiralDecayRate_per_s*spiralTime_s)/ ...
            spiralDecayRate_per_s;
    end
    if spiralDecayRate_per_s<1/realmax
        spiralTimeConstant_s=Inf;
    else
        spiralTimeConstant_s=1/spiralDecayRate_per_s;
    end
    if spiralDecayRate_per_s<log(2)/realmax
        spiralHalfLife_s=Inf;
    else
        spiralHalfLife_s=log(2)/spiralDecayRate_per_s;
    end
    spiralTimeScaleIsRepresentable=isfinite(spiralTimeConstant_s) && ...
        isfinite(spiralHalfLife_s);
    if spiralTimeScaleIsRepresentable
        spiralStabilityLabel='stable spiral: bank decays slowly';
    else
        spiralStabilityLabel= ...
            'stable spiral: decay time exceeds finite numeric range';
    end
end
spiralHeadingChange_rad=gravity_mps2/referenceTrueAirspeed_mps* ...
    bankRelease_rad*spiralIntegralTime_s;
spiralBank_deg=spiralBank_rad*180/pi;
spiralRollRate_deg_s=spiralRollRate_rad_s*180/pi;
spiralHeadingRate_deg_s=spiralHeadingRate_rad_s*180/pi;
spiralHeadingChange_deg=spiralHeadingChange_rad*180/pi;
spiralBankRemainingAtEnd_ratio=spiralExponential(end);

% Dutch roll: a rudder angular impulse establishes r(0+). With the inertial
% path nearly frozen, beta_dot approximately -r. The resulting beta/r pair
% is a transparent underdamped oscillator, not a full stability-derivative
% reconstruction.
rudderPulse_rad=rudderPulse_deg*pi/180;
rudderMoment_Nm=rollMomentScale_Nm*rudderControlDerivative_perRad* ...
    rudderPulse_rad;
initialYawRate_rad_s=rudderMoment_Nm*controlPulseDuration_s/yawInertia_kgm2;
dutchRollBeta=sqrt(1-dutchRollDampingRatio^2);
dutchRollDampedFrequency_rad_s=dutchRollNaturalFrequency_rad_s* ...
    dutchRollBeta;
dutchRollDecayRate_per_s=dutchRollDampingRatio* ...
    dutchRollNaturalFrequency_rad_s;
dutchRollDampedPeriod_s=2*pi/dutchRollDampedFrequency_rad_s;
dutchRollDecayPerPeriod_ratio=exp(-dutchRollDecayRate_per_s* ...
    dutchRollDampedPeriod_s);
dutchRollExponential=exp(-dutchRollDecayRate_per_s*dutchRollTime_s);
initialSideslipRate_rad_s=-initialYawRate_rad_s;
dutchRollSideslip_rad=initialSideslipRate_rad_s/ ...
    dutchRollDampedFrequency_rad_s.*dutchRollExponential.* ...
    sin(dutchRollDampedFrequency_rad_s*dutchRollTime_s);
dutchRollSideslipRate_rad_s=initialSideslipRate_rad_s* ...
    dutchRollExponential.*( ...
    cos(dutchRollDampedFrequency_rad_s*dutchRollTime_s)- ...
    dutchRollDecayRate_per_s/dutchRollDampedFrequency_rad_s.* ...
    sin(dutchRollDampedFrequency_rad_s*dutchRollTime_s));
dutchRollSideslipAcceleration_rad_s2=initialSideslipRate_rad_s* ...
    dutchRollExponential.*( ...
    -2*dutchRollDecayRate_per_s* ...
    cos(dutchRollDampedFrequency_rad_s*dutchRollTime_s)+( ...
    dutchRollDecayRate_per_s^2/dutchRollDampedFrequency_rad_s- ...
    dutchRollDampedFrequency_rad_s).* ...
    sin(dutchRollDampedFrequency_rad_s*dutchRollTime_s));
dutchRollYawRate_rad_s=-dutchRollSideslipRate_rad_s;
dutchRollYawAcceleration_rad_s2=-dutchRollSideslipAcceleration_rad_s2;
dutchRollSideslip_deg=dutchRollSideslip_rad*180/pi;
dutchRollYawRate_deg_s=dutchRollYawRate_rad_s*180/pi;
dutchRollSideslipEnvelope_deg=abs(initialSideslipRate_rad_s)/ ...
    dutchRollDampedFrequency_rad_s*180/pi.*dutchRollExponential;
dutchRollBetaKinematicResidual_rad_s= ...
    dutchRollSideslipRate_rad_s+dutchRollYawRate_rad_s;
dutchRollYawEquationResidual_rad_s2=dutchRollYawAcceleration_rad_s2- ...
    dutchRollNaturalFrequency_rad_s^2*dutchRollSideslip_rad+ ...
    2*dutchRollDecayRate_per_s*dutchRollYawRate_rad_s;
dutchRollModalEnergy_rad2_s2=0.5*(dutchRollYawRate_rad_s.^2+ ...
    dutchRollNaturalFrequency_rad_s^2*dutchRollSideslip_rad.^2);
dutchRollModalEnergyRate_rad2_s3=-2*dutchRollDecayRate_per_s* ...
    dutchRollYawRate_rad_s.^2;

rollPeakRate_deg_s=max(abs(rollRate_deg_s));
dutchRollPeakSideslip_deg=max(abs(dutchRollSideslip_deg));
dutchRollPeakYawRate_deg_s=max(abs(dutchRollYawRate_deg_s));
spiralHeadingRange_deg=max(spiralHeadingChange_deg)- ...
    min(spiralHeadingChange_deg);
isWithinRollBankLinearRange=max(abs(rollBankChange_deg))<=bankLinearLimit_deg;
isWithinSpiralBankLinearRange=max(abs(spiralBank_deg))<=bankLinearLimit_deg;
isWithinDutchRollSideslipLinearRange= ...
    dutchRollPeakSideslip_deg<=sideslipLinearLimit_deg;

if dutchRollDampingRatio==0
    dutchRollDampingLabel='undamped Dutch roll: modal energy is constant';
else
    dutchRollDampingLabel='damped Dutch roll: sideslip and yaw fade';
end

out=struct( ...
    'aileronPulse_deg',aileronPulse_deg, ...
    'bankRelease_deg',bankRelease_deg, ...
    'rudderPulse_deg',rudderPulse_deg, ...
    'rollDecayRate_per_s',rollDecayRate_per_s, ...
    'spiralDecayRate_per_s',spiralDecayRate_per_s, ...
    'dutchRollDampingRatio',dutchRollDampingRatio, ...
    'rollTime_s',rollTime_s, ...
    'dutchRollTime_s',dutchRollTime_s, ...
    'spiralTime_s',spiralTime_s, ...
    'rollSampleCount',numel(rollTime_s), ...
    'dutchRollSampleCount',numel(dutchRollTime_s), ...
    'spiralSampleCount',numel(spiralTime_s), ...
    'rollRate_deg_s',rollRate_deg_s, ...
    'rollRateDerivative_rad_s2',rollRateDerivative_rad_s2, ...
    'rollBankChange_deg',rollBankChange_deg, ...
    'spiralBank_deg',spiralBank_deg, ...
    'spiralRollRate_deg_s',spiralRollRate_deg_s, ...
    'spiralHeadingRate_deg_s',spiralHeadingRate_deg_s, ...
    'spiralHeadingChange_deg',spiralHeadingChange_deg, ...
    'dutchRollSideslip_deg',dutchRollSideslip_deg, ...
    'dutchRollSideslipRate_rad_s',dutchRollSideslipRate_rad_s, ...
    'dutchRollSideslipAcceleration_rad_s2', ...
    dutchRollSideslipAcceleration_rad_s2, ...
    'dutchRollYawRate_deg_s',dutchRollYawRate_deg_s, ...
    'dutchRollYawAcceleration_rad_s2', ...
    dutchRollYawAcceleration_rad_s2, ...
    'dutchRollSideslipEnvelope_deg',dutchRollSideslipEnvelope_deg, ...
    'dutchRollBetaKinematicResidual_rad_s', ...
    dutchRollBetaKinematicResidual_rad_s, ...
    'dutchRollYawEquationResidual_rad_s2', ...
    dutchRollYawEquationResidual_rad_s2, ...
    'dutchRollModalEnergy_rad2_s2',dutchRollModalEnergy_rad2_s2, ...
    'dutchRollModalEnergyRate_rad2_s3', ...
    dutchRollModalEnergyRate_rad2_s3, ...
    'initialRollRate_rad_s',initialRollRate_rad_s, ...
    'initialRollRate_deg_s',initialRollRate_rad_s*180/pi, ...
    'initialYawRate_rad_s',initialYawRate_rad_s, ...
    'initialYawRate_deg_s',initialYawRate_rad_s*180/pi, ...
    'initialSideslipRate_rad_s',initialSideslipRate_rad_s, ...
    'aileronMoment_Nm',aileronMoment_Nm, ...
    'rudderMoment_Nm',rudderMoment_Nm, ...
    'rollMomentScale_Nm',rollMomentScale_Nm, ...
    'rollAsymptoticBankChange_deg',rollAsymptoticBankChange_deg, ...
    'rollTimeConstant_s',rollTimeConstant_s, ...
    'rollHalfLife_s',rollHalfLife_s, ...
    'rollTwoPercentSettlingTime_s',rollTwoPercentSettlingTime_s, ...
    'spiralTimeConstant_s',spiralTimeConstant_s, ...
    'spiralHalfLife_s',spiralHalfLife_s, ...
    'spiralTimeScaleIsRepresentable',spiralTimeScaleIsRepresentable, ...
    'spiralBankRemainingAtEnd_ratio',spiralBankRemainingAtEnd_ratio, ...
    'dutchRollNaturalFrequency_rad_s',dutchRollNaturalFrequency_rad_s, ...
    'dutchRollDampedFrequency_rad_s',dutchRollDampedFrequency_rad_s, ...
    'dutchRollDecayRate_per_s',dutchRollDecayRate_per_s, ...
    'dutchRollDampedPeriod_s',dutchRollDampedPeriod_s, ...
    'dutchRollDecayPerPeriod_ratio',dutchRollDecayPerPeriod_ratio, ...
    'rollPeakRate_deg_s',rollPeakRate_deg_s, ...
    'dutchRollPeakSideslip_deg',dutchRollPeakSideslip_deg, ...
    'dutchRollPeakYawRate_deg_s',dutchRollPeakYawRate_deg_s, ...
    'spiralHeadingRange_deg',spiralHeadingRange_deg, ...
    'dutchToRollTimeScaleRatio',dutchRollDampedPeriod_s/rollTimeConstant_s, ...
    'spiralToDutchTimeScaleRatio', ...
    spiralTimeConstant_s/dutchRollDampedPeriod_s, ...
    'bankLinearLimit_deg',bankLinearLimit_deg, ...
    'sideslipLinearLimit_deg',sideslipLinearLimit_deg, ...
    'isWithinRollBankLinearRange',isWithinRollBankLinearRange, ...
    'isWithinSpiralBankLinearRange',isWithinSpiralBankLinearRange, ...
    'isWithinDutchRollSideslipLinearRange', ...
    isWithinDutchRollSideslipLinearRange, ...
    'referenceTrueAirspeed_mps',referenceTrueAirspeed_mps, ...
    'referenceDynamicPressure_Pa',referenceDynamicPressure_Pa, ...
    'wingArea_m2',wingArea_m2, ...
    'wingSpan_m',wingSpan_m, ...
    'rollInertia_kgm2',rollInertia_kgm2, ...
    'yawInertia_kgm2',yawInertia_kgm2, ...
    'aileronControlDerivative_perRad',aileronControlDerivative_perRad, ...
    'rudderControlDerivative_perRad',rudderControlDerivative_perRad, ...
    'controlPulseDuration_s',controlPulseDuration_s, ...
    'gravity_mps2',gravity_mps2, ...
    'spiralStabilityLabel',spiralStabilityLabel, ...
    'dutchRollDampingLabel',dutchRollDampingLabel, ...
    'aileronConvention', ...
    'positive aileron command produces a right-wing-down roll moment', ...
    'rudderConvention','positive rudder command produces a nose-right yaw moment', ...
    'sideslipConvention','positive beta is air-relative velocity toward body right', ...
    'dutchRollKinematicApproximation', ...
    'flight-path direction nearly frozen, so beta_dot approximately -r', ...
    'spiralHeadingApproximation', ...
    'small-angle coordinated turn: psi_dot approximately g*phi/V0', ...
    'analysisScope',['decoupled linear lateral-directional teaching modes; ' ...
    'not identified aircraft data or a full lateral state-space model']);
end
