function run_checks
%RUN_CHECKS Independent analytic checks for the P07 lateral modal model.
clear model;
tol=1e-10;

%% Determinism, fixed vector shape, and finite resource bounds
first=model(2,5,3,2.5,0.025,0.18);
second=model(2,5,3,2.5,0.025,0.18);
assert(isequaln(first,second), ...
    'Identical lateral-mode inputs must produce identical outputs.');
assert(first.rollSampleCount==251 && ...
    first.dutchRollSampleCount==501 && first.spiralSampleCount==481, ...
    'Roll, Dutch-roll, and spiral response grids must remain fixed.');
assert(isequal(size(first.rollTime_s),[1 251]) && ...
    isequal(size(first.dutchRollTime_s),[1 501]) && ...
    isequal(size(first.spiralTime_s),[1 481]), ...
    'Every time grid must remain a fixed row vector.');

rollFields={'rollRate_deg_s','rollRateDerivative_rad_s2', ...
    'rollBankChange_deg'};
dutchFields={'dutchRollSideslip_deg','dutchRollSideslipRate_rad_s', ...
    'dutchRollSideslipAcceleration_rad_s2','dutchRollYawRate_deg_s', ...
    'dutchRollYawAcceleration_rad_s2','dutchRollSideslipEnvelope_deg', ...
    'dutchRollBetaKinematicResidual_rad_s', ...
    'dutchRollYawEquationResidual_rad_s2', ...
    'dutchRollModalEnergy_rad2_s2','dutchRollModalEnergyRate_rad2_s3'};
spiralFields={'spiralBank_deg','spiralRollRate_deg_s', ...
    'spiralHeadingRate_deg_s','spiralHeadingChange_deg'};
scalarFields={'initialRollRate_rad_s','initialRollRate_deg_s', ...
    'initialYawRate_rad_s','initialYawRate_deg_s', ...
    'initialSideslipRate_rad_s','aileronMoment_Nm','rudderMoment_Nm', ...
    'rollMomentScale_Nm','rollAsymptoticBankChange_deg', ...
    'rollTimeConstant_s','rollHalfLife_s','rollTwoPercentSettlingTime_s', ...
    'spiralBankRemainingAtEnd_ratio','spiralTimeScaleIsRepresentable', ...
    'dutchRollNaturalFrequency_rad_s', ...
    'dutchRollDampedFrequency_rad_s','dutchRollDecayRate_per_s', ...
    'dutchRollDampedPeriod_s','dutchRollDecayPerPeriod_ratio', ...
    'rollPeakRate_deg_s','dutchRollPeakSideslip_deg', ...
    'dutchRollPeakYawRate_deg_s','spiralHeadingRange_deg', ...
    'dutchToRollTimeScaleRatio','bankLinearLimit_deg', ...
    'sideslipLinearLimit_deg'};
for k=1:numel(rollFields)
    value=first.(rollFields{k});
    assert(isequal(size(value),[1 251]) && isreal(value) && ...
        all(isfinite(value)), ...
        'Every roll-mode output must be a finite fixed-size row vector.');
end
for k=1:numel(dutchFields)
    value=first.(dutchFields{k});
    assert(isequal(size(value),[1 501]) && isreal(value) && ...
        all(isfinite(value)), ...
        'Every Dutch-roll output must be a finite fixed-size row vector.');
end
for k=1:numel(spiralFields)
    value=first.(spiralFields{k});
    assert(isequal(size(value),[1 481]) && isreal(value) && ...
        all(isfinite(value)), ...
        'Every spiral output must be a finite fixed-size row vector.');
end
for k=1:numel(scalarFields)
    value=first.(scalarFields{k});
    assert(isscalar(value) && isreal(value) && isfinite(value), ...
        'Every ordinary lateral-mode metric must be a finite real scalar.');
end

edgeAileron_deg=[-5 5];
edgeBank_deg=[-10 10];
edgeRudder_deg=[-5 5];
edgeRollDecay_per_s=[0.8 5];
edgeSpiralDecay_per_s=[0 0.05];
edgeDutchDamping=[0 0.6];
edgeCaseCount=0;
for aileronIndex=1:numel(edgeAileron_deg)
    for bankIndex=1:numel(edgeBank_deg)
        for rudderIndex=1:numel(edgeRudder_deg)
            for rollIndex=1:numel(edgeRollDecay_per_s)
                for spiralIndex=1:numel(edgeSpiralDecay_per_s)
                    for dutchIndex=1:numel(edgeDutchDamping)
                        edge=model(edgeAileron_deg(aileronIndex), ...
                            edgeBank_deg(bankIndex), ...
                            edgeRudder_deg(rudderIndex), ...
                            edgeRollDecay_per_s(rollIndex), ...
                            edgeSpiralDecay_per_s(spiralIndex), ...
                            edgeDutchDamping(dutchIndex));
                        edgeCaseCount=edgeCaseCount+1;
                        assert(edge.rollSampleCount==251 && ...
                            edge.dutchRollSampleCount==501 && ...
                            edge.spiralSampleCount==481 && ...
                            edge.isWithinRollBankLinearRange && ...
                            edge.isWithinSpiralBankLinearRange && ...
                            edge.isWithinDutchRollSideslipLinearRange, ...
                            'Accepted corners must preserve bounded response shapes.');
                        for fieldIndex=1:numel(rollFields)
                            assert(all(isfinite(edge.(rollFields{fieldIndex}))), ...
                                'Accepted corners must keep roll vectors finite.');
                        end
                        for fieldIndex=1:numel(dutchFields)
                            assert(all(isfinite(edge.(dutchFields{fieldIndex}))), ...
                                'Accepted corners must keep Dutch-roll vectors finite.');
                        end
                        for fieldIndex=1:numel(spiralFields)
                            assert(all(isfinite(edge.(spiralFields{fieldIndex}))), ...
                                'Accepted corners must keep spiral vectors finite.');
                        end
                        if edge.spiralDecayRate_per_s==0
                            assert(isinf(edge.spiralTimeConstant_s) && ...
                                isinf(edge.spiralHalfLife_s) && ...
                                isinf(edge.spiralToDutchTimeScaleRatio), ...
                                'A neutral spiral must report no finite decay time.');
                        else
                            assert(isfinite(edge.spiralTimeConstant_s) && ...
                                isfinite(edge.spiralHalfLife_s) && ...
                                isfinite(edge.spiralToDutchTimeScaleRatio), ...
                                'A stable spiral must have finite time-scale metrics.');
                        end
                    end
                end
            end
        end
    end
end
assert(edgeCaseCount==64,'The accepted-corner grid must stay fixed at 64 cases.');

%% Independent dimensional buildup and recognizable baseline
expectedQbar_Pa=1325.00798531847;
expectedWingArea_m2=16.2;
expectedWingSpan_m=10.9;
expectedRollInertia_kgm2=2500;
expectedYawInertia_kgm2=4000;
expectedAileronGain_perRad=0.08;
expectedRudderGain_perRad=0.10;
expectedPulseDuration_s=0.18;
expectedAileron_rad=2*pi/180;
expectedRudder_rad=3*pi/180;
expectedRollDecay_per_s=2.5;
expectedSpiralDecay_per_s=0.025;
expectedDutchDamping=0.18;
expectedDutchNatural_rad_s=1.15;
expectedGravity_mps2=9.80665;
expectedTrueAirspeed_mps=60;

expectedMomentScale_Nm=expectedQbar_Pa*expectedWingArea_m2* ...
    expectedWingSpan_m;
expectedAileronMoment_Nm=expectedMomentScale_Nm* ...
    expectedAileronGain_perRad*expectedAileron_rad;
expectedRudderMoment_Nm=expectedMomentScale_Nm* ...
    expectedRudderGain_perRad*expectedRudder_rad;
expectedInitialRollRate_rad_s=expectedAileronMoment_Nm* ...
    expectedPulseDuration_s/expectedRollInertia_kgm2;
expectedInitialYawRate_rad_s=expectedRudderMoment_Nm* ...
    expectedPulseDuration_s/expectedYawInertia_kgm2;
expectedDutchDamped_rad_s=expectedDutchNatural_rad_s* ...
    sqrt(1-expectedDutchDamping^2);
expectedDutchDecay_per_s=expectedDutchDamping*expectedDutchNatural_rad_s;
expectedDutchPeriod_s=2*pi/expectedDutchDamped_rad_s;
expectedDutchDecayRatio=exp(-expectedDutchDecay_per_s* ...
    expectedDutchPeriod_s);

assert(abs(first.rollMomentScale_Nm-expectedMomentScale_Nm)<1e-8 && ...
    abs(first.aileronMoment_Nm-expectedAileronMoment_Nm)<1e-8 && ...
    abs(first.rudderMoment_Nm-expectedRudderMoment_Nm)<1e-8, ...
    'qbar*S*b and declared command gains must set the moment impulses.');
assert(abs(first.initialRollRate_rad_s-expectedInitialRollRate_rad_s)<tol && ...
    abs(first.initialYawRate_rad_s-expectedInitialYawRate_rad_s)<tol, ...
    'Moment impulse divided by inertia must set the initial body rates.');
assert(abs(first.dutchRollDampedFrequency_rad_s- ...
    expectedDutchDamped_rad_s)<tol && ...
    abs(first.dutchRollDampedPeriod_s-expectedDutchPeriod_s)<tol && ...
    abs(first.dutchRollDecayPerPeriod_ratio- ...
    expectedDutchDecayRatio)<tol, ...
    'Dutch-roll pole metrics must follow independent formulas.');
assert(abs(first.initialRollRate_deg_s-2.695333363747607)<1e-12 && ...
    abs(first.rollAsymptoticBankChange_deg- ...
    1.078133345499043)<1e-12 && ...
    abs(first.rollTwoPercentSettlingTime_s- ...
    1.564809202171258)<1e-12 && ...
    abs(first.initialYawRate_deg_s-3.158593785641729)<1e-12 && ...
    abs(first.dutchRollDampedPeriod_s-5.554360939932403)<1e-12 && ...
    abs(first.dutchRollDecayPerPeriod_ratio- ...
    0.316715078721968)<1e-12 && ...
    abs(first.dutchRollPeakSideslip_deg- ...
    2.129193493985499)<1e-12 && ...
    abs(first.spiralBank_deg(end)-0.248935341839320)<1e-12 && ...
    abs(first.spiralHeadingChange_deg(end)- ...
    31.06135215330095)<1e-11, ...
    'Baseline modal signatures must remain numerically recognizable.');

%% Closed-form responses, state equations, and kinematic proxies
expectedRollRate_rad_s=expectedInitialRollRate_rad_s* ...
    exp(-expectedRollDecay_per_s*first.rollTime_s);
expectedRollBank_rad=expectedInitialRollRate_rad_s/ ...
    expectedRollDecay_per_s*(1-exp(-expectedRollDecay_per_s* ...
    first.rollTime_s));
expectedSpiralBank_rad=5*pi/180*exp(-expectedSpiralDecay_per_s* ...
    first.spiralTime_s);
expectedSpiralHeading_rad=expectedGravity_mps2/ ...
    expectedTrueAirspeed_mps*(5*pi/180)/expectedSpiralDecay_per_s* ...
    (1-exp(-expectedSpiralDecay_per_s*first.spiralTime_s));
expectedSideslipRate0_rad_s=-expectedInitialYawRate_rad_s;
expectedDutchSideslip_rad=expectedSideslipRate0_rad_s/ ...
    expectedDutchDamped_rad_s.*exp(-expectedDutchDecay_per_s* ...
    first.dutchRollTime_s).*sin(expectedDutchDamped_rad_s* ...
    first.dutchRollTime_s);
expectedDutchYawRate_rad_s=expectedInitialYawRate_rad_s* ...
    exp(-expectedDutchDecay_per_s*first.dutchRollTime_s).*( ...
    cos(expectedDutchDamped_rad_s*first.dutchRollTime_s)- ...
    expectedDutchDecay_per_s/expectedDutchDamped_rad_s.* ...
    sin(expectedDutchDamped_rad_s*first.dutchRollTime_s));

assert(max(abs(first.rollRate_deg_s-expectedRollRate_rad_s*180/pi))<tol && ...
    max(abs(first.rollBankChange_deg-expectedRollBank_rad*180/pi))<tol, ...
    'Roll vectors must match the closed-form initial-rate response.');
assert(max(abs(first.spiralBank_deg-expectedSpiralBank_rad*180/pi))<tol && ...
    max(abs(first.spiralHeadingChange_deg- ...
    expectedSpiralHeading_rad*180/pi))<tol, ...
    'Spiral bank and heading vectors must match the stable analytic response.');
assert(max(abs(first.dutchRollSideslip_deg- ...
    expectedDutchSideslip_rad*180/pi))<tol && ...
    max(abs(first.dutchRollYawRate_deg_s- ...
    expectedDutchYawRate_rad_s*180/pi))<tol, ...
    'Dutch-roll vectors must match the beta/r closed-form response.');
assert(abs(first.rollRate_deg_s(1)-first.initialRollRate_deg_s)<tol && ...
    first.rollBankChange_deg(1)==0 && ...
    abs(first.spiralBank_deg(1)-5)<tol && ...
    first.spiralHeadingChange_deg(1)==0 && ...
    first.dutchRollSideslip_deg(1)==0 && ...
    abs(first.dutchRollYawRate_deg_s(1)- ...
    first.initialYawRate_deg_s)<tol, ...
    'Initial conditions must expose which input owns each modal response.');
assert(max(abs(first.rollRateDerivative_rad_s2+ ...
    first.rollDecayRate_per_s*first.rollRate_deg_s*pi/180))<tol, ...
    'Roll subsidence must obey p_dot+lambda_R*p=0.');
assert(max(abs(first.spiralRollRate_deg_s+ ...
    first.spiralDecayRate_per_s*first.spiralBank_deg))<tol, ...
    'The stable spiral must obey phi_dot+lambda_S*phi=0.');
assert(max(abs(first.spiralHeadingRate_deg_s- ...
    first.gravity_mps2/first.referenceTrueAirspeed_mps* ...
    first.spiralBank_deg))<tol, ...
    'The heading proxy must retain psi_dot=(g/V0)*phi with matching angle units.');
assert(max(abs(first.dutchRollBetaKinematicResidual_rad_s))<tol && ...
    max(abs(first.dutchRollYawEquationResidual_rad_s2))<tol, ...
    'Dutch roll must satisfy beta_dot+r=0 and the declared yaw-rate equation.');
assert(abs(first.dutchRollDampedFrequency_rad_s^2+ ...
    first.dutchRollDecayRate_per_s^2- ...
    first.dutchRollNaturalFrequency_rad_s^2)<tol, ...
    'Dutch-roll damped frequency and decay rate must recover omega_n squared.');
assert(all(first.dutchRollModalEnergyRate_rad2_s3<=tol) && ...
    first.dutchRollModalEnergy_rad2_s2(end)< ...
    first.dutchRollModalEnergy_rad2_s2(1), ...
    'Positive Dutch-roll damping must remove the declared normalized energy.');
dutchTimeStep_s=first.dutchRollTime_s(2)-first.dutchRollTime_s(1);
centeredModalEnergyRate_rad2_s3=( ...
    first.dutchRollModalEnergy_rad2_s2(3:end)- ...
    first.dutchRollModalEnergy_rad2_s2(1:end-2))/(2*dutchTimeStep_s);
assert(max(abs(first.dutchRollModalEnergyRate_rad2_s3))>1e-3 && ...
    all(diff(first.dutchRollModalEnergy_rad2_s2)<=tol) && ...
    max(abs(centeredModalEnergyRate_rad2_s3- ...
    first.dutchRollModalEnergyRate_rad2_s3(2:end-1)))<2e-6 && ...
    abs(first.dutchRollModalEnergy_rad2_s2(1)- ...
    0.5*first.initialYawRate_rad_s^2)<tol, ...
    'The sampled Dutch-roll energy must obey its nonzero dissipation identity.');

rollTimeStep_s=first.rollTime_s(2)-first.rollTime_s(1);
centeredRollBankRate_rad_s=(first.rollBankChange_deg(3:end)- ...
    first.rollBankChange_deg(1:end-2))*pi/180/(2*rollTimeStep_s);
assert(max(abs(centeredRollBankRate_rad_s- ...
    first.rollRate_deg_s(2:end-1)*pi/180))<2e-5, ...
    'Integrated roll-mode bank must obey phi_dot=p on the fixed grid.');
spiralTimeStep_s=first.spiralTime_s(2)-first.spiralTime_s(1);
centeredHeadingRate_rad_s=(first.spiralHeadingChange_deg(3:end)- ...
    first.spiralHeadingChange_deg(1:end-2))*pi/180/(2*spiralTimeStep_s);
expectedHeadingRate_rad_s=first.gravity_mps2/ ...
    first.referenceTrueAirspeed_mps*first.spiralBank_deg(2:end-1)*pi/180;
assert(max(abs(centeredHeadingRate_rad_s-expectedHeadingRate_rad_s))<1e-7, ...
    'Integrated heading must obey the coordinated-turn proxy on the slow grid.');

%% Distinct time scales, zero-input isolation, and sign symmetry
assert(abs(first.dutchToRollTimeScaleRatio-13.88590234983101)<1e-11 && ...
    abs(first.spiralToDutchTimeScaleRatio-7.201548554834609)<1e-12 && ...
    first.dutchToRollTimeScaleRatio>10 && ...
    first.spiralToDutchTimeScaleRatio>5, ...
    'Roll, Dutch roll, and spiral must retain visibly distinct time scales.');

noAileron=model(0,5,3,2.5,0.025,0.18);
noBank=model(2,0,3,2.5,0.025,0.18);
noRudder=model(2,5,0,2.5,0.025,0.18);
noExcitation=model(0,0,0,2.5,0.025,0.18);
assert(all(noAileron.rollRate_deg_s==0) && ...
    all(noAileron.rollBankChange_deg==0) && ...
    isequaln(noAileron.spiralBank_deg,first.spiralBank_deg) && ...
    isequaln(noAileron.dutchRollSideslip_deg, ...
    first.dutchRollSideslip_deg), ...
    'Zero aileron pulse must remove only roll subsidence.');
assert(all(noBank.spiralBank_deg==0) && ...
    all(noBank.spiralRollRate_deg_s==0) && ...
    all(noBank.spiralHeadingRate_deg_s==0) && ...
    all(noBank.spiralHeadingChange_deg==0) && ...
    isequaln(noBank.rollRate_deg_s,first.rollRate_deg_s) && ...
    isequaln(noBank.dutchRollYawRate_deg_s, ...
    first.dutchRollYawRate_deg_s), ...
    'Zero bank release must remove only the spiral response.');
assert(all(noRudder.dutchRollSideslip_deg==0) && ...
    all(noRudder.dutchRollYawRate_deg_s==0) && ...
    all(noRudder.dutchRollModalEnergy_rad2_s2==0) && ...
    isequaln(noRudder.rollRate_deg_s,first.rollRate_deg_s) && ...
    isequaln(noRudder.spiralBank_deg,first.spiralBank_deg), ...
    'Zero rudder pulse must remove only Dutch roll.');
assert(all(noExcitation.rollRate_deg_s==0) && ...
    all(noExcitation.spiralBank_deg==0) && ...
    all(noExcitation.dutchRollSideslip_deg==0), ...
    'With all three excitation inputs zero, every response must be zero.');

oppositeAileron=model(-2,5,3,2.5,0.025,0.18);
oppositeBank=model(2,-5,3,2.5,0.025,0.18);
oppositeRudder=model(2,5,-3,2.5,0.025,0.18);
assert(max(abs(oppositeAileron.rollRate_deg_s+first.rollRate_deg_s))<tol && ...
    max(abs(oppositeAileron.rollBankChange_deg+ ...
    first.rollBankChange_deg))<tol, ...
    'Opposite aileron pulses must reverse the roll response.');
assert(max(abs(oppositeBank.spiralBank_deg+first.spiralBank_deg))<tol && ...
    max(abs(oppositeBank.spiralHeadingChange_deg+ ...
    first.spiralHeadingChange_deg))<tol, ...
    'Opposite bank releases must reverse spiral bank and heading.');
assert(max(abs(oppositeRudder.dutchRollSideslip_deg+ ...
    first.dutchRollSideslip_deg))<tol && ...
    max(abs(oppositeRudder.dutchRollYawRate_deg_s+ ...
    first.dutchRollYawRate_deg_s))<tol && ...
    max(abs(oppositeRudder.dutchRollModalEnergy_rad2_s2- ...
    first.dutchRollModalEnergy_rad2_s2))<tol, ...
    'Opposite rudder pulses reverse states but preserve quadratic energy.');

%% Neutral and undamped limits plus two isolated sweep regressions
neutralSpiral=model(2,5,3,2.5,0,0.18);
assert(max(abs(neutralSpiral.spiralBank_deg-5))<tol && ...
    all(neutralSpiral.spiralRollRate_deg_s==0) && ...
    max(abs(neutralSpiral.spiralHeadingChange_deg- ...
    neutralSpiral.spiralHeadingRate_deg_s(1)* ...
    neutralSpiral.spiralTime_s))<tol && ...
    isinf(neutralSpiral.spiralTimeConstant_s) && ...
    isinf(neutralSpiral.spiralHalfLife_s) && ...
    ~neutralSpiral.spiralTimeScaleIsRepresentable, ...
    'Zero spiral decay must preserve bank and create linear heading change.');
nearNeutralSpiral=model(2,5,3,2.5,1e-320,0.18);
assert(all(isfinite(nearNeutralSpiral.spiralBank_deg)) && ...
    all(isfinite(nearNeutralSpiral.spiralRollRate_deg_s)) && ...
    all(isfinite(nearNeutralSpiral.spiralHeadingRate_deg_s)) && ...
    all(isfinite(nearNeutralSpiral.spiralHeadingChange_deg)) && ...
    isinf(nearNeutralSpiral.spiralTimeConstant_s) && ...
    isinf(nearNeutralSpiral.spiralHalfLife_s) && ...
    ~nearNeutralSpiral.spiralTimeScaleIsRepresentable && ...
    abs(nearNeutralSpiral.spiralHeadingChange_deg(end)- ...
    nearNeutralSpiral.gravity_mps2/nearNeutralSpiral.referenceTrueAirspeed_mps* ...
    nearNeutralSpiral.bankRelease_deg*nearNeutralSpiral.spiralTime_s(end))<tol, ...
    'A subnormal positive spiral rate must remain finite and numerically neutral.');
undampedDutch=model(2,5,3,2.5,0.025,0);
assert(undampedDutch.dutchRollDecayRate_per_s==0 && ...
    undampedDutch.dutchRollDecayPerPeriod_ratio==1 && ...
    max(undampedDutch.dutchRollModalEnergy_rad2_s2)- ...
    min(undampedDutch.dutchRollModalEnergy_rad2_s2)<tol && ...
    all(undampedDutch.dutchRollModalEnergyRate_rad2_s3==0), ...
    'Zero Dutch-roll damping must preserve modal energy.');

rollDecayRateSweep_per_s=[1.0 1.5 2.5 3.5 5.0];
rollTimeConstants=zeros(size(rollDecayRateSweep_per_s));
rollSettlingTimes=zeros(size(rollDecayRateSweep_per_s));
rollBankIncrements=zeros(size(rollDecayRateSweep_per_s));
rollSweepFixedFields={ ...
    'spiralTime_s','spiralBank_deg','spiralRollRate_deg_s', ...
    'spiralHeadingRate_deg_s','spiralHeadingChange_deg', ...
    'spiralTimeConstant_s','spiralHalfLife_s', ...
    'spiralTimeScaleIsRepresentable', ...
    'spiralBankRemainingAtEnd_ratio','spiralHeadingRange_deg', ...
    'isWithinSpiralBankLinearRange','spiralStabilityLabel', ...
    'dutchRollTime_s','dutchRollSideslip_deg', ...
    'dutchRollSideslipRate_rad_s','dutchRollSideslipAcceleration_rad_s2', ...
    'dutchRollYawRate_deg_s','dutchRollYawAcceleration_rad_s2', ...
    'dutchRollSideslipEnvelope_deg','dutchRollBetaKinematicResidual_rad_s', ...
    'dutchRollYawEquationResidual_rad_s2','dutchRollModalEnergy_rad2_s2', ...
    'dutchRollModalEnergyRate_rad2_s3','initialYawRate_rad_s', ...
    'initialYawRate_deg_s','initialSideslipRate_rad_s','rudderMoment_Nm', ...
    'dutchRollNaturalFrequency_rad_s','dutchRollDampedFrequency_rad_s', ...
    'dutchRollDecayRate_per_s','dutchRollDampedPeriod_s', ...
    'dutchRollDecayPerPeriod_ratio','dutchRollPeakSideslip_deg', ...
    'dutchRollPeakYawRate_deg_s','isWithinDutchRollSideslipLinearRange', ...
    'dutchRollDampingLabel','spiralToDutchTimeScaleRatio'};
for k=1:numel(rollDecayRateSweep_per_s)
    sample=model(2,5,3,rollDecayRateSweep_per_s(k),0.025,0.18);
    assert(sample.aileronPulse_deg==2 && sample.bankRelease_deg==5 && ...
        sample.rudderPulse_deg==3 && ...
        sample.spiralDecayRate_per_s==0.025 && ...
        sample.dutchRollDampingRatio==0.18, ...
        'Roll sweep must hold all excitation and other-mode inputs fixed.');
    for fieldIndex=1:numel(rollSweepFixedFields)
        fieldName=rollSweepFixedFields{fieldIndex};
        assert(isequaln(sample.(fieldName),first.(fieldName)), ...
            'Roll sweep changed unaffected output %s.',fieldName);
    end
    rollTimeConstants(k)=sample.rollTimeConstant_s;
    rollSettlingTimes(k)=sample.rollTwoPercentSettlingTime_s;
    rollBankIncrements(k)=sample.rollAsymptoticBankChange_deg;
end
assert(all(diff(rollTimeConstants)<0) && ...
    all(diff(rollSettlingTimes)<0) && ...
    all(diff(rollBankIncrements)<0), ...
    'Higher roll decay rate must shorten decay and reduce bank increment.');

dutchRollDampingSweep=[0.00 0.08 0.18 0.30 0.45];
dutchDecay=zeros(size(dutchRollDampingSweep));
dutchPeriods=zeros(size(dutchRollDampingSweep));
dutchSweepFixedFields={ ...
    'rollTime_s','rollRate_deg_s','rollRateDerivative_rad_s2', ...
    'rollBankChange_deg','initialRollRate_rad_s','initialRollRate_deg_s', ...
    'aileronMoment_Nm','rollAsymptoticBankChange_deg', ...
    'rollTimeConstant_s','rollHalfLife_s','rollTwoPercentSettlingTime_s', ...
    'rollPeakRate_deg_s','isWithinRollBankLinearRange', ...
    'spiralTime_s','spiralBank_deg','spiralRollRate_deg_s', ...
    'spiralHeadingRate_deg_s','spiralHeadingChange_deg', ...
    'spiralTimeConstant_s','spiralHalfLife_s', ...
    'spiralTimeScaleIsRepresentable', ...
    'spiralBankRemainingAtEnd_ratio','spiralHeadingRange_deg', ...
    'isWithinSpiralBankLinearRange','spiralStabilityLabel'};
for k=1:numel(dutchRollDampingSweep)
    sample=model(2,5,3,2.5,0.025,dutchRollDampingSweep(k));
    assert(sample.aileronPulse_deg==2 && sample.bankRelease_deg==5 && ...
        sample.rudderPulse_deg==3 && sample.rollDecayRate_per_s==2.5 && ...
        sample.spiralDecayRate_per_s==0.025, ...
        'Dutch-roll sweep must hold all excitation and other-mode inputs fixed.');
    for fieldIndex=1:numel(dutchSweepFixedFields)
        fieldName=dutchSweepFixedFields{fieldIndex};
        assert(isequaln(sample.(fieldName),first.(fieldName)), ...
            'Dutch-roll sweep changed unaffected output %s.',fieldName);
    end
    dutchDecay(k)=sample.dutchRollDecayPerPeriod_ratio;
    dutchPeriods(k)=sample.dutchRollDampedPeriod_s;
end
assert(dutchDecay(1)==1 && all(diff(dutchDecay)<0) && ...
    all(diff(dutchPeriods)>0), ...
    'More Dutch-roll damping must lower decay ratio and damped frequency.');

%% Deliberately broken spiral-stability sign
brokenSpiralBank_deg=first.bankRelease_deg* ...
    exp(+first.spiralDecayRate_per_s*first.spiralTime_s);
firstInvalidIndex=find(abs(brokenSpiralBank_deg)> ...
    first.bankLinearLimit_deg,1,'first');
assert(abs(brokenSpiralBank_deg(end)-100.4276846159384)<1e-10 && ...
    brokenSpiralBank_deg(end)>100*abs(first.spiralBank_deg(end)) && ...
    brokenSpiralBank_deg(end)>5*first.bankLinearLimit_deg && ...
    first.spiralTime_s(firstInvalidIndex)==44, ...
    'Reversing the spiral sign must create slow, out-of-domain divergence.');

%% Malformed inputs fail clearly, then a valid call recovers
expectFailure(@() model(-5.1,5,3,2.5,0.025,0.18), ...
    'P07:model:AileronPulseRange','aileron pulse below range');
expectFailure(@() model(5.1,5,3,2.5,0.025,0.18), ...
    'P07:model:AileronPulseRange','aileron pulse above range');
expectFailure(@() model(2,-10.1,3,2.5,0.025,0.18), ...
    'P07:model:BankReleaseRange','bank release below range');
expectFailure(@() model(2,10.1,3,2.5,0.025,0.18), ...
    'P07:model:BankReleaseRange','bank release above range');
expectFailure(@() model(2,5,-5.1,2.5,0.025,0.18), ...
    'P07:model:RudderPulseRange','rudder pulse below range');
expectFailure(@() model(2,5,5.1,2.5,0.025,0.18), ...
    'P07:model:RudderPulseRange','rudder pulse above range');
expectFailure(@() model(2,5,3,0.79,0.025,0.18), ...
    'P07:model:RollDecayRateRange','roll decay below range');
expectFailure(@() model(2,5,3,5.01,0.025,0.18), ...
    'P07:model:RollDecayRateRange','roll decay above range');
expectFailure(@() model(2,5,3,2.5,-0.001,0.18), ...
    'P07:model:NegativeSpiralDecayRate','negative spiral decay');
expectFailure(@() model(2,5,3,2.5,0.051,0.18), ...
    'P07:model:SpiralDecayRateRange','spiral decay above range');
expectFailure(@() model(2,5,3,2.5,0.025,-0.01), ...
    'P07:model:NegativeDutchRollDamping','negative Dutch-roll damping');
expectFailure(@() model(2,5,3,2.5,0.025,0.61), ...
    'P07:model:DutchRollDampingRange','Dutch-roll damping above range');
expectFailure(@() model([2 3],5,3,2.5,0.025,0.18),'','nonscalar aileron');
expectFailure(@() model(2,5+1i,3,2.5,0.025,0.18),'','complex bank release');
expectFailure(@() model(2,5,NaN,2.5,0.025,0.18),'','nonfinite rudder');
expectFailure(@() model(2,5,3,Inf,0.025,0.18),'','nonfinite roll decay');
afterFailure=model(2,5,3,2.5,0.025,0.18);
assert(isequaln(afterFailure,first), ...
    'Rejected inputs must not alter the next deterministic calculation.');

disp(['P07 checks passed: roll, spiral, and Dutch-roll identities, time scales, ' ...
    'isolated sweeps, limits, malformed inputs, recovery, and broken spiral sign.']);
end

function expectFailure(action,expectedIdentifier,label)
didFail=false;
try
    action();
catch exception
    didFail=true;
    if ~isempty(expectedIdentifier)
        assert(strcmp(exception.identifier,expectedIdentifier), ...
            'Expected %s to raise %s, but received %s.', ...
            label,expectedIdentifier,exception.identifier);
    end
end
assert(didFail,'Expected model to reject %s.',label);
end
