function out=model(arrivalRadius_m,courseResponseGain_per_s,bearingMode)
%MODEL Follow an ordered set of stationary North/East waypoints.
% Course is measured clockwise from North. Guidance uses the exact simulated
% N/E position as an ideal navigation estimate so waypoint sequencing,
% bearing geometry, and bounded course response remain visible.
arguments
    arrivalRadius_m (1,1) double {mustBeReal,mustBeFinite}=30
    courseResponseGain_per_s (1,1) double {mustBeReal,mustBeFinite}=0.8
    bearingMode (1,1) double {mustBeReal,mustBeFinite}=1
end

minimumArrivalRadius_m=10;
maximumArrivalRadius_m=80;
minimumCourseResponseGain_per_s=0;
maximumCourseResponseGain_per_s=1.2;
if arrivalRadius_m<minimumArrivalRadius_m || ...
        arrivalRadius_m>maximumArrivalRadius_m
    error('P18:model:ArrivalRadiusRange', ...
        'Arrival radius must be between 10 and 80 m inclusive.');
end
if courseResponseGain_per_s<minimumCourseResponseGain_per_s || ...
        courseResponseGain_per_s>maximumCourseResponseGain_per_s
    error('P18:model:CourseResponseGainRange', ...
        'Course-response gain must be between 0 and 1.2 1/s inclusive.');
end
if bearingMode~=1 && bearingMode~=-1
    error('P18:model:BearingMode', ...
        ['Bearing mode must be +1 for correct N/E geometry or -1 for ' ...
        'the deliberately broken swapped-component calculation.']);
end

sampleTime_s=0.1;
timeHorizon_s=100;
time_s=0:sampleTime_s:timeHorizon_s;
sampleCount=numel(time_s);
intervalCount=sampleCount-1;
groundSpeed_mps=25;
maximumCourseRate_radps=deg2rad(12);
initialCourse_rad=0;

% The fixed route has four nonzero, nonoverlapping legs. North and East are
% in meters. The vehicle begins exactly at waypoint 1 and initially points
% North toward waypoint 2.
waypointNorth_m=[0 400 400 100 100];
waypointEast_m=[0 0 300 300 650];
waypointCount=numel(waypointNorth_m);
legNorth_m=diff(waypointNorth_m);
legEast_m=diff(waypointEast_m);
legLength_m=hypot(legNorth_m,legEast_m);
plannedRouteLength_m=sum(legLength_m);
minimumLegLength_m=min(legLength_m);

northPosition_m=zeros(1,sampleCount);
eastPosition_m=zeros(1,sampleCount);
courseUnwrapped_rad=initialCourse_rad*ones(1,sampleCount);
courseWrapped_rad=initialCourse_rad*ones(1,sampleCount);
courseCommand_rad=zeros(1,sampleCount);
courseError_rad=zeros(1,sampleCount);
courseRateCommandUnclamped_radps=zeros(1,sampleCount);
courseRate_radps=zeros(1,sampleCount);
courseRateSaturated=false(1,sampleCount);
rangeToActiveWaypoint_m=zeros(1,sampleCount);
alongTrackDistance_m=zeros(1,sampleCount);
crossTrackError_m=zeros(1,sampleCount);
activeWaypointIndex=zeros(1,sampleCount);
activeLegIndex=zeros(1,sampleCount);
motionActive=false(1,sampleCount);

waypointCaptured=false(1,waypointCount);
waypointCaptured(1)=true;
waypointCaptureIndex=zeros(1,waypointCount);
waypointCaptureIndex(1)=1;
waypointCaptureTime_s=zeros(1,waypointCount);
waypointCaptureNorth_m=zeros(1,waypointCount);
waypointCaptureEast_m=zeros(1,waypointCount);
waypointCaptureRange_m=zeros(1,waypointCount);

currentWaypointIndex=2;
routeComplete=false;
missionCompletionIndex=0;
missionCompletionTime_s=timeHorizon_s+sampleTime_s;

for k=1:sampleCount
    if routeComplete
        % The route simulation has terminated. Retaining the terminal sample
        % makes every returned history fixed-size; it is bookkeeping, not a
        % claim that a constant-speed aircraft can stop instantaneously.
        activeWaypointIndex(k)=waypointCount+1;
        courseCommand_rad(k)=courseWrapped_rad(k);
        if k<sampleCount
            northPosition_m(k+1)=northPosition_m(k);
            eastPosition_m(k+1)=eastPosition_m(k);
            courseUnwrapped_rad(k+1)=courseUnwrapped_rad(k);
            courseWrapped_rad(k+1)=courseWrapped_rad(k);
        end
        continue
    end

    % Arrival is an inclusive Euclidean circle test. The while loop is
    % bounded by the five fixed waypoints; the declared radius bounds keep
    % adjacent arrival circles disjoint for this route.
    while currentWaypointIndex<=waypointCount
        deltaNorth_m=waypointNorth_m(currentWaypointIndex)- ...
            northPosition_m(k);
        deltaEast_m=waypointEast_m(currentWaypointIndex)- ...
            eastPosition_m(k);
        waypointRange_m=hypot(deltaNorth_m,deltaEast_m);
        if waypointRange_m>arrivalRadius_m
            break
        end
        waypointCaptured(currentWaypointIndex)=true;
        waypointCaptureIndex(currentWaypointIndex)=k;
        waypointCaptureTime_s(currentWaypointIndex)=time_s(k);
        waypointCaptureNorth_m(currentWaypointIndex)=northPosition_m(k);
        waypointCaptureEast_m(currentWaypointIndex)=eastPosition_m(k);
        waypointCaptureRange_m(currentWaypointIndex)=waypointRange_m;
        currentWaypointIndex=currentWaypointIndex+1;
        if currentWaypointIndex>waypointCount
            routeComplete=true;
            missionCompletionIndex=k;
            missionCompletionTime_s=time_s(k);
            break
        end
    end

    if routeComplete
        activeWaypointIndex(k)=waypointCount+1;
        courseCommand_rad(k)=courseWrapped_rad(k);
        if k<sampleCount
            northPosition_m(k+1)=northPosition_m(k);
            eastPosition_m(k+1)=eastPosition_m(k);
            courseUnwrapped_rad(k+1)=courseUnwrapped_rad(k);
            courseWrapped_rad(k+1)=courseWrapped_rad(k);
        end
        continue
    end

    activeWaypointIndex(k)=currentWaypointIndex;
    activeLegIndex(k)=currentWaypointIndex-1;
    deltaNorth_m=waypointNorth_m(currentWaypointIndex)- ...
        northPosition_m(k);
    deltaEast_m=waypointEast_m(currentWaypointIndex)- ...
        eastPosition_m(k);
    rangeToActiveWaypoint_m(k)=hypot(deltaNorth_m,deltaEast_m);

    legIndex=currentWaypointIndex-1;
    legUnitNorth=legNorth_m(legIndex)/legLength_m(legIndex);
    legUnitEast=legEast_m(legIndex)/legLength_m(legIndex);
    relativeNorth_m=northPosition_m(k)-waypointNorth_m(legIndex);
    relativeEast_m=eastPosition_m(k)-waypointEast_m(legIndex);
    alongTrackDistance_m(k)=relativeNorth_m*legUnitNorth+ ...
        relativeEast_m*legUnitEast;
    % Positive cross-track is to the right of the directed N/E leg.
    crossTrackError_m(k)=relativeNorth_m*(-legUnitEast)+ ...
        relativeEast_m*legUnitNorth;

    if bearingMode==1
        % atan2(East,North) gives course clockwise from North.
        courseCommand_rad(k)=atan2(deltaEast_m,deltaNorth_m);
    else
        % Deliberately broken: swapping the arguments rotates or reflects
        % the N/E meaning. A due-North target commands +90 deg (East).
        courseCommand_rad(k)=atan2(deltaNorth_m,deltaEast_m);
    end
    courseError_rad(k)=mod( ...
        courseCommand_rad(k)-courseWrapped_rad(k)+pi,2*pi)-pi;
    courseRateCommandUnclamped_radps(k)= ...
        courseResponseGain_per_s*courseError_rad(k);
    courseRate_radps(k)=min(max(courseRateCommandUnclamped_radps(k), ...
        -maximumCourseRate_radps),maximumCourseRate_radps);
    courseRateSaturated(k)=abs(courseRateCommandUnclamped_radps(k))> ...
        maximumCourseRate_radps;
    motionActive(k)=true;

    % Fixed-step planar point-mass propagation. Course, rather than a bank
    % or body-rate state, is the reduced-order response at this lesson's
    % boundary. Zero wind makes ground track equal course.
    if k<sampleCount
        northPosition_m(k+1)=northPosition_m(k)+ ...
            sampleTime_s*groundSpeed_mps*cos(courseUnwrapped_rad(k));
        eastPosition_m(k+1)=eastPosition_m(k)+ ...
            sampleTime_s*groundSpeed_mps*sin(courseUnwrapped_rad(k));
        courseUnwrapped_rad(k+1)=courseUnwrapped_rad(k)+ ...
            sampleTime_s*courseRate_radps(k);
        courseWrapped_rad(k+1)=mod(courseUnwrapped_rad(k+1)+pi,2*pi)-pi;
    end
end

motionIntervalMask=motionActive(1:intervalCount);
flownDistance_m=sum(hypot(diff(northPosition_m),diff(eastPosition_m)));
activeCourseError_deg=rad2deg(courseError_rad(motionActive));
activeCrossTrackError_m=crossTrackError_m(motionActive);
if isempty(activeCourseError_deg)
    courseErrorRMS_deg=0;
    peakAbsoluteCourseError_deg=0;
    courseRateSaturationFraction=0;
    crossTrackRMS_m=0;
    peakAbsoluteCrossTrackError_m=0;
else
    courseErrorRMS_deg=sqrt(mean(activeCourseError_deg.^2));
    peakAbsoluteCourseError_deg=max(abs(activeCourseError_deg));
    courseRateSaturationFraction=sum(courseRateSaturated(motionActive))/ ...
        sum(motionActive);
    crossTrackRMS_m=sqrt(mean(activeCrossTrackError_m.^2));
    peakAbsoluteCrossTrackError_m=max(abs(activeCrossTrackError_m));
end

minimumRangeToWaypoint_m=zeros(1,waypointCount);
for waypointIndex=1:waypointCount
    minimumRangeToWaypoint_m(waypointIndex)=min(hypot( ...
        northPosition_m-waypointNorth_m(waypointIndex), ...
        eastPosition_m-waypointEast_m(waypointIndex)));
end
finalTargetDistance_m=hypot( ...
    northPosition_m(end)-waypointNorth_m(end), ...
    eastPosition_m(end)-waypointEast_m(end));

if bearingMode==1
    bearingModeName='correct atan2(delta East,delta North)';
else
    bearingModeName='BROKEN atan2(delta North,delta East)';
end

out=struct( ...
    'arrivalRadius_m',arrivalRadius_m, ...
    'courseResponseGain_per_s',courseResponseGain_per_s, ...
    'bearingMode',bearingMode, ...
    'bearingModeName',bearingModeName, ...
    'minimumArrivalRadius_m',minimumArrivalRadius_m, ...
    'maximumArrivalRadius_m',maximumArrivalRadius_m, ...
    'minimumCourseResponseGain_per_s', ...
    minimumCourseResponseGain_per_s, ...
    'maximumCourseResponseGain_per_s', ...
    maximumCourseResponseGain_per_s, ...
    'sampleTime_s',sampleTime_s, ...
    'timeHorizon_s',timeHorizon_s, ...
    'time_s',time_s, ...
    'sampleCount',sampleCount, ...
    'intervalCount',intervalCount, ...
    'groundSpeed_mps',groundSpeed_mps, ...
    'maximumCourseRate_degps',rad2deg(maximumCourseRate_radps), ...
    'initialCourse_deg',rad2deg(initialCourse_rad), ...
    'waypointNorth_m',waypointNorth_m, ...
    'waypointEast_m',waypointEast_m, ...
    'waypointCount',waypointCount, ...
    'legNorth_m',legNorth_m, ...
    'legEast_m',legEast_m, ...
    'legLength_m',legLength_m, ...
    'minimumLegLength_m',minimumLegLength_m, ...
    'plannedRouteLength_m',plannedRouteLength_m, ...
    'northPosition_m',northPosition_m, ...
    'eastPosition_m',eastPosition_m, ...
    'courseUnwrapped_deg',rad2deg(courseUnwrapped_rad), ...
    'courseWrapped_deg',rad2deg(courseWrapped_rad), ...
    'course_deg',rad2deg(courseWrapped_rad), ...
    'courseCommand_deg',rad2deg(courseCommand_rad), ...
    'courseError_deg',rad2deg(courseError_rad), ...
    'courseRateCommandUnclamped_degps', ...
    rad2deg(courseRateCommandUnclamped_radps), ...
    'courseRate_degps',rad2deg(courseRate_radps), ...
    'courseRateSaturated',courseRateSaturated, ...
    'rangeToActiveWaypoint_m',rangeToActiveWaypoint_m, ...
    'alongTrackDistance_m',alongTrackDistance_m, ...
    'crossTrackError_m',crossTrackError_m, ...
    'activeWaypointIndex',activeWaypointIndex, ...
    'activeLegIndex',activeLegIndex, ...
    'motionActive',motionActive, ...
    'motionActiveSampleCount',sum(motionActive), ...
    'motionActiveIntervalCount',sum(motionIntervalMask), ...
    'waypointCaptured',waypointCaptured, ...
    'waypointCaptureIndex',waypointCaptureIndex, ...
    'waypointCaptureTime_s',waypointCaptureTime_s, ...
    'waypointCaptureNorth_m',waypointCaptureNorth_m, ...
    'waypointCaptureEast_m',waypointCaptureEast_m, ...
    'waypointCaptureRange_m',waypointCaptureRange_m, ...
    'waypointCapturedCount',sum(waypointCaptured), ...
    'targetWaypointCapturedCount',sum(waypointCaptured(2:end)), ...
    'routeComplete',routeComplete, ...
    'missionCompletionIndex',missionCompletionIndex, ...
    'missionCompletionTime_s',missionCompletionTime_s, ...
    'flownDistance_m',flownDistance_m, ...
    'courseErrorRMS_deg',courseErrorRMS_deg, ...
    'peakAbsoluteCourseError_deg',peakAbsoluteCourseError_deg, ...
    'courseRateSaturationFraction',courseRateSaturationFraction, ...
    'crossTrackRMS_m',crossTrackRMS_m, ...
    'peakAbsoluteCrossTrackError_m',peakAbsoluteCrossTrackError_m, ...
    'minimumRangeToWaypoint_m',minimumRangeToWaypoint_m, ...
    'finalTargetDistance_m',finalTargetDistance_m, ...
    'bearingEquation',[ ...
        'chi_command=atan2(delta East,delta North); course is ' ...
        'clockwise from North'], ...
    'courseResponseEquation',[ ...
        'e_chi=wrap(chi_command-chi); chi_dot=' ...
        'sat(K_chi*e_chi,+/-12 deg/s)'], ...
    'positionEquation',[ ...
        'North_dot=V_g*cos(chi); East_dot=V_g*sin(chi)'], ...
    'arrivalEquation',[ ...
        'advance when hypot(delta North,delta East)<=arrival radius'], ...
    'navigationInputDefinition',[ ...
        'exact simulated N/E position stands in for an ideal P17-style ' ...
        'navigation estimate; no P17 runtime arrays are consumed'], ...
    'brokenCaseDefinition',[ ...
        'swap atan2 arguments while route, initial position, position ' ...
        'equations, speed, response, arrival logic, limits, and grid stay fixed'], ...
    'analysisScope',[ ...
        'fixed-speed zero-wind planar stationary-waypoint teaching model; ' ...
        'no estimator error, moving target, pursuit/intercept/lead law, ' ...
        'path optimization, bank dynamics, geodesy, hardware, or aircraft fidelity']);
end
