function run_checks
%RUN_CHECKS P18 independent waypoint geometry and recovery checks.
clear model;
modelFcn=@model;
absoluteTolerance=1e-10;
trajectoryTolerance=1e-8;

%% Deterministic baseline identity, fixed resources, and route definition
baseline=modelFcn(30,0.8,1);
repeat=modelFcn(30,0.8,1);
historyFields={'time_s','northPosition_m','eastPosition_m', ...
    'courseUnwrapped_deg','courseWrapped_deg','courseCommand_deg', ...
    'courseError_deg','courseRateCommandUnclamped_degps', ...
    'courseRate_degps','courseRateSaturated', ...
    'rangeToActiveWaypoint_m','alongTrackDistance_m', ...
    'crossTrackError_m','activeWaypointIndex','activeLegIndex', ...
    'motionActive','waypointCaptured','waypointCaptureIndex', ...
    'waypointCaptureTime_s','waypointCaptureNorth_m', ...
    'waypointCaptureEast_m','waypointCaptureRange_m'};
for k=1:numel(historyFields)
    field=historyFields{k};
    assert(isequal(baseline.(field),repeat.(field)), ...
        ['Repeated baseline calls must exactly reproduce ' field '.']);
end
assert(baseline.sampleCount==1001 && baseline.intervalCount==1000 && ...
    baseline.sampleTime_s==0.1 && baseline.timeHorizon_s==100 && ...
    isequal(baseline.time_s,0:0.1:100), ...
    'The fixed time grid or resource count changed.');
assert(baseline.arrivalRadius_m==30 && ...
    baseline.courseResponseGain_per_s==0.8 && ...
    baseline.bearingMode==1 && baseline.groundSpeed_mps==25 && ...
    baseline.maximumCourseRate_degps==12 && ...
    baseline.initialCourse_deg==0, ...
    'Baseline input, speed, rate limit, or initial course changed.');

expectedWaypointNorth_m=[0 400 400 100 100];
expectedWaypointEast_m=[0 0 300 300 650];
expectedLegNorth_m=diff(expectedWaypointNorth_m);
expectedLegEast_m=diff(expectedWaypointEast_m);
expectedLegLength_m=hypot(expectedLegNorth_m,expectedLegEast_m);
assert(isequal(baseline.waypointNorth_m,expectedWaypointNorth_m) && ...
    isequal(baseline.waypointEast_m,expectedWaypointEast_m) && ...
    isequal(baseline.legNorth_m,expectedLegNorth_m) && ...
    isequal(baseline.legEast_m,expectedLegEast_m) && ...
    isequal(baseline.legLength_m,[400 300 300 350]) && ...
    baseline.waypointCount==5 && ...
    baseline.minimumLegLength_m==300 && ...
    baseline.plannedRouteLength_m==1350 && ...
    2*baseline.maximumArrivalRadius_m<baseline.minimumLegLength_m, ...
    'The fixed route, leg geometry, or nonoverlap bound changed.');

%% Independently reconstruct every event, bearing, response, and state update
sampleCount=baseline.sampleCount;
expectedNorth_m=zeros(1,sampleCount);
expectedEast_m=zeros(1,sampleCount);
expectedCourseUnwrapped_rad=zeros(1,sampleCount);
expectedCourseWrapped_rad=zeros(1,sampleCount);
expectedCommand_rad=zeros(1,sampleCount);
expectedError_rad=zeros(1,sampleCount);
expectedRawRate_radps=zeros(1,sampleCount);
expectedRate_radps=zeros(1,sampleCount);
expectedSaturated=false(1,sampleCount);
expectedRange_m=zeros(1,sampleCount);
expectedAlongTrack_m=zeros(1,sampleCount);
expectedCrossTrack_m=zeros(1,sampleCount);
expectedActiveWaypoint=zeros(1,sampleCount);
expectedActiveLeg=zeros(1,sampleCount);
expectedMotionActive=false(1,sampleCount);
expectedCaptured=false(1,baseline.waypointCount);
expectedCaptured(1)=true;
expectedCaptureIndex=zeros(1,baseline.waypointCount);
expectedCaptureIndex(1)=1;
expectedCaptureTime_s=zeros(1,baseline.waypointCount);
expectedCaptureNorth_m=zeros(1,baseline.waypointCount);
expectedCaptureEast_m=zeros(1,baseline.waypointCount);
expectedCaptureRange_m=zeros(1,baseline.waypointCount);
currentWaypoint=2;
expectedComplete=false;
expectedCompletionIndex=0;
expectedCompletionTime_s=baseline.timeHorizon_s+baseline.sampleTime_s;
maximumRate_radps=deg2rad(baseline.maximumCourseRate_degps);

for k=1:sampleCount
    if expectedComplete
        expectedActiveWaypoint(k)=baseline.waypointCount+1;
        expectedCommand_rad(k)=expectedCourseWrapped_rad(k);
        if k<sampleCount
            expectedNorth_m(k+1)=expectedNorth_m(k);
            expectedEast_m(k+1)=expectedEast_m(k);
            expectedCourseUnwrapped_rad(k+1)= ...
                expectedCourseUnwrapped_rad(k);
            expectedCourseWrapped_rad(k+1)=expectedCourseWrapped_rad(k);
        end
        continue
    end

    deltaNorth=expectedWaypointNorth_m(currentWaypoint)-expectedNorth_m(k);
    deltaEast=expectedWaypointEast_m(currentWaypoint)-expectedEast_m(k);
    range=hypot(deltaNorth,deltaEast);
    if range<=baseline.arrivalRadius_m
        expectedCaptured(currentWaypoint)=true;
        expectedCaptureIndex(currentWaypoint)=k;
        expectedCaptureTime_s(currentWaypoint)=baseline.time_s(k);
        expectedCaptureNorth_m(currentWaypoint)=expectedNorth_m(k);
        expectedCaptureEast_m(currentWaypoint)=expectedEast_m(k);
        expectedCaptureRange_m(currentWaypoint)=range;
        currentWaypoint=currentWaypoint+1;
        if currentWaypoint>baseline.waypointCount
            expectedComplete=true;
            expectedCompletionIndex=k;
            expectedCompletionTime_s=baseline.time_s(k);
        end
    end

    if expectedComplete
        expectedActiveWaypoint(k)=baseline.waypointCount+1;
        expectedCommand_rad(k)=expectedCourseWrapped_rad(k);
        if k<sampleCount
            expectedNorth_m(k+1)=expectedNorth_m(k);
            expectedEast_m(k+1)=expectedEast_m(k);
            expectedCourseUnwrapped_rad(k+1)= ...
                expectedCourseUnwrapped_rad(k);
            expectedCourseWrapped_rad(k+1)=expectedCourseWrapped_rad(k);
        end
        continue
    end

    expectedActiveWaypoint(k)=currentWaypoint;
    expectedActiveLeg(k)=currentWaypoint-1;
    deltaNorth=expectedWaypointNorth_m(currentWaypoint)-expectedNorth_m(k);
    deltaEast=expectedWaypointEast_m(currentWaypoint)-expectedEast_m(k);
    expectedRange_m(k)=hypot(deltaNorth,deltaEast);
    legIndex=currentWaypoint-1;
    unitNorth=expectedLegNorth_m(legIndex)/expectedLegLength_m(legIndex);
    unitEast=expectedLegEast_m(legIndex)/expectedLegLength_m(legIndex);
    relativeNorth=expectedNorth_m(k)-expectedWaypointNorth_m(legIndex);
    relativeEast=expectedEast_m(k)-expectedWaypointEast_m(legIndex);
    expectedAlongTrack_m(k)=relativeNorth*unitNorth+relativeEast*unitEast;
    expectedCrossTrack_m(k)=relativeNorth*(-unitEast)+relativeEast*unitNorth;
    expectedCommand_rad(k)=atan2(deltaEast,deltaNorth);
    expectedError_rad(k)=mod(expectedCommand_rad(k)- ...
        expectedCourseWrapped_rad(k)+pi,2*pi)-pi;
    expectedRawRate_radps(k)=baseline.courseResponseGain_per_s* ...
        expectedError_rad(k);
    expectedRate_radps(k)=min(max(expectedRawRate_radps(k), ...
        -maximumRate_radps),maximumRate_radps);
    expectedSaturated(k)=abs(expectedRawRate_radps(k))>maximumRate_radps;
    expectedMotionActive(k)=true;
    if k<sampleCount
        expectedNorth_m(k+1)=expectedNorth_m(k)+ ...
            baseline.sampleTime_s*baseline.groundSpeed_mps* ...
            cos(expectedCourseUnwrapped_rad(k));
        expectedEast_m(k+1)=expectedEast_m(k)+ ...
            baseline.sampleTime_s*baseline.groundSpeed_mps* ...
            sin(expectedCourseUnwrapped_rad(k));
        expectedCourseUnwrapped_rad(k+1)= ...
            expectedCourseUnwrapped_rad(k)+ ...
            baseline.sampleTime_s*expectedRate_radps(k);
        expectedCourseWrapped_rad(k+1)=mod( ...
            expectedCourseUnwrapped_rad(k+1)+pi,2*pi)-pi;
    end
end

assert(max(abs(baseline.northPosition_m-expectedNorth_m))< ...
    trajectoryTolerance && ...
    max(abs(baseline.eastPosition_m-expectedEast_m))< ...
    trajectoryTolerance && ...
    max(abs(baseline.courseUnwrapped_deg- ...
    rad2deg(expectedCourseUnwrapped_rad)))<trajectoryTolerance && ...
    max(abs(baseline.courseWrapped_deg- ...
    rad2deg(expectedCourseWrapped_rad)))<trajectoryTolerance && ...
    max(abs(baseline.courseCommand_deg- ...
    rad2deg(expectedCommand_rad)))<trajectoryTolerance && ...
    max(abs(baseline.courseError_deg- ...
    rad2deg(expectedError_rad)))<trajectoryTolerance && ...
    max(abs(baseline.courseRateCommandUnclamped_degps- ...
    rad2deg(expectedRawRate_radps)))<trajectoryTolerance && ...
    max(abs(baseline.courseRate_degps- ...
    rad2deg(expectedRate_radps)))<trajectoryTolerance, ...
    'Bearing, course response, or planar propagation failed reconstruction.');
assert(isequal(baseline.courseRateSaturated,expectedSaturated) && ...
    max(abs(baseline.rangeToActiveWaypoint_m-expectedRange_m))< ...
    trajectoryTolerance && ...
    max(abs(baseline.alongTrackDistance_m-expectedAlongTrack_m))< ...
    trajectoryTolerance && ...
    max(abs(baseline.crossTrackError_m-expectedCrossTrack_m))< ...
    trajectoryTolerance && ...
    isequal(baseline.activeWaypointIndex,expectedActiveWaypoint) && ...
    isequal(baseline.activeLegIndex,expectedActiveLeg) && ...
    isequal(baseline.motionActive,expectedMotionActive), ...
    'Range, leg coordinates, active target, or motion mask failed reconstruction.');
assert(isequal(baseline.waypointCaptured,expectedCaptured) && ...
    isequal(baseline.waypointCaptureIndex,expectedCaptureIndex) && ...
    max(abs(baseline.waypointCaptureTime_s- ...
    expectedCaptureTime_s))<absoluteTolerance && ...
    max(abs(baseline.waypointCaptureNorth_m- ...
    expectedCaptureNorth_m))<trajectoryTolerance && ...
    max(abs(baseline.waypointCaptureEast_m- ...
    expectedCaptureEast_m))<trajectoryTolerance && ...
    max(abs(baseline.waypointCaptureRange_m- ...
    expectedCaptureRange_m))<trajectoryTolerance && ...
    baseline.routeComplete==expectedComplete && ...
    baseline.missionCompletionIndex==expectedCompletionIndex && ...
    abs(baseline.missionCompletionTime_s- ...
    expectedCompletionTime_s)<absoluteTolerance, ...
    'Ordered inclusive waypoint capture or terminal event changed.');

%% Reconstruct metrics and retain the deterministic baseline signature
expectedStepDistance=hypot(diff(expectedNorth_m),diff(expectedEast_m));
expectedFlownDistance=sum(expectedStepDistance);
activeErrors_deg=rad2deg(expectedError_rad(expectedMotionActive));
activeCrossTrack=expectedCrossTrack_m(expectedMotionActive);
expectedCourseRMS=sqrt(mean(activeErrors_deg.^2));
expectedCoursePeak=max(abs(activeErrors_deg));
expectedCrossTrackRMS=sqrt(mean(activeCrossTrack.^2));
expectedCrossTrackPeak=max(abs(activeCrossTrack));
expectedSaturationFraction=sum(expectedSaturated(expectedMotionActive))/ ...
    sum(expectedMotionActive);
expectedMinimumRange=zeros(1,baseline.waypointCount);
for waypointIndex=1:baseline.waypointCount
    expectedMinimumRange(waypointIndex)=min(hypot( ...
        expectedNorth_m-expectedWaypointNorth_m(waypointIndex), ...
        expectedEast_m-expectedWaypointEast_m(waypointIndex)));
end
expectedFinalRange=hypot(expectedNorth_m(end)- ...
    expectedWaypointNorth_m(end),expectedEast_m(end)- ...
    expectedWaypointEast_m(end));
assert(abs(baseline.flownDistance_m-expectedFlownDistance)< ...
    trajectoryTolerance && ...
    abs(baseline.courseErrorRMS_deg-expectedCourseRMS)< ...
    trajectoryTolerance && ...
    abs(baseline.peakAbsoluteCourseError_deg-expectedCoursePeak)< ...
    trajectoryTolerance && ...
    abs(baseline.courseRateSaturationFraction- ...
    expectedSaturationFraction)<absoluteTolerance && ...
    abs(baseline.crossTrackRMS_m-expectedCrossTrackRMS)< ...
    trajectoryTolerance && ...
    abs(baseline.peakAbsoluteCrossTrackError_m- ...
    expectedCrossTrackPeak)<trajectoryTolerance && ...
    max(abs(baseline.minimumRangeToWaypoint_m-expectedMinimumRange))< ...
    trajectoryTolerance && ...
    abs(baseline.finalTargetDistance_m-expectedFinalRange)< ...
    trajectoryTolerance, ...
    'Reported route and response metrics must reconstruct from histories.');
activeLeg=baseline.activeLegIndex(baseline.motionActive);
remainingAlongTrack_m=baseline.legLength_m(activeLeg)- ...
    baseline.alongTrackDistance_m(baseline.motionActive);
rangeFromLegCoordinates_m=hypot(remainingAlongTrack_m, ...
    baseline.crossTrackError_m(baseline.motionActive));
assert(max(abs(rangeFromLegCoordinates_m- ...
    baseline.rangeToActiveWaypoint_m(baseline.motionActive)))< ...
    trajectoryTolerance && ...
    any(baseline.crossTrackError_m(baseline.motionActive)>0) && ...
    any(baseline.crossTrackError_m(baseline.motionActive)<0), ...
    ['Active-leg along/cross coordinates must reconstruct target range ' ...
    'and retain both signed sides of the planned route.']);

expectedCaptureTimes_s=[0 14.8 29.4 41.7 59.2];
expectedCaptureRanges_m=[0 30 28.61267913300444 ...
    29.413712525799518 27.827713892891673];
expectedCaptureNorth_m=[0 370 416.35192787405634 ...
    128.96826296595358 85.39034936789741];
expectedCaptureEast_m=[0 0 276.5202244054606 ...
    305.09962991654663 626.3158329487284];
assert(isequal(baseline.waypointCaptureIndex,[1 149 295 418 593]) && ...
    max(abs(baseline.waypointCaptureTime_s- ...
    expectedCaptureTimes_s))<trajectoryTolerance && ...
    max(abs(baseline.waypointCaptureRange_m- ...
    expectedCaptureRanges_m))<trajectoryTolerance && ...
    max(abs(baseline.waypointCaptureNorth_m- ...
    expectedCaptureNorth_m))<trajectoryTolerance && ...
    max(abs(baseline.waypointCaptureEast_m- ...
    expectedCaptureEast_m))<trajectoryTolerance && ...
    baseline.targetWaypointCapturedCount==4 && baseline.routeComplete && ...
    baseline.missionCompletionIndex==593 && ...
    abs(baseline.missionCompletionTime_s-59.2)<absoluteTolerance && ...
    baseline.motionActiveSampleCount==592 && ...
    baseline.motionActiveIntervalCount==592 && ...
    abs(baseline.flownDistance_m-1480)<trajectoryTolerance && ...
    abs(baseline.courseErrorRMS_deg-33.914338204209656)<1e-8 && ...
    abs(baseline.peakAbsoluteCourseError_deg- ...
    95.04123761897495)<1e-8 && ...
    sum(baseline.courseRateSaturated)==223 && ...
    abs(baseline.courseRateSaturationFraction-223/592)< ...
    absoluteTolerance && ...
    abs(baseline.crossTrackRMS_m-52.26952755669431)<1e-8 && ...
    abs(baseline.peakAbsoluteCrossTrackError_m- ...
    112.03266029039757)<1e-8 && ...
    abs(baseline.finalTargetDistance_m-27.827713892891673)<1e-8, ...
    'The deterministic baseline capture or response signature changed.');

%% Limiting cases: inclusive arrival, wrap, turn scale, and zero response
arrivalBoundary=baseline.arrivalRadius_m;
assert(arrivalBoundary<=baseline.arrivalRadius_m && ...
    ~(arrivalBoundary+eps(arrivalBoundary)<=baseline.arrivalRadius_m), ...
    'Arrival must be inclusive without a hidden tolerance.');
zeroError=mod(0+pi,2*pi)-pi;
halfTurn=mod(pi+pi,2*pi)-pi;
assert(zeroError==0 && halfTurn==-pi && ...
    baseline.courseResponseGain_per_s*zeroError==0, ...
    'Zero-error or half-open circular limits changed.');
turnRadiusScale_m=baseline.groundSpeed_mps/ ...
    deg2rad(baseline.maximumCourseRate_degps);
assert(abs(turnRadiusScale_m-119.36620731892151)<1e-10, ...
    'The fixed-speed saturated turn-radius scale changed.');
movingSteps=expectedStepDistance(expectedMotionActive(1:end-1));
terminalSteps=expectedStepDistance(~expectedMotionActive(1:end-1));
assert(max(abs(movingSteps-2.5))<trajectoryTolerance && ...
    all(terminalSteps==0), ...
    'Moving increments must be 2.5 m and terminal hold increments zero.');

zeroResponse=modelFcn(30,0,1);
assert(~zeroResponse.routeComplete && ...
    zeroResponse.targetWaypointCapturedCount==1 && ...
    isequal(zeroResponse.waypointCaptured,[true true false false false]) && ...
    zeroResponse.missionCompletionIndex==0 && ...
    zeroResponse.missionCompletionTime_s==100.1 && ...
    all(zeroResponse.activeWaypointIndex(149:end)==3) && ...
    max(abs(zeroResponse.northPosition_m-25*zeroResponse.time_s))< ...
    trajectoryTolerance && all(zeroResponse.eastPosition_m==0) && ...
    all(zeroResponse.courseUnwrapped_deg==0) && ...
    all(zeroResponse.courseRate_degps==0) && ...
    abs(zeroResponse.flownDistance_m-2500)<trajectoryTolerance, ...
    'Zero response gain must retain the exact open-course-loop limit.');

%% Lever 1: arrival-radius sweep with response and geometry isolated
arrivalRadiusSweep_m=[10 20 30 50 80];
expectedCompletionTimes_s=[63.1 61.0 59.2 55.5 50.0];
expectedFlownDistances_m=[1577.5 1525 1480 1387.5 1250];
observedCompletionTimes_s=zeros(size(arrivalRadiusSweep_m));
observedFlownDistances_m=zeros(size(arrivalRadiusSweep_m));
for k=1:numel(arrivalRadiusSweep_m)
    sample=modelFcn(arrivalRadiusSweep_m(k),0.8,1);
    observedCompletionTimes_s(k)=sample.missionCompletionTime_s;
    observedFlownDistances_m(k)=sample.flownDistance_m;
    assert(isequal(sample.waypointNorth_m,baseline.waypointNorth_m) && ...
        isequal(sample.waypointEast_m,baseline.waypointEast_m) && ...
        isequal(sample.time_s,baseline.time_s) && ...
        sample.courseResponseGain_per_s== ...
        baseline.courseResponseGain_per_s && ...
        sample.bearingMode==baseline.bearingMode && ...
        sample.groundSpeed_mps==baseline.groundSpeed_mps && ...
        sample.maximumCourseRate_degps== ...
        baseline.maximumCourseRate_degps && ...
        sample.initialCourse_deg==baseline.initialCourse_deg, ...
        'The arrival-radius sweep changed a nonlever route or response input.');
    assert(sample.routeComplete && sample.targetWaypointCapturedCount==4 && ...
        all(sample.waypointCaptureRange_m(2:end)<= ...
        arrivalRadiusSweep_m(k)+trajectoryTolerance) && ...
        all(sample.waypointCaptureRange_m(2:end)> ...
        arrivalRadiusSweep_m(k)-2.5-trajectoryTolerance) && ...
        abs(sample.flownDistance_m-25* ...
        sample.missionCompletionTime_s)<trajectoryTolerance, ...
        'Each radius case must complete with sampled inclusive captures.');
end
assert(max(abs(observedCompletionTimes_s- ...
    expectedCompletionTimes_s))<trajectoryTolerance && ...
    max(abs(observedFlownDistances_m- ...
    expectedFlownDistances_m))<trajectoryTolerance && ...
    all(diff(observedCompletionTimes_s)<0) && ...
    all(diff(observedFlownDistances_m)<0), ...
    'Arrival-radius sweep completion and corner-cutting signature changed.');

%% Lever 2: response-gain sweep with route and arrival logic isolated
courseResponseGainSweep_per_s=[0 0.2 0.4 0.8 1.2];
expectedRouteComplete=[false true true true true];
expectedTargetCaptured=[1 4 4 4 4];
expectedGainCompletionTimes_s=[100.1 65.6 60.0 59.2 59.1];
expectedGainFlownDistances_m=[2500 1640 1500 1480 1477.5];
expectedSaturationCounts=[0 109 177 223 239];
observedSaturationFractions=zeros(size(courseResponseGainSweep_per_s));
for k=1:numel(courseResponseGainSweep_per_s)
    sample=modelFcn(30,courseResponseGainSweep_per_s(k),1);
    assert(isequal(sample.waypointNorth_m,baseline.waypointNorth_m) && ...
        isequal(sample.waypointEast_m,baseline.waypointEast_m) && ...
        isequal(sample.time_s,baseline.time_s) && ...
        sample.arrivalRadius_m==baseline.arrivalRadius_m && ...
        sample.bearingMode==baseline.bearingMode && ...
        sample.groundSpeed_mps==baseline.groundSpeed_mps && ...
        sample.maximumCourseRate_degps== ...
        baseline.maximumCourseRate_degps && ...
        sample.initialCourse_deg==baseline.initialCourse_deg, ...
        'The response-gain sweep changed a nonlever route or arrival input.');
    assert(sample.routeComplete==expectedRouteComplete(k) && ...
        sample.targetWaypointCapturedCount==expectedTargetCaptured(k) && ...
        abs(sample.missionCompletionTime_s- ...
        expectedGainCompletionTimes_s(k))<trajectoryTolerance && ...
        abs(sample.flownDistance_m- ...
        expectedGainFlownDistances_m(k))<trajectoryTolerance && ...
        sum(sample.courseRateSaturated)==expectedSaturationCounts(k), ...
        'The response-gain completion or saturation signature changed.');
    observedSaturationFractions(k)=sample.courseRateSaturationFraction;
end
assert(all(diff(observedSaturationFractions)>=0) && ...
    observedSaturationFractions(1)==0 && ...
    abs(observedSaturationFractions(4)-223/592)<absoluteTolerance, ...
    'Higher gain should reach the unchanged course-rate limit more often.');

%% Broken N/E bearing isolation, rollback, and deterministic recovery
broken=modelFcn(30,0.8,-1);
for field={'arrivalRadius_m','courseResponseGain_per_s', ...
        'sampleTime_s','timeHorizon_s','time_s','groundSpeed_mps', ...
        'maximumCourseRate_degps','initialCourse_deg', ...
        'waypointNorth_m','waypointEast_m','legNorth_m','legEast_m', ...
        'legLength_m','plannedRouteLength_m'}
    name=field{1};
    assert(isequal(broken.(name),baseline.(name)), ...
        ['Broken mode must preserve nonbearing field ' name '.']);
end
assert(baseline.courseCommand_deg(1)==0 && ...
    abs(broken.courseCommand_deg(1)-90)<absoluteTolerance && ...
    ~broken.routeComplete && broken.targetWaypointCapturedCount==0 && ...
    isequal(broken.waypointCaptured,[true false false false false]) && ...
    all(broken.activeWaypointIndex==2) && ...
    abs(broken.minimumRangeToWaypoint_m(2)- ...
    296.8687930873698)<1e-8 && ...
    abs(broken.northPosition_m(end)+1429.641274946602)<1e-8 && ...
    abs(broken.eastPosition_m(end)-1817.972989561882)<1e-8 && ...
    abs(broken.flownDistance_m-2500)<trajectoryTolerance, ...
    'Swapped bearing must create the isolated wrong-cardinal-direction failure.');
rollback=modelFcn(30,0.8,1);
assert(isequal(rollback.northPosition_m,baseline.northPosition_m) && ...
    isequal(rollback.eastPosition_m,baseline.eastPosition_m) && ...
    isequal(rollback.courseCommand_deg,baseline.courseCommand_deg) && ...
    isequal(rollback.waypointCaptured,baseline.waypointCaptured), ...
    'Correct mode after broken mode must be exact stateless rollback.');

%% Malformed input rejection and deterministic recovery
invalidCalls={ ...
    @() modelFcn(9.999999,0.8,1), ...
    @() modelFcn(80.000001,0.8,1), ...
    @() modelFcn([30 31],0.8,1), ...
    @() modelFcn(30+1i,0.8,1), ...
    @() modelFcn(NaN,0.8,1), ...
    @() modelFcn(Inf,0.8,1), ...
    @() modelFcn(30,-eps,1), ...
    @() modelFcn(30,1.200001,1), ...
    @() modelFcn(30,[0.8 0.9],1), ...
    @() modelFcn(30,0.8+1i,1), ...
    @() modelFcn(30,NaN,1), ...
    @() modelFcn(30,Inf,1), ...
    @() modelFcn(30,0.8,-2), ...
    @() modelFcn(30,0.8,0), ...
    @() modelFcn(30,0.8,2), ...
    @() modelFcn(30,0.8,[1 -1]), ...
    @() modelFcn(30,0.8,1+1i), ...
    @() modelFcn(30,0.8,NaN), ...
    @() modelFcn(30,0.8,Inf)};
for k=1:numel(invalidCalls)
    assertRejects(invalidCalls{k});
end
afterRejection=modelFcn(30,0.8,1);
assert(isequal(afterRejection.northPosition_m, ...
    baseline.northPosition_m) && ...
    isequal(afterRejection.eastPosition_m,baseline.eastPosition_m) && ...
    isequal(afterRejection.activeWaypointIndex, ...
    baseline.activeWaypointIndex), ...
    'Rejected calls must not poison deterministic baseline recovery.');

%% Accepted corners and capped representative grid bound work and outputs
acceptedCaseCount=0;
for arrivalRadius_m=[10 80]
    for courseResponseGain_per_s=[0 1.2]
        for bearingMode=[-1 1]
            sample=modelFcn(arrivalRadius_m, ...
                courseResponseGain_per_s,bearingMode);
            acceptedCaseCount=acceptedCaseCount+1;
            assertBoundedResult(sample);
        end
    end
end
assert(acceptedCaseCount==8, ...
    'The accepted-corner test matrix must remain capped at 8 calls.');

representativeCaseCount=0;
for arrivalRadius_m=[10 30 80]
    for courseResponseGain_per_s=[0 0.8 1.2]
        for bearingMode=[-1 1]
            sample=modelFcn(arrivalRadius_m, ...
                courseResponseGain_per_s,bearingMode);
            representativeCaseCount=representativeCaseCount+1;
            assertBoundedResult(sample);
        end
    end
end
assert(representativeCaseCount==18, ...
    'The representative resource grid must remain capped at 18 calls.');

%% Compatibility, timeout, cancellation, migration, and backup applicability
% MODEL is synchronous, deterministic, fixed-work, and stateless. It creates
% no timer, future, worker, file, network, device, process, or background
% callback resource, so runtime timeout and cancellation transitions are not
% applicable model semantics. Fixed 1001-sample histories, five route rows,
% bounded scalar inputs, and capped 8/18-case matrices are the resource gates.
% P17 is a conceptual navigation prerequisite, not a runtime-array adapter;
% moving-target pursuit remains outside P18 and belongs to P19. No learner
% state, score, database, service, schema, migration, or backup/restore path
% is read or changed by these checks.

fprintf(['P18 checks passed: route and event reconstruction, two isolated ' ...
    'sweeps, circular and zero-gain limits, broken N/E bearing, malformed ' ...
    'recovery, rollback, compatibility, and bounded resources.\n']);
end

function assertRejects(callable)
didReject=false;
try
    callable();
catch
    didReject=true;
end
assert(didReject,'Malformed or out-of-range input must be rejected.');
end

function assertBoundedResult(sample)
historyFields={'time_s','northPosition_m','eastPosition_m', ...
    'courseUnwrapped_deg','courseWrapped_deg','courseCommand_deg', ...
    'courseError_deg','courseRateCommandUnclamped_degps', ...
    'courseRate_degps','rangeToActiveWaypoint_m', ...
    'alongTrackDistance_m','crossTrackError_m', ...
    'activeWaypointIndex','activeLegIndex'};
assert(sample.sampleCount==1001 && sample.intervalCount==1000 && ...
    numel(sample.waypointNorth_m)==5 && ...
    numel(sample.waypointCaptured)==5, ...
    'Every accepted case must retain fixed resource counts.');
for k=1:numel(historyFields)
    values=sample.(historyFields{k});
    assert(numel(values)==1001 && all(isfinite(values)), ...
        ['History must be finite and fixed-size: ' historyFields{k} '.']);
end
assert(all(abs(sample.courseWrapped_deg)<=180+1e-10) && ...
    all(abs(sample.courseError_deg)<=180+1e-10) && ...
    all(abs(sample.courseRate_degps)<=12+1e-10) && ...
    sample.flownDistance_m<=2500+1e-8 && ...
    all(hypot(sample.northPosition_m,sample.eastPosition_m)<=2500+1e-8) && ...
    all(sample.activeWaypointIndex>=2) && ...
    all(sample.activeWaypointIndex<=6) && ...
    all(diff(sample.activeWaypointIndex)>=0) && ...
    all(diff(sample.activeWaypointIndex)<=1) && ...
    sample.waypointCaptured(1) && ...
    all(diff(double(sample.waypointCaptured))<=0), ...
    'Accepted cases must remain bounded, ordered, and unable to skip targets.');
assert(sample.targetWaypointCapturedCount== ...
    sum(sample.waypointCaptured(2:end)) && ...
    sample.motionActiveIntervalCount<=sample.intervalCount && ...
    sample.motionActiveSampleCount<=sample.sampleCount && ...
    sample.courseRateSaturationFraction>=0 && ...
    sample.courseRateSaturationFraction<=1, ...
    'Reported counts and fractions must remain internally bounded.');
end
