function out = model(forwardSpecificForce_mps2,headingAngle_deg)
%MODEL Audit frame transforms, work, and mechanical energy in NED.
% A fixed body frame starts at 30 deg nose-up with body-forward velocity.
% An explicit DCM maps the commanded body-x non-gravity specific force into
% North-East-Down (NED). The analytic constant-acceleration trajectory must
% satisfy E(t)-E(0)=integral(m*f_b dot v_b dt). Correct altitude is -Down,
% so U=m*g*h=-m*g*Down. The broken ledger treats Down as height while
% preserving the complete trajectory, DCM, force, velocity, and work.
arguments
    forwardSpecificForce_mps2 (1,1) double ...
        {mustBeReal,mustBeFinite} = 1.5
    headingAngle_deg (1,1) double {mustBeReal,mustBeFinite} = 30
end

if forwardSpecificForce_mps2<0 || forwardSpecificForce_mps2>3
    error('P12:model:SpecificForceRange', ...
        ['Forward non-gravity specific force must be between 0 and 3 ' ...
        'm/s^2, inclusive.']);
end
if headingAngle_deg<-180 || headingAngle_deg>180
    error('P12:model:HeadingRange', ...
        'Heading angle must be between -180 and 180 deg, inclusive.');
end

mass_kg=1200;
gravity_mps2=9.80665;
initialAltitude_m=1000;
initialSpeed_mps=60;
pitchAngle_deg=30;
rollAngle_deg=0;
sampleTime_s=0.02;
timeHorizon_s=6;
time_s=0:sampleTime_s:timeHorizon_s;
sampleCount=numel(time_s);

pitch_rad=pitchAngle_deg*pi/180;
heading_rad=headingAngle_deg*pi/180;
cp=cos(pitch_rad); sp=sin(pitch_rad);
cy=cos(heading_rad); sy=sin(heading_rad);

% C_body_to_ned maps body [x forward; y right; z down] components into
% [North; East; Down]. Positive pitch is nose-up and therefore maps a
% body-forward vector and a positive body-x force toward negative Down.
% Changing heading actively yaws the fixed body and path relative to the
% fixed NED axes; it is not a passive re-expression of one trajectory.
bodyToNED=[ ...
    cp*cy, -sy, sp*cy; ...
    cp*sy, cy, sp*sy; ...
    -sp, 0, cp];
nedToBody=bodyToNED.';

gravityNED_mps2=[0;0;gravity_mps2];
initialPositionNED_m=[0;0;-initialAltitude_m];
initialVelocityBody_mps=[initialSpeed_mps;0;0];
initialVelocityNED_mps=bodyToNED*initialVelocityBody_mps;
specificForceBody_mps2=[forwardSpecificForce_mps2;0;0];
specificForceNED_mps2=bodyToNED*specificForceBody_mps2;
accelerationNED_mps2=specificForceNED_mps2+gravityNED_mps2;
accelerationBodyComponents_mps2=nedToBody*accelerationNED_mps2;

% The analytic constant-acceleration trajectory avoids solver and time-step
% ambiguity. The sample grid only selects retained observation points.
velocityNED_mps=repmat(initialVelocityNED_mps,1,sampleCount)+ ...
    accelerationNED_mps2*time_s;
positionNED_m=repmat(initialPositionNED_m,1,sampleCount)+ ...
    initialVelocityNED_mps*time_s+ ...
    0.5*accelerationNED_mps2*(time_s.^2);
velocityBody_mps=nedToBody*velocityNED_mps;
reconstructedVelocityNED_mps=bodyToNED*velocityBody_mps;

altitude_m=-positionNED_m(3,:);
speedNED_mps=sqrt(sum(velocityNED_mps.^2,1));
speedBody_mps=sqrt(sum(velocityBody_mps.^2,1));
kineticEnergyNED_J=0.5*mass_kg*sum(velocityNED_mps.^2,1);
kineticEnergyBody_J=0.5*mass_kg*sum(velocityBody_mps.^2,1);
potentialEnergy_J=mass_kg*gravity_mps2*altitude_m;
mechanicalEnergy_J=kineticEnergyNED_J+potentialEnergy_J;

% The non-gravity power is frame invariant: m*f_b dot v_b equals
% m*f_n dot v_n. Because force and acceleration are constant, the visible
% closed form below is also exactly reproduced by trapezoidal integration.
specificPowerBody_W_per_kg=sum( ...
    repmat(specificForceBody_mps2,1,sampleCount).*velocityBody_mps,1);
specificPowerNED_W_per_kg=sum( ...
    repmat(specificForceNED_mps2,1,sampleCount).*velocityNED_mps,1);
powerBody_W=mass_kg*specificPowerBody_W_per_kg;
powerNED_W=mass_kg*specificPowerNED_W_per_kg;
bodyForwardAcceleration_mps2=accelerationBodyComponents_mps2(1);
workInput_J=mass_kg*forwardSpecificForce_mps2*( ...
    initialSpeed_mps*time_s+0.5*bodyForwardAcceleration_mps2*time_s.^2);
energyBalanceResidual_J=mechanicalEnergy_J-mechanicalEnergy_J(1)-workInput_J;

% Deliberately broken convention: use positive Down itself as height. Both
% ledgers share the exact kinematics, force, power, and work, so their
% difference is caused only by the potential-energy sign.
brokenHeight_m=positionNED_m(3,:);
brokenPotentialEnergy_J=mass_kg*gravity_mps2*brokenHeight_m;
brokenMechanicalEnergy_J=kineticEnergyNED_J+brokenPotentialEnergy_J;
brokenEnergyBalanceResidual_J= ...
    brokenMechanicalEnergy_J-brokenMechanicalEnergy_J(1)-workInput_J;
downChange_m=positionNED_m(3,:)-positionNED_m(3,1);
expectedBrokenEnergyBalanceResidual_J= ...
    2*mass_kg*gravity_mps2*downChange_m;

frameRoundTripResidual_mps= ...
    reconstructedVelocityNED_mps-velocityNED_mps;
kineticFrameDifference_J=kineticEnergyBody_J-kineticEnergyNED_J;
powerFrameDifference_W=powerBody_W-powerNED_W;
dcmOrthonormalityResidual=bodyToNED.'*bodyToNED-eye(3);
dcmOrthonormalityError=max(abs(dcmOrthonormalityResidual(:)));
dcmDeterminantError=abs(det(bodyToNED)-1);

initialClimbRate_mps=-initialVelocityNED_mps(3);
downAcceleration_mps2=accelerationNED_mps2(3);
apexTime_s=initialClimbRate_mps/downAcceleration_mps2;
apexAltitudeGain_m=initialClimbRate_mps^2/(2*downAcceleration_mps2);
horizontalRange_m=sqrt(sum(positionNED_m(1:2,end).^2));

out=struct( ...
    'forwardSpecificForce_mps2',forwardSpecificForce_mps2, ...
    'headingAngle_deg',headingAngle_deg, ...
    'pitchAngle_deg',pitchAngle_deg, ...
    'initialSpeed_mps',initialSpeed_mps, ...
    'rollAngle_deg',rollAngle_deg, ...
    'mass_kg',mass_kg, ...
    'gravity_mps2',gravity_mps2, ...
    'gravityNED_mps2',gravityNED_mps2, ...
    'initialAltitude_m',initialAltitude_m, ...
    'sampleTime_s',sampleTime_s, ...
    'timeHorizon_s',timeHorizon_s, ...
    'time_s',time_s, ...
    'sampleCount',sampleCount, ...
    'intervalCount',sampleCount-1, ...
    'bodyToNED',bodyToNED, ...
    'nedToBody',nedToBody, ...
    'initialPositionNED_m',initialPositionNED_m, ...
    'initialVelocityBody_mps',initialVelocityBody_mps, ...
    'initialVelocityNED_mps',initialVelocityNED_mps, ...
    'specificForceBody_mps2',specificForceBody_mps2, ...
    'specificForceNED_mps2',specificForceNED_mps2, ...
    'accelerationNED_mps2',accelerationNED_mps2, ...
    'accelerationBodyComponents_mps2', ...
    accelerationBodyComponents_mps2, ...
    'positionNED_m',positionNED_m, ...
    'velocityNED_mps',velocityNED_mps, ...
    'velocityBody_mps',velocityBody_mps, ...
    'reconstructedVelocityNED_mps',reconstructedVelocityNED_mps, ...
    'altitude_m',altitude_m, ...
    'speedNED_mps',speedNED_mps, ...
    'speedBody_mps',speedBody_mps, ...
    'kineticEnergyNED_J',kineticEnergyNED_J, ...
    'kineticEnergyBody_J',kineticEnergyBody_J, ...
    'potentialEnergy_J',potentialEnergy_J, ...
    'mechanicalEnergy_J',mechanicalEnergy_J, ...
    'specificPowerBody_W_per_kg',specificPowerBody_W_per_kg, ...
    'specificPowerNED_W_per_kg',specificPowerNED_W_per_kg, ...
    'powerBody_W',powerBody_W, ...
    'powerNED_W',powerNED_W, ...
    'workInput_J',workInput_J, ...
    'energyBalanceResidual_J',energyBalanceResidual_J, ...
    'brokenHeight_m',brokenHeight_m, ...
    'brokenPotentialEnergy_J',brokenPotentialEnergy_J, ...
    'brokenMechanicalEnergy_J',brokenMechanicalEnergy_J, ...
    'brokenEnergyBalanceResidual_J',brokenEnergyBalanceResidual_J, ...
    'expectedBrokenEnergyBalanceResidual_J', ...
    expectedBrokenEnergyBalanceResidual_J, ...
    'downChange_m',downChange_m, ...
    'frameRoundTripResidual_mps',frameRoundTripResidual_mps, ...
    'kineticFrameDifference_J',kineticFrameDifference_J, ...
    'powerFrameDifference_W',powerFrameDifference_W, ...
    'bodyForwardAcceleration_mps2',bodyForwardAcceleration_mps2, ...
    'downAcceleration_mps2',downAcceleration_mps2, ...
    'dcmOrthonormalityError',dcmOrthonormalityError, ...
    'dcmDeterminantError',dcmDeterminantError, ...
    'maxFrameRoundTripError_mps',max(abs( ...
    frameRoundTripResidual_mps(:))), ...
    'maxKineticFrameDifference_J',max(abs(kineticFrameDifference_J)), ...
    'maxPowerFrameDifference_W',max(abs(powerFrameDifference_W)), ...
    'maxEnergyBalanceResidual_J',max(abs(energyBalanceResidual_J)), ...
    'maxBrokenResidualClosure_J',max(abs( ...
    brokenEnergyBalanceResidual_J- ...
    expectedBrokenEnergyBalanceResidual_J)), ...
    'peakBrokenEnergyDrift_J',max(abs(brokenEnergyBalanceResidual_J)), ...
    'initialClimbRate_mps',initialClimbRate_mps, ...
    'apexTime_s',apexTime_s, ...
    'apexAltitudeGain_m',apexAltitudeGain_m, ...
    'horizontalRange_m',horizontalRange_m, ...
    'finalAltitude_m',altitude_m(end), ...
    'initialMechanicalEnergy_J',mechanicalEnergy_J(1), ...
    'finalWorkInput_J',workInput_J(end), ...
    'frameConvention',[ ...
        'body x forward, y right, z down; navigation is North-East-Down; ' ...
        'C_body_to_ned maps body components into NED; positive pitch is nose-up; ' ...
        'heading is active body yaw relative to fixed NED, clockwise from North toward East'], ...
    'specificForceEquation',[ ...
        'a_n=C_body_to_ned*f_b+g_n; f_b is non-gravity specific force ' ...
        'and equals the ideal accelerometer quantity from P11'], ...
    'energyEquation',[ ...
        'E=0.5*m*(v dot v)+m*g*h with h=-Down; E-E0=integral(m*f dot v dt); ' ...
        'kinetic energy and power dot products are frame invariant'], ...
    'brokenCaseDefinition',[ ...
        'positive NED Down is incorrectly treated as height in U=m*g*h; ' ...
        'trajectory, DCM, force, velocity, power, and work remain unchanged'], ...
    'analysisScope',[ ...
        'analytic constant-attitude point mass in uniform gravity; ' ...
        'no wind or horizontal asymmetry, aerodynamics, propulsion-system dynamics, attitude dynamics, ' ...
        'rotational-energy ledger, sensor fusion, control, hardware, or flight fidelity']);
end
