function run_checks
%RUN_CHECKS Independent checks for P12 energy and frame conventions.
clear model;
frameTol=1e-11;
energyTol_J=1e-6;

%% Determinism, fixed shapes, finite resources, and bounded accepted inputs
first=model(1.5,30);
second=model(1.5,30);
assert(isequaln(first,second), ...
    'Identical convention-audit inputs must produce identical outputs.');
assert(first.sampleCount==301 && first.intervalCount==300 && ...
    first.sampleTime_s==0.02 && first.timeHorizon_s==6 && ...
    isequal(size(first.time_s),[1 301]) && ...
    first.time_s(1)==0 && first.time_s(end)==6, ...
    'The synchronous resource boundary must remain 301 samples and 300 intervals.');

rowFields={ ...
    'time_s','altitude_m','speedNED_mps','speedBody_mps', ...
    'kineticEnergyNED_J','kineticEnergyBody_J','potentialEnergy_J', ...
    'mechanicalEnergy_J','specificPowerBody_W_per_kg', ...
    'specificPowerNED_W_per_kg','powerBody_W','powerNED_W', ...
    'workInput_J','energyBalanceResidual_J','brokenHeight_m', ...
    'brokenPotentialEnergy_J','brokenMechanicalEnergy_J', ...
    'brokenEnergyBalanceResidual_J', ...
    'expectedBrokenEnergyBalanceResidual_J','downChange_m', ...
    'kineticFrameDifference_J','powerFrameDifference_W'};
for k=1:numel(rowFields)
    value=first.(rowFields{k});
    assert(isequal(size(value),[1 301]) && isreal(value) && ...
        all(isfinite(value)), ...
        'Every scalar history must remain a finite 1-by-301 row vector.');
end

threeAxisFields={ ...
    'positionNED_m','velocityNED_mps','velocityBody_mps', ...
    'reconstructedVelocityNED_mps','frameRoundTripResidual_mps'};
for k=1:numel(threeAxisFields)
    value=first.(threeAxisFields{k});
    assert(isequal(size(value),[3 301]) && isreal(value) && ...
        all(isfinite(value(:))), ...
        'Every three-axis history must remain a finite 3-by-301 matrix.');
end
assert(isequal(size(first.bodyToNED),[3 3]) && ...
    isequal(size(first.nedToBody),[3 3]) && ...
    isequal(size(first.specificForceBody_mps2),[3 1]) && ...
    isequal(size(first.specificForceNED_mps2),[3 1]) && ...
    isequal(size(first.accelerationNED_mps2),[3 1]) && ...
    all(isfinite(first.bodyToNED(:))), ...
    'Fixed DCM, force, and acceleration shapes must remain finite.');

acceptedForce=[0 3];
acceptedHeading=[-180 180];
acceptedCornerCount=0;
for forceIndex=1:numel(acceptedForce)
    for headingIndex=1:numel(acceptedHeading)
        sample=model(acceptedForce(forceIndex), ...
            acceptedHeading(headingIndex));
        acceptedCornerCount=acceptedCornerCount+1;
        assert(sample.sampleCount==301 && sample.intervalCount==300 && ...
            all(isfinite(sample.positionNED_m(:))) && ...
            all(isfinite(sample.mechanicalEnergy_J)) && ...
            sample.maxFrameRoundTripError_mps<frameTol && ...
            sample.maxEnergyBalanceResidual_J<energyTol_J && ...
            sample.maxBrokenResidualClosure_J<energyTol_J, ...
            'Every accepted input corner must remain finite and bounded.');
    end
end
assert(acceptedCornerCount==4, ...
    'The accepted-corner resource check must remain fixed at four calls.');

representativeForce=[0 1.5 3];
representativeHeading=[-90 30 90];
representativeCaseCount=0;
for forceIndex=1:numel(representativeForce)
    for headingIndex=1:numel(representativeHeading)
        sample=model(representativeForce(forceIndex), ...
            representativeHeading(headingIndex));
        representativeCaseCount=representativeCaseCount+1;
        assert(sample.sampleCount==301 && ...
            all(isfinite(sample.velocityBody_mps(:))) && ...
            all(isfinite(sample.workInput_J)), ...
            'The representative convention grid must retain fixed finite work.');
    end
end
assert(representativeCaseCount==9 && representativeCaseCount<=10, ...
    'The representative resource grid must stay capped at nine calls.');

%% Independently reconstruct the DCM, kinematics, power, work, and energy
expectedMass_kg=1200;
expectedGravity_mps2=9.80665;
expectedAltitude_m=1000;
expectedSpeed_mps=60;
expectedPitch_deg=30;
expectedHeading_deg=30;
expectedForce_mps2=1.5;
expectedTime_s=0:0.02:6;
expectedBodyToNED=independentBodyToNED( ...
    expectedPitch_deg,expectedHeading_deg);
expectedNEDToBody=expectedBodyToNED.';
expectedGravityNED_mps2=[0;0;expectedGravity_mps2];
expectedInitialPositionNED_m=[0;0;-expectedAltitude_m];
expectedInitialVelocityBody_mps=[expectedSpeed_mps;0;0];
expectedInitialVelocityNED_mps= ...
    expectedBodyToNED*expectedInitialVelocityBody_mps;
expectedSpecificForceBody_mps2=[expectedForce_mps2;0;0];
expectedSpecificForceNED_mps2= ...
    expectedBodyToNED*expectedSpecificForceBody_mps2;
expectedAccelerationNED_mps2= ...
    expectedSpecificForceNED_mps2+expectedGravityNED_mps2;
expectedVelocityNED_mps= ...
    repmat(expectedInitialVelocityNED_mps,1,numel(expectedTime_s))+ ...
    expectedAccelerationNED_mps2*expectedTime_s;
expectedPositionNED_m= ...
    repmat(expectedInitialPositionNED_m,1,numel(expectedTime_s))+ ...
    expectedInitialVelocityNED_mps*expectedTime_s+ ...
    0.5*expectedAccelerationNED_mps2*(expectedTime_s.^2);
expectedVelocityBody_mps=expectedNEDToBody*expectedVelocityNED_mps;
expectedKineticEnergy_J=0.5*expectedMass_kg* ...
    sum(expectedVelocityNED_mps.^2,1);
expectedPotentialEnergy_J=-expectedMass_kg*expectedGravity_mps2* ...
    expectedPositionNED_m(3,:);
expectedMechanicalEnergy_J= ...
    expectedKineticEnergy_J+expectedPotentialEnergy_J;
expectedPowerBody_W=expectedMass_kg*sum( ...
    repmat(expectedSpecificForceBody_mps2,1,numel(expectedTime_s)).* ...
    expectedVelocityBody_mps,1);
expectedPowerNED_W=expectedMass_kg*sum( ...
    repmat(expectedSpecificForceNED_mps2,1,numel(expectedTime_s)).* ...
    expectedVelocityNED_mps,1);
expectedWork_J=independentTrapezoidalIntegral( ...
    expectedTime_s,expectedPowerBody_W);
expectedEnergyResidual_J=expectedMechanicalEnergy_J- ...
    expectedMechanicalEnergy_J(1)-expectedWork_J;
expectedDownChange_m= ...
    expectedPositionNED_m(3,:)-expectedPositionNED_m(3,1);
expectedBrokenResidual_J= ...
    2*expectedMass_kg*expectedGravity_mps2*expectedDownChange_m;

assert(maxAbsoluteDifference(first.time_s,expectedTime_s)<frameTol && ...
    maxAbsoluteDifference(first.bodyToNED,expectedBodyToNED)<frameTol && ...
    maxAbsoluteDifference(first.initialVelocityNED_mps, ...
    expectedInitialVelocityNED_mps)<frameTol && ...
    maxAbsoluteDifference(first.specificForceNED_mps2, ...
    expectedSpecificForceNED_mps2)<frameTol && ...
    maxAbsoluteDifference(first.accelerationNED_mps2, ...
    expectedAccelerationNED_mps2)<frameTol, ...
    'The independently reconstructed DCM, initial state, force, and acceleration must match.');
assert(maxAbsoluteDifference(first.velocityNED_mps, ...
    expectedVelocityNED_mps)<frameTol && ...
    maxAbsoluteDifference(first.positionNED_m, ...
    expectedPositionNED_m)<frameTol && ...
    maxAbsoluteDifference(first.velocityBody_mps, ...
    expectedVelocityBody_mps)<frameTol, ...
    'Every analytic position and velocity sample must match reconstruction.');
assert(maxAbsoluteDifference(first.kineticEnergyNED_J, ...
    expectedKineticEnergy_J)<energyTol_J && ...
    maxAbsoluteDifference(first.potentialEnergy_J, ...
    expectedPotentialEnergy_J)<energyTol_J && ...
    maxAbsoluteDifference(first.mechanicalEnergy_J, ...
    expectedMechanicalEnergy_J)<energyTol_J, ...
    'Every independently calculated kinetic, potential, and total energy must match.');
assert(maxAbsoluteDifference(first.powerBody_W,expectedPowerBody_W)<1e-8 && ...
    maxAbsoluteDifference(first.powerNED_W,expectedPowerNED_W)<1e-8 && ...
    maxAbsoluteDifference(first.workInput_J,expectedWork_J)<energyTol_J && ...
    maxAbsoluteDifference(first.energyBalanceResidual_J, ...
    expectedEnergyResidual_J)<energyTol_J, ...
    'Body/NED power, every work update, and work-energy balance must match reconstruction.');
assert(maxAbsoluteDifference(first.brokenEnergyBalanceResidual_J, ...
    expectedBrokenResidual_J)<energyTol_J && ...
    maxAbsoluteDifference(first.expectedBrokenEnergyBalanceResidual_J, ...
    expectedBrokenResidual_J)<energyTol_J, ...
    'The wrong potential sign must produce exactly twice m*g*Down change.');

for k=1:first.intervalCount
    step_s=first.time_s(k+1)-first.time_s(k);
    expectedNextWork=first.workInput_J(k)+0.5*step_s*( ...
        first.powerBody_W(k)+first.powerBody_W(k+1));
    assert(abs(first.workInput_J(k+1)-expectedNextWork)<energyTol_J, ...
        'Every trapezoidal non-gravity work interval must close.');
end

%% Known signed baseline pins transform direction beyond self-consistent closure
expectedFirstColumn=[0.75;sqrt(3)/4;-0.5];
expectedInitialVelocity=[45;15*sqrt(3);-30];
expectedSpecificForce=[1.125;0.375*sqrt(3);-0.75];
expectedAcceleration=[1.125;0.375*sqrt(3);9.05665];
assert(maxAbsoluteDifference(first.bodyToNED(:,1), ...
    expectedFirstColumn)<frameTol && ...
    maxAbsoluteDifference(first.initialVelocityNED_mps, ...
    expectedInitialVelocity)<frameTol && ...
    maxAbsoluteDifference(first.specificForceNED_mps2, ...
    expectedSpecificForce)<frameTol && ...
    maxAbsoluteDifference(first.accelerationNED_mps2, ...
    expectedAcceleration)<frameTol, ...
    ['Positive 30 deg pitch and heading must map body-forward velocity and ' ...
    'force toward positive North/East and negative Down.']);

sampleAtTwo=find(abs(first.time_s-2)<frameTol,1);
assert(~isempty(sampleAtTwo), ...
    'The fixed grid must retain the 2 s signed reference sample.');
expectedVelocityAtTwoNED=[47.25;27.279800219209815;-11.8867];
expectedVelocityAtTwoBody=[53.19335;0;16.98561605204533];
assert(maxAbsoluteDifference(first.velocityNED_mps(:,sampleAtTwo), ...
    expectedVelocityAtTwoNED)<frameTol && ...
    maxAbsoluteDifference(first.velocityBody_mps(:,sampleAtTwo), ...
    expectedVelocityAtTwoBody)<frameTol && ...
    first.altitude_m(sampleAtTwo)>first.initialAltitude_m, ...
    'The nonzero signed frame sample must match independently known components.');

assert(maxAbsoluteDifference(first.positionNED_m(:,end), ...
    [290.25;167.575915632289;-1016.9803])<1e-9 && ...
    maxAbsoluteDifference(first.velocityNED_mps(:,end), ...
    [51.75;29.87787643056313;24.3399])<1e-10 && ...
    abs(first.apexTime_s-3.3124830925342152)<1e-12 && ...
    abs(first.apexAltitudeGain_m-49.68724638801323)<1e-11 && ...
    abs(first.finalWorkInput_J-537732.27)<1e-7, ...
    'The deterministic baseline signature must remain recognizable.');

%% Proper-rotation, round-trip, norm, power, and work-energy invariants
assert(max(max(abs(first.bodyToNED.'*first.bodyToNED-eye(3))))<frameTol && ...
    abs(det(first.bodyToNED)-1)<frameTol && ...
    first.dcmOrthonormalityError<frameTol && ...
    first.dcmDeterminantError<frameTol, ...
    'The declared body-to-NED DCM must remain a proper orthonormal rotation.');
assert(first.maxFrameRoundTripError_mps<frameTol && ...
    max(abs(first.speedBody_mps-first.speedNED_mps))<frameTol && ...
    first.maxKineticFrameDifference_J<energyTol_J && ...
    first.maxPowerFrameDifference_W<1e-8 && ...
    first.maxEnergyBalanceResidual_J<energyTol_J, ...
    'Round trip, speed, kinetic energy, power, and work-energy balance must close.');

%% Free-fall and heading limiting cases
freeFall=model(0,30);
assert(all(freeFall.specificForceBody_mps2==0) && ...
    all(freeFall.specificForceNED_mps2==0) && ...
    all(freeFall.specificPowerBody_W_per_kg==0) && ...
    all(freeFall.powerBody_W==0) && ...
    all(freeFall.workInput_J==0) && ...
    max(abs(freeFall.mechanicalEnergy_J- ...
    freeFall.mechanicalEnergy_J(1)))<energyTol_J, ...
    ['Zero specific force must give free fall, zero ideal accelerometer ' ...
    'output, zero work, and constant mechanical energy.']);

dueNorth=model(1.5,0);
dueEast=model(1.5,90);
dueWest=model(1.5,-90);
assert(all(dueNorth.positionNED_m(2,:)==0) && ...
    all(dueNorth.velocityNED_mps(2,:)==0) && ...
    all(dueNorth.specificForceNED_mps2(2)==0), ...
    'Zero heading must keep East motion and force exactly zero.');
assert(abs(dueEast.initialVelocityNED_mps(1))<frameTol && ...
    dueEast.initialVelocityNED_mps(2)>0 && ...
    dueEast.initialVelocityNED_mps(3)<0 && ...
    abs(dueWest.initialVelocityNED_mps(1))<frameTol && ...
    dueWest.initialVelocityNED_mps(2)<0 && ...
    dueWest.initialVelocityNED_mps(3)<0 && ...
    maxAbsoluteDifference(dueEast.positionNED_m(1,:), ...
    dueWest.positionNED_m(1,:))<frameTol && ...
    maxAbsoluteDifference(dueEast.positionNED_m(2,:), ...
    -dueWest.positionNED_m(2,:))<frameTol, ...
    'Heading +/-90 deg must reverse only the signed East trajectory.');

smallestPositiveForce=model(eps(0),30);
assert(all(isfinite(smallestPositiveForce.workInput_J)) && ...
    smallestPositiveForce.maxEnergyBalanceResidual_J<energyTol_J, ...
    'The smallest positive accepted force must remain finite without division.');

%% Two isolated parameter sweeps
forceSweep=[0 0.75 1.5 2.25 3];
finalWork_J=zeros(size(forceSweep));
apexGain_m=zeros(size(forceSweep));
horizontalRange_m=zeros(size(forceSweep));
for k=1:numel(forceSweep)
    sample=model(forceSweep(k),30);
    finalWork_J(k)=sample.finalWorkInput_J;
    apexGain_m(k)=sample.apexAltitudeGain_m;
    horizontalRange_m(k)=sample.horizontalRange_m;
    assert(isequal(sample.bodyToNED,first.bodyToNED) && ...
        isequal(sample.initialPositionNED_m,first.initialPositionNED_m) && ...
        isequal(sample.initialVelocityNED_mps,first.initialVelocityNED_mps) && ...
        sample.headingAngle_deg==first.headingAngle_deg, ...
        'The specific-force sweep must isolate force from frame and initial state.');
end
expectedFinalWork_J=1200*[ ...
    0 213.9301125 448.110225 702.5403375 977.22045];
expectedApexGain_m=[ ...
    45.887229584006775 47.71169413623279 49.68724638801323 ...
    51.833464836753386 54.173463429902554];
assert(max(abs(finalWork_J-expectedFinalWork_J))<1e-6 && ...
    max(abs(apexGain_m-expectedApexGain_m))<1e-10 && ...
    finalWork_J(1)==0 && all(diff(finalWork_J)>0) && ...
    all(diff(apexGain_m)>0) && all(diff(horizontalRange_m)>0), ...
    'The force sweep must reproduce work, apex, and range trends.');

headingSweep=[-90 -30 0 30 90];
for k=1:numel(headingSweep)
    sample=model(1.5,headingSweep(k));
    headingRadians=headingSweep(k)*pi/180;
    expectedHorizontalPosition_m=[cos(headingRadians);sin(headingRadians)]* ...
        dueNorth.positionNED_m(1,:);
    expectedHorizontalVelocity_mps=[cos(headingRadians);sin(headingRadians)]* ...
        dueNorth.velocityNED_mps(1,:);
    expectedHorizontalSpecificForce_mps2= ...
        [cos(headingRadians);sin(headingRadians)]* ...
        dueNorth.specificForceNED_mps2(1);
    assert(maxAbsoluteDifference(sample.positionNED_m(1:2,:), ...
        expectedHorizontalPosition_m)<frameTol && ...
        maxAbsoluteDifference(sample.velocityNED_mps(1:2,:), ...
        expectedHorizontalVelocity_mps)<frameTol && ...
        maxAbsoluteDifference(sample.specificForceNED_mps2(1:2), ...
        expectedHorizontalSpecificForce_mps2)<frameTol, ...
        ['Every intermediate heading must rotate horizontal position, ' ...
        'velocity, and specific force by the commanded active-yaw angle.']);
    assert(maxAbsoluteDifference(sample.velocityBody_mps, ...
        first.velocityBody_mps)<frameTol && ...
        maxAbsoluteDifference(sample.altitude_m,first.altitude_m)<frameTol && ...
        maxAbsoluteDifference(sample.speedNED_mps,first.speedNED_mps)<frameTol && ...
        maxAbsoluteDifference(sample.workInput_J,first.workInput_J)<energyTol_J && ...
        maxAbsoluteDifference(sample.mechanicalEnergy_J, ...
        first.mechanicalEnergy_J)<energyTol_J && ...
        maxAbsoluteDifference(sample.brokenEnergyBalanceResidual_J, ...
        first.brokenEnergyBalanceResidual_J)<energyTol_J, ...
        ['The heading sweep must rotate N/E components while preserving ' ...
        'body histories, altitude, speed, work, and energy.']);
end

%% Deliberately broken Down-as-height convention
assert(first.brokenEnergyBalanceResidual_J(1)==0 && ...
    first.energyBalanceResidual_J(1)==0 && ...
    first.maxBrokenResidualClosure_J<energyTol_J && ...
    first.peakBrokenEnergyDrift_J>1e6, ...
    ['The sign defect must be invisible at its initial datum but exceed ' ...
    'one megajoule during the baseline history.']);
assert(maxAbsoluteDifference(first.brokenMechanicalEnergy_J- ...
    first.mechanicalEnergy_J, ...
    2*first.mass_kg*first.gravity_mps2*first.positionNED_m(3,:))<energyTol_J && ...
    maxAbsoluteDifference(first.brokenEnergyBalanceResidual_J, ...
    2*first.mass_kg*first.gravity_mps2*first.downChange_m)<energyTol_J, ...
    'The broken ledger must differ only by the exact potential-energy sign.');
apexIndex=find(abs(first.velocityNED_mps(3,:))== ...
    min(abs(first.velocityNED_mps(3,:))),1);
assert(first.downChange_m(apexIndex)<0 && ...
    first.brokenEnergyBalanceResidual_J(apexIndex)<-1e6 && ...
    abs(first.energyBalanceResidual_J(apexIndex))<energyTol_J, ...
    'Near the apex, wrong +g*Down must report a large false energy loss.');

%% Declared meaning and compatibility boundary remain explicit
assert(contains(first.frameConvention,'x forward') && ...
    contains(first.frameConvention,'North-East-Down') && ...
    contains(first.frameConvention,'clockwise') && ...
    contains(first.frameConvention,'active body yaw relative to fixed NED') && ...
    contains(first.specificForceEquation, ...
    'a_n=C_body_to_ned*f_b+g_n') && ...
    contains(first.specificForceEquation,'P11') && ...
    contains(first.energyEquation,'h=-Down') && ...
    contains(first.energyEquation,'integral') && ...
    contains(first.brokenCaseDefinition,'incorrectly treated as height') && ...
    contains(first.brokenCaseDefinition,'work remain unchanged') && ...
    contains(first.analysisScope,'no wind or horizontal asymmetry') && ...
    contains(first.analysisScope,'aerodynamics') && ...
    contains(first.analysisScope,'attitude dynamics'), ...
    'Frames, equations, broken assumption, and analysis limits must stay visible.');

%% Malformed inputs fail clearly, then a valid call recovers
expectFailure(@() model(-0.001,30), ...
    'P12:model:SpecificForceRange','specific force below range');
expectFailure(@() model(3.001,30), ...
    'P12:model:SpecificForceRange','specific force above range');
expectFailure(@() model(1.5,-180.001), ...
    'P12:model:HeadingRange','heading below range');
expectFailure(@() model(1.5,180.001), ...
    'P12:model:HeadingRange','heading above range');
expectFailure(@() model([1 2],30),'','nonscalar specific force');
expectFailure(@() model(1.5,[20 30]),'','nonscalar heading');
expectFailure(@() model(1.5+1i,30),'','complex specific force');
expectFailure(@() model(1.5,30+1i),'','complex heading');
expectFailure(@() model(NaN,30),'','nonfinite specific force');
expectFailure(@() model(1.5,Inf),'','nonfinite heading');
afterFailure=model(1.5,30);
assert(isequaln(afterFailure,first), ...
    'Rejected inputs must not poison deterministic recovery.');

disp(['P12 checks passed: analytic kinematics, signed DCM, frame-invariant ' ...
    'norm and power, work-energy closure, free fall, isolated sweeps, ' ...
    'malformed-input recovery, bounded work, and Down-sign failure detection.']);
end

function bodyToNED = independentBodyToNED(pitch_deg,heading_deg)
%INDEPENDENTBODYTONED Construct the declared zero-roll 3-2-1 DCM.
pitch_rad=pitch_deg*pi/180;
heading_rad=heading_deg*pi/180;
cp=cos(pitch_rad); sp=sin(pitch_rad);
cy=cos(heading_rad); sy=sin(heading_rad);
bodyToNED=[ ...
    cp*cy, -sy, sp*cy; ...
    cp*sy, cy, sp*sy; ...
    -sp, 0, cp];
end

function integral = independentTrapezoidalIntegral(time_s,values)
%INDEPENDENTTRAPEZOIDALINTEGRAL Reconstruct every retained work interval.
integral=zeros(size(values));
for k=1:numel(time_s)-1
    step_s=time_s(k+1)-time_s(k);
    integral(k+1)=integral(k)+0.5*step_s*(values(k)+values(k+1));
end
end

function difference = maxAbsoluteDifference(actual,expected)
%MAXABSOLUTEDIFFERENCE Compare arrays without relying on stored metrics.
difference=max(abs(actual(:)-expected(:)));
end

function expectFailure(action,expectedIdentifier,label)
%EXPECTFAILURE Require clear rejection and optionally an exact identifier.
didFail=false;
try
    action();
catch exception
    didFail=true;
    if ~isempty(expectedIdentifier)
        assert(strcmp(exception.identifier,expectedIdentifier), ...
            ['Wrong error identifier for ' label '.']);
    end
end
assert(didFail,['Expected rejection for ' label '.']);
end
