function out=model(headingGain_bank_per_heading,rollNaturalFrequency_radps,headingErrorMode)
%MODEL Deterministic reduced-order cascaded roll and heading hold.
% Positive bank is right-wing-down and positive heading is nose-right.
% Heading is integrated continuously, then wrapped to [-180,180) only for
% display and circular feedback. Bank rate is an Euler-angle rate in the
% declared level coordinated-turn approximation, not a full body-rate state.
arguments
    headingGain_bank_per_heading (1,1) double {mustBeReal,mustBeFinite}=0.5
    rollNaturalFrequency_radps (1,1) double {mustBeReal,mustBeFinite}=2.4
    headingErrorMode (1,1) double {mustBeReal,mustBeFinite}=1
end

if headingGain_bank_per_heading<0 || headingGain_bank_per_heading>1
    error('P14:model:HeadingGainRange', ...
        'Heading-to-bank gain must be between 0 and 1 rad/rad inclusive.');
end
if rollNaturalFrequency_radps<1.2 || rollNaturalFrequency_radps>3.6
    error('P14:model:RollFrequencyRange', ...
        'Roll natural frequency must be between 1.2 and 3.6 rad/s inclusive.');
end
if headingErrorMode~=0 && headingErrorMode~=1
    error('P14:model:HeadingErrorMode', ...
        ['Heading error mode must be 1 for wrapped shortest-path feedback ' ...
        'or 0 for the deliberately broken raw subtraction.']);
end

sampleTime_s=0.02;
timeHorizon_s=60;
time_s=0:sampleTime_s:timeHorizon_s;
sampleCount=numel(time_s);
commandStepTime_s=1;
initialHeading_rad=deg2rad(170);
commandedHeading_rad=deg2rad(-170);
shortestCommandStep_rad=mod( ...
    commandedHeading_rad-initialHeading_rad+pi,2*pi)-pi;
nearestContinuousTarget_rad=initialHeading_rad+shortestCommandStep_rad;
trueAirspeed_mps=60;
gravity_mps2=9.80665;
rollDampingRatio=0.8;
bankCommandLimit_rad=deg2rad(12);
bankTeachingEnvelope_rad=deg2rad(15);

headingCommandWrapped_rad=initialHeading_rad+zeros(1,sampleCount);
headingCommandWrapped_rad(time_s>=commandStepTime_s)=commandedHeading_rad;
headingCommandContinuous_rad=initialHeading_rad+zeros(1,sampleCount);
headingCommandContinuous_rad(time_s>=commandStepTime_s)= ...
    nearestContinuousTarget_rad;
headingUnwrapped_rad=zeros(1,sampleCount);
headingWrapped_rad=zeros(1,sampleCount);
rawHeadingError_rad=zeros(1,sampleCount);
shortestHeadingError_rad=zeros(1,sampleCount);
headingErrorUsed_rad=zeros(1,sampleCount);
bankCommandUnclamped_rad=zeros(1,sampleCount);
bankCommand_rad=zeros(1,sampleCount);
bankAngle_rad=zeros(1,sampleCount);
bankRate_radps=zeros(1,sampleCount);
bankAcceleration_radps2=zeros(1,sampleCount);
headingRate_radps=zeros(1,sampleCount);

headingUnwrapped_rad(1)=initialHeading_rad;
for k=1:sampleCount
    % The continuous state has no branch cut. Only this displayed heading is
    % mapped to the half-open interval [-pi,pi).
    headingWrapped_rad(k)=mod(headingUnwrapped_rad(k)+pi,2*pi)-pi;
    rawHeadingError_rad(k)= ...
        headingCommandWrapped_rad(k)-headingWrapped_rad(k);
    shortestHeadingError_rad(k)=mod(rawHeadingError_rad(k)+pi,2*pi)-pi;
    if headingErrorMode==1
        headingErrorUsed_rad(k)=shortestHeadingError_rad(k);
    else
        % Broken case: subtract displayed angles without respecting that
        % -170 deg and +190 deg name the same direction.
        headingErrorUsed_rad(k)=rawHeadingError_rad(k);
    end

    % Outer loop: circular heading error becomes a bounded bank command.
    bankCommandUnclamped_rad(k)= ...
        headingGain_bank_per_heading*headingErrorUsed_rad(k);
    bankCommand_rad(k)=min(max(bankCommandUnclamped_rad(k), ...
        -bankCommandLimit_rad),bankCommandLimit_rad);

    % Inner loop: a transparent second-order closed-loop bank response.
    % rollNaturalFrequency_radps is a teaching bandwidth, not an identified
    % aerodynamic roll-subsidence pole or physical actuator model.
    bankAcceleration_radps2(k)=rollNaturalFrequency_radps^2* ...
        (bankCommand_rad(k)-bankAngle_rad(k))- ...
        2*rollDampingRatio*rollNaturalFrequency_radps*bankRate_radps(k);

    % Coordinated, level, zero-wind teaching relation. tan receives radians.
    headingRate_radps(k)=gravity_mps2/trueAirspeed_mps* ...
        tan(bankAngle_rad(k));

    % Fixed-step forward Euler. Every next state uses only sample-k values.
    if k<sampleCount
        headingUnwrapped_rad(k+1)=headingUnwrapped_rad(k)+ ...
            sampleTime_s*headingRate_radps(k);
        bankAngle_rad(k+1)=bankAngle_rad(k)+ ...
            sampleTime_s*bankRate_radps(k);
        bankRate_radps(k+1)=bankRate_radps(k)+ ...
            sampleTime_s*bankAcceleration_radps2(k);
    end
end

bankCommandSaturated= ...
    abs(bankCommandUnclamped_rad)>bankCommandLimit_rad;
activeMask=time_s>=commandStepTime_s;
activeSampleCount=sum(activeMask);
bankTrackingError_deg=rad2deg(bankCommand_rad-bankAngle_rad);
bankTrackingRMS_deg=sqrt(mean(bankTrackingError_deg(activeMask).^2));
finalShortestHeadingError_deg=rad2deg(shortestHeadingError_rad(end));
headingErrorAtTenSeconds_deg=rad2deg(shortestHeadingError_rad( ...
    find(time_s>=10,1,'first')));
captureTolerance_deg=0.1*abs(rad2deg(shortestCommandStep_rad));
captureIndex=find(activeMask & ...
    abs(rad2deg(shortestHeadingError_rad))<=captureTolerance_deg,1,'first');
if isempty(captureIndex)
    reachedNinetyPercent=false;
    timeToNinetyPercent_s=timeHorizon_s-commandStepTime_s;
else
    reachedNinetyPercent=true;
    timeToNinetyPercent_s=time_s(captureIndex)-commandStepTime_s;
end
settlingTolerance_deg=0.02*abs(rad2deg(shortestCommandStep_rad));
settledByEnd=abs(finalShortestHeadingError_deg)<=settlingTolerance_deg;
outsideTolerance=find(activeMask & ...
    abs(rad2deg(shortestHeadingError_rad))>settlingTolerance_deg,1,'last');
if settledByEnd && ~isempty(outsideTolerance) && outsideTolerance<sampleCount
    settlingTime_s=time_s(outsideTolerance+1)-commandStepTime_s;
elseif settledByEnd && isempty(outsideTolerance)
    settlingTime_s=0;
else
    settlingTime_s=timeHorizon_s-commandStepTime_s;
end
headingChange_deg=rad2deg(headingUnwrapped_rad-initialHeading_rad);
signedHeadingTravel_deg=headingChange_deg(end);
absoluteHeadingTravel_deg=sum(abs(diff(rad2deg(headingUnwrapped_rad))));
correctTurnDirection=sign(shortestCommandStep_rad);
wrongWayTravel_deg=max(0,-correctTurnDirection*signedHeadingTravel_deg);
peakAbsoluteShortestHeadingError_deg=max( ...
    abs(rad2deg(shortestHeadingError_rad(activeMask))));

out=struct( ...
    'headingGain_bank_per_heading',headingGain_bank_per_heading, ...
    'rollNaturalFrequency_radps',rollNaturalFrequency_radps, ...
    'headingErrorMode',headingErrorMode, ...
    'sampleTime_s',sampleTime_s, ...
    'timeHorizon_s',timeHorizon_s, ...
    'time_s',time_s, ...
    'sampleCount',sampleCount, ...
    'intervalCount',sampleCount-1, ...
    'activeSampleCount',activeSampleCount, ...
    'commandStepTime_s',commandStepTime_s, ...
    'initialHeading_deg',rad2deg(initialHeading_rad), ...
    'commandedHeading_deg',rad2deg(commandedHeading_rad), ...
    'shortestCommandStep_deg',rad2deg(shortestCommandStep_rad), ...
    'nearestContinuousTarget_deg',rad2deg(nearestContinuousTarget_rad), ...
    'trueAirspeed_mps',trueAirspeed_mps, ...
    'gravity_mps2',gravity_mps2, ...
    'rollDampingRatio',rollDampingRatio, ...
    'bankCommandLimit_deg',rad2deg(bankCommandLimit_rad), ...
    'bankTeachingEnvelope_deg',rad2deg(bankTeachingEnvelope_rad), ...
    'headingCommandWrapped_deg',rad2deg(headingCommandWrapped_rad), ...
    'headingCommandContinuous_deg',rad2deg(headingCommandContinuous_rad), ...
    'headingUnwrapped_deg',rad2deg(headingUnwrapped_rad), ...
    'headingWrapped_deg',rad2deg(headingWrapped_rad), ...
    'headingChange_deg',headingChange_deg, ...
    'rawHeadingError_deg',rad2deg(rawHeadingError_rad), ...
    'shortestHeadingError_deg',rad2deg(shortestHeadingError_rad), ...
    'headingErrorUsed_deg',rad2deg(headingErrorUsed_rad), ...
    'bankCommandUnclamped_deg',rad2deg(bankCommandUnclamped_rad), ...
    'bankCommand_deg',rad2deg(bankCommand_rad), ...
    'bankCommandSaturated',bankCommandSaturated, ...
    'bankCommandSaturationFraction', ...
    sum(bankCommandSaturated)/sampleCount, ...
    'bankAngle_deg',rad2deg(bankAngle_rad), ...
    'bankRate_degps',rad2deg(bankRate_radps), ...
    'bankAcceleration_degps2',rad2deg(bankAcceleration_radps2), ...
    'headingRate_degps',rad2deg(headingRate_radps), ...
    'bankTrackingError_deg',bankTrackingError_deg, ...
    'bankTrackingRMS_deg',bankTrackingRMS_deg, ...
    'headingErrorAtTenSeconds_deg',headingErrorAtTenSeconds_deg, ...
    'finalShortestHeadingError_deg',finalShortestHeadingError_deg, ...
    'captureTolerance_deg',captureTolerance_deg, ...
    'reachedNinetyPercent',reachedNinetyPercent, ...
    'timeToNinetyPercent_s',timeToNinetyPercent_s, ...
    'settlingTolerance_deg',settlingTolerance_deg, ...
    'settledByEnd',settledByEnd, ...
    'settlingTime_s',settlingTime_s, ...
    'signedHeadingTravel_deg',signedHeadingTravel_deg, ...
    'absoluteHeadingTravel_deg',absoluteHeadingTravel_deg, ...
    'wrongWayTravel_deg',wrongWayTravel_deg, ...
    'peakAbsoluteShortestHeadingError_deg', ...
    peakAbsoluteShortestHeadingError_deg, ...
    'peakBankAngle_deg',max(abs(rad2deg(bankAngle_rad))), ...
    'peakBankRate_degps',max(abs(rad2deg(bankRate_radps))), ...
    'peakBankAcceleration_degps2', ...
    max(abs(rad2deg(bankAcceleration_radps2))), ...
    'controllerEquation',[ ...
        'e_psi=wrap(psi_command-wrap(psi_unwrapped)); ' ...
        'phi_command=sat(K_psi*e_psi,+/-12 deg)'], ...
    'rollEquation',[ ...
        'phi_dot=p_phi; p_phi_dot=omega_phi^2*(phi_command-phi)-' ...
        '2*zeta_phi*omega_phi*p_phi'], ...
    'turnEquation','psi_unwrapped_dot=g*tan(phi)/V', ...
    'headingConvention',[ ...
        'headings are cyclic on [-180,180); the state is continuous; positive bank is ' ...
        'right-wing-down and positive heading is nose-right'], ...
    'brokenCaseDefinition',[ ...
        'headingErrorMode=0 raw-subtracts displayed headings, interpreting the ' ...
        '170-to--170 deg command as -340 deg instead of the +20 deg shortest path'], ...
    'analysisScope',[ ...
        'deterministic fixed-speed coordinated-level-turn teaching model; bank rate is an ' ...
        'Euler-angle rate; no wind, sideslip, adverse yaw, Dutch roll, actuator, sensor, ' ...
        'altitude/energy coupling, identified aerodynamics, full 6-DOF, hardware, or flight fidelity']);
end
