function run_checks
%RUN_CHECKS P14 independent circular-error, roll, turn, and recovery checks.
clear model;

%% Determinism, fixed shapes, and finite resources
baseline=model();
repeatedBaseline=model(0.5,2.4,1);
assert(isequaln(baseline,repeatedBaseline), ...
    'Repeated baseline calls must be deterministic and stateless.');
assert(baseline.sampleCount==3001, ...
    'P14 must retain exactly 3001 samples.');
assert(baseline.intervalCount==3000, ...
    'P14 must retain exactly 3000 update intervals.');
assert(baseline.activeSampleCount==2951, ...
    'The command-active segment must retain exactly 2951 samples.');
assert(baseline.time_s(1)==0 && baseline.time_s(end)==60 && ...
    max(abs(diff(baseline.time_s)-0.02))<1e-14, ...
    'The fixed 0:0.02:60 s resource grid changed.');
historyFields={ ...
    'headingCommandWrapped_deg','headingCommandContinuous_deg', ...
    'headingUnwrapped_deg','headingWrapped_deg','headingChange_deg', ...
    'rawHeadingError_deg','shortestHeadingError_deg', ...
    'headingErrorUsed_deg','bankCommandUnclamped_deg', ...
    'bankCommand_deg','bankCommandSaturated','bankAngle_deg', ...
    'bankRate_degps','bankAcceleration_degps2','headingRate_degps', ...
    'bankTrackingError_deg'};
for k=1:numel(historyFields)
    values=baseline.(historyFields{k});
    assert(isequal(size(values),[1 baseline.sampleCount]), ...
        'Every retained baseline history must be a fixed row vector.');
    assert(all(isfinite(double(values(:)))), ...
        'Every retained baseline history must be finite.');
end

%% Signed baseline, circular command, and exact pre-step trim
commandIndex=find(baseline.time_s>=baseline.commandStepTime_s,1,'first');
onePointFiveIndex=find(baseline.time_s>=1.5,1,'first');
tenSecondIndex=find(baseline.time_s>=10,1,'first');
preStepIndices=find(baseline.time_s<baseline.commandStepTime_s);
assert(max(abs(baseline.headingCommandWrapped_deg(preStepIndices)- ...
    baseline.initialHeading_deg))<1e-12 && ...
    max(abs(baseline.headingCommandContinuous_deg(preStepIndices)- ...
    baseline.initialHeading_deg))<1e-12 && ...
    max(abs(baseline.headingUnwrapped_deg(preStepIndices)- ...
    baseline.initialHeading_deg))<1e-12 && ...
    max(abs(baseline.headingWrapped_deg(preStepIndices)- ...
    baseline.initialHeading_deg))<1e-12, ...
    'Command and both heading representations must remain at trim before the step.');
assert(all(baseline.rawHeadingError_deg(preStepIndices)==0) && ...
    all(baseline.shortestHeadingError_deg(preStepIndices)==0) && ...
    all(baseline.headingErrorUsed_deg(preStepIndices)==0) && ...
    all(baseline.bankCommand_deg(preStepIndices)==0) && ...
    all(baseline.bankAngle_deg(preStepIndices)==0) && ...
    all(baseline.bankRate_degps(preStepIndices)==0) && ...
    all(baseline.bankAcceleration_degps2(preStepIndices)==0) && ...
    all(baseline.headingRate_degps(preStepIndices)==0), ...
    'Every controller, state, and derivative must be zero at pre-step trim.');
assert(commandIndex==51 && baseline.time_s(commandIndex)==1 && ...
    abs(baseline.headingCommandWrapped_deg(commandIndex)+170)<1e-12 && ...
    abs(baseline.headingCommandContinuous_deg(commandIndex)-190)<1e-12 && ...
    abs(baseline.headingUnwrapped_deg(commandIndex)-170)<1e-12 && ...
    baseline.bankAngle_deg(commandIndex)==0 && ...
    baseline.bankRate_degps(commandIndex)==0, ...
    'The retained command must begin at sample 51 from an unchanged state.');
assert(abs(baseline.rawHeadingError_deg(commandIndex)+340)<1e-12 && ...
    abs(baseline.shortestHeadingError_deg(commandIndex)-20)<1e-12 && ...
    abs(baseline.headingErrorUsed_deg(commandIndex)-20)<1e-12, ...
    'Raw -340 deg subtraction must wrap to the +20 deg shortest error.');
assert(abs(baseline.bankCommand_deg(commandIndex)-10)<1e-12 && ...
    abs(baseline.bankAcceleration_degps2(commandIndex)-57.6)<1e-11 && ...
    baseline.headingRate_degps(commandIndex)==0, ...
    'The positive circular error must create the pinned bank command and acceleration.');
assert(abs(baseline.bankAngle_deg(onePointFiveIndex)- ...
    3.765653541420135)<1e-10 && ...
    abs(baseline.headingRate_degps(onePointFiveIndex)- ...
    0.616361823037713)<1e-10, ...
    'The signed baseline must retain bank-leading-heading behavior.');
assert(abs(baseline.shortestHeadingError_deg(tenSecondIndex)- ...
    9.693404960655482)<1e-9, ...
    'The signed baseline shortest error at 10 s changed.');
assert(abs(baseline.finalShortestHeadingError_deg- ...
    0.126913314957683)<1e-9 && ...
    abs(baseline.timeToNinetyPercent_s-27.2)<1e-12 && ...
    abs(baseline.bankTrackingRMS_deg- ...
    0.905378979330061)<1e-9 && ...
    abs(baseline.peakBankAngle_deg- ...
    9.691004143934801)<1e-9 && ...
    baseline.settledByEnd, ...
    'The retained baseline capture, tracking, and envelope metrics changed.');

%% Independently reconstruct wrapping, controller, dynamics, and every recurrence
expectedWrappedHeading_deg=rad2deg(mod( ...
    deg2rad(baseline.headingUnwrapped_deg)+pi,2*pi)-pi);
expectedRawError_deg= ...
    baseline.headingCommandWrapped_deg-expectedWrappedHeading_deg;
expectedShortestError_deg=rad2deg(mod( ...
    deg2rad(expectedRawError_deg)+pi,2*pi)-pi);
expectedBankCommandUnclamped_deg= ...
    baseline.headingGain_bank_per_heading*expectedShortestError_deg;
expectedBankCommand_deg=min(max(expectedBankCommandUnclamped_deg, ...
    -baseline.bankCommandLimit_deg),baseline.bankCommandLimit_deg);
expectedBankAcceleration_degps2= ...
    baseline.rollNaturalFrequency_radps^2* ...
    (expectedBankCommand_deg-baseline.bankAngle_deg)- ...
    2*baseline.rollDampingRatio*baseline.rollNaturalFrequency_radps* ...
    baseline.bankRate_degps;
expectedHeadingRate_degps=rad2deg(baseline.gravity_mps2/ ...
    baseline.trueAirspeed_mps*tan(deg2rad(baseline.bankAngle_deg)));
assert(max(abs(baseline.headingWrapped_deg- ...
    expectedWrappedHeading_deg))<1e-12 && ...
    max(abs(baseline.rawHeadingError_deg-expectedRawError_deg))<1e-12 && ...
    max(abs(baseline.shortestHeadingError_deg- ...
    expectedShortestError_deg))<1e-12 && ...
    max(abs(baseline.headingErrorUsed_deg- ...
    expectedShortestError_deg))<1e-12, ...
    'The independently reconstructed circular heading errors must match.');
assert(max(abs(baseline.bankCommandUnclamped_deg- ...
    expectedBankCommandUnclamped_deg))<1e-12 && ...
    max(abs(baseline.bankCommand_deg-expectedBankCommand_deg))<1e-12 && ...
    max(abs(baseline.bankAcceleration_degps2- ...
    expectedBankAcceleration_degps2))<1e-10 && ...
    max(abs(baseline.headingRate_degps- ...
    expectedHeadingRate_degps))<1e-12, ...
    'The independently reconstructed controller, roll, and turn equations must match.');

expectedHeadingNext_deg=baseline.headingUnwrapped_deg(1:end-1)+ ...
    baseline.sampleTime_s*baseline.headingRate_degps(1:end-1);
expectedBankNext_deg=baseline.bankAngle_deg(1:end-1)+ ...
    baseline.sampleTime_s*baseline.bankRate_degps(1:end-1);
expectedBankRateNext_degps=baseline.bankRate_degps(1:end-1)+ ...
    baseline.sampleTime_s*baseline.bankAcceleration_degps2(1:end-1);
assert(max(abs(baseline.headingUnwrapped_deg(2:end)- ...
    expectedHeadingNext_deg))<1e-11, ...
    'Every continuous-heading update must use sample-k heading rate.');
assert(max(abs(baseline.bankAngle_deg(2:end)-expectedBankNext_deg))<1e-12, ...
    'Every bank update must use sample-k bank rate.');
assert(max(abs(baseline.bankRate_degps(2:end)- ...
    expectedBankRateNext_degps))<1e-11, ...
    'Every bank-rate update must use sample-k bank acceleration.');

%% Branch-cut continuity, envelopes, and the P07 small-bank limit
assert(max(abs(diff(baseline.headingWrapped_deg)))>350 && ...
    max(abs(diff(baseline.headingUnwrapped_deg)))<0.04, ...
    ['The wrapped display must cross its branch cut while continuous heading ' ...
    'retains bounded sample-to-sample motion.']);
assert(max(abs(baseline.bankCommand_deg))<= ...
    baseline.bankCommandLimit_deg && ...
    baseline.peakBankAngle_deg<baseline.bankTeachingEnvelope_deg, ...
    'Command and actual bank must remain inside their declared envelopes.');
assert(isequal(baseline.bankCommandSaturated, ...
    abs(baseline.bankCommandUnclamped_deg)> ...
    baseline.bankCommandLimit_deg) && ...
    ~any(baseline.bankCommandSaturated), ...
    'Baseline saturation flags must exactly identify envelope violations.');
smallBankHeadingRate_radps=baseline.gravity_mps2/ ...
    baseline.trueAirspeed_mps*deg2rad(baseline.bankAngle_deg);
exactHeadingRate_radps=deg2rad(baseline.headingRate_degps);
assert(max(abs(exactHeadingRate_radps-smallBankHeadingRate_radps))<3e-4 && ...
    exactHeadingRate_radps(1)==smallBankHeadingRate_radps(1), ...
    ['The exact tan relation must recover P07''s linear proxy at zero bank ' ...
    'and remain close over the retained teaching envelope.']);

%% Limiting case: zero heading gain leaves the command uncorrected
openHeadingLoop=model(0,2.4,1);
assert(max(abs(openHeadingLoop.headingUnwrapped_deg- ...
    openHeadingLoop.initialHeading_deg))<1e-12 && ...
    max(abs(openHeadingLoop.headingWrapped_deg- ...
    openHeadingLoop.initialHeading_deg))<1e-12 && ...
    all(openHeadingLoop.headingChange_deg==0) && ...
    all(openHeadingLoop.bankCommand_deg==0) && ...
    all(openHeadingLoop.bankAngle_deg==0) && ...
    all(openHeadingLoop.bankRate_degps==0) && ...
    all(openHeadingLoop.bankAcceleration_degps2==0) && ...
    all(openHeadingLoop.headingRate_degps==0), ...
    'Zero outer gain must be the exact open-heading-loop trim limit.');
assert(abs(openHeadingLoop.finalShortestHeadingError_deg-20)<1e-12 && ...
    ~openHeadingLoop.reachedNinetyPercent && ...
    ~openHeadingLoop.settledByEnd, ...
    'The open heading loop must retain the full circular command error.');

%% Two isolated parameter sweeps
headingGainSweep_bank_per_heading=[0 0.25 0.5 0.75 1.0];
gainErrorAtTenSeconds_deg=zeros(size(headingGainSweep_bank_per_heading));
gainCaptureTime_s=zeros(size(headingGainSweep_bank_per_heading));
gainPeakBank_deg=zeros(size(headingGainSweep_bank_per_heading));
gainBankSaturationFraction=zeros(size(headingGainSweep_bank_per_heading));
for k=1:numel(headingGainSweep_bank_per_heading)
    sample=model(headingGainSweep_bank_per_heading(k),2.4,1);
    gainErrorAtTenSeconds_deg(k)=sample.headingErrorAtTenSeconds_deg;
    gainCaptureTime_s(k)=sample.timeToNinetyPercent_s;
    gainPeakBank_deg(k)=sample.peakBankAngle_deg;
    gainBankSaturationFraction(k)=sample.bankCommandSaturationFraction;
    assert(sample.rollNaturalFrequency_radps==2.4 && ...
        sample.headingErrorMode==1 && ...
        sample.rollDampingRatio==baseline.rollDampingRatio && ...
        isequal(sample.time_s,baseline.time_s) && ...
        isequal(sample.headingCommandWrapped_deg, ...
        baseline.headingCommandWrapped_deg), ...
        'The heading-gain sweep must isolate only its selected public input.');
end
expectedGainErrors_deg=[20 14.087257521807203 9.693404960655482 ...
    6.828117306718742 5.403664247613667];
assert(max(abs(gainErrorAtTenSeconds_deg-expectedGainErrors_deg))<1e-9 && ...
    all(diff(gainErrorAtTenSeconds_deg)<0) && ...
    all(diff(gainCaptureTime_s(2:end))<0), ...
    'Higher heading gain must reduce retained early error and capture time.');
assert(gainPeakBank_deg(1)==0 && ...
    gainPeakBank_deg(3)>gainPeakBank_deg(2) && ...
    gainBankSaturationFraction(3)==0 && ...
    gainBankSaturationFraction(4)>0 && ...
    gainBankSaturationFraction(5)>gainBankSaturationFraction(4), ...
    'Outer gain must expose the bank-authority and saturation tradeoff.');

rollFrequencySweep_radps=[1.2 1.8 2.4 3.0 3.6];
frequencyBankAtOnePointFive_deg=zeros(size(rollFrequencySweep_radps));
frequencyTrackingRMS_deg=zeros(size(rollFrequencySweep_radps));
frequencyPeakAcceleration_degps2=zeros(size(rollFrequencySweep_radps));
for k=1:numel(rollFrequencySweep_radps)
    sample=model(0.5,rollFrequencySweep_radps(k),1);
    frequencyBankAtOnePointFive_deg(k)= ...
        sample.bankAngle_deg(onePointFiveIndex);
    frequencyTrackingRMS_deg(k)=sample.bankTrackingRMS_deg;
    frequencyPeakAcceleration_degps2(k)= ...
        sample.peakBankAcceleration_degps2;
    assert(sample.headingGain_bank_per_heading==0.5 && ...
        sample.headingErrorMode==1 && ...
        sample.rollDampingRatio==baseline.rollDampingRatio && ...
        sample.trueAirspeed_mps==baseline.trueAirspeed_mps && ...
        isequal(sample.headingCommandWrapped_deg, ...
        baseline.headingCommandWrapped_deg), ...
        'The roll-frequency sweep must isolate only its selected public input.');
end
expectedBankAtOnePointFive_deg=[1.280716133992437 ...
    2.472623001030339 3.765653541420135 ...
    5.034393487542499 6.198635785562148];
expectedPeakAcceleration_degps2=[14.4 32.4 57.6 90 129.6];
assert(max(abs(frequencyBankAtOnePointFive_deg- ...
    expectedBankAtOnePointFive_deg))<1e-9 && ...
    max(abs(frequencyPeakAcceleration_degps2- ...
    expectedPeakAcceleration_degps2))<1e-9 && ...
    all(diff(frequencyBankAtOnePointFive_deg)>0) && ...
    all(diff(frequencyTrackingRMS_deg)<0) && ...
    all(diff(frequencyPeakAcceleration_degps2)>0), ...
    'Faster roll response must trade tracking error for acceleration demand.');

%% Broken raw subtraction, wrong-way symptom, rollback, and recovery
broken=model(0.5,2.4,0);
stateFields={ ...
    'headingUnwrapped_deg','headingWrapped_deg','bankAngle_deg', ...
    'bankRate_degps','headingRate_degps'};
for k=1:numel(stateFields)
    brokenState=broken.(stateFields{k});
    baselineState=baseline.(stateFields{k});
    assert(isequal(brokenState(1:commandIndex), ...
        baselineState(1:commandIndex)), ...
        'Correct and broken states must match through command onset.');
end
assert(broken.headingGain_bank_per_heading== ...
    baseline.headingGain_bank_per_heading && ...
    broken.rollNaturalFrequency_radps== ...
    baseline.rollNaturalFrequency_radps && ...
    broken.headingErrorMode==0 && ...
    isequal(broken.time_s,baseline.time_s) && ...
    isequal(broken.headingCommandWrapped_deg, ...
    baseline.headingCommandWrapped_deg) && ...
    isequal(broken.rawHeadingError_deg(1:commandIndex), ...
    baseline.rawHeadingError_deg(1:commandIndex)) && ...
    isequal(broken.shortestHeadingError_deg(1:commandIndex), ...
    baseline.shortestHeadingError_deg(1:commandIndex)), ...
    'The broken case must change only the selected circular-error mode.');
assert(abs(broken.headingErrorUsed_deg(commandIndex)+340)<1e-12 && ...
    abs(broken.bankCommand_deg(commandIndex)+12)<1e-12 && ...
    abs(broken.bankAcceleration_degps2(commandIndex)+69.12)<1e-10 && ...
    baseline.bankCommand_deg(commandIndex)>0, ...
    'Raw subtraction must command the opposite, saturated bank direction.');
assert(all(diff(broken.shortestHeadingError_deg(commandIndex:end))>=-1e-11) && ...
    all(diff(abs(broken.rawHeadingError_deg(commandIndex:end)))<=1e-11) && ...
    broken.signedHeadingTravel_deg<-110 && ...
    broken.absoluteHeadingTravel_deg>110 && ...
    broken.wrongWayTravel_deg>110 && ...
    broken.finalShortestHeadingError_deg>130 && ...
    broken.peakAbsoluteShortestHeadingError_deg>130 && ...
    ~broken.reachedNinetyPercent && ~broken.settledByEnd, ...
    ['The proper circular error must grow while raw arithmetic contracts ' ...
    'along the saturated wrong-way route.']);
assert(abs(broken.signedHeadingTravel_deg+ ...
    116.10501891177968)<1e-8 && ...
    abs(broken.finalShortestHeadingError_deg- ...
    136.10501891177967)<1e-8 && ...
    broken.bankCommandSaturationFraction>0.98 && ...
    broken.peakBankAngle_deg<broken.bankTeachingEnvelope_deg && ...
    all(isfinite(broken.headingUnwrapped_deg)) && ...
    all(isfinite(broken.bankAngle_deg)), ...
    'The retained broken-route signature, bounds, and finite histories changed.');

% Saturation bounds bank command but must not be mistaken for recovery. The
% retained final second must still show leftward motion and growing proper
% circular error under the raw-subtraction route.
brokenTailIndices=find(broken.time_s>=broken.timeHorizon_s-1);
brokenHeadingTailIntervals=brokenTailIndices(1:end-1);
assert(all(broken.bankCommandSaturated(brokenTailIndices)) && ...
    all(diff(broken.headingUnwrapped_deg(brokenTailIndices))<0) && ...
    all(diff(broken.shortestHeadingError_deg(brokenTailIndices))>0) && ...
    all(diff(abs(broken.rawHeadingError_deg(brokenTailIndices)))<0) && ...
    broken.shortestHeadingError_deg(end)- ...
    broken.shortestHeadingError_deg(brokenTailIndices(1))>1.9 && ...
    broken.headingUnwrapped_deg(brokenTailIndices(1))- ...
    broken.headingUnwrapped_deg(end)>1.9 && ...
    max(abs(diff(broken.headingUnwrapped_deg(brokenTailIndices))- ...
    broken.sampleTime_s* ...
    broken.headingRate_degps(brokenHeadingTailIntervals)))<1e-10 && ...
    broken.headingRate_degps(end)<-1.9, ...
    ['Bank-command saturation must not masquerade as recovery: the broken ' ...
    'heading must keep moving the wrong way through the retained tail.']);
rolledBackBaseline=model(0.5,2.4,1);
assert(isequaln(rolledBackBaseline,baseline), ...
    'Rollback from raw subtraction must reproduce the correct baseline exactly.');

%% Malformed and rejected inputs do not poison deterministic recovery
assertRejects(@()model(-eps,2.4,1),'P14:model:HeadingGainRange');
assertRejects(@()model(1+eps,2.4,1),'P14:model:HeadingGainRange');
assertRejects(@()model(0.5,1.2-eps,1), ...
    'P14:model:RollFrequencyRange');
assertRejects(@()model(0.5,3.6+eps,1), ...
    'P14:model:RollFrequencyRange');
assertRejects(@()model(0.5,2.4,-1),'P14:model:HeadingErrorMode');
assertRejects(@()model(0.5,2.4,2),'P14:model:HeadingErrorMode');
malformedCalls={ ...
    @()model([0.25 0.5],2.4,1), ...
    @()model(0.5,[1.8 2.4],1), ...
    @()model(0.5,2.4,[0 1]), ...
    @()model(0.5+1i,2.4,1), ...
    @()model(0.5,2.4+1i,1), ...
    @()model(NaN,2.4,1), ...
    @()model(0.5,Inf,1), ...
    @()model(0.5,2.4,NaN)};
for k=1:numel(malformedCalls)
    assertRejects(malformedCalls{k},'');
end
recoveredBaseline=model();
assert(isequaln(recoveredBaseline,baseline), ...
    'A valid call after rejected inputs must recover the exact baseline.');

%% Accepted corners, representative grid, and resource bounds
acceptedCornerCount=0;
for headingGain_bank_per_heading=[0 1]
    for rollNaturalFrequency_radps=[1.2 3.6]
        for headingErrorMode=[0 1]
            sample=model(headingGain_bank_per_heading, ...
                rollNaturalFrequency_radps,headingErrorMode);
            acceptedCornerCount=acceptedCornerCount+1;
            assert(sample.sampleCount==3001 && sample.intervalCount==3000, ...
                'Accepted corners may not change allocated history size.');
            assert(all(isfinite(sample.headingUnwrapped_deg)) && ...
                all(isfinite(sample.headingWrapped_deg)) && ...
                all(isfinite(sample.shortestHeadingError_deg)) && ...
                all(isfinite(sample.bankAngle_deg)) && ...
                all(isfinite(sample.bankRate_degps)) && ...
                all(isfinite(sample.bankAcceleration_degps2)) && ...
                all(isfinite(sample.headingRate_degps)), ...
                'Accepted corners must retain finite states and derivatives.');
            assert(max(abs(sample.bankCommand_deg))<= ...
                sample.bankCommandLimit_deg+1e-12 && ...
                sample.peakBankAngle_deg<15, ...
                'Accepted corners must preserve command and teaching envelopes.');
        end
    end
end
assert(acceptedCornerCount==8, ...
    'The accepted-corner check must remain capped at eight cases.');

representativeCaseCount=0;
for headingGain_bank_per_heading=[0 0.5 1]
    for rollNaturalFrequency_radps=[1.2 2.4 3.6]
        for headingErrorMode=[0 1]
            sample=model(headingGain_bank_per_heading, ...
                rollNaturalFrequency_radps,headingErrorMode);
            representativeCaseCount=representativeCaseCount+1;
            assert(sample.sampleCount==baseline.sampleCount && ...
                sample.intervalCount==baseline.intervalCount && ...
                isequal(sample.time_s,baseline.time_s), ...
                'Representative cases must use the fixed synchronous grid.');
        end
    end
end
assert(representativeCaseCount==18, ...
    'The representative finite-resource grid must remain capped at 18 cases.');

%% Compatibility, timeout, cancellation, migration, and backup applicability
% P14 is a synchronous stateless base-MATLAB teaching calculation. It owns
% no file, network, device, process, timer, future, parallel worker, or
% background callback resource. There is therefore no asynchronous timeout
% or cancellation transition to exercise; fixed sample/interval counts and
% the capped case grid are the applicable resource boundary. No learner data,
% service schema, scoring model, migration, database, or backup/restore path
% changes in this module. P13/P07 are conceptual prerequisites, not runtime
% compatibility adapters.

fprintf(['P14 checks passed: deterministic circular cascade, every recurrence, ' ...
    'isolated parameter sweeps, open-loop limit, broken raw subtraction, ' ...
    'saturated-tail failure, malformed-input recovery, rollback, ' ...
    'compatibility, and resources.\n']);
end

function assertRejects(testCall,expectedIdentifier)
caught=false;
try
    unusedOutput=testCall(); %#ok<NASGU>
catch exception
    caught=true;
    if ~isempty(expectedIdentifier)
        assert(strcmp(exception.identifier,expectedIdentifier), ...
            'Rejected input raised an unexpected error identifier.');
    else
        assert(~isempty(exception.identifier), ...
            'Malformed input rejection must provide an error identifier.');
    end
end
assert(caught,'The malformed or out-of-range input must be rejected.');
end
